upkeeper: controller/buddy.c File Reference
controller/buddy.c File Reference
#include "buddy.h"
#include <assert.h>
#include <stdarg.h>
#include <upkeeper/upk_error.h>
Defines
#define BUDDY_RETRY_TIMEOUT_SEC 1
#define BUDDY_RETRY_TIMEOUT_NSEC 0
#define BUDDY_SELECT_TIMEOUT_SEC 1
#define BUDDY_SELECT_TIMEOUT_USEC 0
#define RESPAWN_WINDOW 5
#define MAX_RESPAWN_COUNT 10
#define RESPAWN_RATELIMIT 300
Functions
void buddy_init (diag_output_callback_t logger)
int32_t buddy_event_loop (void)
void buddy_cleanup (void)
static void buddy_init_paths (void)
static char * buddy_path (const char *suffixfmt,...)
static void buddy_init_socket (void)
static bool buddy_phone_home (void)
static void buddy_record_state (void)
static void buddy_zero_info (void)
static void buddy_init_ringbuffer (void)
static void buddy_free_ringbuffer (void)
static void buddy_accept (void)
static int buddy_build_fd_set (fd_set *socks, bool listen_sock)
static bool buddy_handle_flags (void)
static void buddy_stop_proc (void)
static void buddy_reload_proc (void)
static void buddy_cust_action (uint32_t act_num)
static void buddy_handle_command (void)
static void buddy_setreguid (void)
static void buddy_setup_fds (void)
static int32_t read_ctrl (buddy_cmnd_t *buf)
static int32_t write_ctrl (buddy_info_t *buf)
static pid_t buddy_exec_action (void)
static bool buddy_start_proc (void)
static void resolve_symlink (void)
static void buddy_flush_ringbuffer (void)
static void sa_sigaction_func (int signal, siginfo_t *siginfo, void *ucontext)
void commit_buddycide (int32_t signum)
static bool buddy_disconnect (size_t count)
static void buddy_supp_groups (void)
static void phone_home_if_appropriate (void)
Variables
upk_uuid_t buddy_uuid
char * buddy_service_name = NULL
char buddy_root_path [BUDDY_MAX_PATH_LEN] = ""
uid_t buddy_setuid
gid_t buddy_setgid
size_t ringbuffer_size = 32
char ** proc_envp = NULL
long reconnect_retries = 5
bool randomize_ratelimit = false
bool initialize_supplemental_groups = false
bool clear_supplemental_groups = false
uint32_t user_ratelimit = 0
static time_t respawn_timestamp = 0
static uint32_t rapid_respawn_count = 0
static bool force_ratelimit = false
static size_t ringbuffer_pending = 0
static bool chld_terminated = false
static pid_t proc_pid = 0
static buddy_cmnd_t last_command = UPK_CTRL_NONE
static buddy_cmnd_t this_command = UPK_CTRL_NONE
static int buddy_shutdown = 0
static buddy_info_t * info_ringbuffer = NULL
static int buddy_sockfd = -1
static int buddy_ctrlfd = -1
static char buddy_path_buf [BUDDY_MAX_PATH_LEN] = ""
static char buddy_path_prefix [BUDDY_MAX_PATH_LEN] = ""
static char buddy_string_buf [BUDDY_MAX_PATH_LEN] = ""
static struct sockaddr_un buddy_sockaddr = { 0 }
static socklen_t buddy_sockaddr_len = 0
static int sockopts = 0
static int highest_fd = 0
static struct timeval timeout = {.tv_sec = BUDDY_SELECT_TIMEOUT_SEC,.tv_usec = BUDDY_SELECT_TIMEOUT_USEC }
static struct timespec nanotimeout
static size_t ncount = 0
static buddy_runstate_t desired_state = BUDDY_STOPPED
Define Documentation
#define BUDDY_RETRY_TIMEOUT_NSEC 0
#define BUDDY_RETRY_TIMEOUT_SEC 1
#define BUDDY_SELECT_TIMEOUT_SEC 1
Referenced by buddy_event_loop(), read_ctrl(), and write_ctrl().
#define BUDDY_SELECT_TIMEOUT_USEC 0
Referenced by buddy_event_loop(), read_ctrl(), and write_ctrl().
#define MAX_RESPAWN_COUNT 10
Referenced by buddy_start_proc().
#define RESPAWN_RATELIMIT 300
Referenced by buddy_handle_flags(), and buddy_start_proc().
#define RESPAWN_WINDOW 5
Referenced by buddy_start_proc().
Function Documentation
static void buddy_accept (void) [inline, static]
References accept(), buddy_ctrlfd, buddy_sockaddr_len, buddy_sockfd, fcntl(), sockopts, and upk_debug1.
Referenced by buddy_event_loop().
static int buddy_build_fd_set (fd_set * socks, bool listen_sock) [inline, static]
References buddy_ctrlfd, and buddy_sockfd.
Referenced by buddy_event_loop(), read_ctrl(), and write_ctrl().
void buddy_cleanup (void)
References buddy_flush_ringbuffer(), buddy_free_ringbuffer(), buddy_path(), buddy_service_name, buddy_stop_proc(), free(), and proc_pid.
Referenced by buddy_init(), commit_buddycide(), and main().
static void buddy_cust_action (uint32_t act_num) [inline, static]
References buddy_exec_action(), and buddy_path().
Referenced by buddy_handle_command().
static bool buddy_disconnect (size_t count) [inline, static]
References buddy_ctrlfd, SHUT_RDWR, shutdown(), and upk_debug1.
Referenced by buddy_flush_ringbuffer(), read_ctrl(), and write_ctrl().
int32_t buddy_event_loop (void)
References buddy_accept(), buddy_build_fd_set(), buddy_ctrlfd, buddy_flush_ringbuffer(), buddy_handle_command(), buddy_handle_flags(), BUDDY_SELECT_TIMEOUT_SEC, BUDDY_SELECT_TIMEOUT_USEC, buddy_shutdown, buddy_sockfd, commit_buddycide(), highest_fd, read_ctrl(), select(), this_command, timeval::tv_sec, timeval::tv_usec, and upk_debug1.
Referenced by main().
static pid_t buddy_exec_action (void) [static]
References BUDDY_MAX_PATH_LEN, buddy_path_buf, buddy_setreguid(), buddy_setup_fds(), buddy_string_buf, buddy_supp_groups(), proc_envp, proc_pid, sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, sigaction(), sigemptyset(), sigfillset(), sigprocmask(), sigset(), stat::st_mode, stat(), upk_alert, upk_debug0, and upk_notice.
Referenced by buddy_cust_action(), buddy_reload_proc(), buddy_start_proc(), and buddy_stop_proc().
static void buddy_flush_ringbuffer (void) [static]
References buddy_ctrlfd, buddy_disconnect(), buddy_zero_info(), info_ringbuffer, _buddy_info::next, phone_home_if_appropriate(), _buddy_info::populated, read_ctrl(), _buddy_info::remaining, ringbuffer_pending, sigfillset(), sigprocmask(), sigset(), this_command, UPK_CTRL_ACK, upk_debug1, and write_ctrl().
Referenced by buddy_cleanup(), and buddy_event_loop().
static void buddy_free_ringbuffer (void) [inline, static]
References free(), _buddy_info::next, and ringbuffer_size.
Referenced by buddy_cleanup().
static void buddy_handle_command (void) [inline, static]
References buddy_cust_action(), BUDDY_RANONCE, buddy_reload_proc(), BUDDY_RUNNING, buddy_shutdown, buddy_start_proc(), buddy_stop_proc(), BUDDY_STOPPED, desired_state, last_command, proc_pid, this_command, UPK_CTRL_ACTION_RELOAD, UPK_CTRL_ACTION_RUNONCE, UPK_CTRL_ACTION_START, UPK_CTRL_ACTION_STOP, UPK_CTRL_CUSTOM_ACTION_00, UPK_CTRL_CUSTOM_ACTION_31, UPK_CTRL_SHUTDOWN, UPK_CTRL_SIGNAL_01, UPK_CTRL_SIGNAL_32, UPK_CTRL_STATUS_REQ, upk_debug1, and upk_verbose.
Referenced by buddy_event_loop().
static bool buddy_handle_flags (void) [inline, static]
References BUDDY_RUNNING, buddy_shutdown, buddy_start_proc(), chld_terminated, desired_state, force_ratelimit, RESPAWN_RATELIMIT, respawn_timestamp, and upk_notice.
Referenced by buddy_event_loop().
void buddy_init (diag_output_callback_t logger)
References buddy_cleanup(), buddy_ctrlfd, buddy_init_paths(), buddy_init_ringbuffer(), buddy_init_socket(), buddy_path(), buddy_setgid, buddy_setuid, buddy_sockfd, sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, sigaction::sa_sigaction, sa_sigaction_func(), sigaction(), sigaddset(), sigemptyset(), sigfillset(), sigset(), upk_notice, upk_reg_diag_callback(), upk_verbose, and upk_warn.
Referenced by main().
static void buddy_init_paths (void) [inline, static]
References BUDDY_MAX_PATH_LEN, buddy_path_prefix, buddy_root_path, buddy_service_name, strnlen(), upk_fatal, and UPK_MAX_STRING_LEN.
Referenced by buddy_init().
static void buddy_init_ringbuffer (void) [inline, static]
References calloc(), _buddy_info::next, ringbuffer_size, and _buddy_info::slot_n.
Referenced by buddy_init().
static void buddy_init_socket (void) [inline, static]
References bind(), buddy_path(), buddy_sockaddr, buddy_sockaddr_len, buddy_sockfd, fcntl(), listen(), SOCK_STREAM, socket(), sockaddr_un::sun_family, sockaddr_un::sun_path, umask(), and upk_debug0.
Referenced by buddy_init().
static char * buddy_path (const char * suffixfmt, ...) [inline, static]
References buddy_path_buf, buddy_path_prefix, and buddy_string_buf.
Referenced by buddy_cleanup(), buddy_cust_action(), buddy_init(), buddy_init_socket(), buddy_phone_home(), buddy_reload_proc(), buddy_setup_fds(), buddy_start_proc(), buddy_stop_proc(), and spawn_buddy().
static bool buddy_phone_home (void) [inline, static]
References buddy_ctrlfd, buddy_path(), buddy_sockaddr_len, buddy_string_buf, connect(), resolve_symlink(), SOCK_STREAM, socket(), sockaddr_un::sun_family, and sockaddr_un::sun_path.
Referenced by phone_home_if_appropriate().
static void buddy_record_state (void) [inline, static]
References buddy_uuid, buddy_zero_info(), _buddy_info::command, desired_state, _buddy_info::desired_state, last_command, _buddy_info::populated, proc_pid, ringbuffer_pending, ringbuffer_size, _buddy_info::service_pid, _buddy_info::timestamp, upk_debug1, and _buddy_info::uuid.
Referenced by buddy_start_proc(), and sa_sigaction_func().
static void buddy_reload_proc (void) [inline, static]
References buddy_exec_action(), buddy_path(), and proc_pid.
Referenced by buddy_handle_command().
static void buddy_setreguid (void) [inline, static]
References buddy_setgid, and buddy_setuid.
Referenced by buddy_exec_action().
static void buddy_setup_fds (void) [inline, static]
References buddy_path().
Referenced by buddy_exec_action().
static bool buddy_start_proc (void) [static]
References buddy_exec_action(), buddy_path(), buddy_record_state(), buddy_service_name, force_ratelimit, MAX_RESPAWN_COUNT, _buddy_info::next, proc_pid, rapid_respawn_count, RESPAWN_RATELIMIT, respawn_timestamp, RESPAWN_WINDOW, sigaddset(), sigemptyset(), sigprocmask(), sigset(), upk_debug0, and upk_notice.
Referenced by buddy_handle_command(), and buddy_handle_flags().
static void buddy_stop_proc (void) [inline, static]
References buddy_exec_action(), buddy_path(), proc_pid, timespec::tv_nsec, and timespec::tv_sec.
Referenced by buddy_cleanup(), and buddy_handle_command().
static void buddy_supp_groups (void) [inline, static]
References buddy_setuid, clear_supplemental_groups, getpwuid(), initgroups(), initialize_supplemental_groups, and setgroups().
Referenced by buddy_exec_action().
static void buddy_zero_info (void) [inline, static]
References _buddy_info::next, _buddy_info::populated, ringbuffer_pending, _buddy_info::slot_n, and upk_debug1.
Referenced by buddy_flush_ringbuffer(), and buddy_record_state().
void commit_buddycide (int32_t signum)
References buddy_cleanup(), getpid(), sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, sigaction(), sigemptyset(), sigfillset(), sigprocmask(), sigset(), and upk_debug1.
Referenced by buddy_event_loop().
static void phone_home_if_appropriate (void) [inline, static]
References buddy_phone_home(), buddy_shutdown, reconnect_retries, ringbuffer_pending, ringbuffer_size, timespec::tv_nsec, timespec::tv_sec, and upk_verbose.
Referenced by buddy_flush_ringbuffer().
static int32_t read_ctrl (buddy_cmnd_t * buf) [inline, static]
References buddy_build_fd_set(), buddy_ctrlfd, buddy_disconnect(), BUDDY_SELECT_TIMEOUT_SEC, BUDDY_SELECT_TIMEOUT_USEC, highest_fd, ncount, select(), timeval::tv_sec, and timeval::tv_usec.
Referenced by buddy_event_loop(), and buddy_flush_ringbuffer().
static void resolve_symlink (void) [static]
References buddy_path_buf, buddy_string_buf, lstat(), and stat::st_mode.
Referenced by buddy_phone_home().
static void sa_sigaction_func (int signal, siginfo_t * siginfo, void * ucontext) [static]
References buddy_record_state(), buddy_shutdown, chld_terminated, _buddy_info::next, proc_pid, _buddy_info::siginfo, upk_debug1, _buddy_info::wait_pid, _buddy_info::wait_status, and waitpid().
Referenced by buddy_init().
static int32_t write_ctrl (buddy_info_t * buf) [inline, static]
References buddy_build_fd_set(), buddy_ctrlfd, buddy_disconnect(), BUDDY_SELECT_TIMEOUT_SEC, BUDDY_SELECT_TIMEOUT_USEC, highest_fd, ncount, select(), timeval::tv_sec, and timeval::tv_usec.
Referenced by buddy_flush_ringbuffer().
Variable Documentation
int buddy_ctrlfd = -1 [static]
Referenced by buddy_accept(), buddy_build_fd_set(), buddy_disconnect(), buddy_event_loop(), buddy_flush_ringbuffer(), buddy_init(), buddy_phone_home(), read_ctrl(), and write_ctrl().
char buddy_path_buf[BUDDY_MAX_PATH_LEN] = "" [static]
Referenced by buddy_exec_action(), buddy_path(), and resolve_symlink().
char buddy_path_prefix[BUDDY_MAX_PATH_LEN] = "" [static]
Referenced by buddy_init_paths(), and buddy_path().
char buddy_root_path[BUDDY_MAX_PATH_LEN] = ""
Referenced by buddy_init_paths(), and opt_parse().
char* buddy_service_name = NULL
Referenced by buddy_cleanup(), buddy_init_paths(), buddy_start_proc(), and opt_parse().
gid_t buddy_setgid
Referenced by buddy_init(), buddy_setreguid(), and opt_parse().
uid_t buddy_setuid
Referenced by buddy_init(), buddy_setreguid(), buddy_supp_groups(), and opt_parse().
int buddy_shutdown = 0 [static]
Referenced by buddy_event_loop(), buddy_handle_command(), buddy_handle_flags(), phone_home_if_appropriate(), and sa_sigaction_func().
struct sockaddr_un buddy_sockaddr = { 0 } [static]
Referenced by buddy_init_socket().
socklen_t buddy_sockaddr_len = 0 [static]
Referenced by buddy_accept(), buddy_init_socket(), and buddy_phone_home().
int buddy_sockfd = -1 [static]
Referenced by buddy_accept(), buddy_build_fd_set(), buddy_event_loop(), buddy_init(), and buddy_init_socket().
char buddy_string_buf[BUDDY_MAX_PATH_LEN] = "" [static]
Referenced by buddy_exec_action(), buddy_path(), buddy_phone_home(), and resolve_symlink().
upk_uuid_t buddy_uuid
Referenced by buddy_record_state(), opt_parse(), and spawn_buddy().
bool chld_terminated = false [static]
Referenced by buddy_handle_flags(), and sa_sigaction_func().
bool clear_supplemental_groups = false
Referenced by buddy_supp_groups(), and opt_parse().
buddy_runstate_t desired_state = BUDDY_STOPPED [static]
Referenced by buddy_handle_command(), buddy_handle_flags(), and buddy_record_state().
bool force_ratelimit = false [static]
Referenced by buddy_handle_flags(), and buddy_start_proc().
int highest_fd = 0 [static]
Referenced by buddy_event_loop(), read_ctrl(), and write_ctrl().
buddy_info_t* info_ringbuffer = NULL [static]
Referenced by buddy_flush_ringbuffer().
bool initialize_supplemental_groups = false
Referenced by buddy_supp_groups(), and opt_parse().
buddy_cmnd_t last_command = UPK_CTRL_NONE [static]
Referenced by buddy_handle_command(), and buddy_record_state().
struct timespec nanotimeout [static]
Initial value:
 {.tv_sec = BUDDY_RETRY_TIMEOUT_SEC,.tv_nsec =
        BUDDY_RETRY_TIMEOUT_NSEC }
size_t ncount = 0 [static]
Referenced by read_ctrl(), and write_ctrl().
char** proc_envp = NULL
Referenced by buddy_exec_action(), and main().
pid_t proc_pid = 0 [static]
Referenced by buddy_cleanup(), buddy_exec_action(), buddy_handle_command(), buddy_record_state(), buddy_reload_proc(), buddy_start_proc(), buddy_stop_proc(), deserial_svcinfo_data(), sa_sigaction_func(), and serial_svcinfo_data().
bool randomize_ratelimit = false
uint32_t rapid_respawn_count = 0 [static]
Referenced by buddy_start_proc().
long reconnect_retries = 5
Referenced by opt_parse(), and phone_home_if_appropriate().
time_t respawn_timestamp = 0 [static]
Referenced by buddy_handle_flags(), and buddy_start_proc().
size_t ringbuffer_pending = 0 [static]
Referenced by buddy_flush_ringbuffer(), buddy_record_state(), buddy_zero_info(), and phone_home_if_appropriate().
size_t ringbuffer_size = 32
Referenced by buddy_free_ringbuffer(), buddy_init_ringbuffer(), buddy_record_state(), main(), opt_parse(), and phone_home_if_appropriate().
int sockopts = 0 [static]
Referenced by buddy_accept(), and upk_net_add_socket_handle().
buddy_cmnd_t this_command = UPK_CTRL_NONE [static]
Referenced by buddy_event_loop(), buddy_flush_ringbuffer(), and buddy_handle_command().
struct timeval timeout = {.tv_sec = BUDDY_SELECT_TIMEOUT_SEC,.tv_usec = BUDDY_SELECT_TIMEOUT_USEC } [static]
uint32_t user_ratelimit = 0