upkeeper: controller/buddy_main.c File Reference
controller/buddy_main.c File Reference
#include "buddy.h"
#include <getopt.h>
#include <stdio.h>
#include <errno.h>
Functions
static void buddy_usage (char *progname)
static bool numeric_string (const char *string, long *num)
static int opt_parse (int argc, char **argv, char **envp)
static void buddy_diag_handler (upk_diaglvl_t diaglvl, const char *label, const char *loc, const char *fmt, va_list ap)
int main (int argc, char **argv, char **envp)
Function Documentation
static void buddy_diag_handler (upk_diaglvl_t diaglvl, const char * label, const char * loc, const char * fmt, va_list ap) [static]
References upk_diag_verbosity, UPK_DIAGLVL_ALERT, UPK_DIAGLVL_CRIT, UPK_DIAGLVL_ERROR, UPK_DIAGLVL_FATAL, and UPK_DIAGLVL_INFO.
Referenced by main().
static void buddy_usage (char * progname) [static]
Referenced by opt_parse().
int main (int argc, char ** argv, char ** envp)
References buddy_cleanup(), buddy_diag_handler(), buddy_event_loop(), buddy_init(), opt_parse(), proc_envp, ringbuffer_size, and upk_diag_verbosity.
static bool numeric_string (const char * string, long * num) [inline, static]
Referenced by opt_parse().
static int opt_parse (int argc, char ** argv, char ** envp) [static]
< ringbuffer size
< ringbuffer size
< initialize supplemental groups
< initialize supplemental groups
< initialize supplemental groups
< clear supplemental groups
< clear supplemental groups
< clear supplemental groups
References BUDDY_MAX_STRING_LEN, buddy_root_path, buddy_service_name, buddy_setgid, buddy_setuid, buddy_usage(), buddy_uuid, calloc(), clear_supplemental_groups, initialize_supplemental_groups, is_valid_upk_uuid_string(), numeric_string(), reconnect_retries, ringbuffer_size, strnlen(), upk_diag_verbosity, and upk_string_to_uuid().
Referenced by main().