upkeeper: controller/buddy.h File Reference
controller/buddy.h File Reference
#include "buddyinc.h"
#include "ctrl_protocol.h"
#include <upkeeper/upk_error.h>
#include <upkeeper/upk_uuid.h>
#include <upkeeper/upk_types.h>
Defines
#define BUDDY_MAX_STRING_LEN UPK_MAX_STRING_LEN
#define BUDDY_MAX_PATH_LEN UPK_MAX_PATH_LEN
Functions
void buddy_init (diag_output_callback_t logger)
void commit_buddycide (int32_t signum)
int32_t buddy_event_loop (void)
void buddy_cleanup (void)
Variables
upk_uuid_t buddy_uuid
char * buddy_service_name
char buddy_root_path [8192]
uid_t buddy_setuid
gid_t buddy_setgid
size_t ringbuffer_size
char ** proc_envp
long reconnect_retries
bool randomize_ratelimit
bool initialize_supplemental_groups
bool clear_supplemental_groups
uint32_t user_ratelimit
Define Documentation
#define BUDDY_MAX_PATH_LEN UPK_MAX_PATH_LEN
Referenced by buddy_exec_action(), and buddy_init_paths().
#define BUDDY_MAX_STRING_LEN UPK_MAX_STRING_LEN
Referenced by opt_parse().
Function Documentation
void buddy_cleanup (void)
References buddy_flush_ringbuffer(), buddy_free_ringbuffer(), buddy_path(), buddy_service_name, buddy_stop_proc(), free(), and proc_pid.
Referenced by buddy_init(), commit_buddycide(), and main().
int32_t buddy_event_loop (void)
References buddy_accept(), buddy_build_fd_set(), buddy_ctrlfd, buddy_flush_ringbuffer(), buddy_handle_command(), buddy_handle_flags(), BUDDY_SELECT_TIMEOUT_SEC, BUDDY_SELECT_TIMEOUT_USEC, buddy_shutdown, buddy_sockfd, commit_buddycide(), highest_fd, read_ctrl(), select(), this_command, timeval::tv_sec, timeval::tv_usec, and upk_debug1.
Referenced by main().
void buddy_init (diag_output_callback_t logger)
References buddy_cleanup(), buddy_ctrlfd, buddy_init_paths(), buddy_init_ringbuffer(), buddy_init_socket(), buddy_path(), buddy_setgid, buddy_setuid, buddy_sockfd, sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, sigaction::sa_sigaction, sa_sigaction_func(), sigaction(), sigaddset(), sigemptyset(), sigfillset(), sigset(), upk_notice, upk_reg_diag_callback(), upk_verbose, and upk_warn.
Referenced by main().
void commit_buddycide (int32_t signum)
References buddy_cleanup(), getpid(), sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, sigaction(), sigemptyset(), sigfillset(), sigprocmask(), sigset(), and upk_debug1.
Referenced by buddy_event_loop().
Variable Documentation
char buddy_root_path[8192]
Referenced by buddy_init_paths(), and opt_parse().
char* buddy_service_name
Referenced by buddy_cleanup(), buddy_init_paths(), buddy_start_proc(), and opt_parse().
gid_t buddy_setgid
Referenced by buddy_init(), buddy_setreguid(), and opt_parse().
uid_t buddy_setuid
Referenced by buddy_init(), buddy_setreguid(), buddy_supp_groups(), and opt_parse().
upk_uuid_t buddy_uuid
Referenced by buddy_record_state(), opt_parse(), and spawn_buddy().
bool clear_supplemental_groups
Referenced by buddy_supp_groups(), and opt_parse().
bool initialize_supplemental_groups
Referenced by buddy_supp_groups(), and opt_parse().
char** proc_envp
Referenced by buddy_exec_action(), and main().
bool randomize_ratelimit
long reconnect_retries
Referenced by opt_parse(), and phone_home_if_appropriate().
size_t ringbuffer_size
Referenced by buddy_free_ringbuffer(), buddy_init_ringbuffer(), buddy_record_state(), main(), opt_parse(), and phone_home_if_appropriate().
uint32_t user_ratelimit