upkeeper: controller/controller.h File Reference
controller/controller.h File Reference
#include <upkeeper.h>
#include <stdio.h>
#include <ctrl_protocol.h>
Defines
#define UPK_CTRL_MAX_CLIENTS FD_SETSIZE
Functions
int socket_setup (const char *sock_path)
void handle_signals (void)
void handle_buddies (void)
int32_t ctrl_sock_setup (void)
void event_loop (int32_t listen_sock)
int upk_ctrl_init (void)
void create_buddy (upk_svc_desc_t *buddy)
void remove_buddy (upk_svc_desc_t *buddy)
int buddy_connect (const char *sockpath)
buddy_info_t * buddy_readstate (int fd)
bool kill_buddy (upk_svc_desc_t *buddy)
bool start_buddy_svc (upk_svc_desc_t *buddy)
bool stop_buddy_svc (upk_svc_desc_t *buddy)
bool reload_buddy_svc (upk_svc_desc_t *buddy)
Define Documentation
#define UPK_CTRL_MAX_CLIENTS FD_SETSIZE
Function Documentation
int buddy_connect (const char * sockpath)
References upk_alert.
Referenced by handle_buddies(), kill_buddy(), reload_buddy_svc(), start_buddy_svc(), and stop_buddy_svc().
buddy_info_t* buddy_readstate (int fd)
References _buddy_info::command, _buddy_info::desired_state, _buddy_info::remaining, _buddy_info::service_pid, _buddy_info::timestamp, UPK_CTRL_ACK, upk_debug0, upk_debug1, upk_uuid_to_string(), _buddy_info::uuid, _buddy_info::wait_pid, and _buddy_info::wait_status.
Referenced by send_buddy_cmd().
void create_buddy (upk_svc_desc_t * buddy)
References buddy_sock_path(), create_buddy_statedir(), spawn_buddy(), and UPK_MAX_PATH_LEN.
Referenced by main().
int32_t ctrl_sock_setup (void)
References _upk_controller_config::controller_socket, IF_UPK_ERROR, UPK_ERR_INIT, UPK_FUNC_ASSERT, UPK_FUNC_ASSERT_MSG, upk_runtime_configuration, and UPK_SOCKET_FAILURE.
Referenced by main().
void event_loop (int32_t listen_sock)
References accept_conn(), _upk_controller_config::BuddyPollingInterval, handle_buddies(), handle_signals(), upk_conn_handle_meta_t, upk_debug1, upk_net_conn_handle_init(), upk_net_event_dispatcher(), upk_net_flush_closed_sockets(), upk_runtime_configuration, and UPKLIST_FREE.
Referenced by main().
void handle_buddies (void)
References buddy_connect(), DEFAULT_BUDDY_ROOT, send_buddy_cmd(), UPK_CTRL_STATUS_REQ, and UPK_MAX_PATH_LEN.
Referenced by event_loop().
void handle_signals (void)
Referenced by event_loop().
bool kill_buddy (upk_svc_desc_t * buddy)
References buddy_connect(), buddy_sock_path(), send_buddy_cmd(), UPK_CTRL_SHUTDOWN, and UPK_MAX_PATH_LEN.
Referenced by remove_buddy().
bool reload_buddy_svc (upk_svc_desc_t * buddy)
References buddy_connect(), buddy_sock_path(), send_buddy_cmd(), UPK_CTRL_ACTION_RELOAD, and UPK_MAX_PATH_LEN.
Referenced by controller_packet_callback().
void remove_buddy (upk_svc_desc_t * buddy)
References kill_buddy(), and remove_buddy_statedir().
int socket_setup (const char * sock_path)
bool start_buddy_svc (upk_svc_desc_t * buddy)
References buddy_connect(), buddy_sock_path(), send_buddy_cmd(), UPK_CTRL_ACTION_START, and UPK_MAX_PATH_LEN.
Referenced by controller_packet_callback().
bool stop_buddy_svc (upk_svc_desc_t * buddy)
References buddy_connect(), buddy_sock_path(), send_buddy_cmd(), UPK_CTRL_ACTION_STOP, and UPK_MAX_PATH_LEN.
Referenced by controller_packet_callback().
int upk_ctrl_init (void)
References upk_ctrl_init_db(), upk_ctrl_load_config(), upk_db_path(), upk_load_runtime_services(), and UPK_MAX_PATH_LEN.
Referenced by main().