upkeeper: controller/tp.c File Reference
controller/tp.c File Reference
Data Structures
struct __fsid_t
struct __sigset_t
struct timespec
struct timeval
struct fd_set
union pthread_attr_t
struct __pthread_internal_list
union pthread_mutex_t
struct pthread_mutex_t::__pthread_mutex_s
union pthread_mutexattr_t
union pthread_cond_t
union pthread_condattr_t
union pthread_rwlock_t
union pthread_rwlockattr_t
union pthread_barrier_t
union pthread_barrierattr_t
union wait
union __WAIT_STATUS
struct div_t
struct ldiv_t
struct lldiv_t
struct siginfo
struct sigevent
struct sigaction
struct sigvec
struct _fpreg
struct _fpxreg
struct _xmmreg
struct _fpstate
struct sigcontext
struct sigstack
struct sigaltstack
struct _libc_fpxreg
struct _libc_xmmreg
struct _libc_fpstate
struct mcontext_t
struct ucontext
struct rlimit
struct rlimit64
struct rusage
struct iovec
struct sockaddr
struct sockaddr_storage
struct msghdr
struct cmsghdr
struct ucred
struct linger
struct osockaddr
union __SOCKADDR_ARG
union __CONST_SOCKADDR_ARG
struct in_addr
struct in6_addr
struct sockaddr_in
struct sockaddr_in6
struct ip_mreq
struct ip_mreq_source
struct ipv6_mreq
struct group_req
struct group_source_req
struct ip_msfilter
struct group_filter
struct ip_opts
struct ip_mreqn
struct in_pktinfo
struct in6_pktinfo
struct ip6_mtuinfo
struct sockaddr_un
struct timezone
struct itimerval
struct flock
struct flock64
struct stat
struct stat64
struct dirent64
struct __mbstate_t
struct _G_fpos_t
struct _G_fpos64_t
struct __gconv_trans_data
struct __gconv_step
struct __gconv_step_data
struct __gconv_info
union _G_iconv_t
struct _IO_marker
struct _IO_FILE
struct _IO_cookie_io_functions_t
struct _upk_uuid
structure for holding 16 byte UUID.
struct _upk_svcid
linked list of service identifiers.
struct _upk_cust_actscr_list
linked list of custom action scripts.
struct _upk_stringlist
struct _upk_svcinfo
see definition in *protocol_fields.h.
struct _upk_svcid_meta_p
struct _upk_cust_actscr_meta_p
struct _upk_stringlist_meta_p
struct _upk_json_data_output_options
struct _upk_svc_desc
service configuration.
struct upk_svc_desc_meta_p
struct _upk_controller_config
controller configuration.
struct upk_packet_t
struct upk_req_preamble_t
struct upk_repl_preamble_t
struct upk_generic_msg_t
struct upk_req_seq_start_t
struct upk_req_seq_end_t
struct upk_req_action_t
struct upk_req_signal_t
struct upk_req_list_t
struct upk_req_status_t
struct upk_req_subscribe_t
struct upk_req_unsubscribe_t
struct upk_req_disconnect_t
struct upk_repl_seq_start_t
struct upk_repl_seq_end_t
struct upk_repl_result_t
struct upk_repl_listing_t
struct upk_repl_svcinfo_t
struct upk_repl_ack_t
struct upk_repl_error_t
struct upk_pub_publication_t
struct upk_pub_cancelation_t
union _upk_payload_types
struct _upk_payload
struct upk_conn_handle_meta_p
struct _upk_netmsg_queue
this is a tailq for network message queuing
struct upk_netmsg_queue_meta_p
struct _upk_net_cb_stk
a callback-stack for use in nesting/branching expectations in a conversation
struct upk_net_cb_stk_meta_p
struct _upk_net_state
struct _upklist_userdata_state_partition
a struct to use as 'userdata' to be passed around, which partitions the 'userdata' segment into global state and then any other userdata you might care about.
struct _upk_conn_handle
struct v0_req_seq_start_t
struct v0_req_seq_end_t
struct v0_req_action_t
struct v0_req_signal_t
struct v0_req_list_t
struct v0_req_status_t
struct v0_req_subscribe_t
struct v0_req_unsubscribe_t
struct v0_req_disconnect_t
struct v0_repl_seq_start_t
struct v0_repl_seq_end_t
struct v0_repl_result_t
struct v0_repl_listing_t
struct v0_svcinfo_t
struct v0_repl_svcinfo_t
struct v0_repl_ack_t
struct v0_repl_error_t
struct v0_pub_publication_t
struct v0_pub_cancelation_t
struct tm
struct itimerspec
struct _buddy_info
information buddy returns.
struct _ctrl_sigqueue
struct ctrl_sigqueue_meta_p
Typedefs
typedef long unsigned int size_t
typedef unsigned char __u_char
typedef unsigned short int __u_short
typedef unsigned int __u_int
typedef unsigned long int __u_long
typedef signed char __int8_t
typedef unsigned char __uint8_t
typedef signed short int __int16_t
typedef unsigned short int __uint16_t
typedef signed int __int32_t
typedef unsigned int __uint32_t
typedef signed long int __int64_t
typedef unsigned long int __uint64_t
typedef long int __quad_t
typedef unsigned long int __u_quad_t
typedef unsigned long int __dev_t
typedef unsigned int __uid_t
typedef unsigned int __gid_t
typedef unsigned long int __ino_t
typedef unsigned long int __ino64_t
typedef unsigned int __mode_t
typedef unsigned long int __nlink_t
typedef long int __off_t
typedef long int __off64_t
typedef int __pid_t
typedef long int __clock_t
typedef unsigned long int __rlim_t
typedef unsigned long int __rlim64_t
typedef unsigned int __id_t
typedef long int __time_t
typedef unsigned int __useconds_t
typedef long int __suseconds_t
typedef int __daddr_t
typedef long int __swblk_t
typedef int __key_t
typedef int __clockid_t
typedef void * __timer_t
typedef long int __blksize_t
typedef long int __blkcnt_t
typedef long int __blkcnt64_t
typedef unsigned long int __fsblkcnt_t
typedef unsigned long int __fsblkcnt64_t
typedef unsigned long int __fsfilcnt_t
typedef unsigned long int __fsfilcnt64_t
typedef long int __ssize_t
typedef __off64_t __loff_t
typedef __quad_t * __qaddr_t
typedef char * __caddr_t
typedef long int __intptr_t
typedef unsigned int __socklen_t
typedef __u_char u_char
typedef __u_short u_short
typedef __u_int u_int
typedef __u_long u_long
typedef __quad_t quad_t
typedef __u_quad_t u_quad_t
typedef __fsid_t fsid_t
typedef __loff_t loff_t
typedef __ino_t ino_t
typedef __ino64_t ino64_t
typedef __dev_t dev_t
typedef __gid_t gid_t
typedef __mode_t mode_t
typedef __nlink_t nlink_t
typedef __uid_t uid_t
typedef __off_t off_t
typedef __off64_t off64_t
typedef __pid_t pid_t
typedef __id_t id_t
typedef __ssize_t ssize_t
typedef __daddr_t daddr_t
typedef __caddr_t caddr_t
typedef __key_t key_t
typedef __clock_t clock_t
typedef __time_t time_t
typedef __clockid_t clockid_t
typedef __timer_t timer_t
typedef __useconds_t useconds_t
typedef __suseconds_t suseconds_t
typedef unsigned long int ulong
typedef unsigned short int ushort
typedef unsigned int uint
typedef int int8_t __attribute__ ((__mode__(__QI__)))
typedef int __sig_atomic_t
typedef __sigset_t sigset_t
typedef long int __fd_mask
typedef __fd_mask fd_mask
typedef __blksize_t blksize_t
typedef __blkcnt_t blkcnt_t
typedef __fsblkcnt_t fsblkcnt_t
typedef __fsfilcnt_t fsfilcnt_t
typedef __blkcnt64_t blkcnt64_t
typedef __fsblkcnt64_t fsblkcnt64_t
typedef __fsfilcnt64_t fsfilcnt64_t
typedef unsigned long int pthread_t
typedef struct
__pthread_internal_list __pthread_list_t
typedef unsigned int pthread_key_t
typedef int pthread_once_t
typedef volatile int pthread_spinlock_t
typedef unsigned char uint8_t
typedef unsigned short int uint16_t
typedef unsigned int uint32_t
typedef unsigned long int uint64_t
typedef signed char int_least8_t
typedef short int int_least16_t
typedef int int_least32_t
typedef long int int_least64_t
typedef unsigned char uint_least8_t
typedef unsigned short int uint_least16_t
typedef unsigned int uint_least32_t
typedef unsigned long int uint_least64_t
typedef signed char int_fast8_t
typedef long int int_fast16_t
typedef long int int_fast32_t
typedef long int int_fast64_t
typedef unsigned char uint_fast8_t
typedef unsigned long int uint_fast16_t
typedef unsigned long int uint_fast32_t
typedef unsigned long int uint_fast64_t
typedef long int intptr_t
typedef unsigned long int uintptr_t
typedef long int intmax_t
typedef unsigned long int uintmax_t
typedef int wchar_t
typedef struct siginfo siginfo_t
typedef struct sigevent sigevent_t
typedef struct sigaltstack stack_t
typedef long int greg_t
typedef greg_t gregset_t [23]
typedef struct _libc_fpstate * fpregset_t
typedef struct ucontext ucontext_t
typedef __rlim_t rlim_t
typedef __rlim64_t rlim64_t
typedef enum __rlimit_resource __rlimit_resource_t
typedef enum __rusage_who __rusage_who_t
typedef enum __priority_which __priority_which_t
typedef unsigned short int sa_family_t
typedef uint16_t in_port_t
typedef uint32_t in_addr_t
typedef struct timezone *__restrict __timezone_ptr_t
typedef enum __itimer_which __itimer_which_t
typedef struct __dirstream DIR
typedef struct _IO_FILE FILE
typedef struct _IO_FILE __FILE
typedef unsigned int wint_t
typedef int(* __gconv_fct)(struct __gconv_step *, struct __gconv_step_data *, __const unsigned char **, __const unsigned char *, unsigned char **, size_t *, int, int)
typedef wint_t(* __gconv_btowc_fct)(struct __gconv_step *, unsigned char)
typedef int(* __gconv_init_fct)(struct __gconv_step *)
typedef void(* __gconv_end_fct)(struct __gconv_step *)
typedef int(* __gconv_trans_fct)(struct __gconv_step *, struct __gconv_step_data *, void *, __const unsigned char *, __const unsigned char **, __const unsigned char *, unsigned char **, size_t *)
typedef int(* __gconv_trans_context_fct)(void *, __const unsigned char *, __const unsigned char *, unsigned char *, unsigned char *)
typedef int(* __gconv_trans_query_fct)(__const char *, __const char ***, size_t *)
typedef int(* __gconv_trans_init_fct)(void **, const char *)
typedef void(* __gconv_trans_end_fct)(void *)
typedef struct __gconv_info * __gconv_t
typedef __builtin_va_list __gnuc_va_list
typedef void _IO_lock_t
typedef struct _IO_FILE _IO_FILE
typedef __ssize_t __io_read_fn (void *__cookie, char *__buf, size_t __nbytes)
typedef __ssize_t __io_write_fn (void *__cookie, __const char *__buf, size_t __n)
typedef int __io_seek_fn (void *__cookie, __off64_t *__pos, int __w)
typedef int __io_close_fn (void *__cookie)
typedef __io_read_fn cookie_read_function_t
typedef __io_write_fn cookie_write_function_t
typedef __io_seek_fn cookie_seek_function_t
typedef __io_close_fn cookie_close_function_t
typedef _IO_cookie_io_functions_t cookie_io_functions_t
typedef struct _upk_uuid upk_uuid_t
typedef struct _upk_svcid upk_svcid_t
typedef struct
_upk_cust_actscr_list upk_cust_actscr_list_t
typedef struct _upk_stringlist upk_stringlist_t
typedef struct _upk_svcinfo upk_svcinfo_t
typedef struct _upk_svcid_meta_p upk_svcid_meta_t
typedef struct
_upk_cust_actscr_meta_p upk_cust_actscr_meta_t
typedef struct
_upk_stringlist_meta_p upk_stringlist_meta_t
typedef void(* err_rpt_callback_t)(upk_errno_t)
typedef void(* err_rpt_msg_callback_t)(upk_errno_t, const char *)
typedef void(* diag_output_callback_t)(upk_diaglvl_t diaglvl, const char *label, const char *loc, const char *fmt, va_list ap)
typedef struct
_upk_json_data_output_options upk_json_data_output_opts_t
typedef struct _upk_svc_desc upk_svc_desc_t
typedef struct upk_svc_desc_meta_p upk_svc_desc_meta_t
typedef struct
_upk_controller_config upk_controller_config_t
typedef unsigned char upk_pkt_buf_t
typedef enum _upk_msgtype upk_msgtype_t
typedef union _upk_payload_types upk_payload_types_u
typedef struct _upk_payload upk_payload_t
typedef struct _upk_conn_handle upk_conn_handle_t
typedef struct
upk_conn_handle_meta_p upk_conn_handle_meta_t
typedef void(* upk_net_callback_t)(upk_conn_handle_meta_t *handles, upk_payload_t *msg)
typedef struct _upk_netmsg_queue upk_netmsg_queue_t
typedef struct
upk_netmsg_queue_meta_p upk_netmsg_queue_meta_t
typedef struct _upk_net_cb_stk upk_net_cb_stk_t
typedef struct
upk_net_cb_stk_meta_p upk_net_cb_stk_meta_t
typedef struct _upk_net_state upk_net_state_t
typedef struct
_upklist_userdata_state_partition upklist_userdata_state_partition_t
typedef upk_conn_handle_t upk_protocol_handle_t
typedef enum _buddy_cmnd buddy_cmnd_t
typedef struct _buddy_info buddy_info_t
typedef struct sqlite3 sqlite3
typedef long long int sqlite_int64
typedef unsigned long long int sqlite_uint64
typedef int(* sqlite3_callback)(void *, int, char **, char **)
typedef struct sqlite3_stmt sqlite3_stmt
typedef struct sqlite3_context sqlite3_context
typedef struct Mem sqlite3_value
typedef struct _ctrl_sigqueue ctrl_sigqueue_t
typedef struct ctrl_sigqueue_meta_p ctrl_sigqueue_meta_t
Enumerations
enum {
_SC_ARG_MAX, _SC_CHILD_MAX, _SC_CLK_TCK, _SC_NGROUPS_MAX,
_SC_OPEN_MAX, _SC_STREAM_MAX, _SC_TZNAME_MAX, _SC_JOB_CONTROL,
_SC_SAVED_IDS, _SC_REALTIME_SIGNALS, _SC_PRIORITY_SCHEDULING, _SC_TIMERS,
_SC_ASYNCHRONOUS_IO, _SC_PRIORITIZED_IO, _SC_SYNCHRONIZED_IO, _SC_FSYNC,
_SC_MAPPED_FILES, _SC_MEMLOCK, _SC_MEMLOCK_RANGE, _SC_MEMORY_PROTECTION,
_SC_MESSAGE_PASSING, _SC_SEMAPHORES, _SC_SHARED_MEMORY_OBJECTS, _SC_AIO_LISTIO_MAX,
_SC_AIO_MAX, _SC_AIO_PRIO_DELTA_MAX, _SC_DELAYTIMER_MAX, _SC_MQ_OPEN_MAX,
_SC_MQ_PRIO_MAX, _SC_VERSION, _SC_PAGESIZE, _SC_RTSIG_MAX,
_SC_SEM_NSEMS_MAX, _SC_SEM_VALUE_MAX, _SC_SIGQUEUE_MAX, _SC_TIMER_MAX,
_SC_BC_BASE_MAX, _SC_BC_DIM_MAX, _SC_BC_SCALE_MAX, _SC_BC_STRING_MAX,
_SC_COLL_WEIGHTS_MAX, _SC_EQUIV_CLASS_MAX, _SC_EXPR_NEST_MAX, _SC_LINE_MAX,
_SC_RE_DUP_MAX, _SC_CHARCLASS_NAME_MAX, _SC_2_VERSION, _SC_2_C_BIND,
_SC_2_C_DEV, _SC_2_FORT_DEV, _SC_2_FORT_RUN, _SC_2_SW_DEV,
_SC_2_LOCALEDEF, _SC_PII, _SC_PII_XTI, _SC_PII_SOCKET,
_SC_PII_INTERNET, _SC_PII_OSI, _SC_POLL, _SC_SELECT,
_SC_UIO_MAXIOV, _SC_IOV_MAX = _SC_UIO_MAXIOV, _SC_PII_INTERNET_STREAM, _SC_PII_INTERNET_DGRAM,
_SC_PII_OSI_COTS, _SC_PII_OSI_CLTS, _SC_PII_OSI_M, _SC_T_IOV_MAX,
_SC_THREADS, _SC_THREAD_SAFE_FUNCTIONS, _SC_GETGR_R_SIZE_MAX, _SC_GETPW_R_SIZE_MAX,
_SC_LOGIN_NAME_MAX, _SC_TTY_NAME_MAX, _SC_THREAD_DESTRUCTOR_ITERATIONS, _SC_THREAD_KEYS_MAX,
_SC_THREAD_STACK_MIN, _SC_THREAD_THREADS_MAX, _SC_THREAD_ATTR_STACKADDR, _SC_THREAD_ATTR_STACKSIZE,
_SC_THREAD_PRIORITY_SCHEDULING, _SC_THREAD_PRIO_INHERIT, _SC_THREAD_PRIO_PROTECT, _SC_THREAD_PROCESS_SHARED,
_SC_NPROCESSORS_CONF, _SC_NPROCESSORS_ONLN, _SC_PHYS_PAGES, _SC_AVPHYS_PAGES,
_SC_ATEXIT_MAX, _SC_PASS_MAX, _SC_XOPEN_VERSION, _SC_XOPEN_XCU_VERSION,
_SC_XOPEN_UNIX, _SC_XOPEN_CRYPT, _SC_XOPEN_ENH_I18N, _SC_XOPEN_SHM,
_SC_2_CHAR_TERM, _SC_2_C_VERSION, _SC_2_UPE, _SC_XOPEN_XPG2,
_SC_XOPEN_XPG3, _SC_XOPEN_XPG4, _SC_CHAR_BIT, _SC_CHAR_MAX,
_SC_CHAR_MIN, _SC_INT_MAX, _SC_INT_MIN, _SC_LONG_BIT,
_SC_WORD_BIT, _SC_MB_LEN_MAX, _SC_NZERO, _SC_SSIZE_MAX,
_SC_SCHAR_MAX, _SC_SCHAR_MIN, _SC_SHRT_MAX, _SC_SHRT_MIN,
_SC_UCHAR_MAX, _SC_UINT_MAX, _SC_ULONG_MAX, _SC_USHRT_MAX,
_SC_NL_ARGMAX, _SC_NL_LANGMAX, _SC_NL_MSGMAX, _SC_NL_NMAX,
_SC_NL_SETMAX, _SC_NL_TEXTMAX, _SC_XBS5_ILP32_OFF32, _SC_XBS5_ILP32_OFFBIG,
_SC_XBS5_LP64_OFF64, _SC_XBS5_LPBIG_OFFBIG, _SC_XOPEN_LEGACY, _SC_XOPEN_REALTIME,
_SC_XOPEN_REALTIME_THREADS, _SC_ADVISORY_INFO, _SC_BARRIERS, _SC_BASE,
_SC_C_LANG_SUPPORT, _SC_C_LANG_SUPPORT_R, _SC_CLOCK_SELECTION, _SC_CPUTIME,
_SC_THREAD_CPUTIME, _SC_DEVICE_IO, _SC_DEVICE_SPECIFIC, _SC_DEVICE_SPECIFIC_R,
_SC_FD_MGMT, _SC_FIFO, _SC_PIPE, _SC_FILE_ATTRIBUTES,
_SC_FILE_LOCKING, _SC_FILE_SYSTEM, _SC_MONOTONIC_CLOCK, _SC_MULTI_PROCESS,
_SC_SINGLE_PROCESS, _SC_NETWORKING, _SC_READER_WRITER_LOCKS, _SC_SPIN_LOCKS,
_SC_REGEXP, _SC_REGEX_VERSION, _SC_SHELL, _SC_SIGNALS,
_SC_SPAWN, _SC_SPORADIC_SERVER, _SC_THREAD_SPORADIC_SERVER, _SC_SYSTEM_DATABASE,
_SC_SYSTEM_DATABASE_R, _SC_TIMEOUTS, _SC_TYPED_MEMORY_OBJECTS, _SC_USER_GROUPS,
_SC_USER_GROUPS_R, _SC_2_PBS, _SC_2_PBS_ACCOUNTING, _SC_2_PBS_LOCATE,
_SC_2_PBS_MESSAGE, _SC_2_PBS_TRACK, _SC_SYMLOOP_MAX, _SC_STREAMS,
_SC_2_PBS_CHECKPOINT, _SC_V6_ILP32_OFF32, _SC_V6_ILP32_OFFBIG, _SC_V6_LP64_OFF64,
_SC_V6_LPBIG_OFFBIG, _SC_HOST_NAME_MAX, _SC_TRACE, _SC_TRACE_EVENT_FILTER,
_SC_TRACE_INHERIT, _SC_TRACE_LOG, _SC_LEVEL1_ICACHE_SIZE, _SC_LEVEL1_ICACHE_ASSOC,
_SC_LEVEL1_ICACHE_LINESIZE, _SC_LEVEL1_DCACHE_SIZE, _SC_LEVEL1_DCACHE_ASSOC, _SC_LEVEL1_DCACHE_LINESIZE,
_SC_LEVEL2_CACHE_SIZE, _SC_LEVEL2_CACHE_ASSOC, _SC_LEVEL2_CACHE_LINESIZE, _SC_LEVEL3_CACHE_SIZE,
_SC_LEVEL3_CACHE_ASSOC, _SC_LEVEL3_CACHE_LINESIZE, _SC_LEVEL4_CACHE_SIZE, _SC_LEVEL4_CACHE_ASSOC,
_SC_LEVEL4_CACHE_LINESIZE, _SC_IPV6 = _SC_LEVEL1_ICACHE_SIZE + 50, _SC_RAW_SOCKETS
}
enum {
_CS_PATH, _CS_V6_WIDTH_RESTRICTED_ENVS, _CS_GNU_LIBC_VERSION, _CS_GNU_LIBPTHREAD_VERSION,
_CS_LFS_CFLAGS = 1000, _CS_LFS_LDFLAGS, _CS_LFS_LIBS, _CS_LFS_LINTFLAGS,
_CS_LFS64_CFLAGS, _CS_LFS64_LDFLAGS, _CS_LFS64_LIBS, _CS_LFS64_LINTFLAGS,
_CS_XBS5_ILP32_OFF32_CFLAGS = 1100, _CS_XBS5_ILP32_OFF32_LDFLAGS, _CS_XBS5_ILP32_OFF32_LIBS, _CS_XBS5_ILP32_OFF32_LINTFLAGS,
_CS_XBS5_ILP32_OFFBIG_CFLAGS, _CS_XBS5_ILP32_OFFBIG_LDFLAGS, _CS_XBS5_ILP32_OFFBIG_LIBS, _CS_XBS5_ILP32_OFFBIG_LINTFLAGS,
_CS_XBS5_LP64_OFF64_CFLAGS, _CS_XBS5_LP64_OFF64_LDFLAGS, _CS_XBS5_LP64_OFF64_LIBS, _CS_XBS5_LP64_OFF64_LINTFLAGS,
_CS_XBS5_LPBIG_OFFBIG_CFLAGS, _CS_XBS5_LPBIG_OFFBIG_LDFLAGS, _CS_XBS5_LPBIG_OFFBIG_LIBS, _CS_XBS5_LPBIG_OFFBIG_LINTFLAGS,
_CS_POSIX_V6_ILP32_OFF32_CFLAGS, _CS_POSIX_V6_ILP32_OFF32_LDFLAGS, _CS_POSIX_V6_ILP32_OFF32_LIBS, _CS_POSIX_V6_ILP32_OFF32_LINTFLAGS,
_CS_POSIX_V6_ILP32_OFFBIG_CFLAGS, _CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS, _CS_POSIX_V6_ILP32_OFFBIG_LIBS, _CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS,
_CS_POSIX_V6_LP64_OFF64_CFLAGS, _CS_POSIX_V6_LP64_OFF64_LDFLAGS, _CS_POSIX_V6_LP64_OFF64_LIBS, _CS_POSIX_V6_LP64_OFF64_LINTFLAGS,
_CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS, _CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS, _CS_POSIX_V6_LPBIG_OFFBIG_LIBS, _CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS
}
enum {
SI_ASYNCNL = -60, SI_TKILL = -6, SI_SIGIO, SI_ASYNCIO,
SI_MESGQ, SI_TIMER, SI_QUEUE, SI_USER,
SI_KERNEL = 0x80
}
enum {
ILL_ILLOPC = 1, ILL_ILLOPN, ILL_ILLADR, ILL_ILLTRP,
ILL_PRVOPC, ILL_PRVREG, ILL_COPROC, ILL_BADSTK
}
enum {
FPE_INTDIV = 1, FPE_INTOVF, FPE_FLTDIV, FPE_FLTOVF,
FPE_FLTUND, FPE_FLTRES, FPE_FLTINV, FPE_FLTSUB
}
enum { SEGV_MAPERR = 1, SEGV_ACCERR }
enum { BUS_ADRALN = 1, BUS_ADRERR, BUS_OBJERR }
enum { TRAP_BRKPT = 1, TRAP_TRACE }
enum {
CLD_EXITED = 1, CLD_KILLED, CLD_DUMPED, CLD_TRAPPED,
CLD_STOPPED, CLD_CONTINUED
}
enum {
POLL_IN = 1, POLL_OUT, POLL_MSG, POLL_ERR,
POLL_PRI, POLL_HUP
}
enum { SIGEV_SIGNAL = 0, SIGEV_NONE, SIGEV_THREAD, SIGEV_THREAD_ID = 4 }
enum { SS_ONSTACK = 1, SS_DISABLE }
enum {
REG_R8 = 0, REG_R9, REG_R10, REG_R11,
REG_R12, REG_R13, REG_R14, REG_R15,
REG_RDI, REG_RSI, REG_RBP, REG_RBX,
REG_RDX, REG_RAX, REG_RCX, REG_RSP,
REG_RIP, REG_EFL, REG_CSGSFS, REG_ERR,
REG_TRAPNO, REG_OLDMASK, REG_CR2
}
enum __rusage_who {
RUSAGE_SELF = 0, RUSAGE_CHILDREN = -1, RUSAGE_THREAD = 1, RUSAGE_SELF = 0,
RUSAGE_CHILDREN = -1, RUSAGE_THREAD = 1
}
enum __priority_which {
PRIO_PROCESS = 0, PRIO_PGRP = 1, PRIO_USER = 2, PRIO_PROCESS = 0,
PRIO_PGRP = 1, PRIO_USER = 2
}
enum idtype_t {
P_ALL, P_PID, P_PGID, P_ALL,
P_PID, P_PGID
}
enum __socket_type {
SOCK_STREAM = 1, SOCK_DGRAM = 2, SOCK_RAW = 3, SOCK_RDM = 4,
SOCK_SEQPACKET = 5, SOCK_PACKET = 10, SOCK_STREAM = 1, SOCK_DGRAM = 2,
SOCK_RAW = 3, SOCK_RDM = 4, SOCK_SEQPACKET = 5, SOCK_PACKET = 10
}
enum {
MSG_OOB = 0x01, MSG_PEEK = 0x02, MSG_DONTROUTE = 0x04, MSG_TRYHARD = MSG_DONTROUTE,
MSG_CTRUNC = 0x08, MSG_PROXY = 0x10, MSG_TRUNC = 0x20, MSG_DONTWAIT = 0x40,
MSG_EOR = 0x80, MSG_WAITALL = 0x100, MSG_FIN = 0x200, MSG_SYN = 0x400,
MSG_CONFIRM = 0x800, MSG_RST = 0x1000, MSG_ERRQUEUE = 0x2000, MSG_NOSIGNAL = 0x4000,
MSG_MORE = 0x8000
}
enum { SCM_RIGHTS = 0x01, SCM_CREDENTIALS = 0x02 }
enum { SHUT_RD = 0, SHUT_WR, SHUT_RDWR }
enum {
IPPROTO_IP = 0, IPPROTO_HOPOPTS = 0, IPPROTO_ICMP = 1, IPPROTO_IGMP = 2,
IPPROTO_IPIP = 4, IPPROTO_TCP = 6, IPPROTO_EGP = 8, IPPROTO_PUP = 12,
IPPROTO_UDP = 17, IPPROTO_IDP = 22, IPPROTO_TP = 29, IPPROTO_IPV6 = 41,
IPPROTO_ROUTING = 43, IPPROTO_FRAGMENT = 44, IPPROTO_RSVP = 46, IPPROTO_GRE = 47,
IPPROTO_ESP = 50, IPPROTO_AH = 51, IPPROTO_ICMPV6 = 58, IPPROTO_NONE = 59,
IPPROTO_DSTOPTS = 60, IPPROTO_MTP = 92, IPPROTO_ENCAP = 98, IPPROTO_PIM = 103,
IPPROTO_COMP = 108, IPPROTO_SCTP = 132, IPPROTO_RAW = 255, IPPROTO_MAX
}
enum {
IPPORT_ECHO = 7, IPPORT_DISCARD = 9, IPPORT_SYSTAT = 11, IPPORT_DAYTIME = 13,
IPPORT_NETSTAT = 15, IPPORT_FTP = 21, IPPORT_TELNET = 23, IPPORT_SMTP = 25,
IPPORT_TIMESERVER = 37, IPPORT_NAMESERVER = 42, IPPORT_WHOIS = 43, IPPORT_MTP = 57,
IPPORT_TFTP = 69, IPPORT_RJE = 77, IPPORT_FINGER = 79, IPPORT_TTYLINK = 87,
IPPORT_SUPDUP = 95, IPPORT_EXECSERVER = 512, IPPORT_LOGINSERVER = 513, IPPORT_CMDSERVER = 514,
IPPORT_EFSSERVER = 520, IPPORT_BIFFUDP = 512, IPPORT_WHOSERVER = 513, IPPORT_ROUTESERVER = 520,
IPPORT_RESERVED = 1024, IPPORT_USERRESERVED = 5000
}
enum __itimer_which {
ITIMER_REAL = 0, ITIMER_VIRTUAL = 1, ITIMER_PROF = 2, ITIMER_REAL = 0,
ITIMER_VIRTUAL = 1, ITIMER_PROF = 2
}
enum {
DT_UNKNOWN = 0, DT_FIFO = 1, DT_CHR = 2, DT_DIR = 4,
DT_BLK = 6, DT_REG = 8, DT_LNK = 10, DT_SOCK = 12,
DT_WHT = 14
}
enum {
__GCONV_OK = 0, __GCONV_NOCONV, __GCONV_NODB, __GCONV_NOMEM,
__GCONV_EMPTY_INPUT, __GCONV_FULL_OUTPUT, __GCONV_ILLEGAL_INPUT, __GCONV_INCOMPLETE_INPUT,
__GCONV_ILLEGAL_DESCRIPTOR, __GCONV_INTERNAL_ERROR
}
enum { __GCONV_IS_LAST = 0x0001, __GCONV_IGNORE_ERRORS = 0x0002 }
enum __codecvt_result {
__codecvt_ok, __codecvt_partial, __codecvt_error, __codecvt_noconv,
__codecvt_ok, __codecvt_partial, __codecvt_error, __codecvt_noconv
}
enum upk_state_t {
UPK_STATE_UNDEFINED, UPK_STATE_RUNNING, UPK_STATE_STOPPED, UPK_STATE_SHUTDOWN,
UPK_STATE_UNDEFINED, UPK_STATE_RUNNING, UPK_STATE_STOPPED, UPK_STATE_SHUTDOWN,
UPK_STATE_UNDEFINED, UPK_STATE_RUNNING, UPK_STATE_STOPPED, UPK_STATE_SHUTDOWN
}
enum upk_signal_t {
UPK_SIG_HUP = 1, UPK_SIG_INT = 2, UPK_SIG_QUIT = 3, UPK_SIG_ILL = 4,
UPK_SIG_TRAP = 5, UPK_SIG_ABRT = 6, UPK_SIG_BUS = 7, UPK_SIG_FPE = 8,
UPK_SIG_KILL = 9, UPK_SIG_USR1 = 10, UPK_SIG_SEGV = 11, UPK_SIG_USR2 = 12,
UPK_SIG_PIPE = 13, UPK_SIG_ALRM = 14, UPK_SIG_TERM = 15, UPK_SIG_STKFLT = 16,
UPK_SIG_CHLD = 17, UPK_SIG_CONT = 18, UPK_SIG_STOP = 19, UPK_SIG_TSTP = 20,
UPK_SIG_TTIN = 21, UPK_SIG_TTOU = 22, UPK_SIG_URG = 23, UPK_SIG_XCPU = 24,
UPK_SIG_XFSZ = 25, UPK_SIG_VTALRM = 26, UPK_SIG_PROF = 27, UPK_SIG_WINCH = 28,
UPK_SIG_IO = 29, UPK_SIG_PWR = 30, UPK_SIG_SYS = 31, UPK_SIG_HUP = 1,
UPK_SIG_INT = 2, UPK_SIG_QUIT = 3, UPK_SIG_ILL = 4, UPK_SIG_TRAP = 5,
UPK_SIG_ABRT = 6, UPK_SIG_BUS = 7, UPK_SIG_FPE = 8, UPK_SIG_KILL = 9,
UPK_SIG_USR1 = 10, UPK_SIG_SEGV = 11, UPK_SIG_USR2 = 12, UPK_SIG_PIPE = 13,
UPK_SIG_ALRM = 14, UPK_SIG_TERM = 15, UPK_SIG_STKFLT = 16, UPK_SIG_CHLD = 17,
UPK_SIG_CONT = 18, UPK_SIG_STOP = 19, UPK_SIG_TSTP = 20, UPK_SIG_TTIN = 21,
UPK_SIG_TTOU = 22, UPK_SIG_URG = 23, UPK_SIG_XCPU = 24, UPK_SIG_XFSZ = 25,
UPK_SIG_VTALRM = 26, UPK_SIG_PROF = 27, UPK_SIG_WINCH = 28, UPK_SIG_IO = 29,
UPK_SIG_PWR = 30, UPK_SIG_SYS = 31, UPK_SIG_HUP = 1, UPK_SIG_INT = 2,
UPK_SIG_QUIT = 3, UPK_SIG_ILL = 4, UPK_SIG_TRAP = 5, UPK_SIG_ABRT = 6,
UPK_SIG_BUS = 7, UPK_SIG_FPE = 8, UPK_SIG_KILL = 9, UPK_SIG_USR1 = 10,
UPK_SIG_SEGV = 11, UPK_SIG_USR2 = 12, UPK_SIG_PIPE = 13, UPK_SIG_ALRM = 14,
UPK_SIG_TERM = 15, UPK_SIG_STKFLT = 16, UPK_SIG_CHLD = 17, UPK_SIG_CONT = 18,
UPK_SIG_STOP = 19, UPK_SIG_TSTP = 20, UPK_SIG_TTIN = 21, UPK_SIG_TTOU = 22,
UPK_SIG_URG = 23, UPK_SIG_XCPU = 24, UPK_SIG_XFSZ = 25, UPK_SIG_VTALRM = 26,
UPK_SIG_PROF = 27, UPK_SIG_WINCH = 28, UPK_SIG_IO = 29, UPK_SIG_PWR = 30,
UPK_SIG_SYS = 31
}
enum upk_diaglvl_t {
UPK_DIAGLVL_FATAL = 0, UPK_DIAGLVL_ALERT, UPK_DIAGLVL_CRIT, UPK_DIAGLVL_ERROR,
UPK_DIAGLVL_WARN, UPK_DIAGLVL_NOTICE, UPK_DIAGLVL_VERBOSE, UPK_DIAGLVL_INFO,
UPK_DIAGLVL_DEBUG0, UPK_DIAGLVL_DEBUG1, UPK_DIAGLVL_FATAL = 0, UPK_DIAGLVL_ALERT,
UPK_DIAGLVL_CRIT, UPK_DIAGLVL_ERROR, UPK_DIAGLVL_WARN, UPK_DIAGLVL_NOTICE,
UPK_DIAGLVL_VERBOSE, UPK_DIAGLVL_INFO, UPK_DIAGLVL_DEBUG0, UPK_DIAGLVL_DEBUG1,
UPK_DIAGLVL_FATAL = 0, UPK_DIAGLVL_ALERT, UPK_DIAGLVL_CRIT, UPK_DIAGLVL_ERROR,
UPK_DIAGLVL_WARN, UPK_DIAGLVL_NOTICE, UPK_DIAGLVL_VERBOSE, UPK_DIAGLVL_INFO,
UPK_DIAGLVL_DEBUG0, UPK_DIAGLVL_DEBUG1
}
enum upk_errlevel_t { UPK_ERRLVL_ERROR, UPK_ERRLVL_ERROR, UPK_ERRLVL_ERROR }
enum upk_errno_t {
UPK_ERR_UNKNOWN = 0, UPK_ERR_UNSUP, UPK_ERR_INVALID_PKT, UPK_SOCKET_FAILURE,
UPK_JSON_PARSE_ERROR, UPK_SQL_ERROR, UPK_CONF_ERROR, UPK_ERR_UNKNOWN = 0,
UPK_ERR_UNSUP, UPK_ERR_INVALID_PKT, UPK_SOCKET_FAILURE, UPK_JSON_PARSE_ERROR,
UPK_SQL_ERROR, UPK_CONF_ERROR, UPK_ERR_UNKNOWN = 0, UPK_ERR_UNSUP,
UPK_ERR_INVALID_PKT, UPK_SOCKET_FAILURE, UPK_JSON_PARSE_ERROR, UPK_SQL_ERROR,
UPK_CONF_ERROR
}
enum upk_pkttype_t {
PKT_REQUEST = 1, PKT_REPLY, PKT_PUBMSG, PKT_V0_PROTO_LIMIT,
PKT_REQUEST = 1, PKT_REPLY, PKT_PUBMSG, PKT_V0_PROTO_LIMIT,
PKT_REQUEST = 1, PKT_REPLY, PKT_PUBMSG, PKT_V0_PROTO_LIMIT
}
enum _upk_msgtype {
UPK_REQ_ORIGIN = 1, UPK_REQ_PREAMBLE = 1, UPK_REQ_SEQ_START, UPK_REQ_SEQ_END,
UPK_REQ_ACTION, UPK_REQ_SIGNAL, UPK_REQ_LIST, UPK_REQ_STATUS,
UPK_REQ_SUBSCRIBE, UPK_REQ_UNSUBSCRIBE, UPK_REQ_DISCONNECT, UPK_REQ_V0_PROTO_LIMIT,
UPK_REQ_LIMIT, UPK_REPL_ORIGIN = 4096, UPK_REPL_PREAMBLE = 4096, UPK_REPL_SEQ_START,
UPK_REPL_SEQ_END, UPK_REPL_RESULT, UPK_REPL_LISTING, UPK_REPL_SVCINFO,
UPK_REPL_ACK, UPK_REPL_ERROR, UPK_REPL_V0_PROTO_LIMIT, UPK_REPL_LIMIT,
UPK_PUB_ORIGIN = 8192, UPK_PUB_PUBLICATION = 8192, UPK_PUB_CANCELATION, UPK_PUB_V0_PROTO_LIMIT,
UPK_PUB_LIMIT, UPK_REQ_ORIGIN = 1, UPK_REQ_PREAMBLE = 1, UPK_REQ_SEQ_START,
UPK_REQ_SEQ_END, UPK_REQ_ACTION, UPK_REQ_SIGNAL, UPK_REQ_LIST,
UPK_REQ_STATUS, UPK_REQ_SUBSCRIBE, UPK_REQ_UNSUBSCRIBE, UPK_REQ_DISCONNECT,
UPK_REQ_V0_PROTO_LIMIT, UPK_REQ_LIMIT, UPK_REPL_ORIGIN = 4096, UPK_REPL_PREAMBLE = 4096,
UPK_REPL_SEQ_START, UPK_REPL_SEQ_END, UPK_REPL_RESULT, UPK_REPL_LISTING,
UPK_REPL_SVCINFO, UPK_REPL_ACK, UPK_REPL_ERROR, UPK_REPL_V0_PROTO_LIMIT,
UPK_REPL_LIMIT, UPK_PUB_ORIGIN = 8192, UPK_PUB_PUBLICATION = 8192, UPK_PUB_CANCELATION,
UPK_PUB_V0_PROTO_LIMIT, UPK_PUB_LIMIT, UPK_REQ_ORIGIN = 1, UPK_REQ_PREAMBLE = 1,
UPK_REQ_SEQ_START, UPK_REQ_SEQ_END, UPK_REQ_ACTION, UPK_REQ_SIGNAL,
UPK_REQ_LIST, UPK_REQ_STATUS, UPK_REQ_SUBSCRIBE, UPK_REQ_UNSUBSCRIBE,
UPK_REQ_DISCONNECT, UPK_REQ_V0_PROTO_LIMIT, UPK_REQ_LIMIT, UPK_REPL_ORIGIN = 4096,
UPK_REPL_PREAMBLE = 4096, UPK_REPL_SEQ_START, UPK_REPL_SEQ_END, UPK_REPL_RESULT,
UPK_REPL_LISTING, UPK_REPL_SVCINFO, UPK_REPL_ACK, UPK_REPL_ERROR,
UPK_REPL_V0_PROTO_LIMIT, UPK_REPL_LIMIT, UPK_PUB_ORIGIN = 8192, UPK_PUB_PUBLICATION = 8192,
UPK_PUB_CANCELATION, UPK_PUB_V0_PROTO_LIMIT, UPK_PUB_LIMIT
}
enum _buddy_cmnd {
UPK_CTRL_NONE = 0, UPK_CTRL_ACK = 1, UPK_CTRL_SHUTDOWN, UPK_CTRL_STATUS_REQ,
UPK_CTRL_ACTION_START, UPK_CTRL_ACTION_STOP, UPK_CTRL_ACTION_RELOAD, UPK_CTRL_ACTION_RUNONCE,
UPK_CTRL_CUSTOM_ACTION_00, UPK_CTRL_CUSTOM_ACTION_01, UPK_CTRL_CUSTOM_ACTION_02, UPK_CTRL_CUSTOM_ACTION_03,
UPK_CTRL_CUSTOM_ACTION_04, UPK_CTRL_CUSTOM_ACTION_05, UPK_CTRL_CUSTOM_ACTION_06, UPK_CTRL_CUSTOM_ACTION_07,
UPK_CTRL_CUSTOM_ACTION_08, UPK_CTRL_CUSTOM_ACTION_09, UPK_CTRL_CUSTOM_ACTION_10, UPK_CTRL_CUSTOM_ACTION_11,
UPK_CTRL_CUSTOM_ACTION_12, UPK_CTRL_CUSTOM_ACTION_13, UPK_CTRL_CUSTOM_ACTION_14, UPK_CTRL_CUSTOM_ACTION_15,
UPK_CTRL_CUSTOM_ACTION_16, UPK_CTRL_CUSTOM_ACTION_17, UPK_CTRL_CUSTOM_ACTION_18, UPK_CTRL_CUSTOM_ACTION_19,
UPK_CTRL_CUSTOM_ACTION_20, UPK_CTRL_CUSTOM_ACTION_21, UPK_CTRL_CUSTOM_ACTION_22, UPK_CTRL_CUSTOM_ACTION_23,
UPK_CTRL_CUSTOM_ACTION_24, UPK_CTRL_CUSTOM_ACTION_25, UPK_CTRL_CUSTOM_ACTION_26, UPK_CTRL_CUSTOM_ACTION_27,
UPK_CTRL_CUSTOM_ACTION_28, UPK_CTRL_CUSTOM_ACTION_29, UPK_CTRL_CUSTOM_ACTION_30, UPK_CTRL_CUSTOM_ACTION_31,
UPK_CTRL_SIGNAL_01, UPK_CTRL_SIGNAL_02, UPK_CTRL_SIGNAL_03, UPK_CTRL_SIGNAL_04,
UPK_CTRL_SIGNAL_05, UPK_CTRL_SIGNAL_06, UPK_CTRL_SIGNAL_07, UPK_CTRL_SIGNAL_08,
UPK_CTRL_SIGNAL_09, UPK_CTRL_SIGNAL_10, UPK_CTRL_SIGNAL_11, UPK_CTRL_SIGNAL_12,
UPK_CTRL_SIGNAL_13, UPK_CTRL_SIGNAL_14, UPK_CTRL_SIGNAL_15, UPK_CTRL_SIGNAL_16,
UPK_CTRL_SIGNAL_17, UPK_CTRL_SIGNAL_18, UPK_CTRL_SIGNAL_19, UPK_CTRL_SIGNAL_20,
UPK_CTRL_SIGNAL_21, UPK_CTRL_SIGNAL_22, UPK_CTRL_SIGNAL_23, UPK_CTRL_SIGNAL_24,
UPK_CTRL_SIGNAL_25, UPK_CTRL_SIGNAL_26, UPK_CTRL_SIGNAL_27, UPK_CTRL_SIGNAL_28,
UPK_CTRL_SIGNAL_29, UPK_CTRL_SIGNAL_30, UPK_CTRL_SIGNAL_31, UPK_CTRL_SIGNAL_32,
UPK_CTRL_NONE = 0, UPK_CTRL_ACK = 1, UPK_CTRL_SHUTDOWN, UPK_CTRL_STATUS_REQ,
UPK_CTRL_ACTION_START, UPK_CTRL_ACTION_STOP, UPK_CTRL_ACTION_RELOAD, UPK_CTRL_ACTION_RUNONCE,
UPK_CTRL_CUSTOM_ACTION_00, UPK_CTRL_CUSTOM_ACTION_01, UPK_CTRL_CUSTOM_ACTION_02, UPK_CTRL_CUSTOM_ACTION_03,
UPK_CTRL_CUSTOM_ACTION_04, UPK_CTRL_CUSTOM_ACTION_05, UPK_CTRL_CUSTOM_ACTION_06, UPK_CTRL_CUSTOM_ACTION_07,
UPK_CTRL_CUSTOM_ACTION_08, UPK_CTRL_CUSTOM_ACTION_09, UPK_CTRL_CUSTOM_ACTION_10, UPK_CTRL_CUSTOM_ACTION_11,
UPK_CTRL_CUSTOM_ACTION_12, UPK_CTRL_CUSTOM_ACTION_13, UPK_CTRL_CUSTOM_ACTION_14, UPK_CTRL_CUSTOM_ACTION_15,
UPK_CTRL_CUSTOM_ACTION_16, UPK_CTRL_CUSTOM_ACTION_17, UPK_CTRL_CUSTOM_ACTION_18, UPK_CTRL_CUSTOM_ACTION_19,
UPK_CTRL_CUSTOM_ACTION_20, UPK_CTRL_CUSTOM_ACTION_21, UPK_CTRL_CUSTOM_ACTION_22, UPK_CTRL_CUSTOM_ACTION_23,
UPK_CTRL_CUSTOM_ACTION_24, UPK_CTRL_CUSTOM_ACTION_25, UPK_CTRL_CUSTOM_ACTION_26, UPK_CTRL_CUSTOM_ACTION_27,
UPK_CTRL_CUSTOM_ACTION_28, UPK_CTRL_CUSTOM_ACTION_29, UPK_CTRL_CUSTOM_ACTION_30, UPK_CTRL_CUSTOM_ACTION_31,
UPK_CTRL_SIGNAL_01, UPK_CTRL_SIGNAL_02, UPK_CTRL_SIGNAL_03, UPK_CTRL_SIGNAL_04,
UPK_CTRL_SIGNAL_05, UPK_CTRL_SIGNAL_06, UPK_CTRL_SIGNAL_07, UPK_CTRL_SIGNAL_08,
UPK_CTRL_SIGNAL_09, UPK_CTRL_SIGNAL_10, UPK_CTRL_SIGNAL_11, UPK_CTRL_SIGNAL_12,
UPK_CTRL_SIGNAL_13, UPK_CTRL_SIGNAL_14, UPK_CTRL_SIGNAL_15, UPK_CTRL_SIGNAL_16,
UPK_CTRL_SIGNAL_17, UPK_CTRL_SIGNAL_18, UPK_CTRL_SIGNAL_19, UPK_CTRL_SIGNAL_20,
UPK_CTRL_SIGNAL_21, UPK_CTRL_SIGNAL_22, UPK_CTRL_SIGNAL_23, UPK_CTRL_SIGNAL_24,
UPK_CTRL_SIGNAL_25, UPK_CTRL_SIGNAL_26, UPK_CTRL_SIGNAL_27, UPK_CTRL_SIGNAL_28,
UPK_CTRL_SIGNAL_29, UPK_CTRL_SIGNAL_30, UPK_CTRL_SIGNAL_31, UPK_CTRL_SIGNAL_32,
UPK_CTRL_NONE = 0, UPK_CTRL_ACK = 1, UPK_CTRL_SHUTDOWN, UPK_CTRL_STATUS_REQ,
UPK_CTRL_ACTION_START, UPK_CTRL_ACTION_STOP, UPK_CTRL_ACTION_RELOAD, UPK_CTRL_ACTION_RUNONCE,
UPK_CTRL_CUSTOM_ACTION_00, UPK_CTRL_CUSTOM_ACTION_01, UPK_CTRL_CUSTOM_ACTION_02, UPK_CTRL_CUSTOM_ACTION_03,
UPK_CTRL_CUSTOM_ACTION_04, UPK_CTRL_CUSTOM_ACTION_05, UPK_CTRL_CUSTOM_ACTION_06, UPK_CTRL_CUSTOM_ACTION_07,
UPK_CTRL_CUSTOM_ACTION_08, UPK_CTRL_CUSTOM_ACTION_09, UPK_CTRL_CUSTOM_ACTION_10, UPK_CTRL_CUSTOM_ACTION_11,
UPK_CTRL_CUSTOM_ACTION_12, UPK_CTRL_CUSTOM_ACTION_13, UPK_CTRL_CUSTOM_ACTION_14, UPK_CTRL_CUSTOM_ACTION_15,
UPK_CTRL_CUSTOM_ACTION_16, UPK_CTRL_CUSTOM_ACTION_17, UPK_CTRL_CUSTOM_ACTION_18, UPK_CTRL_CUSTOM_ACTION_19,
UPK_CTRL_CUSTOM_ACTION_20, UPK_CTRL_CUSTOM_ACTION_21, UPK_CTRL_CUSTOM_ACTION_22, UPK_CTRL_CUSTOM_ACTION_23,
UPK_CTRL_CUSTOM_ACTION_24, UPK_CTRL_CUSTOM_ACTION_25, UPK_CTRL_CUSTOM_ACTION_26, UPK_CTRL_CUSTOM_ACTION_27,
UPK_CTRL_CUSTOM_ACTION_28, UPK_CTRL_CUSTOM_ACTION_29, UPK_CTRL_CUSTOM_ACTION_30, UPK_CTRL_CUSTOM_ACTION_31,
UPK_CTRL_SIGNAL_01, UPK_CTRL_SIGNAL_02, UPK_CTRL_SIGNAL_03, UPK_CTRL_SIGNAL_04,
UPK_CTRL_SIGNAL_05, UPK_CTRL_SIGNAL_06, UPK_CTRL_SIGNAL_07, UPK_CTRL_SIGNAL_08,
UPK_CTRL_SIGNAL_09, UPK_CTRL_SIGNAL_10, UPK_CTRL_SIGNAL_11, UPK_CTRL_SIGNAL_12,
UPK_CTRL_SIGNAL_13, UPK_CTRL_SIGNAL_14, UPK_CTRL_SIGNAL_15, UPK_CTRL_SIGNAL_16,
UPK_CTRL_SIGNAL_17, UPK_CTRL_SIGNAL_18, UPK_CTRL_SIGNAL_19, UPK_CTRL_SIGNAL_20,
UPK_CTRL_SIGNAL_21, UPK_CTRL_SIGNAL_22, UPK_CTRL_SIGNAL_23, UPK_CTRL_SIGNAL_24,
UPK_CTRL_SIGNAL_25, UPK_CTRL_SIGNAL_26, UPK_CTRL_SIGNAL_27, UPK_CTRL_SIGNAL_28,
UPK_CTRL_SIGNAL_29, UPK_CTRL_SIGNAL_30, UPK_CTRL_SIGNAL_31, UPK_CTRL_SIGNAL_32
}
enum buddy_runstate_t {
BUDDY_UNKNOWN = 0, BUDDY_STOPPED = 1, BUDDY_RUNNING, BUDDY_RANONCE,
BUDDY_UNKNOWN = 0, BUDDY_STOPPED = 1, BUDDY_RUNNING, BUDDY_RANONCE,
BUDDY_UNKNOWN = 0, BUDDY_STOPPED = 1, BUDDY_RUNNING, BUDDY_RANONCE
}
Functions
int select (int __nfds, fd_set *__restrict __readfds, fd_set *__restrict __writefds, fd_set *__restrict __exceptfds, struct timeval *__restrict __timeout)
int pselect (int __nfds, fd_set *__restrict __readfds, fd_set *__restrict __writefds, fd_set *__restrict __exceptfds, const struct timespec *__restrict __timeout, const __sigset_t *__restrict __sigmask)
__extension__ __inline unsigned int gnu_dev_major (unsigned long long int __dev) __attribute__((__nothrow__))
__extension__ __inline unsigned int gnu_dev_minor (unsigned long long int __dev) __attribute__((__nothrow__))
__extension__ __inline
unsigned long long int gnu_dev_makedev (unsigned int __major, unsigned int __minor) __attribute__((__nothrow__))
__extension__ __inline unsigned int __attribute__ ((__nothrow__))
size_t __ctype_get_mb_cur_max (void)
long int strtol_l (__const char *__restrict __nptr, char **__restrict __endptr, int __base, __locale_t __loc) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
long int unsigned long int strtoul_l (__const char *__restrict __nptr, char **__restrict __endptr, int __base, __locale_t __loc) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
long int unsigned long int
__extension__ long long int strtoll_l (__const char *__restrict __nptr, char **__restrict __endptr, int __base, __locale_t __loc) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
long int unsigned long int
__extension__ long long int
__extension__ unsigned long
long int strtoull_l (__const char *__restrict __nptr, char **__restrict __endptr, int __base, __locale_t __loc) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
long int unsigned long int
__extension__ long long int
__extension__ unsigned long
long int double strtod_l (__const char *__restrict __nptr, char **__restrict __endptr, __locale_t __loc) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
long int unsigned long int
__extension__ long long int
__extension__ unsigned long
long int double float strtof_l (__const char *__restrict __nptr, char **__restrict __endptr, __locale_t __loc) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
long int unsigned long int
__extension__ long long int
__extension__ unsigned long
long int double float long
double strtold_l (__const char *__restrict __nptr, char **__restrict __endptr, __locale_t __loc) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
long int unsigned long int
__extension__ long long int
__extension__ unsigned long
long int double float long
double double __strtod_internal (__const char *__restrict __nptr, char **__restrict __endptr, int __group) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
float __strtof_internal (__const char *__restrict __nptr, char **__restrict __endptr, int __group) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
long double __strtold_internal (__const char *__restrict __nptr, char **__restrict __endptr, int __group) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
long int __strtol_internal (__const char *__restrict __nptr, char **__restrict __endptr, int __base, int __group) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
unsigned long int __strtoul_internal (__const char *__restrict __nptr, char **__restrict __endptr, int __base, int __group) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
__extension__ long long int __strtoll_internal (__const char *__restrict __nptr, char **__restrict __endptr, int __base, int __group) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
__extension__ unsigned long
long int __strtoull_internal (__const char *__restrict __nptr, char **__restrict __endptr, int __base, int __group) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
char * l64a (long int __n) __attribute__((__nothrow__))
long int a64l (__const char *__s) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1)))
long int random (void)
int random_r (struct random_data *__restrict __buf, int32_t *__restrict __result) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
int int srandom_r (unsigned int __seed, struct random_data *__buf) __attribute__((__nothrow__)) __attribute__((__nonnull__(2)))
int initstate_r (unsigned int __seed, char *__restrict __statebuf, size_t __statelen, struct random_data *__restrict __buf) __attribute__((__nothrow__)) __attribute__((__nonnull__(2
int int setstate_r (char *__restrict __statebuf, struct random_data *__restrict __buf) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
int int int rand (void)
int drand48_r (struct drand48_data *__restrict __buffer, double *__restrict __result) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
int int erand48_r (unsigned short int __xsubi[3], struct drand48_data *__restrict __buffer, double *__restrict __result) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
int int int lrand48_r (struct drand48_data *__restrict __buffer, long int *__restrict __result) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
int int int int nrand48_r (unsigned short int __xsubi[3], struct drand48_data *__restrict __buffer, long int *__restrict __result) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
int int int int int mrand48_r (struct drand48_data *__restrict __buffer, long int *__restrict __result) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
int int int int int int jrand48_r (unsigned short int __xsubi[3], struct drand48_data *__restrict __buffer, long int *__restrict __result) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
int int int int int int int srand48_r (long int __seedval, struct drand48_data *__buffer) __attribute__((__nothrow__)) __attribute__((__nonnull__(2)))
int seed48_r (unsigned short int __seed16v[3], struct drand48_data *__buffer) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
int int lcong48_r (unsigned short int __param[7], struct drand48_data *__buffer) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
int int void * malloc (size_t __size) __attribute__((__nothrow__)) __attribute__((__malloc__))
void * calloc (size_t __nmemb, size_t __size) __attribute__((__nothrow__)) __attribute__((__malloc__))
void * realloc (void *__ptr, size_t __size) __attribute__((__nothrow__)) __attribute__((__malloc__)) __attribute__((__warn_unused_result__))
void free (void *__ptr) __attribute__((__nothrow__))
void cfree (void *__ptr) __attribute__((__nothrow__))
void * alloca (size_t __size) __attribute__((__nothrow__))
void * valloc (size_t __size) __attribute__((__nothrow__)) __attribute__((__malloc__))
int posix_memalign (void **__memptr, size_t __alignment, size_t __size) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
void abort (extern int on_exit((*__func)(int __status void)
long int pathconf (__const char *__path, int __name) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
long int fpathconf (int __fd, int __name) __attribute__((__nothrow__))
long int sysconf (int __name) __attribute__((__nothrow__))
size_t confstr (int __name, char *__buf, size_t __len) __attribute__((__nothrow__))
__pid_t getpid (void)
int sigemptyset (sigset_t *__set) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
int sigfillset (sigset_t *__set) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
int sigaddset (sigset_t *__set, int __signo) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
int sigdelset (sigset_t *__set, int __signo) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
int sigismember (__const sigset_t *__set, int __signo) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
int sigisemptyset (__const sigset_t *__set) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
int sigandset (sigset_t *__set, __const sigset_t *__left, __const sigset_t *__right) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
int int sigorset (sigset_t *__set, __const sigset_t *__left, __const sigset_t *__right) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
int sigprocmask (int __how, __const sigset_t *__restrict __set, sigset_t *__restrict __oset) __attribute__((__nothrow__))
int sigsuspend (__const sigset_t *__set) __attribute__((__nonnull__(1)))
int sigaction (int __sig, __const struct sigaction *__restrict __act, struct sigaction *__restrict __oact) __attribute__((__nothrow__))
int sigpending (sigset_t *__set) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
int sigwait (__const sigset_t *__restrict __set, int *__restrict __sig) __attribute__((__nonnull__(1
int int sigwaitinfo (__const sigset_t *__restrict __set, siginfo_t *__restrict __info) __attribute__((__nonnull__(1)))
int sigtimedwait (__const sigset_t *__restrict __set, siginfo_t *__restrict __info, __const struct timespec *__restrict __timeout) __attribute__((__nonnull__(1)))
int sigqueue (__pid_t __pid, int __sig, __const union sigval __val) __attribute__((__nothrow__))
int sigvec (int __sig, __const struct sigvec *__vec, struct sigvec *__ovec) __attribute__((__nothrow__))
int sigreturn (struct sigcontext *__scp) __attribute__((__nothrow__))
int siginterrupt (int __sig, int __interrupt) __attribute__((__nothrow__))
int sigstack (struct sigstack *__ss, struct sigstack *__oss) __attribute__((__nothrow__)) __attribute__((__deprecated__))
int sigaltstack (__const struct sigaltstack *__restrict __ss, struct sigaltstack *__restrict __oss) __attribute__((__nothrow__))
int sighold (int __sig) __attribute__((__nothrow__))
int sigrelse (int __sig) __attribute__((__nothrow__))
int sigignore (int __sig) __attribute__((__nothrow__))
__sighandler_t sigset (int __sig, __sighandler_t __disp) __attribute__((__nothrow__))
int pthread_sigmask (int __how, __const __sigset_t *__restrict __newmask, __sigset_t *__restrict __oldmask) __attribute__((__nothrow__))
int pthread_kill (pthread_t __threadid, int __signo) __attribute__((__nothrow__))
int __libc_current_sigrtmin (void)
int getrlimit (__rlimit_resource_t __resource, struct rlimit *__rlimits) __attribute__((__nothrow__))
int getrlimit64 (__rlimit_resource_t __resource, struct rlimit64 *__rlimits) __attribute__((__nothrow__))
int setrlimit (__rlimit_resource_t __resource, __const struct rlimit *__rlimits) __attribute__((__nothrow__))
int setrlimit64 (__rlimit_resource_t __resource, __const struct rlimit64 *__rlimits) __attribute__((__nothrow__))
int getrusage (__rusage_who_t __who, struct rusage *__usage) __attribute__((__nothrow__))
int getpriority (__priority_which_t __which, id_t __who) __attribute__((__nothrow__))
int setpriority (__priority_which_t __which, id_t __who, int __prio) __attribute__((__nothrow__))
__pid_t wait (__WAIT_STATUS __stat_loc)
__pid_t waitpid (__pid_t __pid, int *__stat_loc, int __options)
int waitid (idtype_t __idtype, __id_t __id, siginfo_t *__infop, int __options)
__pid_t wait3 (__WAIT_STATUS __stat_loc, int __options, struct rusage *__usage) __attribute__((__nothrow__))
__pid_t wait4 (__pid_t __pid, __WAIT_STATUS __stat_loc, int __options, struct rusage *__usage) __attribute__((__nothrow__))
ssize_t readv (int __fd, __const struct iovec *__iovec, int __count)
ssize_t writev (int __fd, __const struct iovec *__iovec, int __count)
struct cmsghdr * __cmsg_nxthdr (struct msghdr *__mhdr, struct cmsghdr *__cmsg) __attribute__((__nothrow__))
int socket (int __domain, int __type, int __protocol) __attribute__((__nothrow__))
int socketpair (int __domain, int __type, int __protocol, int __fds[2]) __attribute__((__nothrow__))
int bind (int __fd, __CONST_SOCKADDR_ARG __addr, socklen_t __len) __attribute__((__nothrow__))
int getsockname (int __fd, __SOCKADDR_ARG __addr, socklen_t *__restrict __len) __attribute__((__nothrow__))
int connect (int __fd, __CONST_SOCKADDR_ARG __addr, socklen_t __len)
int getpeername (int __fd, __SOCKADDR_ARG __addr, socklen_t *__restrict __len) __attribute__((__nothrow__))
ssize_t send (int __fd, __const void *__buf, size_t __n, int __flags)
ssize_t recv (int __fd, void *__buf, size_t __n, int __flags)
ssize_t sendto (int __fd, __const void *__buf, size_t __n, int __flags, __CONST_SOCKADDR_ARG __addr, socklen_t __addr_len)
ssize_t recvfrom (int __fd, void *__restrict __buf, size_t __n, int __flags, __SOCKADDR_ARG __addr, socklen_t *__restrict __addr_len)
ssize_t sendmsg (int __fd, __const struct msghdr *__message, int __flags)
ssize_t recvmsg (int __fd, struct msghdr *__message, int __flags)
int getsockopt (int __fd, int __level, int __optname, void *__restrict __optval, socklen_t *__restrict __optlen) __attribute__((__nothrow__))
int setsockopt (int __fd, int __level, int __optname, __const void *__optval, socklen_t __optlen) __attribute__((__nothrow__))
int listen (int __fd, int __n) __attribute__((__nothrow__))
int accept (int __fd, __SOCKADDR_ARG __addr, socklen_t *__restrict __addr_len)
int shutdown (int __fd, int __how) __attribute__((__nothrow__))
int sockatmark (int __fd) __attribute__((__nothrow__))
int isfdtype (int __fd, int __fdtype) __attribute__((__nothrow__))
uint32_t ntohl (uint32_t __netlong) __attribute__((__nothrow__)) __attribute__((__const__))
uint16_t ntohs (uint16_t __netshort) __attribute__((__nothrow__)) __attribute__((__const__))
uint32_t htonl (uint32_t __hostlong) __attribute__((__nothrow__)) __attribute__((__const__))
uint16_t htons (uint16_t __hostshort) __attribute__((__nothrow__)) __attribute__((__const__))
int bindresvport (int __sockfd, struct sockaddr_in *__sock_in) __attribute__((__nothrow__))
int bindresvport6 (int __sockfd, struct sockaddr_in6 *__sock_in) __attribute__((__nothrow__))
int inet6_option_space (int __nbytes) __attribute__((__nothrow__)) __attribute__((__deprecated__))
int inet6_option_init (void *__bp, struct cmsghdr **__cmsgp, int __type) __attribute__((__nothrow__)) __attribute__((__deprecated__))
int inet6_option_append (struct cmsghdr *__cmsg, __const uint8_t *__typep, int __multx, int __plusy) __attribute__((__nothrow__)) __attribute__((__deprecated__))
uint8_t * inet6_option_alloc (struct cmsghdr *__cmsg, int __datalen, int __multx, int __plusy) __attribute__((__nothrow__)) __attribute__((__deprecated__))
int inet6_option_next (__const struct cmsghdr *__cmsg, uint8_t **__tptrp) __attribute__((__nothrow__)) __attribute__((__deprecated__))
int inet6_option_find (__const struct cmsghdr *__cmsg, uint8_t **__tptrp, int __type) __attribute__((__nothrow__)) __attribute__((__deprecated__))
int inet6_opt_init (void *__extbuf, socklen_t __extlen) __attribute__((__nothrow__))
int inet6_opt_append (void *__extbuf, socklen_t __extlen, int __offset, uint8_t __type, socklen_t __len, uint8_t __align, void **__databufp) __attribute__((__nothrow__))
int inet6_opt_finish (void *__extbuf, socklen_t __extlen, int __offset) __attribute__((__nothrow__))
int inet6_opt_set_val (void *__databuf, int __offset, void *__val, socklen_t __vallen) __attribute__((__nothrow__))
int inet6_opt_next (void *__extbuf, socklen_t __extlen, int __offset, uint8_t *__typep, socklen_t *__lenp, void **__databufp) __attribute__((__nothrow__))
int inet6_opt_find (void *__extbuf, socklen_t __extlen, int __offset, uint8_t __type, socklen_t *__lenp, void **__databufp) __attribute__((__nothrow__))
int inet6_opt_get_val (void *__databuf, int __offset, void *__val, socklen_t __vallen) __attribute__((__nothrow__))
socklen_t inet6_rth_space (int __type, int __segments) __attribute__((__nothrow__))
void * inet6_rth_init (void *__bp, socklen_t __bp_len, int __type, int __segments) __attribute__((__nothrow__))
int inet6_rth_add (void *__bp, __const struct in6_addr *__addr) __attribute__((__nothrow__))
int inet6_rth_reverse (__const void *__in, void *__out) __attribute__((__nothrow__))
int inet6_rth_segments (__const void *__bp) __attribute__((__nothrow__))
struct in6_addr * inet6_rth_getaddr (__const void *__bp, int __index) __attribute__((__nothrow__))
int getipv4sourcefilter (int __s, struct in_addr __interface_addr, struct in_addr __group, uint32_t *__fmode, uint32_t *__numsrc, struct in_addr *__slist) __attribute__((__nothrow__))
int setipv4sourcefilter (int __s, struct in_addr __interface_addr, struct in_addr __group, uint32_t __fmode, uint32_t __numsrc, __const struct in_addr *__slist) __attribute__((__nothrow__))
int getsourcefilter (int __s, uint32_t __interface_addr, __const struct sockaddr *__group, socklen_t __grouplen, uint32_t *__fmode, uint32_t *__numsrc, struct sockaddr_storage *__slist) __attribute__((__nothrow__))
int setsourcefilter (int __s, uint32_t __interface_addr, __const struct sockaddr *__group, socklen_t __grouplen, uint32_t __fmode, uint32_t __numsrc, __const struct sockaddr_storage *__slist) __attribute__((__nothrow__))
in_addr_t inet_addr (__const char *__cp) __attribute__((__nothrow__))
in_addr_t inet_lnaof (struct in_addr __in) __attribute__((__nothrow__))
struct in_addr inet_makeaddr (in_addr_t __net, in_addr_t __host) __attribute__((__nothrow__))
in_addr_t inet_netof (struct in_addr __in) __attribute__((__nothrow__))
in_addr_t inet_network (__const char *__cp) __attribute__((__nothrow__))
char * inet_ntoa (struct in_addr __in) __attribute__((__nothrow__))
int inet_pton (int __af, __const char *__restrict __cp, void *__restrict __buf) __attribute__((__nothrow__))
__const char * inet_ntop (int __af, __const void *__restrict __cp, char *__restrict __buf, socklen_t __len) __attribute__((__nothrow__))
int inet_aton (__const char *__cp, struct in_addr *__inp) __attribute__((__nothrow__))
char * inet_neta (in_addr_t __net, char *__buf, size_t __len) __attribute__((__nothrow__))
char * inet_net_ntop (int __af, __const void *__cp, int __bits, char *__buf, size_t __len) __attribute__((__nothrow__))
int inet_net_pton (int __af, __const char *__cp, void *__buf, size_t __len) __attribute__((__nothrow__))
unsigned int inet_nsap_addr (__const char *__cp, unsigned char *__buf, int __len) __attribute__((__nothrow__))
char * inet_nsap_ntoa (int __len, __const unsigned char *__cp, char *__buf) __attribute__((__nothrow__))
int gettimeofday (struct timeval *__restrict __tv, __timezone_ptr_t __tz) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
int settimeofday (__const struct timeval *__tv, __const struct timezone *__tz) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
int adjtime (__const struct timeval *__delta, struct timeval *__olddelta) __attribute__((__nothrow__))
int getitimer (__itimer_which_t __which, struct itimerval *__value) __attribute__((__nothrow__))
int setitimer (__itimer_which_t __which, __const struct itimerval *__restrict __new, struct itimerval *__restrict __old) __attribute__((__nothrow__))
int utimes (__const char *__file, __const struct timeval __tvp[2]) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
int lutimes (__const char *__file, __const struct timeval __tvp[2]) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
int futimes (int __fd, __const struct timeval __tvp[2]) __attribute__((__nothrow__))
int futimesat (int __fd, __const char *__file, __const struct timeval __tvp[2]) __attribute__((__nothrow__))
ssize_t readahead (int __fd, __off64_t __offset, size_t __count) __attribute__((__nothrow__))
int sync_file_range (int __fd, __off64_t __from, __off64_t __to, unsigned int __flags)
int vmsplice (int __fdout, const struct iovec *__iov, size_t __count, unsigned int __flags)
int splice (int __fdin, __off64_t *__offin, int __fdout, __off64_t *__offout, size_t __len, unsigned int __flags) __attribute__((__nothrow__))
int tee (int __fdin, int __fdout, size_t __len, unsigned int __flags) __attribute__((__nothrow__))
int stat (__const char *__restrict __file, struct stat *__restrict __buf) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
int int fstat (int __fd, struct stat *__buf) __attribute__((__nothrow__)) __attribute__((__nonnull__(2)))
int stat64 (__const char *__restrict __file, struct stat64 *__restrict __buf) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
int int fstat64 (int __fd, struct stat64 *__buf) __attribute__((__nothrow__)) __attribute__((__nonnull__(2)))
int fstatat (int __fd, __const char *__restrict __file, struct stat *__restrict __buf, int __flag) __attribute__((__nothrow__)) __attribute__((__nonnull__(2
int int fstatat64 (int __fd, __const char *__restrict __file, struct stat64 *__restrict __buf, int __flag) __attribute__((__nothrow__)) __attribute__((__nonnull__(2
int int int lstat (__const char *__restrict __file, struct stat *__restrict __buf) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
int int int int lstat64 (__const char *__restrict __file, struct stat64 *__restrict __buf) __attribute__((__nothrow__)) __attribute__((__nonnull__(1
int int int int int chmod (__const char *__file, __mode_t __mode) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
int lchmod (__const char *__file, __mode_t __mode) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
int fchmod (int __fd, __mode_t __mode) __attribute__((__nothrow__))
int fchmodat (int __fd, __const char *__file, __mode_t mode, int __flag) __attribute__((__nothrow__)) __attribute__((__nonnull__(2)))
__mode_t umask (__mode_t __mask) __attribute__((__nothrow__))
__mode_t getumask (void)
int fcntl (int __fd, int __cmd,...)
int open (__const char *__file, int __oflag,...) __attribute__((__nonnull__(1)))
int open64 (__const char *__file, int __oflag,...) __attribute__((__nonnull__(1)))
int openat (int __fd, __const char *__file, int __oflag,...) __attribute__((__nonnull__(2)))
int openat64 (int __fd, __const char *__file, int __oflag,...) __attribute__((__nonnull__(2)))
int creat (__const char *__file, __mode_t __mode) __attribute__((__nonnull__(1)))
int creat64 (__const char *__file, __mode_t __mode) __attribute__((__nonnull__(1)))
int posix_fadvise (int __fd, __off_t __offset, __off_t __len, int __advise) __attribute__((__nothrow__))
int posix_fadvise64 (int __fd, __off64_t __offset, __off64_t __len, int __advise) __attribute__((__nothrow__))
int posix_fallocate (int __fd, __off_t __offset, __off_t __len)
int posix_fallocate64 (int __fd, __off64_t __offset, __off64_t __len)
int flock (int __fd, int __operation) __attribute__((__nothrow__))
void __assert_fail (__const char *__assertion, __const char *__file, unsigned int __line, __const char *__function) __attribute__((__nothrow__)) __attribute__((__noreturn__))
void __assert_perror_fail (int __errnum, __const char *__file, unsigned int __line, __const char *__function) __attribute__((__nothrow__)) __attribute__((__noreturn__))
void __assert (const char *__assertion, const char *__file, int __line) __attribute__((__nothrow__)) __attribute__((__noreturn__))
int * __errno_location (void)
__const unsigned short int ** __ctype_b_loc (void)
DIR * opendir (__const char *__name) __attribute__((__nonnull__(1)))
DIR * fdopendir (int __fd)
int closedir (DIR *__dirp) __attribute__((__nonnull__(1)))
struct dirent * readdir (DIR *__dirp) __attribute__((__nonnull__(1)))
struct dirent64 * readdir64 (DIR *__dirp) __attribute__((__nonnull__(1)))
int readdir_r (DIR *__restrict __dirp, struct dirent *__restrict __entry, struct dirent **__restrict __result) __attribute__((__nonnull__(1
int int readdir64_r (DIR *__restrict __dirp, struct dirent64 *__restrict __entry, struct dirent64 **__restrict __result) __attribute__((__nonnull__(1
int int void rewinddir (DIR *__dirp) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
void seekdir (DIR *__dirp, long int __pos) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
long int telldir (DIR *__dirp) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
int dirfd (DIR *__dirp) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)))
int scandir (__const char *__restrict __dir, struct dirent ***__restrict __namelist, int(*__selector)(__const struct dirent *), int(*__cmp)(__const void *, __const void *)) __attribute__((__nonnull__(1
int int scandir64 (__const char *__restrict __dir, struct dirent64 ***__restrict __namelist, int(*__selector)(__const struct dirent64 *), int(*__cmp)(__const void *, __const void *)) __attribute__((__nonnull__(1
int int int alphasort (__const void *__e1, __const void *__e2) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1
int int int int alphasort64 (__const void *__e1, __const void *__e2) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1
int int int int int versionsort (__const void *__e1, __const void *__e2) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1
int int int int int int versionsort64 (__const void *__e1, __const void *__e2) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1
int int int int int int __ssize_t getdirentries (int __fd, char *__restrict __buf, size_t __nbytes, __off_t *__restrict __basep) __attribute__((__nothrow__)) __attribute__((__nonnull__(2
int int int int int int
__ssize_t __ssize_t getdirentries64 (int __fd, char *__restrict __buf, size_t __nbytes, __off64_t *__restrict __basep) __attribute__((__nothrow__)) __attribute__((__nonnull__(2
int int int int int int
__ssize_t __ssize_t char * dirname (char *__path) __attribute__((__nothrow__))
char * __xpg_basename (char *__path) __attribute__((__nothrow__))
void _IO_cookie_init (struct _IO_cookie_file *__cfile, int __read_write, void *__cookie, _IO_cookie_io_functions_t __fns)
int __underflow (_IO_FILE *)
int __uflow (_IO_FILE *)
int __overflow (_IO_FILE *, int)
wint_t __wunderflow (_IO_FILE *)
wint_t __wuflow (_IO_FILE *)
wint_t __woverflow (_IO_FILE *, wint_t)
int _IO_getc (_IO_FILE *__fp)
int _IO_putc (int __c, _IO_FILE *__fp)
int _IO_feof (_IO_FILE *__fp) __attribute__((__nothrow__))
int _IO_ferror (_IO_FILE *__fp) __attribute__((__nothrow__))
int _IO_peekc_locked (_IO_FILE *__fp)
void _IO_flockfile (_IO_FILE *)
void setpwent (void)
void endpwent (void)
struct passwd * getpwent (void)
struct passwd * fgetpwent (FILE *__stream)
int putpwent (__const struct passwd *__restrict __p, FILE *__restrict __f)
struct passwd * getpwuid (__uid_t __uid)
struct passwd * getpwnam (__const char *__name)
int getpwent_r (struct passwd *__restrict __resultbuf, char *__restrict __buffer, size_t __buflen, struct passwd **__restrict __result)
int getpwuid_r (__uid_t __uid, struct passwd *__restrict __resultbuf, char *__restrict __buffer, size_t __buflen, struct passwd **__restrict __result)
int getpwnam_r (__const char *__restrict __name, struct passwd *__restrict __resultbuf, char *__restrict __buffer, size_t __buflen, struct passwd **__restrict __result)
int fgetpwent_r (FILE *__restrict __stream, struct passwd *__restrict __resultbuf, char *__restrict __buffer, size_t __buflen, struct passwd **__restrict __result)
int getpw (__uid_t __uid, char *__buffer)
void upk_uuid_seed_random (void)
int upk_uuid_open_random (void)
void upk_gen_uuid_bytes (upk_uuid_t *buf)
void upk_uuid_to_string (char *buf, const upk_uuid_t *uuid)
_Bool is_valid_upk_uuid_string (const char *string)
void upk_string_to_uuid (upk_uuid_t *uuid, const char *string)
const char * upk_strerror (upk_errno_t err)
void upk_report_error (upk_errno_t err)
void upk_report_error_msg (upk_errno_t err, const char *msg)
err_rpt_callback_t upk_reg_error_callback (err_rpt_callback_t func)
err_rpt_msg_callback_t upk_reg_err_msg_callback (err_rpt_msg_callback_t func)
diag_output_callback_t upk_reg_diag_callback (diag_output_callback_t func)
int32_t _upk_fatal (const char *loc, const char *fmt,...)
int32_t _upk_alert (const char *loc, const char *fmt,...)
int32_t _upk_crit (const char *loc, const char *fmt,...)
int32_t _upk_error (const char *loc, const char *fmt,...)
int32_t _upk_warn (const char *loc, const char *fmt,...)
int32_t _upk_notice (const char *loc, const char *fmt,...)
int32_t _upk_info (const char *loc, const char *fmt,...)
int32_t _upk_verbose (const char *loc, const char *fmt,...)
int32_t _upk_debug0 (const char *loc, const char *fmt,...)
int32_t _upk_debug1 (const char *loc, const char *fmt,...)
void upk_svc_desc_free (upk_svc_desc_t *svc)
void upk_svclist_free (upk_svc_desc_meta_t *svclist)
void upk_ctrlconf_free (upk_controller_config_t *cfg)
void upk_ctrl_free_config (void)
void upk_svcconf_pack (upk_controller_config_t *cfg, const char *json_string)
void upk_ctrl_load_config (void)
void upk_svc_desc_clear (upk_svc_desc_t *svc)
char * upk_concat_svcid (char *dest, const char *pkg, const char *name)
char * upk_svc_id (char *dest, upk_svc_desc_t *svc)
void upk_parse_svc_id (char *key, upk_svc_desc_t *svc)
struct json_object * upk_svclist_to_json_obj (upk_svc_desc_meta_t *svclist)
struct json_object * upk_svc_desc_to_json_obj (upk_svc_desc_t *svc)
char * upk_json_serialize_svc_config (upk_svc_desc_t *svc, upk_json_data_output_opts_t opts)
void upk_overlay_svcconf_values (upk_svc_desc_t *dest, upk_svc_desc_t *high)
void upk_overlay_ctrlconf_values (upk_controller_config_t *dest, upk_controller_config_t *high)
void upk_finalize_svc_desc (upk_svc_desc_t *dest, upk_svc_desc_t *orig)
void upk_load_runtime_service_file (const char *filename)
void upk_load_runtime_services (void)
void upk_create_crc32_table (uint32_t crc_table[256])
uint32_t upk_crc32 (unsigned char *block, uint32_t len)
_Bool upk_verify_crc32 (unsigned char *block, uint32_t crc32, uint32_t len)
upk_pkt_buf_t * upk_serialize_packet (upk_packet_t *__upk_data_ptr)
upk_packet_t * upk_deserialize_packet (upk_pkt_buf_t *__upk_buf)
void * upk_deserialize_req_preamble (upk_pkt_buf_t *__upk_buf)
upk_pkt_buf_t * upk_serialize_req_preamble (void *__upk_data_ptr, size_t __upk_data_len)
void * upk_deserialize_repl_preamble (upk_pkt_buf_t *__upk_buf)
upk_pkt_buf_t * upk_serialize_repl_preamble (void *__upk_data_ptr, size_t __upk_data_len)
upk_packet_t * upk_create_pkt (void *payload, uint32_t payload_len, upk_pkttype_t pkttype, uint32_t proto_ver)
upk_packet_t * upk_create_req_preamble (upk_protocol_handle_t *handle, char *client_name)
upk_packet_t * upk_create_req_seq_start (upk_protocol_handle_t *handle, upk_msgtype_t seq_type, uint32_t count)
upk_packet_t * upk_create_req_seq_end (upk_protocol_handle_t *handle, _Bool commit)
upk_packet_t * upk_create_req_action (upk_protocol_handle_t *handle, char *svc_id, char *action)
upk_packet_t * upk_create_req_signal (upk_protocol_handle_t *handle, char *svc_id, upk_signal_t signal, _Bool signal_sid, _Bool signal_pgrp)
upk_packet_t * upk_create_req_list (upk_protocol_handle_t *handle)
upk_packet_t * upk_create_req_status (upk_protocol_handle_t *handle, char *svc_id, uint32_t restart_window_seconds)
upk_packet_t * upk_create_req_subscribe (upk_protocol_handle_t *handle, char *svc_id, _Bool all_svcs)
upk_packet_t * upk_create_req_unsubscribe (upk_protocol_handle_t *handle, char *svc_id, _Bool all_svcs)
upk_packet_t * upk_create_req_disconnect (upk_protocol_handle_t *handle)
upk_packet_t * upk_create_repl_preamble (upk_protocol_handle_t *handle, uint32_t best_version)
upk_packet_t * upk_create_repl_seq_start (upk_protocol_handle_t *handle, upk_msgtype_t seq_type, uint32_t count)
upk_packet_t * upk_create_repl_seq_end (upk_protocol_handle_t *handle, _Bool commit)
upk_packet_t * upk_create_repl_result (upk_protocol_handle_t *handle, char *msg, _Bool successful)
upk_packet_t * upk_create_repl_listing (upk_protocol_handle_t *handle, char *svc_id)
upk_packet_t * upk_create_repl_svcinfo (upk_protocol_handle_t *handle, char *svc_id, upk_svcinfo_t *svcinfo)
upk_packet_t * upk_create_repl_ack (upk_protocol_handle_t *handle)
upk_packet_t * upk_create_repl_error (upk_protocol_handle_t *handle, char *svc_id, upk_errno_t uerrno, char *errmsg, upk_errlevel_t errlvl)
upk_packet_t * upk_create_pub_publication (upk_protocol_handle_t *handle)
upk_packet_t * upk_create_pub_cancelation (upk_protocol_handle_t *handle)
void upk_pkt_free (upk_packet_t *pkt)
upk_msgtype_t upk_get_msgtype (upk_packet_t *pkt)
size_t upk_get_msgsize (upk_msgtype_t type)
upk_pkt_buf_t * v0_serialize_payload (upk_packet_t *pkt)
void * v0_deserialize_payload (upk_pkt_buf_t *__upk_buf, upk_pkttype_t pkttype)
upk_packet_t * v0_create_req_seq_start (upk_msgtype_t msg_seq_type, uint32_t msg_seq_count)
upk_packet_t * v0_create_req_seq_end (_Bool commit)
upk_packet_t * v0_create_req_action (char *svc_id, char *action)
upk_packet_t * v0_create_req_signal (char *svc_id, upk_signal_t signal, _Bool signal_sid, _Bool signal_pgrp)
upk_packet_t * v0_create_req_list (void)
upk_packet_t * v0_create_req_status (char *svc_id, uint32_t restart_window_seconds)
upk_packet_t * v0_create_req_subscribe (char *svc_id, _Bool all_svcs)
upk_packet_t * v0_create_req_unsubscribe (char *svc_id, _Bool all_svcs)
upk_packet_t * v0_create_req_disconnect (void)
upk_packet_t * v0_create_repl_seq_start (upk_msgtype_t msg_seq_type, uint32_t msg_seq_count)
upk_packet_t * v0_create_repl_seq_end (_Bool commit)
upk_packet_t * v0_create_repl_result (char *msg, _Bool successful)
upk_packet_t * v0_create_repl_listing (char *svc_id)
upk_packet_t * v0_create_repl_svcinfo (char *svc_id, v0_svcinfo_t *svcinfo)
upk_packet_t * v0_create_repl_ack (void)
upk_packet_t * v0_create_repl_error (char *svc_id, upk_errno_t uerrno, char *errmsg, upk_errlevel_t errlvl)
upk_packet_t * v0_create_pub_publication (void)
upk_packet_t * v0_create_pub_cancelation (void)
void v0_free_payload (upk_packet_t *pkt)
int upk_domain_socket_connect (const char *sockpath)
connect to a domain socket.
void upk_read_packets (upk_conn_handle_meta_t *handles)
read any packets from the handle handles->thisp, and call read-callbacks.
void upk_queue_packet (upk_conn_handle_meta_t *handles, upk_conn_handle_t *handle, upk_packet_t *pkt, upk_net_callback_t after_write_callback)
enqueue a packet for sending
void upk_write_packets (upk_conn_handle_meta_t *handles)
write the packets in the writeq for handles->thisp, and call any write callbacks
void upk_disconnect_handle (upk_conn_handle_meta_t *handles)
disconnect the ->thisp handle in handles.
_Bool upk_net_add_socket_handle (upk_conn_handle_meta_t *handles, int fd)
add a new socket handle to the handles list
void upk_net_event_dispatcher (upk_conn_handle_meta_t *handles, double poll_ival)
The event dispatcher, called via an event-loop.
void upk_net_flush_closed_sockets (upk_conn_handle_meta_t *handles)
iterate through the list of handles, and prune any that are no longer valid.
int upk_net_block_until_msg (upk_conn_handle_meta_t *handles, double poll_ival, struct timeval *timeout)
block until a complete message is received, up to timeout.
upk_conn_handle_meta_t * upk_net_conn_handles_init (void *userdata, void(*userdata_free_func)(void *ptr))
initialize connection handles
void upk_net_shutdown_callback (upk_conn_handle_meta_t *handles, upk_payload_t *msg)
wrapper around upk-disconnect_handle for use as a callback.
upk_net_state_t * upk_net_get_global_state (upk_conn_handle_meta_t *handles)
extract the nested global_state component from the generic (void *) userdata element
void upk_callback_stack_push (upk_conn_handle_t *handle, upk_net_cb_stk_t *state)
push a callback-stack state element onto the callback stack for a handle.
void upk_callback_stack_pop (upk_conn_handle_t *handle)
pop the top element off the callback-stack for a handle.
upk_payload_t * upk_clnet_serial_request (upk_conn_handle_meta_t *ctrl, upk_packet_t *pkt)
void upk_clnet_req_preamble (upk_conn_handle_meta_t *ctrl)
upk_conn_handle_meta_t * upk_clnet_ctrl_connect (void)
void upk_clnet_req_disconnect (upk_conn_handle_meta_t *ctrl)
void upk_clnet_ctrl_disconnect (upk_conn_handle_meta_t *ctrl)
_Bool upk_clnet_req_action (upk_conn_handle_meta_t *ctrl, char *svc_id, char *action)
_Bool upkeeper_action_request (char *service_id, char *action_name)
_Bool upkeeper_signal_request (char *service_id, upk_signal_t signal)
upk_svcid_t * upkeeper_list_services (void)
upk_svcinfo_t upkeeper_get_status (char *service_id)
_Bool upkeeper_subscribe (const char *svc_id)
_Bool upkeeper_subscribe_all (void)
char * upk_clientid (void)
_Bool upk_numeric_string (const char *string, long *num)
_Bool upk_boolean_string (const char *string, _Bool *val)
void upk_replace_string (char **haystack, const char *needle, const char *repl)
struct timeval upk_double_to_timeval (long double rational)
int upk_rm_rf (char *start_path)
int upk_mkdir_p (const char *path)
create a directory and any path components leading up to it.
clock_t clock (void)
void setgrent (void)
void endgrent (void)
struct group * getgrent (void)
struct group * fgetgrent (FILE *__stream)
int putgrent (__const struct group *__restrict __p, FILE *__restrict __f)
struct group * getgrgid (__gid_t __gid)
struct group * getgrnam (__const char *__name)
int getgrent_r (struct group *__restrict __resultbuf, char *__restrict __buffer, size_t __buflen, struct group **__restrict __result)
int getgrgid_r (__gid_t __gid, struct group *__restrict __resultbuf, char *__restrict __buffer, size_t __buflen, struct group **__restrict __result)
int getgrnam_r (__const char *__restrict __name, struct group *__restrict __resultbuf, char *__restrict __buffer, size_t __buflen, struct group **__restrict __result)
int fgetgrent_r (FILE *__restrict __stream, struct group *__restrict __resultbuf, char *__restrict __buffer, size_t __buflen, struct group **__restrict __result)
int setgroups (size_t __n, __const __gid_t *__groups) __attribute__((__nothrow__))
int getgrouplist (__const char *__user, __gid_t __group, __gid_t *__groups, int *__ngroups)
int initgroups (__const char *__user, __gid_t __group)
const char * sqlite3_libversion (void)
int sqlite3_libversion_number (void)
int sqlite3_close (sqlite3 *)
int sqlite3_exec (sqlite3 *, const char *sql, sqlite3_callback, void *, char **errmsg)
sqlite_int64 sqlite3_last_insert_rowid (sqlite3 *)
int sqlite3_changes (sqlite3 *)
int sqlite3_total_changes (sqlite3 *)
void sqlite3_interrupt (sqlite3 *)
int sqlite3_complete (const char *sql)
int sqlite3_complete16 (const void *sql)
int sqlite3_busy_handler (sqlite3 *, int(*)(void *, int), void *)
int sqlite3_busy_timeout (sqlite3 *, int ms)
int sqlite3_get_table (sqlite3 *, const char *sql, char ***resultp, int *nrow, int *ncolumn, char **errmsg)
void sqlite3_free_table (char **result)
char * sqlite3_mprintf (const char *,...)
char * sqlite3_vmprintf (const char *, va_list)
void sqlite3_free (char *z)
char * sqlite3_snprintf (int, char *, const char *,...)
int sqlite3_set_authorizer (sqlite3 *, int(*xAuth)(void *, int, const char *, const char *, const char *, const char *), void *pUserData)
void * sqlite3_trace (sqlite3 *, void(*xTrace)(void *, const char *), void *)
void * sqlite3_profile (sqlite3 *, void(*xProfile)(void *, const char *, sqlite_uint64), void *)
void sqlite3_progress_handler (sqlite3 *, int, int(*)(void *), void *)
void * sqlite3_commit_hook (sqlite3 *, int(*)(void *), void *)
int sqlite3_open (const char *filename, sqlite3 **ppDb)
int sqlite3_open16 (const void *filename, sqlite3 **ppDb)
int sqlite3_errcode (sqlite3 *db)
const char * sqlite3_errmsg (sqlite3 *)
const void * sqlite3_errmsg16 (sqlite3 *)
int sqlite3_prepare (sqlite3 *db, const char *zSql, int nBytes, sqlite3_stmt **ppStmt, const char **pzTail)
int sqlite3_prepare16 (sqlite3 *db, const void *zSql, int nBytes, sqlite3_stmt **ppStmt, const void **pzTail)
int sqlite3_bind_blob (sqlite3_stmt *, int, const void *, int n, void(*)(void *))
int sqlite3_bind_double (sqlite3_stmt *, int, double)
int sqlite3_bind_int (sqlite3_stmt *, int, int)
int sqlite3_bind_int64 (sqlite3_stmt *, int, sqlite_int64)
int sqlite3_bind_null (sqlite3_stmt *, int)
int sqlite3_bind_text (sqlite3_stmt *, int, const char *, int n, void(*)(void *))
int sqlite3_bind_text16 (sqlite3_stmt *, int, const void *, int, void(*)(void *))
int sqlite3_bind_value (sqlite3_stmt *, int, const sqlite3_value *)
int sqlite3_bind_parameter_count (sqlite3_stmt *)
const char * sqlite3_bind_parameter_name (sqlite3_stmt *, int)
int sqlite3_bind_parameter_index (sqlite3_stmt *, const char *zName)
int sqlite3_clear_bindings (sqlite3_stmt *)
int sqlite3_column_count (sqlite3_stmt *pStmt)
const char * sqlite3_column_name (sqlite3_stmt *, int)
const void * sqlite3_column_name16 (sqlite3_stmt *, int)
const char * sqlite3_column_database_name (sqlite3_stmt *, int)
const void * sqlite3_column_database_name16 (sqlite3_stmt *, int)
const char * sqlite3_column_table_name (sqlite3_stmt *, int)
const void * sqlite3_column_table_name16 (sqlite3_stmt *, int)
const char * sqlite3_column_origin_name (sqlite3_stmt *, int)
const void * sqlite3_column_origin_name16 (sqlite3_stmt *, int)
const char * sqlite3_column_decltype (sqlite3_stmt *, int i)
const void * sqlite3_column_decltype16 (sqlite3_stmt *, int)
int sqlite3_step (sqlite3_stmt *)
int sqlite3_data_count (sqlite3_stmt *pStmt)
const void * sqlite3_column_blob (sqlite3_stmt *, int iCol)
int sqlite3_column_bytes (sqlite3_stmt *, int iCol)
int sqlite3_column_bytes16 (sqlite3_stmt *, int iCol)
double sqlite3_column_double (sqlite3_stmt *, int iCol)
int sqlite3_column_int (sqlite3_stmt *, int iCol)
sqlite_int64 sqlite3_column_int64 (sqlite3_stmt *, int iCol)
const unsigned char * sqlite3_column_text (sqlite3_stmt *, int iCol)
const void * sqlite3_column_text16 (sqlite3_stmt *, int iCol)
int sqlite3_column_type (sqlite3_stmt *, int iCol)
int sqlite3_column_numeric_type (sqlite3_stmt *, int iCol)
int sqlite3_finalize (sqlite3_stmt *pStmt)
int sqlite3_reset (sqlite3_stmt *pStmt)
int sqlite3_create_function (sqlite3 *, const char *zFunctionName, int nArg, int eTextRep, void *, void(*xFunc)(sqlite3_context *, int, sqlite3_value **), void(*xStep)(sqlite3_context *, int, sqlite3_value **), void(*xFinal)(sqlite3_context *))
int sqlite3_create_function16 (sqlite3 *, const void *zFunctionName, int nArg, int eTextRep, void *, void(*xFunc)(sqlite3_context *, int, sqlite3_value **), void(*xStep)(sqlite3_context *, int, sqlite3_value **), void(*xFinal)(sqlite3_context *))
int sqlite3_aggregate_count (sqlite3_context *)
const void * sqlite3_value_blob (sqlite3_value *)
int sqlite3_value_bytes (sqlite3_value *)
int sqlite3_value_bytes16 (sqlite3_value *)
double sqlite3_value_double (sqlite3_value *)
int sqlite3_value_int (sqlite3_value *)
sqlite_int64 sqlite3_value_int64 (sqlite3_value *)
const unsigned char * sqlite3_value_text (sqlite3_value *)
const void * sqlite3_value_text16 (sqlite3_value *)
const void * sqlite3_value_text16le (sqlite3_value *)
const void * sqlite3_value_text16be (sqlite3_value *)
int sqlite3_value_type (sqlite3_value *)
int sqlite3_value_numeric_type (sqlite3_value *)
void * sqlite3_aggregate_context (sqlite3_context *, int nBytes)
void * sqlite3_user_data (sqlite3_context *)
void * sqlite3_get_auxdata (sqlite3_context *, int)
void sqlite3_set_auxdata (sqlite3_context *, int, void *, void(*)(void *))
void sqlite3_result_blob (sqlite3_context *, const void *, int, void(*)(void *))
void sqlite3_result_double (sqlite3_context *, double)
void sqlite3_result_error (sqlite3_context *, const char *, int)
void sqlite3_result_error16 (sqlite3_context *, const void *, int)
void sqlite3_result_int (sqlite3_context *, int)
void sqlite3_result_int64 (sqlite3_context *, sqlite_int64)
void sqlite3_result_null (sqlite3_context *)
void sqlite3_result_text (sqlite3_context *, const char *, int, void(*)(void *))
void sqlite3_result_text16 (sqlite3_context *, const void *, int, void(*)(void *))
void sqlite3_result_text16le (sqlite3_context *, const void *, int, void(*)(void *))
void sqlite3_result_text16be (sqlite3_context *, const void *, int, void(*)(void *))
void sqlite3_result_value (sqlite3_context *, sqlite3_value *)
int sqlite3_create_collation (sqlite3 *, const char *zName, int eTextRep, void *, int(*xCompare)(void *, int, const void *, int, const void *))
int sqlite3_create_collation16 (sqlite3 *, const char *zName, int eTextRep, void *, int(*xCompare)(void *, int, const void *, int, const void *))
int sqlite3_collation_needed (sqlite3 *, void *, void(*)(void *, sqlite3 *, int eTextRep, const char *))
int sqlite3_collation_needed16 (sqlite3 *, void *, void(*)(void *, sqlite3 *, int eTextRep, const void *))
int sqlite3_key (sqlite3 *db, const void *pKey, int nKey)
int sqlite3_rekey (sqlite3 *db, const void *pKey, int nKey)
int sqlite3_sleep (int)
int sqlite3_expired (sqlite3_stmt *)
int sqlite3_transfer_bindings (sqlite3_stmt *, sqlite3_stmt *)
int sqlite3_global_recover (void)
int sqlite3_get_autocommit (sqlite3 *)
sqlite3 * sqlite3_db_handle (sqlite3_stmt *)
void * sqlite3_update_hook (sqlite3 *, void(*)(void *, int, char const *, char const *, sqlite_int64), void *)
void * sqlite3_rollback_hook (sqlite3 *, void(*)(void *), void *)
int sqlite3_enable_shared_cache (int)
int sqlite3_release_memory (int)
void sqlite3_soft_heap_limit (int)
void sqlite3_thread_cleanup (void)
int sqlite3_table_column_metadata (sqlite3 *db, const char *zDbName, const char *zTableName, const char *zColumnName, char const **pzDataType, char const **pzCollSeq, int *pNotNull, int *pPrimaryKey, int *pAutoinc)
int socket_setup (const char *sock_path)
void handle_signals (void)
deal with signals pending action in signal_queue.
void handle_buddies (void)
int32_t ctrl_sock_setup (void)
setup controller's socket
void event_loop (int32_t listen_sock)
the main event loop.
int upk_ctrl_init (void)
void create_buddy (upk_svc_desc_t *buddy)
void remove_buddy (upk_svc_desc_t *buddy)
int buddy_connect (const char *sockpath)
buddy_info_t * buddy_readstate (int fd)
_Bool kill_buddy (upk_svc_desc_t *buddy)
_Bool start_buddy_svc (upk_svc_desc_t *buddy)
_Bool stop_buddy_svc (upk_svc_desc_t *buddy)
_Bool reload_buddy_svc (upk_svc_desc_t *buddy)
int upk_db_get_single_text (sqlite3 *dbh, char *value, const char *sql,...)
lookup a table_id from the schema table.
static int upk_db_get_table_id (sqlite3 *dbh, const char *db, const char *table_name, char *table_id)
int upk_db_get_audit_service_table (sqlite3 *dbh, char *table_id)
lookup the table_id for upk_audit.service from the schema table.
int upk_db_get_cfg_services_table (sqlite3 *dbh, char *table_id)
lookup the table_id for upk_cfg.services from the schema table.
int upk_db_get_cfg_svc_options_table (sqlite3 *dbh, char *table_id)
lookup the table_id for upk_cfg.svc_optionsfrom the schema table.
int upk_db_get_cfg_svc_list_options_table (sqlite3 *dbh, char *table_id)
char * upk_db_svc_uuid_lookup (sqlite3 *dbh, const char *svcid, const char *package)
lookup a service <package>-<name>
char * upk_db_gen_uuid (sqlite3 *dbh)
_Bool upk_db_add_new_service (sqlite3 *dbh, upk_svc_desc_t *svc)
static int upk_db_try_insert (sqlite3 *dbh, char *table_id, upk_svc_desc_t *svc, int type, char *optkey, void *optval, size_t len, char *section, char *id)
static int upk_db_try_update (sqlite3 *dbh, char *table_id, upk_svc_desc_t *svc, int type, char *optkey, void *optval, size_t len, char *section, char *id)
_Bool upk_db_upsert (sqlite3 *dbh, char *table_id, upk_svc_desc_t *svc, int type, char *optkey, void *optval, size_t len, char *section, char *id)
int32_t upk_db_upsert_options (sqlite3 *dbh, upk_svc_desc_t *svc)
_Bool upk_db_insert_cfg (sqlite3 *dbh, upk_svc_desc_t *svc)
Insert a configuration into the database.
Variables
const char * __progname
* __locale_t
sigval_t
__const char *__const _sys_siglist [65]
__const char *__const sys_siglist [65]
struct in6_addr in6addr_any
struct in6_addr in6addr_loopback
struct _IO_FILE_plus _IO_2_1_stdin_
struct _IO_FILE_plus _IO_2_1_stdout_
struct _IO_FILE_plus _IO_2_1_stderr_
static const char upk_diag_label_idx [][16]
static const char __upk_errors [][128]
char __upk_err_buf [4096]
upk_errno_t __upk_errno_type
int32_t upk_diag_verbosity
char label_idx [][16]
char upk_ctrl_configuration_file [8192]
const char upk_default_configuration_str []
upk_controller_config_t upk_default_configuration
upk_controller_config_t upk_file_configuration
upk_controller_config_t upk_runtime_configuration
const char sqlite3_version []
char * sqlite3_temp_directory
sqlite3 * ctrl_dbh
Typedef Documentation
typedef unsigned int _G_uint32_t __attribute__((__mode__(__SI__)))
typedef long int __blkcnt64_t
typedef long int __blkcnt_t
typedef long int __blksize_t
typedef char* __caddr_t
typedef long int __clock_t
typedef int __clockid_t
typedef int __daddr_t
typedef unsigned long int __dev_t
typedef long int __fd_mask
typedef struct _IO_FILE __FILE
typedef unsigned long int __fsblkcnt64_t
typedef unsigned long int __fsblkcnt_t
typedef unsigned long int __fsfilcnt64_t
typedef unsigned long int __fsfilcnt_t
typedef wint_t(* __gconv_btowc_fct)(struct __gconv_step *, unsigned char)
typedef void(* __gconv_end_fct)(struct __gconv_step *)
typedef int(* __gconv_fct)(struct __gconv_step *, struct __gconv_step_data *, __const unsigned char **, __const unsigned char *, unsigned char **, size_t *, int, int)
typedef int(* __gconv_init_fct)(struct __gconv_step *)
typedef struct __gconv_info * __gconv_t
typedef int(* __gconv_trans_context_fct)(void *, __const unsigned char *, __const unsigned char *, unsigned char *, unsigned char *)
typedef void(* __gconv_trans_end_fct)(void *)
typedef int(* __gconv_trans_fct)(struct __gconv_step *, struct __gconv_step_data *, void *, __const unsigned char *, __const unsigned char **, __const unsigned char *, unsigned char **, size_t *)
typedef int(* __gconv_trans_init_fct)(void **, const char *)
typedef int(* __gconv_trans_query_fct)(__const char *, __const char ***, size_t *)
typedef unsigned int __gid_t
typedef __builtin_va_list __gnuc_va_list
typedef unsigned int __id_t
typedef unsigned long int __ino64_t
typedef unsigned long int __ino_t
typedef signed short int __int16_t
typedef signed int __int32_t
typedef signed long int __int64_t
typedef signed char __int8_t
typedef long int __intptr_t
typedef int __io_close_fn(void *__cookie)
typedef __ssize_t __io_read_fn(void *__cookie, char *__buf, size_t __nbytes)
typedef int __io_seek_fn(void *__cookie, __off64_t *__pos, int __w)
typedef __ssize_t __io_write_fn(void *__cookie, __const char *__buf, size_t __n)
typedef enum __itimer_which __itimer_which_t
typedef int __key_t
typedef __off64_t __loff_t
typedef unsigned int __mode_t
typedef unsigned long int __nlink_t
typedef long int __off64_t
typedef long int __off_t
typedef int __pid_t
typedef enum __priority_which __priority_which_t
typedef struct __pthread_internal_list __pthread_list_t
typedef __quad_t* __qaddr_t
typedef long int __quad_t
typedef unsigned long int __rlim64_t
typedef unsigned long int __rlim_t
typedef enum __rlimit_resource __rlimit_resource_t
typedef enum __rusage_who __rusage_who_t
typedef int __sig_atomic_t
typedef unsigned int __socklen_t
typedef long int __ssize_t
typedef long int __suseconds_t
typedef long int __swblk_t
typedef long int __time_t
typedef void* __timer_t
typedef struct timezone* __restrict __timezone_ptr_t
typedef unsigned char __u_char
typedef unsigned int __u_int
typedef unsigned long int __u_long
typedef unsigned long int __u_quad_t
typedef unsigned short int __u_short
typedef unsigned int __uid_t
typedef unsigned short int __uint16_t
typedef unsigned int __uint32_t
typedef unsigned long int __uint64_t
typedef unsigned char __uint8_t
typedef unsigned int __useconds_t
typedef struct _IO_FILE _IO_FILE
typedef void _IO_lock_t
typedef __blkcnt64_t blkcnt64_t
typedef __blkcnt_t blkcnt_t
typedef __blksize_t blksize_t
typedef enum _buddy_cmnd buddy_cmnd_t
typedef struct _buddy_info buddy_info_t
typedef __caddr_t caddr_t
typedef __clock_t clock_t
typedef __clockid_t clockid_t
typedef __io_close_fn cookie_close_function_t
typedef _IO_cookie_io_functions_t cookie_io_functions_t
typedef __io_read_fn cookie_read_function_t
typedef __io_seek_fn cookie_seek_function_t
typedef __io_write_fn cookie_write_function_t
typedef struct ctrl_sigqueue_meta_p ctrl_sigqueue_meta_t
typedef struct _ctrl_sigqueue ctrl_sigqueue_t
typedef __daddr_t daddr_t
typedef __dev_t dev_t
typedef void(* diag_output_callback_t)(upk_diaglvl_t diaglvl, const char *label, const char *loc, const char *fmt, va_list ap)
typedef struct __dirstream DIR
typedef void(* err_rpt_callback_t)(upk_errno_t)
typedef void(* err_rpt_msg_callback_t)(upk_errno_t, const char *)
typedef __fd_mask fd_mask
typedef struct _IO_FILE FILE
typedef struct _libc_fpstate* fpregset_t
typedef __fsblkcnt64_t fsblkcnt64_t
typedef __fsblkcnt_t fsblkcnt_t
typedef __fsfilcnt64_t fsfilcnt64_t
typedef __fsfilcnt_t fsfilcnt_t
typedef __fsid_t fsid_t
typedef __gid_t gid_t
typedef long int greg_t
typedef greg_t gregset_t[23]
typedef __id_t id_t
typedef uint32_t in_addr_t
typedef uint16_t in_port_t
typedef __ino64_t ino64_t
typedef __ino_t ino_t
typedef long int int_fast16_t
typedef long int int_fast32_t
typedef long int int_fast64_t
typedef signed char int_fast8_t
typedef short int int_least16_t
typedef int int_least32_t
typedef long int int_least64_t
typedef signed char int_least8_t
typedef long int intmax_t
typedef long int intptr_t
typedef __key_t key_t
typedef __loff_t loff_t
typedef __mode_t mode_t
typedef __nlink_t nlink_t
typedef __off64_t off64_t
typedef __off_t off_t
typedef __pid_t pid_t
typedef unsigned int pthread_key_t
typedef int pthread_once_t
typedef volatile int pthread_spinlock_t
typedef unsigned long int pthread_t
typedef __quad_t quad_t
typedef __rlim64_t rlim64_t
typedef __rlim_t rlim_t
typedef unsigned short int sa_family_t
typedef struct sigevent sigevent_t
typedef struct siginfo siginfo_t
typedef __sigset_t sigset_t
typedef long unsigned int size_t
typedef struct sqlite3 sqlite3
typedef int(* sqlite3_callback)(void *, int, char **, char **)
typedef struct sqlite3_context sqlite3_context
typedef struct sqlite3_stmt sqlite3_stmt
typedef struct Mem sqlite3_value
typedef long long int sqlite_int64
typedef unsigned long long int sqlite_uint64
typedef __ssize_t ssize_t
typedef struct sigaltstack stack_t
typedef __suseconds_t suseconds_t
typedef __time_t time_t
typedef __timer_t timer_t
typedef __u_char u_char
typedef __u_int u_int
typedef __u_long u_long
typedef __u_quad_t u_quad_t
typedef __u_short u_short
typedef struct ucontext ucontext_t
typedef __uid_t uid_t
typedef unsigned int uint
typedef unsigned short int uint16_t
typedef unsigned int uint32_t
typedef unsigned long int uint64_t
typedef unsigned char uint8_t
typedef unsigned long int uint_fast16_t
typedef unsigned long int uint_fast32_t
typedef unsigned long int uint_fast64_t
typedef unsigned char uint_fast8_t
typedef unsigned short int uint_least16_t
typedef unsigned int uint_least32_t
typedef unsigned long int uint_least64_t
typedef unsigned char uint_least8_t
typedef unsigned long int uintmax_t
typedef unsigned long int uintptr_t
typedef unsigned long int ulong
typedef struct upk_conn_handle_meta_p upk_conn_handle_meta_t
typedef struct _upk_conn_handle upk_conn_handle_t
typedef struct _upk_controller_config upk_controller_config_t
typedef struct _upk_cust_actscr_list upk_cust_actscr_list_t
typedef struct _upk_cust_actscr_meta_p upk_cust_actscr_meta_t
typedef struct _upk_json_data_output_options upk_json_data_output_opts_t
typedef enum _upk_msgtype upk_msgtype_t
typedef void(* upk_net_callback_t)(upk_conn_handle_meta_t *handles, upk_payload_t *msg)
typedef struct upk_net_cb_stk_meta_p upk_net_cb_stk_meta_t
typedef struct _upk_net_cb_stk upk_net_cb_stk_t
typedef struct _upk_net_state upk_net_state_t
typedef struct upk_netmsg_queue_meta_p upk_netmsg_queue_meta_t
typedef struct _upk_netmsg_queue upk_netmsg_queue_t
typedef struct _upk_payload upk_payload_t
typedef union _upk_payload_types upk_payload_types_u
typedef unsigned char upk_pkt_buf_t
typedef upk_conn_handle_t upk_protocol_handle_t
typedef struct _upk_stringlist_meta_p upk_stringlist_meta_t
typedef struct _upk_stringlist upk_stringlist_t
typedef struct upk_svc_desc_meta_p upk_svc_desc_meta_t
typedef struct _upk_svc_desc upk_svc_desc_t
typedef struct _upk_svcid_meta_p upk_svcid_meta_t
typedef struct _upk_svcid upk_svcid_t
typedef struct _upk_svcinfo upk_svcinfo_t
typedef struct _upk_uuid upk_uuid_t
typedef struct _upklist_userdata_state_partition upklist_userdata_state_partition_t
typedef __useconds_t useconds_t
typedef unsigned short int ushort
typedef int wchar_t
typedef unsigned int wint_t
Enumeration Type Documentation
anonymous enum
Enumerator:
_SC_ARG_MAX
_SC_CHILD_MAX
_SC_CLK_TCK
_SC_NGROUPS_MAX
_SC_OPEN_MAX
_SC_STREAM_MAX
_SC_TZNAME_MAX
_SC_JOB_CONTROL
_SC_SAVED_IDS
_SC_REALTIME_SIGNALS
_SC_PRIORITY_SCHEDULING
_SC_TIMERS
_SC_ASYNCHRONOUS_IO
_SC_PRIORITIZED_IO
_SC_SYNCHRONIZED_IO
_SC_FSYNC
_SC_MAPPED_FILES
_SC_MEMLOCK
_SC_MEMLOCK_RANGE
_SC_MEMORY_PROTECTION
_SC_MESSAGE_PASSING
_SC_SEMAPHORES
_SC_SHARED_MEMORY_OBJECTS
_SC_AIO_LISTIO_MAX
_SC_AIO_MAX
_SC_AIO_PRIO_DELTA_MAX
_SC_DELAYTIMER_MAX
_SC_MQ_OPEN_MAX
_SC_MQ_PRIO_MAX
_SC_VERSION
_SC_PAGESIZE
_SC_RTSIG_MAX
_SC_SEM_NSEMS_MAX
_SC_SEM_VALUE_MAX
_SC_SIGQUEUE_MAX
_SC_TIMER_MAX
_SC_BC_BASE_MAX
_SC_BC_DIM_MAX
_SC_BC_SCALE_MAX
_SC_BC_STRING_MAX
_SC_COLL_WEIGHTS_MAX
_SC_EQUIV_CLASS_MAX
_SC_EXPR_NEST_MAX
_SC_LINE_MAX
_SC_RE_DUP_MAX
_SC_CHARCLASS_NAME_MAX
_SC_2_VERSION
_SC_2_C_BIND
_SC_2_C_DEV
_SC_2_FORT_DEV
_SC_2_FORT_RUN
_SC_2_SW_DEV
_SC_2_LOCALEDEF
_SC_PII
_SC_PII_XTI
_SC_PII_SOCKET
_SC_PII_INTERNET
_SC_PII_OSI
_SC_POLL
_SC_SELECT
_SC_UIO_MAXIOV
_SC_IOV_MAX
_SC_PII_INTERNET_STREAM
_SC_PII_INTERNET_DGRAM
_SC_PII_OSI_COTS
_SC_PII_OSI_CLTS
_SC_PII_OSI_M
_SC_T_IOV_MAX
_SC_THREADS
_SC_THREAD_SAFE_FUNCTIONS
_SC_GETGR_R_SIZE_MAX
_SC_GETPW_R_SIZE_MAX
_SC_LOGIN_NAME_MAX
_SC_TTY_NAME_MAX
_SC_THREAD_DESTRUCTOR_ITERATIONS
_SC_THREAD_KEYS_MAX
_SC_THREAD_STACK_MIN
_SC_THREAD_THREADS_MAX
_SC_THREAD_ATTR_STACKADDR
_SC_THREAD_ATTR_STACKSIZE
_SC_THREAD_PRIORITY_SCHEDULING
_SC_THREAD_PRIO_INHERIT
_SC_THREAD_PRIO_PROTECT
_SC_THREAD_PROCESS_SHARED
_SC_NPROCESSORS_CONF
_SC_NPROCESSORS_ONLN
_SC_PHYS_PAGES
_SC_AVPHYS_PAGES
_SC_ATEXIT_MAX
_SC_PASS_MAX
_SC_XOPEN_VERSION
_SC_XOPEN_XCU_VERSION
_SC_XOPEN_UNIX
_SC_XOPEN_CRYPT
_SC_XOPEN_ENH_I18N
_SC_XOPEN_SHM
_SC_2_CHAR_TERM
_SC_2_C_VERSION
_SC_2_UPE
_SC_XOPEN_XPG2
_SC_XOPEN_XPG3
_SC_XOPEN_XPG4
_SC_CHAR_BIT
_SC_CHAR_MAX
_SC_CHAR_MIN
_SC_INT_MAX
_SC_INT_MIN
_SC_LONG_BIT
_SC_WORD_BIT
_SC_MB_LEN_MAX
_SC_NZERO
_SC_SSIZE_MAX
_SC_SCHAR_MAX
_SC_SCHAR_MIN
_SC_SHRT_MAX
_SC_SHRT_MIN
_SC_UCHAR_MAX
_SC_UINT_MAX
_SC_ULONG_MAX
_SC_USHRT_MAX
_SC_NL_ARGMAX
_SC_NL_LANGMAX
_SC_NL_MSGMAX
_SC_NL_NMAX
_SC_NL_SETMAX
_SC_NL_TEXTMAX
_SC_XBS5_ILP32_OFF32
_SC_XBS5_ILP32_OFFBIG
_SC_XBS5_LP64_OFF64
_SC_XBS5_LPBIG_OFFBIG
_SC_XOPEN_LEGACY
_SC_XOPEN_REALTIME
_SC_XOPEN_REALTIME_THREADS
_SC_ADVISORY_INFO
_SC_BARRIERS
_SC_BASE
_SC_C_LANG_SUPPORT
_SC_C_LANG_SUPPORT_R
_SC_CLOCK_SELECTION
_SC_CPUTIME
_SC_THREAD_CPUTIME
_SC_DEVICE_IO
_SC_DEVICE_SPECIFIC
_SC_DEVICE_SPECIFIC_R
_SC_FD_MGMT
_SC_FIFO
_SC_PIPE
_SC_FILE_ATTRIBUTES
_SC_FILE_LOCKING
_SC_FILE_SYSTEM
_SC_MONOTONIC_CLOCK
_SC_MULTI_PROCESS
_SC_SINGLE_PROCESS
_SC_NETWORKING
_SC_READER_WRITER_LOCKS
_SC_SPIN_LOCKS
_SC_REGEXP
_SC_REGEX_VERSION
_SC_SHELL
_SC_SIGNALS
_SC_SPAWN
_SC_SPORADIC_SERVER
_SC_THREAD_SPORADIC_SERVER
_SC_SYSTEM_DATABASE
_SC_SYSTEM_DATABASE_R
_SC_TIMEOUTS
_SC_TYPED_MEMORY_OBJECTS
_SC_USER_GROUPS
_SC_USER_GROUPS_R
_SC_2_PBS
_SC_2_PBS_ACCOUNTING
_SC_2_PBS_LOCATE
_SC_2_PBS_MESSAGE
_SC_2_PBS_TRACK
_SC_SYMLOOP_MAX
_SC_STREAMS
_SC_2_PBS_CHECKPOINT
_SC_V6_ILP32_OFF32
_SC_V6_ILP32_OFFBIG
_SC_V6_LP64_OFF64
_SC_V6_LPBIG_OFFBIG
_SC_HOST_NAME_MAX
_SC_TRACE
_SC_TRACE_EVENT_FILTER
_SC_TRACE_INHERIT
_SC_TRACE_LOG
_SC_LEVEL1_ICACHE_SIZE
_SC_LEVEL1_ICACHE_ASSOC
_SC_LEVEL1_ICACHE_LINESIZE
_SC_LEVEL1_DCACHE_SIZE
_SC_LEVEL1_DCACHE_ASSOC
_SC_LEVEL1_DCACHE_LINESIZE
_SC_LEVEL2_CACHE_SIZE
_SC_LEVEL2_CACHE_ASSOC
_SC_LEVEL2_CACHE_LINESIZE
_SC_LEVEL3_CACHE_SIZE
_SC_LEVEL3_CACHE_ASSOC
_SC_LEVEL3_CACHE_LINESIZE
_SC_LEVEL4_CACHE_SIZE
_SC_LEVEL4_CACHE_ASSOC
_SC_LEVEL4_CACHE_LINESIZE
_SC_IPV6
_SC_RAW_SOCKETS
anonymous enum
Enumerator:
_CS_PATH
_CS_V6_WIDTH_RESTRICTED_ENVS
_CS_GNU_LIBC_VERSION
_CS_GNU_LIBPTHREAD_VERSION
_CS_LFS_CFLAGS
_CS_LFS_LDFLAGS
_CS_LFS_LIBS
_CS_LFS_LINTFLAGS
_CS_LFS64_CFLAGS
_CS_LFS64_LDFLAGS
_CS_LFS64_LIBS
_CS_LFS64_LINTFLAGS
_CS_XBS5_ILP32_OFF32_CFLAGS
_CS_XBS5_ILP32_OFF32_LDFLAGS
_CS_XBS5_ILP32_OFF32_LIBS
_CS_XBS5_ILP32_OFF32_LINTFLAGS
_CS_XBS5_ILP32_OFFBIG_CFLAGS
_CS_XBS5_ILP32_OFFBIG_LDFLAGS
_CS_XBS5_ILP32_OFFBIG_LIBS
_CS_XBS5_ILP32_OFFBIG_LINTFLAGS
_CS_XBS5_LP64_OFF64_CFLAGS
_CS_XBS5_LP64_OFF64_LDFLAGS
_CS_XBS5_LP64_OFF64_LIBS
_CS_XBS5_LP64_OFF64_LINTFLAGS
_CS_XBS5_LPBIG_OFFBIG_CFLAGS
_CS_XBS5_LPBIG_OFFBIG_LDFLAGS
_CS_XBS5_LPBIG_OFFBIG_LIBS
_CS_XBS5_LPBIG_OFFBIG_LINTFLAGS
_CS_POSIX_V6_ILP32_OFF32_CFLAGS
_CS_POSIX_V6_ILP32_OFF32_LDFLAGS
_CS_POSIX_V6_ILP32_OFF32_LIBS
_CS_POSIX_V6_ILP32_OFF32_LINTFLAGS
_CS_POSIX_V6_ILP32_OFFBIG_CFLAGS
_CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS
_CS_POSIX_V6_ILP32_OFFBIG_LIBS
_CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS
_CS_POSIX_V6_LP64_OFF64_CFLAGS
_CS_POSIX_V6_LP64_OFF64_LDFLAGS
_CS_POSIX_V6_LP64_OFF64_LIBS
_CS_POSIX_V6_LP64_OFF64_LINTFLAGS
_CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS
_CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS
_CS_POSIX_V6_LPBIG_OFFBIG_LIBS
_CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS
anonymous enum
Enumerator:
SIGEV_SIGNAL
SIGEV_NONE
SIGEV_THREAD
SIGEV_THREAD_ID
anonymous enum
Enumerator:
SS_ONSTACK
SS_DISABLE
anonymous enum
Enumerator:
REG_R8
REG_R9
REG_R10
REG_R11
REG_R12
REG_R13
REG_R14
REG_R15
REG_RDI
REG_RSI
REG_RBP
REG_RBX
REG_RDX
REG_RAX
REG_RCX
REG_RSP
REG_RIP
REG_EFL
REG_CSGSFS
REG_ERR
REG_TRAPNO
REG_OLDMASK
REG_CR2
anonymous enum
Enumerator:
MSG_OOB
MSG_PEEK
MSG_DONTROUTE
MSG_TRYHARD
MSG_CTRUNC
MSG_PROXY
MSG_TRUNC
MSG_DONTWAIT
MSG_EOR
MSG_WAITALL
MSG_FIN
MSG_SYN
MSG_CONFIRM
MSG_RST
MSG_ERRQUEUE
MSG_NOSIGNAL
MSG_MORE
anonymous enum
Enumerator:
SCM_RIGHTS
SCM_CREDENTIALS
anonymous enum
Enumerator:
SHUT_RD
SHUT_WR
SHUT_RDWR
anonymous enum
Enumerator:
IPPROTO_IP
IPPROTO_HOPOPTS
IPPROTO_ICMP
IPPROTO_IGMP
IPPROTO_IPIP
IPPROTO_TCP
IPPROTO_EGP
IPPROTO_PUP
IPPROTO_UDP
IPPROTO_IDP
IPPROTO_TP
IPPROTO_IPV6
IPPROTO_ROUTING
IPPROTO_FRAGMENT
IPPROTO_RSVP
IPPROTO_GRE
IPPROTO_ESP
IPPROTO_AH
IPPROTO_ICMPV6
IPPROTO_NONE
IPPROTO_DSTOPTS
IPPROTO_MTP
IPPROTO_ENCAP
IPPROTO_PIM
IPPROTO_COMP
IPPROTO_SCTP
IPPROTO_RAW
IPPROTO_MAX
anonymous enum
Enumerator:
IPPORT_ECHO
IPPORT_DISCARD
IPPORT_SYSTAT
IPPORT_DAYTIME
IPPORT_NETSTAT
IPPORT_FTP
IPPORT_TELNET
IPPORT_SMTP
IPPORT_TIMESERVER
IPPORT_NAMESERVER
IPPORT_WHOIS
IPPORT_MTP
IPPORT_TFTP
IPPORT_RJE
IPPORT_FINGER
IPPORT_TTYLINK
IPPORT_SUPDUP
IPPORT_EXECSERVER
IPPORT_LOGINSERVER
IPPORT_CMDSERVER
IPPORT_EFSSERVER
IPPORT_BIFFUDP
IPPORT_WHOSERVER
IPPORT_ROUTESERVER
IPPORT_RESERVED
IPPORT_USERRESERVED
anonymous enum
Enumerator:
DT_UNKNOWN
DT_FIFO
DT_CHR
DT_DIR
DT_BLK
DT_REG
DT_LNK
DT_SOCK
DT_WHT
anonymous enum
Enumerator:
__GCONV_OK
__GCONV_NOCONV
__GCONV_NODB
__GCONV_NOMEM
__GCONV_EMPTY_INPUT
__GCONV_FULL_OUTPUT
__GCONV_ILLEGAL_INPUT
__GCONV_INCOMPLETE_INPUT
__GCONV_ILLEGAL_DESCRIPTOR
__GCONV_INTERNAL_ERROR
anonymous enum
Enumerator:
SI_ASYNCNL
SI_TKILL
SI_SIGIO
SI_ASYNCIO
SI_MESGQ
SI_TIMER
SI_QUEUE
SI_USER
SI_KERNEL
anonymous enum
Enumerator:
__GCONV_IS_LAST
__GCONV_IGNORE_ERRORS
anonymous enum
Enumerator:
ILL_ILLOPC
ILL_ILLOPN
ILL_ILLADR
ILL_ILLTRP
ILL_PRVOPC
ILL_PRVREG
ILL_COPROC
ILL_BADSTK
anonymous enum
Enumerator:
FPE_INTDIV
FPE_INTOVF
FPE_FLTDIV
FPE_FLTOVF
FPE_FLTUND
FPE_FLTRES
FPE_FLTINV
FPE_FLTSUB
anonymous enum
Enumerator:
SEGV_MAPERR
SEGV_ACCERR
anonymous enum
Enumerator:
BUS_ADRALN
BUS_ADRERR
BUS_OBJERR
anonymous enum
Enumerator:
TRAP_BRKPT
TRAP_TRACE
anonymous enum
Enumerator:
CLD_EXITED
CLD_KILLED
CLD_DUMPED
CLD_TRAPPED
CLD_STOPPED
CLD_CONTINUED
anonymous enum
Enumerator:
POLL_IN
POLL_OUT
POLL_MSG
POLL_ERR
POLL_PRI
POLL_HUP
enum __codecvt_result
Enumerator:
__codecvt_ok
__codecvt_partial
__codecvt_error
__codecvt_noconv
__codecvt_ok
__codecvt_partial
__codecvt_error
__codecvt_noconv
enum __itimer_which
Enumerator:
ITIMER_REAL
ITIMER_VIRTUAL
ITIMER_PROF
ITIMER_REAL
ITIMER_VIRTUAL
ITIMER_PROF
enum __priority_which
Enumerator:
PRIO_PROCESS
PRIO_PGRP
PRIO_USER
PRIO_PROCESS
PRIO_PGRP
PRIO_USER
enum __rusage_who
Enumerator:
RUSAGE_SELF
RUSAGE_CHILDREN
RUSAGE_THREAD
RUSAGE_SELF
RUSAGE_CHILDREN
RUSAGE_THREAD
enum __socket_type
Enumerator:
SOCK_STREAM
SOCK_DGRAM
SOCK_RAW
SOCK_RDM
SOCK_SEQPACKET
SOCK_PACKET
SOCK_STREAM
SOCK_DGRAM
SOCK_RAW
SOCK_RDM
SOCK_SEQPACKET
SOCK_PACKET
enum _buddy_cmnd
Enumerator:
UPK_CTRL_NONE
unset
UPK_CTRL_ACK
controller received the last msg buddy sent it
UPK_CTRL_SHUTDOWN
buddy shutdown
UPK_CTRL_STATUS_REQ
report status to controller
UPK_CTRL_ACTION_START
UPK_CTRL_ACTION_STOP
run stop script, which should kill the monitored process
UPK_CTRL_ACTION_RELOAD
run reload script, which could, for example, send SIGHUP
UPK_CTRL_ACTION_RUNONCE
run a monitored process in a restarter... only once... ???
UPK_CTRL_CUSTOM_ACTION_00
run user-defined action 00
UPK_CTRL_CUSTOM_ACTION_01
run user-defined action 01
UPK_CTRL_CUSTOM_ACTION_02
run user-defined action 02
UPK_CTRL_CUSTOM_ACTION_03
run user-defined action 03
UPK_CTRL_CUSTOM_ACTION_04
run user-defined action 04
UPK_CTRL_CUSTOM_ACTION_05
run user-defined action 05
UPK_CTRL_CUSTOM_ACTION_06
run user-defined action 06
UPK_CTRL_CUSTOM_ACTION_07
run user-defined action 07
UPK_CTRL_CUSTOM_ACTION_08
run user-defined action 08
UPK_CTRL_CUSTOM_ACTION_09
run user-defined action 09
UPK_CTRL_CUSTOM_ACTION_10
run user-defined action 10
UPK_CTRL_CUSTOM_ACTION_11
run user-defined action 11
UPK_CTRL_CUSTOM_ACTION_12
run user-defined action 12
UPK_CTRL_CUSTOM_ACTION_13
run user-defined action 13
UPK_CTRL_CUSTOM_ACTION_14
run user-defined action 14
UPK_CTRL_CUSTOM_ACTION_15
run user-defined action 15
UPK_CTRL_CUSTOM_ACTION_16
run user-defined action 16
UPK_CTRL_CUSTOM_ACTION_17
run user-defined action 17
UPK_CTRL_CUSTOM_ACTION_18
run user-defined action 18
UPK_CTRL_CUSTOM_ACTION_19
run user-defined action 19
UPK_CTRL_CUSTOM_ACTION_20
run user-defined action 20
UPK_CTRL_CUSTOM_ACTION_21
run user-defined action 21
UPK_CTRL_CUSTOM_ACTION_22
run user-defined action 22
UPK_CTRL_CUSTOM_ACTION_23
run user-defined action 23
UPK_CTRL_CUSTOM_ACTION_24
run user-defined action 24
UPK_CTRL_CUSTOM_ACTION_25
run user-defined action 25
UPK_CTRL_CUSTOM_ACTION_26
run user-defined action 26
UPK_CTRL_CUSTOM_ACTION_27
run user-defined action 27
UPK_CTRL_CUSTOM_ACTION_28
run user-defined action 28
UPK_CTRL_CUSTOM_ACTION_29
run user-defined action 29
UPK_CTRL_CUSTOM_ACTION_30
run user-defined action 30
UPK_CTRL_CUSTOM_ACTION_31
run user-defined action 31
UPK_CTRL_SIGNAL_01
send managed process signal 01
UPK_CTRL_SIGNAL_02
send managed process signal 02
UPK_CTRL_SIGNAL_03
send managed process signal 03
UPK_CTRL_SIGNAL_04
send managed process signal 04
UPK_CTRL_SIGNAL_05
send managed process signal 05
UPK_CTRL_SIGNAL_06
send managed process signal 06
UPK_CTRL_SIGNAL_07
send managed process signal 07
UPK_CTRL_SIGNAL_08
send managed process signal 08
UPK_CTRL_SIGNAL_09
send managed process signal 09
UPK_CTRL_SIGNAL_10
send managed process signal 10
UPK_CTRL_SIGNAL_11
send managed process signal 11
UPK_CTRL_SIGNAL_12
send managed process signal 12
UPK_CTRL_SIGNAL_13
send managed process signal 13
UPK_CTRL_SIGNAL_14
send managed process signal 14
UPK_CTRL_SIGNAL_15
send managed process signal 15
UPK_CTRL_SIGNAL_16
send managed process signal 16
UPK_CTRL_SIGNAL_17
send managed process signal 17
UPK_CTRL_SIGNAL_18
send managed process signal 18
UPK_CTRL_SIGNAL_19
send managed process signal 19
UPK_CTRL_SIGNAL_20
send managed process signal 20
UPK_CTRL_SIGNAL_21
send managed process signal 21
UPK_CTRL_SIGNAL_22
send managed process signal 22
UPK_CTRL_SIGNAL_23
send managed process signal 23
UPK_CTRL_SIGNAL_24
send managed process signal 24
UPK_CTRL_SIGNAL_25
send managed process signal 25
UPK_CTRL_SIGNAL_26
send managed process signal 26
UPK_CTRL_SIGNAL_27
send managed process signal 27
UPK_CTRL_SIGNAL_28
send managed process signal 28
UPK_CTRL_SIGNAL_29
send managed process signal 29
UPK_CTRL_SIGNAL_30
send managed process signal 30
UPK_CTRL_SIGNAL_31
send managed process signal 31
UPK_CTRL_SIGNAL_32
send managed process signal 32
UPK_CTRL_NONE
UPK_CTRL_ACK
UPK_CTRL_SHUTDOWN
UPK_CTRL_STATUS_REQ
UPK_CTRL_ACTION_START
UPK_CTRL_ACTION_STOP
UPK_CTRL_ACTION_RELOAD
UPK_CTRL_ACTION_RUNONCE
UPK_CTRL_CUSTOM_ACTION_00
UPK_CTRL_CUSTOM_ACTION_01
UPK_CTRL_CUSTOM_ACTION_02
UPK_CTRL_CUSTOM_ACTION_03
UPK_CTRL_CUSTOM_ACTION_04
UPK_CTRL_CUSTOM_ACTION_05
UPK_CTRL_CUSTOM_ACTION_06
UPK_CTRL_CUSTOM_ACTION_07
UPK_CTRL_CUSTOM_ACTION_08
UPK_CTRL_CUSTOM_ACTION_09
UPK_CTRL_CUSTOM_ACTION_10
UPK_CTRL_CUSTOM_ACTION_11
UPK_CTRL_CUSTOM_ACTION_12
UPK_CTRL_CUSTOM_ACTION_13
UPK_CTRL_CUSTOM_ACTION_14
UPK_CTRL_CUSTOM_ACTION_15
UPK_CTRL_CUSTOM_ACTION_16
UPK_CTRL_CUSTOM_ACTION_17
UPK_CTRL_CUSTOM_ACTION_18
UPK_CTRL_CUSTOM_ACTION_19
UPK_CTRL_CUSTOM_ACTION_20
UPK_CTRL_CUSTOM_ACTION_21
UPK_CTRL_CUSTOM_ACTION_22
UPK_CTRL_CUSTOM_ACTION_23
UPK_CTRL_CUSTOM_ACTION_24
UPK_CTRL_CUSTOM_ACTION_25
UPK_CTRL_CUSTOM_ACTION_26
UPK_CTRL_CUSTOM_ACTION_27
UPK_CTRL_CUSTOM_ACTION_28
UPK_CTRL_CUSTOM_ACTION_29
UPK_CTRL_CUSTOM_ACTION_30
UPK_CTRL_CUSTOM_ACTION_31
UPK_CTRL_SIGNAL_01
UPK_CTRL_SIGNAL_02
UPK_CTRL_SIGNAL_03
UPK_CTRL_SIGNAL_04
UPK_CTRL_SIGNAL_05
UPK_CTRL_SIGNAL_06
UPK_CTRL_SIGNAL_07
UPK_CTRL_SIGNAL_08
UPK_CTRL_SIGNAL_09
UPK_CTRL_SIGNAL_10
UPK_CTRL_SIGNAL_11
UPK_CTRL_SIGNAL_12
UPK_CTRL_SIGNAL_13
UPK_CTRL_SIGNAL_14
UPK_CTRL_SIGNAL_15
UPK_CTRL_SIGNAL_16
UPK_CTRL_SIGNAL_17
UPK_CTRL_SIGNAL_18
UPK_CTRL_SIGNAL_19
UPK_CTRL_SIGNAL_20
UPK_CTRL_SIGNAL_21
UPK_CTRL_SIGNAL_22
UPK_CTRL_SIGNAL_23
UPK_CTRL_SIGNAL_24
UPK_CTRL_SIGNAL_25
UPK_CTRL_SIGNAL_26
UPK_CTRL_SIGNAL_27
UPK_CTRL_SIGNAL_28
UPK_CTRL_SIGNAL_29
UPK_CTRL_SIGNAL_30
UPK_CTRL_SIGNAL_31
UPK_CTRL_SIGNAL_32
UPK_CTRL_NONE
UPK_CTRL_ACK
UPK_CTRL_SHUTDOWN
UPK_CTRL_STATUS_REQ
UPK_CTRL_ACTION_START
UPK_CTRL_ACTION_STOP
UPK_CTRL_ACTION_RELOAD
UPK_CTRL_ACTION_RUNONCE
UPK_CTRL_CUSTOM_ACTION_00
UPK_CTRL_CUSTOM_ACTION_01
UPK_CTRL_CUSTOM_ACTION_02
UPK_CTRL_CUSTOM_ACTION_03
UPK_CTRL_CUSTOM_ACTION_04
UPK_CTRL_CUSTOM_ACTION_05
UPK_CTRL_CUSTOM_ACTION_06
UPK_CTRL_CUSTOM_ACTION_07
UPK_CTRL_CUSTOM_ACTION_08
UPK_CTRL_CUSTOM_ACTION_09
UPK_CTRL_CUSTOM_ACTION_10
UPK_CTRL_CUSTOM_ACTION_11
UPK_CTRL_CUSTOM_ACTION_12
UPK_CTRL_CUSTOM_ACTION_13
UPK_CTRL_CUSTOM_ACTION_14
UPK_CTRL_CUSTOM_ACTION_15
UPK_CTRL_CUSTOM_ACTION_16
UPK_CTRL_CUSTOM_ACTION_17
UPK_CTRL_CUSTOM_ACTION_18
UPK_CTRL_CUSTOM_ACTION_19
UPK_CTRL_CUSTOM_ACTION_20
UPK_CTRL_CUSTOM_ACTION_21
UPK_CTRL_CUSTOM_ACTION_22
UPK_CTRL_CUSTOM_ACTION_23
UPK_CTRL_CUSTOM_ACTION_24
UPK_CTRL_CUSTOM_ACTION_25
UPK_CTRL_CUSTOM_ACTION_26
UPK_CTRL_CUSTOM_ACTION_27
UPK_CTRL_CUSTOM_ACTION_28
UPK_CTRL_CUSTOM_ACTION_29
UPK_CTRL_CUSTOM_ACTION_30
UPK_CTRL_CUSTOM_ACTION_31
UPK_CTRL_SIGNAL_01
UPK_CTRL_SIGNAL_02
UPK_CTRL_SIGNAL_03
UPK_CTRL_SIGNAL_04
UPK_CTRL_SIGNAL_05
UPK_CTRL_SIGNAL_06
UPK_CTRL_SIGNAL_07
UPK_CTRL_SIGNAL_08
UPK_CTRL_SIGNAL_09
UPK_CTRL_SIGNAL_10
UPK_CTRL_SIGNAL_11
UPK_CTRL_SIGNAL_12
UPK_CTRL_SIGNAL_13
UPK_CTRL_SIGNAL_14
UPK_CTRL_SIGNAL_15
UPK_CTRL_SIGNAL_16
UPK_CTRL_SIGNAL_17
UPK_CTRL_SIGNAL_18
UPK_CTRL_SIGNAL_19
UPK_CTRL_SIGNAL_20
UPK_CTRL_SIGNAL_21
UPK_CTRL_SIGNAL_22
UPK_CTRL_SIGNAL_23
UPK_CTRL_SIGNAL_24
UPK_CTRL_SIGNAL_25
UPK_CTRL_SIGNAL_26
UPK_CTRL_SIGNAL_27
UPK_CTRL_SIGNAL_28
UPK_CTRL_SIGNAL_29
UPK_CTRL_SIGNAL_30
UPK_CTRL_SIGNAL_31
UPK_CTRL_SIGNAL_32
enum _upk_msgtype
Enumerator:
UPK_REQ_ORIGIN
UPK_REQ_PREAMBLE
UPK_REQ_SEQ_START
UPK_REQ_SEQ_END
UPK_REQ_ACTION
UPK_REQ_SIGNAL
UPK_REQ_LIST
UPK_REQ_STATUS
UPK_REQ_SUBSCRIBE
UPK_REQ_UNSUBSCRIBE
UPK_REQ_DISCONNECT
UPK_REQ_V0_PROTO_LIMIT
UPK_REQ_LIMIT
UPK_REPL_ORIGIN
UPK_REPL_PREAMBLE
UPK_REPL_SEQ_START
UPK_REPL_SEQ_END
UPK_REPL_RESULT
UPK_REPL_LISTING
UPK_REPL_SVCINFO
UPK_REPL_ACK
UPK_REPL_ERROR
UPK_REPL_V0_PROTO_LIMIT
UPK_REPL_LIMIT
UPK_PUB_ORIGIN
UPK_PUB_PUBLICATION
UPK_PUB_CANCELATION
UPK_PUB_V0_PROTO_LIMIT
UPK_PUB_LIMIT
UPK_REQ_ORIGIN
idenitfy start of range
UPK_REQ_PREAMBLE
A preamble message, used to negotiate version, and handshake
UPK_REQ_SEQ_START
The start of a request sequence
UPK_REQ_SEQ_END
the end of a request sequence
UPK_REQ_ACTION
An action request (e.g. start, stop, reload, or custom actions)
UPK_REQ_SIGNAL
a signal request (e.g. send signal N)
UPK_REQ_LIST
A listing request. for a listing of all service-ids known to the controller
UPK_REQ_STATUS
A status request, to get information on a particular service
UPK_REQ_SUBSCRIBE
subscribe to a feed of status updates
UPK_REQ_UNSUBSCRIBE
unsubscribe from a feed of status updates
UPK_REQ_DISCONNECT
notify controller of your intent to disconnect
UPK_REQ_V0_PROTO_LIMIT
all valid v0 requests are < this
UPK_REQ_LIMIT
all requests are < this
UPK_REPL_ORIGIN
identify start of range
UPK_REPL_PREAMBLE
the reply to a preamble request, used to send back what the server decided was the best protocol, and complete the handshake
UPK_REPL_SEQ_START
the start of a sequence of replies
UPK_REPL_SEQ_END
the end of a sequence of replies
UPK_REPL_RESULT
the result of an action or signal request (or anything else that might benefit from a result msg
UPK_REPL_LISTING
the name of a service in a sequence listing all services
UPK_REPL_SVCINFO
all the information known about a service
UPK_REPL_ACK
an ack, when nothing else really fits, but a reply is still mandated
UPK_REPL_ERROR
report an error to the client, for instance, if the named service doesn't exist, or an action doesn't exist, etc
UPK_REPL_V0_PROTO_LIMIT
All valid v0 replies are < this
UPK_REPL_LIMIT
All replies are < this
UPK_PUB_ORIGIN
pub origin
UPK_PUB_PUBLICATION
a message sent from the controller to a subscriber, followed by svcinfo packets for all subscribed services
UPK_PUB_CANCELATION
notification that a particular service is no longer available to subscribe to, for instance if its been removed
UPK_PUB_V0_PROTO_LIMIT
All valid pub v0 publication messages are < this
UPK_PUB_LIMIT
All publication messages are < this
UPK_REQ_ORIGIN
UPK_REQ_PREAMBLE
UPK_REQ_SEQ_START
UPK_REQ_SEQ_END
UPK_REQ_ACTION
UPK_REQ_SIGNAL
UPK_REQ_LIST
UPK_REQ_STATUS
UPK_REQ_SUBSCRIBE
UPK_REQ_UNSUBSCRIBE
UPK_REQ_DISCONNECT
UPK_REQ_V0_PROTO_LIMIT
UPK_REQ_LIMIT
UPK_REPL_ORIGIN
UPK_REPL_PREAMBLE
UPK_REPL_SEQ_START
UPK_REPL_SEQ_END
UPK_REPL_RESULT
UPK_REPL_LISTING
UPK_REPL_SVCINFO
UPK_REPL_ACK
UPK_REPL_ERROR
UPK_REPL_V0_PROTO_LIMIT
UPK_REPL_LIMIT
UPK_PUB_ORIGIN
UPK_PUB_PUBLICATION
UPK_PUB_CANCELATION
UPK_PUB_V0_PROTO_LIMIT
UPK_PUB_LIMIT
enum buddy_runstate_t
Enumerator:
BUDDY_UNKNOWN
BUDDY_STOPPED
the current state of the managed process is stopped
BUDDY_RUNNING
the current state of the managed process is running
BUDDY_RANONCE
the current state of the managed process was that it ran once
BUDDY_UNKNOWN
BUDDY_STOPPED
BUDDY_RUNNING
BUDDY_RANONCE
BUDDY_UNKNOWN
BUDDY_STOPPED
BUDDY_RUNNING
BUDDY_RANONCE
enum idtype_t
Enumerator:
P_ALL
P_PID
P_PGID
P_ALL
P_PID
P_PGID
enum upk_diaglvl_t
Enumerator:
UPK_DIAGLVL_FATAL
UPK_DIAGLVL_ALERT
UPK_DIAGLVL_CRIT
UPK_DIAGLVL_ERROR
UPK_DIAGLVL_WARN
UPK_DIAGLVL_NOTICE
UPK_DIAGLVL_VERBOSE
UPK_DIAGLVL_INFO
UPK_DIAGLVL_DEBUG0
UPK_DIAGLVL_DEBUG1
UPK_DIAGLVL_FATAL
fatal error, operation cannot continue
UPK_DIAGLVL_ALERT
alert; something really bad happened, but we believe we can continue
UPK_DIAGLVL_CRIT
critical; something really bad happened, that probably shouldn't happen; we can continue
UPK_DIAGLVL_ERROR
An error occurred.
UPK_DIAGLVL_WARN
A warning, serious, but not too serious
UPK_DIAGLVL_NOTICE
Something you might want to notice; possibly normal operation
UPK_DIAGLVL_VERBOSE
verbose, probably normal operation
UPK_DIAGLVL_INFO
information, definitely normal operation, intended to aid in troubleshooting user-configurable things
UPK_DIAGLVL_DEBUG0
debug0, intended to help find bugs in the program; but may also help in finding configuration or environment problems
UPK_DIAGLVL_DEBUG1
debug1, useful in finding and demonstrating bugs in the program (you should probably be using gdb by this point)
UPK_DIAGLVL_FATAL
UPK_DIAGLVL_ALERT
UPK_DIAGLVL_CRIT
UPK_DIAGLVL_ERROR
UPK_DIAGLVL_WARN
UPK_DIAGLVL_NOTICE
UPK_DIAGLVL_VERBOSE
UPK_DIAGLVL_INFO
UPK_DIAGLVL_DEBUG0
UPK_DIAGLVL_DEBUG1
enum upk_errlevel_t
Enumerator:
UPK_ERRLVL_ERROR
UPK_ERRLVL_ERROR
semantically similar to diaglvl; but for error-reporting; may become purely protocol
UPK_ERRLVL_ERROR
enum upk_errno_t
Enumerator:
UPK_ERR_UNKNOWN
UPK_ERR_UNSUP
UPK_ERR_INVALID_PKT
UPK_SOCKET_FAILURE
UPK_JSON_PARSE_ERROR
UPK_SQL_ERROR
UPK_CONF_ERROR
UPK_ERR_UNKNOWN
unknown error
UPK_ERR_UNSUP
unsupported
UPK_ERR_INVALID_PKT
invalid packet, possibly invalid protocol, packet dimensions, or checksum
UPK_SOCKET_FAILURE
unable to bind/connect/accept/listen on a socket
UPK_JSON_PARSE_ERROR
json parse error; additional information should also be provided
UPK_SQL_ERROR
SQLite Error
UPK_CONF_ERROR
Configuration error
UPK_ERR_UNKNOWN
UPK_ERR_UNSUP
UPK_ERR_INVALID_PKT
UPK_SOCKET_FAILURE
UPK_JSON_PARSE_ERROR
UPK_SQL_ERROR
UPK_CONF_ERROR
enum upk_pkttype_t
Enumerator:
PKT_REQUEST
PKT_REPLY
PKT_PUBMSG
PKT_V0_PROTO_LIMIT
PKT_REQUEST
PKT_REPLY
PKT_PUBMSG
PKT_V0_PROTO_LIMIT
PKT_REQUEST
PKT_REPLY
PKT_PUBMSG
PKT_V0_PROTO_LIMIT
enum upk_signal_t
Enumerator:
UPK_SIG_HUP
UPK_SIG_INT
UPK_SIG_QUIT
UPK_SIG_ILL
UPK_SIG_TRAP
UPK_SIG_ABRT
UPK_SIG_BUS
UPK_SIG_FPE
UPK_SIG_KILL
UPK_SIG_USR1
UPK_SIG_SEGV
UPK_SIG_USR2
UPK_SIG_PIPE
UPK_SIG_ALRM
UPK_SIG_TERM
UPK_SIG_STKFLT
UPK_SIG_CHLD
UPK_SIG_CONT
UPK_SIG_STOP
UPK_SIG_TSTP
UPK_SIG_TTIN
UPK_SIG_TTOU
UPK_SIG_URG
UPK_SIG_XCPU
UPK_SIG_XFSZ
UPK_SIG_VTALRM
UPK_SIG_PROF
UPK_SIG_WINCH
UPK_SIG_IO
UPK_SIG_PWR
UPK_SIG_SYS
UPK_SIG_HUP
hup
UPK_SIG_INT
int
UPK_SIG_QUIT
quit
UPK_SIG_ILL
ill
UPK_SIG_TRAP
trap
UPK_SIG_ABRT
abrt
UPK_SIG_BUS
bus
UPK_SIG_FPE
fpe
UPK_SIG_KILL
kill
UPK_SIG_USR1
usr1
UPK_SIG_SEGV
segv
UPK_SIG_USR2
usr2
UPK_SIG_PIPE
pipe
UPK_SIG_ALRM
alrm
UPK_SIG_TERM
term
UPK_SIG_STKFLT
stkflt
UPK_SIG_CHLD
chld
UPK_SIG_CONT
cont
UPK_SIG_STOP
stop
UPK_SIG_TSTP
tstp
UPK_SIG_TTIN
ttin
UPK_SIG_TTOU
ttou
UPK_SIG_URG
urg
UPK_SIG_XCPU
xcpu
UPK_SIG_XFSZ
xfsz
UPK_SIG_VTALRM
vtalrm
UPK_SIG_PROF
prof
UPK_SIG_WINCH
winch
UPK_SIG_IO
io
UPK_SIG_PWR
pwr
UPK_SIG_SYS
sys
UPK_SIG_HUP
UPK_SIG_INT
UPK_SIG_QUIT
UPK_SIG_ILL
UPK_SIG_TRAP
UPK_SIG_ABRT
UPK_SIG_BUS
UPK_SIG_FPE
UPK_SIG_KILL
UPK_SIG_USR1
UPK_SIG_SEGV
UPK_SIG_USR2
UPK_SIG_PIPE
UPK_SIG_ALRM
UPK_SIG_TERM
UPK_SIG_STKFLT
UPK_SIG_CHLD
UPK_SIG_CONT
UPK_SIG_STOP
UPK_SIG_TSTP
UPK_SIG_TTIN
UPK_SIG_TTOU
UPK_SIG_URG
UPK_SIG_XCPU
UPK_SIG_XFSZ
UPK_SIG_VTALRM
UPK_SIG_PROF
UPK_SIG_WINCH
UPK_SIG_IO
UPK_SIG_PWR
UPK_SIG_SYS
enum upk_state_t
Enumerator:
UPK_STATE_UNDEFINED
UPK_STATE_RUNNING
UPK_STATE_STOPPED
UPK_STATE_SHUTDOWN
UPK_STATE_UNDEFINED
unknown/undefined; probably an error
UPK_STATE_RUNNING
the service is running
UPK_STATE_STOPPED
the service is stopped
UPK_STATE_SHUTDOWN
the service is stopped, and its buddy is not running
UPK_STATE_UNDEFINED
UPK_STATE_RUNNING
UPK_STATE_STOPPED
UPK_STATE_SHUTDOWN
Function Documentation
void __assert (const char * __assertion, const char * __file, int __line)
void __assert_fail (__const char * __assertion, __const char * __file, unsigned int __line, __const char * __function)
void __assert_perror_fail (int __errnum, __const char * __file, unsigned int __line, __const char * __function)
__extension__ __inline unsigned int __attribute__ ((__nothrow__))
struct cmsghdr* __cmsg_nxthdr (struct msghdr * __mhdr, struct cmsghdr * __cmsg) [read]
__const unsigned short int** __ctype_b_loc (void)
size_t __ctype_get_mb_cur_max (void)
int* __errno_location (void)
int __libc_current_sigrtmin (void)
int __overflow (_IO_FILE * , int)
long int unsigned long int __extension__ long long int __extension__ unsigned long long int double float long double double __strtod_internal (__const char *__restrict __nptr, char **__restrict __endptr, int __group)
float __strtof_internal (__const char *__restrict __nptr, char **__restrict __endptr, int __group)
long int __strtol_internal (__const char *__restrict __nptr, char **__restrict __endptr, int __base, int __group)
long double __strtold_internal (__const char *__restrict __nptr, char **__restrict __endptr, int __group)
__extension__ long long int __strtoll_internal (__const char *__restrict __nptr, char **__restrict __endptr, int __base, int __group)
unsigned long int __strtoul_internal (__const char *__restrict __nptr, char **__restrict __endptr, int __base, int __group)
__extension__ unsigned long long int __strtoull_internal (__const char *__restrict __nptr, char **__restrict __endptr, int __base, int __group)
int __uflow (_IO_FILE *)
int __underflow (_IO_FILE *)
wint_t __woverflow (_IO_FILE * , wint_t)
wint_t __wuflow (_IO_FILE *)
wint_t __wunderflow (_IO_FILE *)
char* __xpg_basename (char * __path)
void _IO_cookie_init (struct _IO_cookie_file * __cfile, int __read_write, void * __cookie, _IO_cookie_io_functions_t __fns)
int _IO_feof (_IO_FILE * __fp)
int _IO_ferror (_IO_FILE * __fp)
void _IO_flockfile (_IO_FILE *)
int _IO_getc (_IO_FILE * __fp)
int _IO_peekc_locked (_IO_FILE * __fp)
int _IO_putc (int __c, _IO_FILE * __fp)
int32_t _upk_alert (const char * loc, const char * fmt, ...)
int32_t _upk_crit (const char * loc, const char * fmt, ...)
int32_t _upk_debug0 (const char * loc, const char * fmt, ...)
int32_t _upk_debug1 (const char * loc, const char * fmt, ...)
Referenced by upk_db_get_single_text(), upk_db_insert_cfg(), and upk_db_upsert_options().
int32_t _upk_error (const char * loc, const char * fmt, ...)
Referenced by upk_db_add_new_service(), upk_db_get_single_text(), upk_db_insert_cfg(), upk_db_try_insert(), and upk_db_try_update().
int32_t _upk_fatal (const char * loc, const char * fmt, ...)
int32_t _upk_info (const char * loc, const char * fmt, ...)
int32_t _upk_notice (const char * loc, const char * fmt, ...)
int32_t _upk_verbose (const char * loc, const char * fmt, ...)
Referenced by upk_db_upsert().
int32_t _upk_warn (const char * loc, const char * fmt, ...)
long int a64l (__const char * __s)
void abort (extern int on_exit ((*__func) (int __status void)
int accept (int __fd, __SOCKADDR_ARG __addr, socklen_t *__restrict __addr_len)
Referenced by buddy_accept(), and ctrl_accept_conn().
int adjtime (__const struct timeval * __delta, struct timeval * __olddelta)
void* alloca (size_t __size)
int int int alphasort (__const void * __e1, __const void * __e2)
int int int int alphasort64 (__const void * __e1, __const void * __e2)
int bind (int __fd, __CONST_SOCKADDR_ARG __addr, socklen_t __len)
Referenced by buddy_init_socket(), and ctrl_sock_setup().
int bindresvport (int __sockfd, struct sockaddr_in * __sock_in)
int bindresvport6 (int __sockfd, struct sockaddr_in6 * __sock_in)
int buddy_connect (const char * sockpath)
buddy_info_t* buddy_readstate (int fd)
void* calloc (size_t __nmemb, size_t __size)
Referenced by buddy_init_ringbuffer(), ctrl_init(), deserial_svcinfo_data(), main(), opt_parse(), START_TEST(), upk_clnet_req_status(), upk_clnet_serial_request(), upk_config_loadfile(), upk_create_pkt(), upk_create_repl_preamble(), upk_create_req_preamble(), upk_ctrlconf_pack(), upk_db_upsert_options(), upk_deserialize_packet(), upk_json_append_string(), upk_json_obj_serializer(), upk_json_serialize_svc_config(), upk_load_runtime_services(), upk_mkdir_p(), upk_net_add_socket_handle(), upk_net_conn_handles_init(), upk_overlay_ctrlconf_values(), upk_overlay_svcconf_values(), upk_svcconf_array_handler(), upk_svcconf_customaction_array_appender(), upk_svcconf_nested_object_handler(), upk_svcconf_object_handler(), upk_svcconf_pack(), and upk_svcconf_string_handler().
void cfree (void * __ptr)
int int int int int chmod (__const char * __file, __mode_t __mode)
clock_t clock (void)
int closedir (DIR * __dirp)
Referenced by handle_buddies(), remove_buddy_statedir(), upk_load_runtime_services(), and upk_rm_rf().
size_t confstr (int __name, char * __buf, size_t __len)
int connect (int __fd, __CONST_SOCKADDR_ARG __addr, socklen_t __len)
Referenced by buddy_connect(), buddy_phone_home(), and upk_domain_socket_connect().
int creat (__const char * __file, __mode_t __mode)
int creat64 (__const char * __file, __mode_t __mode)
void create_buddy (upk_svc_desc_t * buddy)
int32_t ctrl_sock_setup (void)
setup controller's socket
*****************************************************************************************************************
int dirfd (DIR * __dirp)
int int int int int int __ssize_t __ssize_t char* dirname (char * __path)
Referenced by upk_mkdir_p().
int drand48_r (struct drand48_data *__restrict __buffer, double *__restrict __result)
void endgrent (void)
void endpwent (void)
int int erand48_r (unsigned short int __xsubi[3], struct drand48_data *__restrict __buffer, double *__restrict __result)
void event_loop (int32_t listen_sock)
the main event loop.
***************************************************************************************************************** This will handle signals, poll buddies, poll clients, publish events, and cleanup sockets.
int fchmod (int __fd, __mode_t __mode)
Referenced by create_buddy_statedir().
int fchmodat (int __fd, __const char * __file, __mode_t mode, int __flag)
int fcntl (int __fd, int __cmd, ...)
Referenced by buddy_accept(), buddy_init_socket(), ctrl_sock_setup(), upk_build_fd_sets(), upk_net_add_socket_handle(), and upk_net_event_dispatcher().
DIR* fdopendir (int __fd)
struct group* fgetgrent (FILE * __stream) [read]
int fgetgrent_r (FILE *__restrict __stream, struct group *__restrict __resultbuf, char *__restrict __buffer, size_t __buflen, struct group **__restrict __result)
struct passwd* fgetpwent (FILE * __stream) [read]
int fgetpwent_r (FILE *__restrict __stream, struct passwd *__restrict __resultbuf, char *__restrict __buffer, size_t __buflen, struct passwd **__restrict __result)
int flock (int __fd, int __operation)
long int fpathconf (int __fd, int __name)
void free (void * __ptr)
Referenced by buddy_cleanup(), buddy_free_ringbuffer(), deserial_repl_svcinfo(), main(), serial_repl_svcinfo(), START_TEST(), upk_clnet_req_action(), upk_clnet_req_disconnect(), upk_clnet_req_preamble(), upk_clnet_req_signal(), upk_clnet_req_status(), upk_ctrl_load_config(), upk_db_upsert_options(), upk_deserialize_packet(), upk_free_payload(), upk_load_runtime_services(), upk_net_flush_closed_sockets(), upk_overlay_svcconf_values(), upk_partitioned_userdata_free(), upk_pkt_free(), upk_queue_packet(), upk_serialize_packet(), upk_svc_desc_free(), and upk_svcconf_string_handler().
int int fstat (int __fd, struct stat * __buf)
int int fstat64 (int __fd, struct stat64 * __buf)
int fstatat (int __fd, __const char *__restrict __file, struct stat *__restrict __buf, int __flag)
int int fstatat64 (int __fd, __const char *__restrict __file, struct stat64 *__restrict __buf, int __flag)
int futimes (int __fd, __const struct timeval __tvp[2])
int futimesat (int __fd, __const char * __file, __const struct timeval __tvp[2])
int int int int int int __ssize_t getdirentries (int __fd, char *__restrict __buf, size_t __nbytes, __off_t *__restrict __basep)
int int int int int int __ssize_t __ssize_t getdirentries64 (int __fd, char *__restrict __buf, size_t __nbytes, __off64_t *__restrict __basep)
struct group* getgrent (void) [read]
int getgrent_r (struct group *__restrict __resultbuf, char *__restrict __buffer, size_t __buflen, struct group **__restrict __result)
struct group* getgrgid (__gid_t __gid) [read]
int getgrgid_r (__gid_t __gid, struct group *__restrict __resultbuf, char *__restrict __buffer, size_t __buflen, struct group **__restrict __result)
struct group* getgrnam (__const char * __name) [read]
int getgrnam_r (__const char *__restrict __name, struct group *__restrict __resultbuf, char *__restrict __buffer, size_t __buflen, struct group **__restrict __result)
int getgrouplist (__const char * __user, __gid_t __group, __gid_t * __groups, int * __ngroups)
int getipv4sourcefilter (int __s, struct in_addr __interface_addr, struct in_addr __group, uint32_t * __fmode, uint32_t * __numsrc, struct in_addr * __slist)
int getitimer (__itimer_which_t __which, struct itimerval * __value)
int getpeername (int __fd, __SOCKADDR_ARG __addr, socklen_t *__restrict __len)
__pid_t getpid (void)
Referenced by commit_buddycide(), upk_clientid(), and upk_uuid_seed_random().
int getpriority (__priority_which_t __which, id_t __who)
int getpw (__uid_t __uid, char * __buffer)
struct passwd* getpwent (void) [read]
int getpwent_r (struct passwd *__restrict __resultbuf, char *__restrict __buffer, size_t __buflen, struct passwd **__restrict __result)
struct passwd* getpwnam (__const char * __name) [read]
int getpwnam_r (__const char *__restrict __name, struct passwd *__restrict __resultbuf, char *__restrict __buffer, size_t __buflen, struct passwd **__restrict __result)
Referenced by upk_svcconf_string_handler().
struct passwd* getpwuid (__uid_t __uid) [read]
Referenced by buddy_supp_groups().
int getpwuid_r (__uid_t __uid, struct passwd *__restrict __resultbuf, char *__restrict __buffer, size_t __buflen, struct passwd **__restrict __result)
int getrlimit (__rlimit_resource_t __resource, struct rlimit * __rlimits)
int getrlimit64 (__rlimit_resource_t __resource, struct rlimit64 * __rlimits)
int getrusage (__rusage_who_t __who, struct rusage * __usage)
int getsockname (int __fd, __SOCKADDR_ARG __addr, socklen_t *__restrict __len)
int getsockopt (int __fd, int __level, int __optname, void *__restrict __optval, socklen_t *__restrict __optlen)
int getsourcefilter (int __s, uint32_t __interface_addr, __const struct sockaddr * __group, socklen_t __grouplen, uint32_t * __fmode, uint32_t * __numsrc, struct sockaddr_storage * __slist)
int gettimeofday (struct timeval *__restrict __tv, __timezone_ptr_t __tz)
Referenced by upk_net_block_until_msg(), and upk_uuid_seed_random().
__mode_t getumask (void)
__extension__ __inline unsigned int gnu_dev_major (unsigned long long int __dev)
__extension__ __inline unsigned long long int gnu_dev_makedev (unsigned int __major, unsigned int __minor)
__extension__ __inline unsigned int gnu_dev_minor (unsigned long long int __dev)
void handle_buddies (void)
void handle_signals (void)
deal with signals pending action in signal_queue.
***************************************************************************************************************** Block all signals during copy to avoid annoying race conditions.
uint32_t htonl (uint32_t __hostlong) const
uint16_t htons (uint16_t __hostshort) const
int inet6_opt_append (void * __extbuf, socklen_t __extlen, int __offset, uint8_t __type, socklen_t __len, uint8_t __align, void ** __databufp)
int inet6_opt_find (void * __extbuf, socklen_t __extlen, int __offset, uint8_t __type, socklen_t * __lenp, void ** __databufp)
int inet6_opt_finish (void * __extbuf, socklen_t __extlen, int __offset)
int inet6_opt_get_val (void * __databuf, int __offset, void * __val, socklen_t __vallen)
int inet6_opt_init (void * __extbuf, socklen_t __extlen)
int inet6_opt_next (void * __extbuf, socklen_t __extlen, int __offset, uint8_t * __typep, socklen_t * __lenp, void ** __databufp)
int inet6_opt_set_val (void * __databuf, int __offset, void * __val, socklen_t __vallen)
uint8_t* inet6_option_alloc (struct cmsghdr * __cmsg, int __datalen, int __multx, int __plusy)
int inet6_option_append (struct cmsghdr * __cmsg, __const uint8_t * __typep, int __multx, int __plusy)
int inet6_option_find (__const struct cmsghdr * __cmsg, uint8_t ** __tptrp, int __type)
int inet6_option_init (void * __bp, struct cmsghdr ** __cmsgp, int __type)
int inet6_option_next (__const struct cmsghdr * __cmsg, uint8_t ** __tptrp)
int inet6_option_space (int __nbytes)
int inet6_rth_add (void * __bp, __const struct in6_addr * __addr)
struct in6_addr* inet6_rth_getaddr (__const void * __bp, int __index) [read]
void* inet6_rth_init (void * __bp, socklen_t __bp_len, int __type, int __segments)
int inet6_rth_reverse (__const void * __in, void * __out)
int inet6_rth_segments (__const void * __bp)
socklen_t inet6_rth_space (int __type, int __segments)
in_addr_t inet_addr (__const char * __cp)
int inet_aton (__const char * __cp, struct in_addr * __inp)
in_addr_t inet_lnaof (struct in_addr __in)
struct in_addr inet_makeaddr (in_addr_t __net, in_addr_t __host) [read]
char* inet_net_ntop (int __af, __const void * __cp, int __bits, char * __buf, size_t __len)
int inet_net_pton (int __af, __const char * __cp, void * __buf, size_t __len)
char* inet_neta (in_addr_t __net, char * __buf, size_t __len)
in_addr_t inet_netof (struct in_addr __in)
in_addr_t inet_network (__const char * __cp)
unsigned int inet_nsap_addr (__const char * __cp, unsigned char * __buf, int __len)
char* inet_nsap_ntoa (int __len, __const unsigned char * __cp, char * __buf)
char* inet_ntoa (struct in_addr __in)
__const char* inet_ntop (int __af, __const void *__restrict __cp, char *__restrict __buf, socklen_t __len)
int inet_pton (int __af, __const char *__restrict __cp, void *__restrict __buf)
int initgroups (__const char * __user, __gid_t __group)
Referenced by buddy_supp_groups().
int initstate_r (unsigned int __seed, char *__restrict __statebuf, size_t __statelen, struct random_data *__restrict __buf)
_Bool is_valid_upk_uuid_string (const char * string)
Referenced by opt_parse(), START_TEST(), and upk_string_to_uuid().
int isfdtype (int __fd, int __fdtype)
int int int int int int jrand48_r (unsigned short int __xsubi[3], struct drand48_data *__restrict __buffer, long int *__restrict __result)
_Bool kill_buddy (upk_svc_desc_t * buddy)
char* l64a (long int __n)
int lchmod (__const char * __file, __mode_t __mode)
int int lcong48_r (unsigned short int __param[7], struct drand48_data * __buffer)
int listen (int __fd, int __n)
Referenced by buddy_init_socket(), and ctrl_sock_setup().
int int int lrand48_r (struct drand48_data *__restrict __buffer, long int *__restrict __result)
int int int lstat (__const char *__restrict __file, struct stat *__restrict __buf)
Referenced by resolve_symlink().
int int int int lstat64 (__const char *__restrict __file, struct stat64 *__restrict __buf)
int lutimes (__const char * __file, __const struct timeval __tvp[2])
int int void* malloc (size_t __size)
int int int int int mrand48_r (struct drand48_data *__restrict __buffer, long int *__restrict __result)
int int int int nrand48_r (unsigned short int __xsubi[3], struct drand48_data *__restrict __buffer, long int *__restrict __result)
uint32_t ntohl (uint32_t __netlong) const
Referenced by deserialize_pub_payload(), deserialize_repl_payload(), deserialize_req_payload(), and upk_read_packets().
uint16_t ntohs (uint16_t __netshort) const
int open (__const char * __file, int __oflag, ...)
Referenced by upk_uuid_open_random().
int open64 (__const char * __file, int __oflag, ...)
int openat (int __fd, __const char * __file, int __oflag, ...)
int openat64 (int __fd, __const char * __file, int __oflag, ...)
DIR* opendir (__const char * __name)
Referenced by handle_buddies(), remove_buddy_statedir(), upk_load_runtime_services(), and upk_rm_rf().
long int pathconf (__const char * __path, int __name)
int posix_fadvise (int __fd, __off_t __offset, __off_t __len, int __advise)
int posix_fadvise64 (int __fd, __off64_t __offset, __off64_t __len, int __advise)
int posix_fallocate (int __fd, __off_t __offset, __off_t __len)
int posix_fallocate64 (int __fd, __off64_t __offset, __off64_t __len)
int posix_memalign (void ** __memptr, size_t __alignment, size_t __size)
int pselect (int __nfds, fd_set *__restrict __readfds, fd_set *__restrict __writefds, fd_set *__restrict __exceptfds, const struct timespec *__restrict __timeout, const __sigset_t *__restrict __sigmask)
int pthread_kill (pthread_t __threadid, int __signo)
int pthread_sigmask (int __how, __const __sigset_t *__restrict __newmask, __sigset_t *__restrict __oldmask)
int putgrent (__const struct group *__restrict __p, FILE *__restrict __f)
int putpwent (__const struct passwd *__restrict __p, FILE *__restrict __f)
int int int rand (void)
Referenced by upk_gen_uuid_bytes().
long int random (void)
int random_r (struct random_data *__restrict __buf, int32_t *__restrict __result)
ssize_t readahead (int __fd, __off64_t __offset, size_t __count)
struct dirent* readdir (DIR * __dirp) [read]
Referenced by handle_buddies(), remove_buddy_statedir(), upk_load_runtime_services(), and upk_rm_rf().
struct dirent64* readdir64 (DIR * __dirp) [read]
int int readdir64_r (DIR *__restrict __dirp, struct dirent64 *__restrict __entry, struct dirent64 **__restrict __result)
int readdir_r (DIR *__restrict __dirp, struct dirent *__restrict __entry, struct dirent **__restrict __result)
ssize_t readv (int __fd, __const struct iovec * __iovec, int __count)
void* realloc (void * __ptr, size_t __size)
Referenced by upk_config_loadfile(), upk_db_upsert_options(), upk_json_append_string(), and upk_replace_string().
ssize_t recv (int __fd, void * __buf, size_t __n, int __flags)
ssize_t recvfrom (int __fd, void *__restrict __buf, size_t __n, int __flags, __SOCKADDR_ARG __addr, socklen_t *__restrict __addr_len)
ssize_t recvmsg (int __fd, struct msghdr * __message, int __flags)
_Bool reload_buddy_svc (upk_svc_desc_t * buddy)
void remove_buddy (upk_svc_desc_t * buddy)
int int void rewinddir (DIR * __dirp)
int scandir (__const char *__restrict __dir, struct dirent ***__restrict __namelist, int(*)(__const struct dirent *) __selector, int(*)(__const void *, __const void *) __cmp)
int int scandir64 (__const char *__restrict __dir, struct dirent64 ***__restrict __namelist, int(*)(__const struct dirent64 *) __selector, int(*)(__const void *, __const void *) __cmp)
int seed48_r (unsigned short int __seed16v[3], struct drand48_data * __buffer)
void seekdir (DIR * __dirp, long int __pos)
int select (int __nfds, fd_set *__restrict __readfds, fd_set *__restrict __writefds, fd_set *__restrict __exceptfds, struct timeval *__restrict __timeout)
Referenced by buddy_event_loop(), buddy_readstate(), event_loop(), read_ctrl(), send_buddy_cmd(), upk_net_event_dispatcher(), and write_ctrl().
ssize_t send (int __fd, __const void * __buf, size_t __n, int __flags)
ssize_t sendmsg (int __fd, __const struct msghdr * __message, int __flags)
ssize_t sendto (int __fd, __const void * __buf, size_t __n, int __flags, __CONST_SOCKADDR_ARG __addr, socklen_t __addr_len)
void setgrent (void)
int setgroups (size_t __n, __const __gid_t * __groups)
Referenced by buddy_supp_groups().
int setipv4sourcefilter (int __s, struct in_addr __interface_addr, struct in_addr __group, uint32_t __fmode, uint32_t __numsrc, __const struct in_addr * __slist)
int setitimer (__itimer_which_t __which, __const struct itimerval *__restrict __new, struct itimerval *__restrict __old)
int setpriority (__priority_which_t __which, id_t __who, int __prio)
void setpwent (void)
int setrlimit (__rlimit_resource_t __resource, __const struct rlimit * __rlimits)
int setrlimit64 (__rlimit_resource_t __resource, __const struct rlimit64 * __rlimits)
int setsockopt (int __fd, int __level, int __optname, __const void * __optval, socklen_t __optlen)
int setsourcefilter (int __s, uint32_t __interface_addr, __const struct sockaddr * __group, socklen_t __grouplen, uint32_t __fmode, uint32_t __numsrc, __const struct sockaddr_storage * __slist)
int int setstate_r (char *__restrict __statebuf, struct random_data *__restrict __buf)
int settimeofday (__const struct timeval * __tv, __const struct timezone * __tz)
int shutdown (int __fd, int __how)
Referenced by buddy_disconnect(), send_buddy_cmd(), and upk_disconnect_handle().
int sigaction (int __sig, __const struct sigaction *__restrict __act, struct sigaction *__restrict __oact)
Referenced by buddy_exec_action(), buddy_init(), commit_buddycide(), and ctrl_setup_sighandlers().
int sigaddset (sigset_t * __set, int __signo)
Referenced by buddy_init(), and buddy_start_proc().
int sigaltstack (__const struct sigaltstack *__restrict __ss, struct sigaltstack *__restrict __oss)
int sigandset (sigset_t * __set, __const sigset_t * __left, __const sigset_t * __right)
int sigdelset (sigset_t * __set, int __signo)
int sigemptyset (sigset_t * __set)
Referenced by buddy_exec_action(), buddy_init(), buddy_start_proc(), commit_buddycide(), and ctrl_setup_sighandlers().
int sigfillset (sigset_t * __set)
Referenced by buddy_exec_action(), buddy_flush_ringbuffer(), buddy_init(), commit_buddycide(), ctrl_setup_sighandlers(), handle_signals(), and upk_net_event_dispatcher().
int sighold (int __sig)
int sigignore (int __sig)
int siginterrupt (int __sig, int __interrupt)
int sigisemptyset (__const sigset_t * __set)
int sigismember (__const sigset_t * __set, int __signo)
int int sigorset (sigset_t * __set, __const sigset_t * __left, __const sigset_t * __right)
int sigpending (sigset_t * __set)
int sigprocmask (int __how, __const sigset_t *__restrict __set, sigset_t *__restrict __oset)
Referenced by buddy_exec_action(), buddy_flush_ringbuffer(), buddy_start_proc(), commit_buddycide(), handle_signals(), and upk_net_event_dispatcher().
int sigqueue (__pid_t __pid, int __sig, __const union sigval __val)
int sigrelse (int __sig)
int sigreturn (struct sigcontext * __scp)
__sighandler_t sigset (int __sig, __sighandler_t __disp)
Referenced by buddy_exec_action(), buddy_flush_ringbuffer(), buddy_init(), buddy_start_proc(), commit_buddycide(), and handle_signals().
int sigstack (struct sigstack * __ss, struct sigstack * __oss)
int sigsuspend (__const sigset_t * __set)
int sigtimedwait (__const sigset_t *__restrict __set, siginfo_t *__restrict __info, __const struct timespec *__restrict __timeout)
int sigvec (int __sig, __const struct sigvec * __vec, struct sigvec * __ovec)
int sigwait (__const sigset_t *__restrict __set, int *__restrict __sig)
int int sigwaitinfo (__const sigset_t *__restrict __set, siginfo_t *__restrict __info)
int sockatmark (int __fd)
int socket (int __domain, int __type, int __protocol)
Referenced by buddy_connect(), buddy_init_socket(), buddy_phone_home(), ctrl_sock_setup(), and upk_domain_socket_connect().
int socket_setup (const char * sock_path)
int socketpair (int __domain, int __type, int __protocol, int __fds[2])
Referenced by main().
int splice (int __fdin, __off64_t * __offin, int __fdout, __off64_t * __offout, size_t __len, unsigned int __flags)
void* sqlite3_aggregate_context (sqlite3_context * , int nBytes)
int sqlite3_aggregate_count (sqlite3_context *)
int sqlite3_bind_blob (sqlite3_stmt * , int , const void * , int n, void(*)(void *))
Referenced by upk_db_try_insert(), and upk_db_try_update().
int sqlite3_bind_double (sqlite3_stmt * , int , double)
Referenced by upk_db_try_insert(), and upk_db_try_update().
int sqlite3_bind_int (sqlite3_stmt * , int , int)
Referenced by upk_db_try_insert(), and upk_db_try_update().
int sqlite3_bind_int64 (sqlite3_stmt * , int , sqlite_int64)
int sqlite3_bind_null (sqlite3_stmt * , int)
Referenced by upk_db_try_insert(), and upk_db_try_update().
int sqlite3_bind_parameter_count (sqlite3_stmt *)
int sqlite3_bind_parameter_index (sqlite3_stmt * , const char * zName)
const char* sqlite3_bind_parameter_name (sqlite3_stmt * , int)
int sqlite3_bind_text (sqlite3_stmt * , int , const char * , int n, void(*)(void *))
Referenced by upk_db_get_single_text(), upk_db_try_insert(), and upk_db_try_update().
int sqlite3_bind_text16 (sqlite3_stmt * , int , const void * , int , void(*)(void *))
int sqlite3_bind_value (sqlite3_stmt * , int , const sqlite3_value *)
int sqlite3_busy_handler (sqlite3 * , int(*)(void *, int) , void *)
int sqlite3_busy_timeout (sqlite3 * , int ms)
int sqlite3_changes (sqlite3 *)
int sqlite3_clear_bindings (sqlite3_stmt *)
int sqlite3_close (sqlite3 *)
Referenced by upk_ctrl_exit().
int sqlite3_collation_needed (sqlite3 * , void * , void(*)(void *, sqlite3 *, int eTextRep, const char *))
int sqlite3_collation_needed16 (sqlite3 * , void * , void(*)(void *, sqlite3 *, int eTextRep, const void *))
const void* sqlite3_column_blob (sqlite3_stmt * , int iCol)
int sqlite3_column_bytes (sqlite3_stmt * , int iCol)
int sqlite3_column_bytes16 (sqlite3_stmt * , int iCol)
int sqlite3_column_count (sqlite3_stmt * pStmt)
const char* sqlite3_column_database_name (sqlite3_stmt * , int)
const void* sqlite3_column_database_name16 (sqlite3_stmt * , int)
const char* sqlite3_column_decltype (sqlite3_stmt * , int i)
const void* sqlite3_column_decltype16 (sqlite3_stmt * , int)
double sqlite3_column_double (sqlite3_stmt * , int iCol)
int sqlite3_column_int (sqlite3_stmt * , int iCol)
sqlite_int64 sqlite3_column_int64 (sqlite3_stmt * , int iCol)
const char* sqlite3_column_name (sqlite3_stmt * , int)
const void* sqlite3_column_name16 (sqlite3_stmt * , int)
int sqlite3_column_numeric_type (sqlite3_stmt * , int iCol)
const char* sqlite3_column_origin_name (sqlite3_stmt * , int)
const void* sqlite3_column_origin_name16 (sqlite3_stmt * , int)
const char* sqlite3_column_table_name (sqlite3_stmt * , int)
const void* sqlite3_column_table_name16 (sqlite3_stmt * , int)
const unsigned char* sqlite3_column_text (sqlite3_stmt * , int iCol)
Referenced by upk_db_get_single_text().
const void* sqlite3_column_text16 (sqlite3_stmt * , int iCol)
int sqlite3_column_type (sqlite3_stmt * , int iCol)
void* sqlite3_commit_hook (sqlite3 * , int(*)(void *) , void *)
int sqlite3_complete (const char * sql)
int sqlite3_complete16 (const void * sql)
int sqlite3_create_collation (sqlite3 * , const char * zName, int eTextRep, void * , int(*)(void *, int, const void *, int, const void *) xCompare)
int sqlite3_create_collation16 (sqlite3 * , const char * zName, int eTextRep, void * , int(*)(void *, int, const void *, int, const void *) xCompare)
int sqlite3_create_function (sqlite3 * , const char * zFunctionName, int nArg, int eTextRep, void * , void(*)(sqlite3_context *, int, sqlite3_value **) xFunc, void(*)(sqlite3_context *, int, sqlite3_value **) xStep, void(*)(sqlite3_context *) xFinal)
int sqlite3_create_function16 (sqlite3 * , const void * zFunctionName, int nArg, int eTextRep, void * , void(*)(sqlite3_context *, int, sqlite3_value **) xFunc, void(*)(sqlite3_context *, int, sqlite3_value **) xStep, void(*)(sqlite3_context *) xFinal)
int sqlite3_data_count (sqlite3_stmt * pStmt)
sqlite3* sqlite3_db_handle (sqlite3_stmt *)
int sqlite3_enable_shared_cache (int)
int sqlite3_errcode (sqlite3 * db)
const char* sqlite3_errmsg (sqlite3 *)
Referenced by upk_db_get_single_text(), upk_db_try_insert(), and upk_db_try_update().
const void* sqlite3_errmsg16 (sqlite3 *)
int sqlite3_exec (sqlite3 * , const char * sql, sqlite3_callback , void * , char ** errmsg)
Referenced by upk_ctrl_attach_db(), upk_ctrl_init_db(), upk_db_add_new_service(), and upk_db_upsert_options().
int sqlite3_expired (sqlite3_stmt *)
int sqlite3_finalize (sqlite3_stmt * pStmt)
Referenced by upk_db_get_single_text(), upk_db_try_insert(), and upk_db_try_update().
void sqlite3_free (char * z)
Referenced by upk_ctrl_attach_db(), upk_ctrl_init_db(), upk_db_add_new_service(), and upk_db_upsert_options().
void sqlite3_free_table (char ** result)
int sqlite3_get_autocommit (sqlite3 *)
void* sqlite3_get_auxdata (sqlite3_context * , int)
int sqlite3_get_table (sqlite3 * , const char * sql, char *** resultp, int * nrow, int * ncolumn, char ** errmsg)
int sqlite3_global_recover (void)
void sqlite3_interrupt (sqlite3 *)
int sqlite3_key (sqlite3 * db, const void * pKey, int nKey)
sqlite_int64 sqlite3_last_insert_rowid (sqlite3 *)
const char* sqlite3_libversion (void)
int sqlite3_libversion_number (void)
char* sqlite3_mprintf (const char * , ...)
int sqlite3_open (const char * filename, sqlite3 ** ppDb)
Referenced by upk_ctrl_init_db().
int sqlite3_open16 (const void * filename, sqlite3 ** ppDb)
int sqlite3_prepare (sqlite3 * db, const char * zSql, int nBytes, sqlite3_stmt ** ppStmt, const char ** pzTail)
Referenced by upk_db_get_single_text(), upk_db_try_insert(), and upk_db_try_update().
int sqlite3_prepare16 (sqlite3 * db, const void * zSql, int nBytes, sqlite3_stmt ** ppStmt, const void ** pzTail)
void* sqlite3_profile (sqlite3 * , void(*)(void *, const char *, sqlite_uint64) xProfile, void *)
void sqlite3_progress_handler (sqlite3 * , int , int(*)(void *) , void *)
int sqlite3_rekey (sqlite3 * db, const void * pKey, int nKey)
int sqlite3_release_memory (int)
int sqlite3_reset (sqlite3_stmt * pStmt)
Referenced by upk_db_get_single_text(), upk_db_try_insert(), and upk_db_try_update().
void sqlite3_result_blob (sqlite3_context * , const void * , int , void(*)(void *))
void sqlite3_result_double (sqlite3_context * , double)
void sqlite3_result_error (sqlite3_context * , const char * , int)
void sqlite3_result_error16 (sqlite3_context * , const void * , int)
void sqlite3_result_int (sqlite3_context * , int)
void sqlite3_result_int64 (sqlite3_context * , sqlite_int64)
void sqlite3_result_null (sqlite3_context *)
void sqlite3_result_text (sqlite3_context * , const char * , int , void(*)(void *))
void sqlite3_result_text16 (sqlite3_context * , const void * , int , void(*)(void *))
void sqlite3_result_text16be (sqlite3_context * , const void * , int , void(*)(void *))
void sqlite3_result_text16le (sqlite3_context * , const void * , int , void(*)(void *))
void sqlite3_result_value (sqlite3_context * , sqlite3_value *)
void* sqlite3_rollback_hook (sqlite3 * , void(*)(void *) , void *)
int sqlite3_set_authorizer (sqlite3 * , int(*)(void *, int, const char *, const char *, const char *, const char *) xAuth, void * pUserData)
void sqlite3_set_auxdata (sqlite3_context * , int , void * , void(*)(void *))
int sqlite3_sleep (int)
char* sqlite3_snprintf (int , char * , const char * , ...)
void sqlite3_soft_heap_limit (int)
int sqlite3_step (sqlite3_stmt *)
Referenced by upk_db_get_single_text(), upk_db_try_insert(), and upk_db_try_update().
int sqlite3_table_column_metadata (sqlite3 * db, const char * zDbName, const char * zTableName, const char * zColumnName, char const ** pzDataType, char const ** pzCollSeq, int * pNotNull, int * pPrimaryKey, int * pAutoinc)
void sqlite3_thread_cleanup (void)
int sqlite3_total_changes (sqlite3 *)
void* sqlite3_trace (sqlite3 * , void(*)(void *, const char *) xTrace, void *)
int sqlite3_transfer_bindings (sqlite3_stmt * , sqlite3_stmt *)
void* sqlite3_update_hook (sqlite3 * , void(*)(void *, int, char const *, char const *, sqlite_int64) , void *)
void* sqlite3_user_data (sqlite3_context *)
const void* sqlite3_value_blob (sqlite3_value *)
int sqlite3_value_bytes (sqlite3_value *)
int sqlite3_value_bytes16 (sqlite3_value *)
double sqlite3_value_double (sqlite3_value *)
int sqlite3_value_int (sqlite3_value *)
sqlite_int64 sqlite3_value_int64 (sqlite3_value *)
int sqlite3_value_numeric_type (sqlite3_value *)
const unsigned char* sqlite3_value_text (sqlite3_value *)
const void* sqlite3_value_text16 (sqlite3_value *)
const void* sqlite3_value_text16be (sqlite3_value *)
const void* sqlite3_value_text16le (sqlite3_value *)
int sqlite3_value_type (sqlite3_value *)
char* sqlite3_vmprintf (const char * , va_list)
int int int int int int int srand48_r (long int __seedval, struct drand48_data * __buffer)
int int srandom_r (unsigned int __seed, struct random_data * __buf)
_Bool start_buddy_svc (upk_svc_desc_t * buddy)
int stat (__const char *__restrict __file, struct stat *__restrict __buf)
Referenced by buddy_exec_action(), create_buddy(), upk_mkdir_p(), upk_rm_rf(), and upk_state_init().
int stat64 (__const char *__restrict __file, struct stat64 *__restrict __buf)
_Bool stop_buddy_svc (upk_svc_desc_t * buddy)
long int unsigned long int __extension__ long long int __extension__ unsigned long long int double strtod_l (__const char *__restrict __nptr, char **__restrict __endptr, __locale_t __loc)
long int unsigned long int __extension__ long long int __extension__ unsigned long long int double float strtof_l (__const char *__restrict __nptr, char **__restrict __endptr, __locale_t __loc)
long int strtol_l (__const char *__restrict __nptr, char **__restrict __endptr, int __base, __locale_t __loc)
long int unsigned long int __extension__ long long int __extension__ unsigned long long int double float long double strtold_l (__const char *__restrict __nptr, char **__restrict __endptr, __locale_t __loc)
long int unsigned long int __extension__ long long int strtoll_l (__const char *__restrict __nptr, char **__restrict __endptr, int __base, __locale_t __loc)
long int unsigned long int strtoul_l (__const char *__restrict __nptr, char **__restrict __endptr, int __base, __locale_t __loc)
long int unsigned long int __extension__ long long int __extension__ unsigned long long int strtoull_l (__const char *__restrict __nptr, char **__restrict __endptr, int __base, __locale_t __loc)
int sync_file_range (int __fd, __off64_t __from, __off64_t __to, unsigned int __flags)
long int sysconf (int __name)
Referenced by upk_svcconf_string_handler().
int tee (int __fdin, int __fdout, size_t __len, unsigned int __flags)
long int telldir (DIR * __dirp)
__mode_t umask (__mode_t __mask)
Referenced by buddy_init_socket().
_Bool upk_boolean_string (const char * string, _Bool * val)
Referenced by main().
upk_conn_handle_meta_t* upk_clnet_ctrl_connect (void)
****************************************************************************************************************
Referenced by main().
void upk_clnet_ctrl_disconnect (upk_conn_handle_meta_t * ctrl)
****************************************************************************************************************
Referenced by main().
_Bool upk_clnet_req_action (upk_conn_handle_meta_t * ctrl, char * svc_id, char * action)
****************************************************************************************************************
Referenced by main().
void upk_clnet_req_disconnect (upk_conn_handle_meta_t * ctrl)
****************************************************************************************************************
Referenced by upk_clnet_ctrl_disconnect().
void upk_clnet_req_preamble (upk_conn_handle_meta_t * ctrl)
****************************************************************************************************************
Referenced by upk_clnet_ctrl_connect().
upk_payload_t* upk_clnet_serial_request (upk_conn_handle_meta_t * ctrl, upk_packet_t * pkt)
****************************************************************************************************************
Referenced by upk_clnet_req_action(), upk_clnet_req_disconnect(), upk_clnet_req_preamble(), upk_clnet_req_signal(), and upk_clnet_req_status().
uint32_t upk_crc32 (unsigned char * block, uint32_t len)
Referenced by upk_db_upsert_options(), upk_serialize_packet(), and upk_verify_crc32().
void upk_create_crc32_table (uint32_t crc_table[256])
upk_packet_t* upk_create_repl_result (upk_protocol_handle_t * handle, char * msg, _Bool successful)
Referenced by ctrl_req_action_handler().
upk_packet_t* upk_create_repl_seq_end (upk_protocol_handle_t * handle, _Bool commit)
upk_packet_t* upk_create_req_seq_end (upk_protocol_handle_t * handle, _Bool commit)
upk_packet_t* upk_create_req_signal (upk_protocol_handle_t * handle, char * svc_id, upk_signal_t signal, _Bool signal_sid, _Bool signal_pgrp)
Referenced by upk_clnet_req_signal().
upk_packet_t* upk_create_req_subscribe (upk_protocol_handle_t * handle, char * svc_id, _Bool all_svcs)
upk_packet_t* upk_create_req_unsubscribe (upk_protocol_handle_t * handle, char * svc_id, _Bool all_svcs)
int upk_ctrl_init (void)
******************************************************************************************************************
_Bool upk_db_add_new_service (sqlite3 * dbh, upk_svc_desc_t * svc)
References __upk_err_buf, __upk_errno_type, _upk_error(), _upk_svc_desc::Name, _upk_svc_desc::Package, sqlite3_exec(), sqlite3_free(), upk_concat_svcid(), UPK_CONF_ERROR, upk_db_gen_uuid(), upk_db_get_cfg_services_table(), upk_db_get_single_text(), UPK_SQL_ERROR, upk_strerror(), upk_string_to_uuid(), upk_uuid_to_string(), and _upk_svc_desc::UUID.
char* upk_db_gen_uuid (sqlite3 * dbh)
References strnlen(), upk_db_get_cfg_services_table(), upk_db_get_single_text(), upk_gen_uuid_bytes(), upk_uuid_open_random(), upk_uuid_seed_random(), and upk_uuid_to_string().
int upk_db_get_cfg_svc_list_options_table (sqlite3 * dbh, char * table_id)
References upk_db_get_table_id().
static int upk_db_get_table_id (sqlite3 * dbh, const char * db, const char * table_name, char * table_id) [static]
References upk_db_get_single_text().
Referenced by upk_db_get_audit_service_table(), upk_db_get_cfg_services_table(), upk_db_get_cfg_svc_list_options_table(), and upk_db_get_cfg_svc_options_table().
static int upk_db_try_insert (sqlite3 * dbh, char * table_id, upk_svc_desc_t * svc, int type, char * optkey, void * optval, size_t len, char * section, char * id) [inline, static]
References __upk_err_buf, __upk_errno_type, _upk_error(), sqlite3_bind_blob(), sqlite3_bind_double(), sqlite3_bind_int(), sqlite3_bind_null(), sqlite3_bind_text(), sqlite3_errmsg(), sqlite3_finalize(), sqlite3_prepare(), sqlite3_reset(), sqlite3_step(), UPK_SQL_ERROR, upk_strerror(), upk_uuid_to_string(), and _upk_svc_desc::UUID.
Referenced by upk_db_upsert().
static int upk_db_try_update (sqlite3 * dbh, char * table_id, upk_svc_desc_t * svc, int type, char * optkey, void * optval, size_t len, char * section, char * id) [inline, static]
References __upk_err_buf, __upk_errno_type, _upk_error(), sqlite3_bind_blob(), sqlite3_bind_double(), sqlite3_bind_int(), sqlite3_bind_null(), sqlite3_bind_text(), sqlite3_errmsg(), sqlite3_finalize(), sqlite3_prepare(), sqlite3_reset(), sqlite3_step(), UPK_SQL_ERROR, upk_strerror(), upk_uuid_to_string(), and _upk_svc_desc::UUID.
Referenced by upk_db_upsert().
_Bool upk_db_upsert (sqlite3 * dbh, char * table_id, upk_svc_desc_t * svc, int type, char * optkey, void * optval, size_t len, char * section, char * id)
References _upk_verbose(), _upk_svc_desc::Name, _upk_svc_desc::Package, upk_concat_svcid(), upk_db_try_insert(), upk_db_try_update(), upk_uuid_to_string(), and _upk_svc_desc::UUID.
int32_t upk_db_upsert_options (sqlite3 * dbh, upk_svc_desc_t * svc)
References _upk_debug1(), calloc(), _upk_cust_actscr_meta_p::count, _upk_svcid_meta_p::count, _upk_svc_desc::CustomActions, _upk_svc_desc::ExecReload, _upk_svc_desc::ExecStart, _upk_svc_desc::ExecStop, free(), _upk_cust_actscr_meta_p::head, _upk_svcid_meta_p::head, _upk_svc_desc::InitialState, _upk_svc_desc::KillTimeout, _upk_svc_desc::LongDescription, _upk_svc_desc::MaxConsecutiveFailures, _upk_cust_actscr_list::name, _upk_svcid::name, _upk_svc_desc::Name, _upk_cust_actscr_list::next, _upk_svcid::next, _upk_cust_actscr_meta_p::nextp, _upk_svcid_meta_p::nextp, _upk_svc_desc::Package, _upk_svc_desc::PipeStderrScript, _upk_svc_desc::PipeStdoutScript, _upk_svcid::pkg, _upk_svc_desc::PreferBuddyStateForRunning, _upk_svc_desc::PreferBuddyStateForStopped, _upk_cust_actscr_meta_p::prevp, _upk_svcid_meta_p::prevp, _upk_svc_desc::Provides, _upk_svc_desc::RandomizeRateLimit, realloc(), _upk_svc_desc::ReconnectRetries, _upk_svc_desc::RedirectStderr, _upk_svc_desc::RedirectStdout, _upk_svc_desc::ReloadScript, _upk_svc_desc::RestartAllDependencies, _upk_svc_desc::RestartOnNamedPrereqRestart, _upk_svc_desc::RestartOnPrerequisiteRestart, _upk_svc_desc::RingbufferSize, _upk_cust_actscr_list::script, _upk_svc_desc::SetGID, _upk_svc_desc::SetUID, _upk_svc_desc::ShortDescription, sqlite3_exec(), sqlite3_free(), _upk_svc_desc::StartAfter, _upk_svc_desc::StartPriority, _upk_svc_desc::StartScript, _upk_svc_desc::StartupDelay, _upk_svc_desc::StopScript, strnlen(), _upk_cust_actscr_meta_p::tempp, _upk_svcid_meta_p::tempp, _upk_cust_actscr_meta_p::thisp, _upk_svcid_meta_p::thisp, _upk_svc_desc::UnconfigureOnFileRemoval, upk_crc32(), upk_db_get_cfg_svc_list_options_table(), upk_db_get_cfg_svc_options_table(), upk_db_upsert(), upk_uuid_to_string(), _upk_svc_desc::UserMaxRestarts, _upk_svc_desc::UserRateLimit, _upk_svc_desc::UserRestartWindow, and _upk_svc_desc::UUID.
upk_packet_t* upk_deserialize_packet (upk_pkt_buf_t * __upk_buf)
Referenced by upk_read_packets().
void* upk_deserialize_repl_preamble (upk_pkt_buf_t * __upk_buf)
void* upk_deserialize_req_preamble (upk_pkt_buf_t * __upk_buf)
struct timeval upk_double_to_timeval (long double r) [read]
***************************************************************************
Referenced by upk_net_event_dispatcher().
void upk_gen_uuid_bytes (upk_uuid_t * buf)
Referenced by START_TEST(), and upk_db_gen_uuid().
int upk_mkdir_p (const char * path)
create a directory and any path components leading up to it.
***************************************************************************
Parameters:
[in] path directory to create.
Returns:
the number of directories successfully created.
Referenced by upk_state_init().
_Bool upk_numeric_string (const char * string, long * num)
***************************************************************************
Referenced by main(), and upk_boolean_string().
diag_output_callback_t upk_reg_diag_callback (diag_output_callback_t func)
Referenced by buddy_init().
err_rpt_msg_callback_t upk_reg_err_msg_callback (err_rpt_msg_callback_t func)
err_rpt_callback_t upk_reg_error_callback (err_rpt_callback_t func)
void upk_replace_string (char ** haystack, const char * needle, const char * repl)
***************************************************************************
Referenced by START_TEST(), and upk_finalize_svc_desc().
void upk_report_error (upk_errno_t err)
void upk_report_error_msg (upk_errno_t err, const char * msg)
int upk_rm_rf (char * start_path)
***************************************************************************
Referenced by handle_buddies(), main(), remove_buddy_statedir(), and upk_rm_rf().
upk_pkt_buf_t* upk_serialize_packet (upk_packet_t * __upk_data_ptr)
Referenced by upk_queue_packet().
upk_pkt_buf_t* upk_serialize_repl_preamble (void * __upk_data_ptr, size_t __upk_data_len)
upk_pkt_buf_t* upk_serialize_req_preamble (void * __upk_data_ptr, size_t __upk_data_len)
const char* upk_strerror (upk_errno_t err)
Referenced by upk_db_add_new_service(), upk_db_get_single_text(), upk_db_insert_cfg(), upk_db_try_insert(), and upk_db_try_update().
void upk_string_to_uuid (upk_uuid_t * uuid, const char * string)
Referenced by main(), opt_parse(), START_TEST(), upk_db_add_new_service(), upk_db_insert_cfg(), upk_svc_desc_to_json_obj(), and upk_svcconf_string_handler().
int upk_uuid_open_random (void)
Referenced by upk_db_gen_uuid(), and upk_gen_uuid_bytes().
void upk_uuid_seed_random (void)
Referenced by upk_db_gen_uuid().
void upk_uuid_to_string (char * buf, const upk_uuid_t * uuid)
Referenced by buddy_readstate(), spawn_buddy(), START_TEST(), upk_db_add_new_service(), upk_db_gen_uuid(), upk_db_insert_cfg(), upk_db_try_insert(), upk_db_try_update(), upk_db_upsert(), and upk_db_upsert_options().
_Bool upk_verify_crc32 (unsigned char * block, uint32_t crc32, uint32_t len)
Referenced by upk_deserialize_packet().
_Bool upkeeper_action_request (char * service_id, char * action_name)
upk_svcinfo_t upkeeper_get_status (char * service_id)
upk_svcid_t* upkeeper_list_services (void)
_Bool upkeeper_signal_request (char * service_id, upk_signal_t signal)
_Bool upkeeper_subscribe (const char * svc_id)
_Bool upkeeper_subscribe_all (void)
int utimes (__const char * __file, __const struct timeval __tvp[2])
upk_packet_t* v0_create_repl_result (char * msg, _Bool successful)
Referenced by upk_create_repl_result().
upk_packet_t* v0_create_repl_seq_end (_Bool commit)
Referenced by upk_create_repl_seq_end().
upk_packet_t* v0_create_req_seq_end (_Bool commit)
Referenced by upk_create_req_seq_end().
upk_packet_t* v0_create_req_signal (char * svc_id, upk_signal_t signal, _Bool signal_sid, _Bool signal_pgrp)
Referenced by upk_create_req_signal().
upk_packet_t* v0_create_req_subscribe (char * svc_id, _Bool all_svcs)
Referenced by upk_create_req_subscribe().
upk_packet_t* v0_create_req_unsubscribe (char * svc_id, _Bool all_svcs)
Referenced by upk_create_req_unsubscribe().
void* v0_deserialize_payload (upk_pkt_buf_t * __upk_buf, upk_pkttype_t pkttype)
Referenced by upk_deserialize_payload().
upk_pkt_buf_t* v0_serialize_payload (upk_packet_t * pkt)
Referenced by upk_serialize_payload().
void* valloc (size_t __size)
int int int int int versionsort (__const void * __e1, __const void * __e2)
int int int int int int versionsort64 (__const void * __e1, __const void * __e2)
int vmsplice (int __fdout, const struct iovec * __iov, size_t __count, unsigned int __flags)
__pid_t wait (__WAIT_STATUS __stat_loc)
__pid_t wait3 (__WAIT_STATUS __stat_loc, int __options, struct rusage * __usage)
__pid_t wait4 (__pid_t __pid, __WAIT_STATUS __stat_loc, int __options, struct rusage * __usage)
int waitid (idtype_t __idtype, __id_t __id, siginfo_t * __infop, int __options)
__pid_t waitpid (__pid_t __pid, int * __stat_loc, int __options)
Referenced by handle_signals(), and sa_sigaction_func().
ssize_t writev (int __fd, __const struct iovec * __iovec, int __count)
Variable Documentation
* __locale_t
const char* __progname
char __upk_err_buf[4096]
Referenced by upk_db_add_new_service(), upk_db_get_single_text(), upk_db_insert_cfg(), upk_db_try_insert(), and upk_db_try_update().
upk_errno_t __upk_errno_type
Referenced by upk_db_add_new_service(), upk_db_get_single_text(), upk_db_insert_cfg(), upk_db_try_insert(), and upk_db_try_update().
const char __upk_errors[][128] [static]
Initial value:
 {
    "unknown",
    "unsupported",
    "invalid packet",
    "socket failure",
    "JSON parser error",
    "SQlite Error",
    "Configuration Error",
}
Referenced by upk_strerror().
struct _IO_FILE_plus _IO_2_1_stderr_
struct _IO_FILE_plus _IO_2_1_stdin_
struct _IO_FILE_plus _IO_2_1_stdout_
__const char* __const _sys_siglist[65]
sqlite3* ctrl_dbh
struct in6_addr in6addr_any
struct in6_addr in6addr_loopback
char label_idx[][16]
sigval_t
char* sqlite3_temp_directory
const char sqlite3_version[]
__const char* __const sys_siglist[65]
const char upk_diag_label_idx[][16] [static]
Initial value:
 {
    [UPK_DIAGLVL_FATAL] = "FATAL",
    [UPK_DIAGLVL_ALERT] = "ALERT",
    [UPK_DIAGLVL_CRIT] = "CRITICAL",
    [UPK_DIAGLVL_ERROR] = "ERROR",
    [UPK_DIAGLVL_WARN] = "WARNING",
    [UPK_DIAGLVL_NOTICE] = "NOTICE",
    [UPK_DIAGLVL_VERBOSE] = "VERBOSE",
    [UPK_DIAGLVL_INFO] = "INFO",
    [UPK_DIAGLVL_DEBUG0] = "DEBUG0",
    [UPK_DIAGLVL_DEBUG1] = "DEBUG1"
}
Referenced by _upk_diagnostic().
int32_t upk_diag_verbosity
Referenced by _upk_default_diag_output(), _upk_diagnostic(), buddy_diag_handler(), main(), opt_parse(), upk_clnet_req_action(), upk_clnet_req_signal(), upk_clnet_req_status(), and upk_load_runtime_services().