upkeeper: controller/controller_main.c File Reference
controller/controller_main.c File Reference
#include "controller.h"
#include "ctrl_protocol.h"
#include <stdio.h>
#include <errno.h>
Functions
int main (int argc, char **argv, char **envp)
Function Documentation
int main (int argc, char ** argv, char ** envp)
References create_buddy(), ctrl_sock_setup(), event_loop(), _upk_controller_config::svclist, upk_svc_desc_meta_p::thisp, upk_ctrl_free_config(), upk_ctrl_init(), upk_diag_verbosity, UPK_DIAGLVL_DEBUG1, upk_runtime_configuration, and UPKLIST_FOREACH.