upkeeper: controller/controller.c File Reference
controller/controller.c File Reference
#include <upkeeper.h>
#include "controller.h"
#include <sqlite3.h>
#include "ctrl_sql.h"
#include "ctrl_data.h"
Functions
void upk_state_init (void)
controller state initialization.
static void upk_db_path (char **pathbuf)
void upk_ctrl_attach_db (sqlite3 *dbh, char *db_path, char *db_name)
sqlite3 * upk_ctrl_init_db (char *db_path)
void upk_ctrl_exit (void)
int upk_ctrl_init (void)
Variables
sqlite3 * ctrl_dbh
Function Documentation
void upk_ctrl_attach_db (sqlite3 * dbh, char * db_path, char * db_name)
******************************************************************************************************************
References sqlite3_exec(), sqlite3_free(), upk_fatal, UPK_MAX_PATH_LEN, and UPK_MAX_STRING_LEN.
Referenced by upk_ctrl_init_db().
void upk_ctrl_exit (void)
******************************************************************************************************************
References ctrl_dbh, sqlite3_close(), and upk_ctrl_free_config().
Referenced by upk_ctrl_init().
int upk_ctrl_init (void)
******************************************************************************************************************
References ctrl_dbh, _upk_controller_config::svclist, upk_svc_desc_meta_p::thisp, upk_ctrl_exit(), upk_ctrl_init_db(), upk_ctrl_load_config(), upk_db_insert_cfg(), upk_db_path(), upk_file_configuration, upk_load_runtime_services(), UPK_MAX_PATH_LEN, upk_state_init(), and UPKLIST_FOREACH.
Referenced by main().
sqlite3* upk_ctrl_init_db (char * db_path)
******************************************************************************************************************
References ctrl_create_audit_sql, ctrl_create_cfg_sql, sqlite3_exec(), sqlite3_free(), sqlite3_open(), strnlen(), upk_ctrl_attach_db(), upk_fatal, and UPK_MAX_PATH_LEN.
Referenced by upk_ctrl_init().
static void upk_db_path (char ** pathbuf) [static]
******************************************************************************************************************
References _upk_controller_config::StateDir, upk_fatal, and upk_runtime_configuration.
Referenced by upk_ctrl_init().
void upk_state_init (void)
controller state initialization.
******************************************************************************************************************
References stat::st_mode, stat(), _upk_controller_config::StateDir, upk_fatal, upk_mkdir_p(), and upk_runtime_configuration.
Referenced by upk_ctrl_init().
Variable Documentation
sqlite3* ctrl_dbh
Referenced by upk_ctrl_exit(), and upk_ctrl_init().