upkeeper: controller/ctrl_eventloop.c File Reference
controller/ctrl_eventloop.c File Reference
#include "controller.h"
#include <stdio.h>
#include <errno.h>
Functions
void controller_packet_callback (upk_conn_handle_meta_t *clients, upk_payload_t *)
void ctrl_req_action_handler (upk_conn_handle_meta_t *clients, upk_payload_t *msg)
Handler to call when an action request is received from a client, signature is of upk_net_callback_t,.
void ctrl_req_preamble_handler (upk_conn_handle_meta_t *clients, upk_payload_t *msg)
Handler to call when an preamble request is received from a client, signature is of upk_net_callback_t,.
void ctrl_req_disconnect_handler (upk_conn_handle_meta_t *clients, upk_payload_t *msg)
Handler to call when an disconnect request is received from a client, signature is of upk_net_callback_t,.
static void init_callback_handlers (upk_conn_handle_meta_t *clients)
setup initial callback handlers
static void ctrl_accept_conn (int32_t listen_sock, upk_conn_handle_meta_t *clients)
accept() and setup a handle for an incomming connection.
void sa_sigaction_func (int signal, siginfo_t *siginfo, void *ucontext)
place received signals into a queue to handle later.
void ctrl_exit_cleanup (void)
cleanup allocated structures at exit; makes valgrind happy, so I can find more signicant issues
static void ctrl_setup_sighandlers (void)
setup signal handlers
upk_conn_handle_meta_t * ctrl_init (void)
initialization before eventloop
void event_loop (int32_t listen_sock)
the main event loop.
int32_t ctrl_sock_setup (void)
setup controller's socket
void handle_signals (void)
deal with signals pending action in signal_queue.
Variables
static ctrl_sigqueue_meta_t * ctrl_signal_queue
static upk_conn_handle_meta_t * clients_list_for_cleanup
Function Documentation
void controller_packet_callback (upk_conn_handle_meta_t * clients, upk_payload_t *)
static void ctrl_accept_conn (int32_t listen_sock, upk_conn_handle_meta_t * clients) [static]
accept() and setup a handle for an incomming connection.
*****************************************************************************************************************
Parameters:
[in] listen_sock The socket the request is coming in on.
[in,out] clients The llist of clients, which will be modified if the connection is accepted.
References accept(), and upk_net_add_socket_handle().
Referenced by event_loop().
void ctrl_exit_cleanup (void)
cleanup allocated structures at exit; makes valgrind happy, so I can find more signicant issues
*****************************************************************************************************************
References UPKLIST_FREE.
Referenced by ctrl_init().
upk_conn_handle_meta_t* ctrl_init (void)
initialization before eventloop
***************************************************************************************************************** This will handle signals, poll buddies, poll clients, publish events, and cleanup sockets.
References calloc(), ctrl_exit_cleanup(), ctrl_setup_sighandlers(), init_callback_handlers(), and upk_net_conn_handles_init().
Referenced by event_loop().
void ctrl_req_action_handler (upk_conn_handle_meta_t * clients, upk_payload_t * msg)
Handler to call when an action request is received from a client, signature is of upk_net_callback_t,.
*****************************************************************************************************************
Parameters:
[in] clients The llist of handles, and clients->thisp is the current handle.
[in] msg The action request message.
References upk_req_action_t::action, _upk_svc_desc::Name, _upk_payload::payload, reload_buddy_svc(), _upk_payload_types::req_action, start_buddy_svc(), stop_buddy_svc(), upk_req_action_t::svc_id, _upk_controller_config::svclist, upk_svc_desc_meta_p::thisp, upk_conn_handle_meta_p::thisp, upk_create_repl_result(), upk_debug1, UPK_MAX_STRING_LEN, upk_pkt_free(), upk_queue_packet(), upk_runtime_configuration, and UPKLIST_FOREACH.
Referenced by init_callback_handlers().
void ctrl_req_disconnect_handler (upk_conn_handle_meta_t * clients, upk_payload_t * msg)
Handler to call when an disconnect request is received from a client, signature is of upk_net_callback_t,.
*****************************************************************************************************************
Parameters:
[in] clients The llist of handles, and clients->thisp is the current handle.
[in] msg The disconnect request message.
References _upk_conn_handle::cl_name, upk_conn_handle_meta_p::thisp, upk_create_req_disconnect(), upk_debug1, upk_net_shutdown_callback(), upk_pkt_free(), and upk_queue_packet().
Referenced by init_callback_handlers().
void ctrl_req_preamble_handler (upk_conn_handle_meta_t * clients, upk_payload_t * msg)
Handler to call when an preamble request is received from a client, signature is of upk_net_callback_t,.
*****************************************************************************************************************
Parameters:
[in] clients The llist of handles, and clients->thisp is the current handle.
[in] msg The preamble request message.
References _upk_conn_handle::cl_name, upk_req_preamble_t::client_name, upk_req_preamble_t::max_supported_ver, upk_req_preamble_t::min_supported_ver, upk_packet_t::payload, _upk_payload::payload, _upk_payload_types::req_preamble, upk_conn_handle_meta_p::thisp, upk_create_repl_preamble(), upk_debug1, UPK_MAX_STRING_LEN, UPK_MAX_SUPPORTED_PROTO, UPK_MIN_SUPPORTED_PROTO, upk_pkt_free(), and upk_queue_packet().
Referenced by init_callback_handlers().
static void ctrl_setup_sighandlers (void) [inline, static]
setup signal handlers
*****************************************************************************************************************
References sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, sa_sigaction_func(), sigaction(), sigemptyset(), sigfillset(), and upk_fatal.
Referenced by ctrl_init().
int32_t ctrl_sock_setup (void)
setup controller's socket
*****************************************************************************************************************
References bind(), _upk_controller_config::controller_socket, fcntl(), IF_UPK_ERROR, listen(), SOCK_STREAM, socket(), sockaddr_un::sun_family, sockaddr_un::sun_path, UPK_FUNC_ASSERT, UPK_FUNC_ASSERT_MSG, upk_runtime_configuration, and UPK_SOCKET_FAILURE.
Referenced by main().
void event_loop (int32_t listen_sock)
the main event loop.
***************************************************************************************************************** This will handle signals, poll buddies, poll clients, publish events, and cleanup sockets.
References _upk_controller_config::BuddyPollingInterval, ctrl_accept_conn(), ctrl_init(), handle_buddies(), handle_signals(), select(), upk_debug1, upk_net_event_dispatcher(), upk_net_flush_closed_sockets(), and upk_runtime_configuration.
Referenced by main().
void handle_signals (void)
deal with signals pending action in signal_queue.
***************************************************************************************************************** Block all signals during copy to avoid annoying race conditions.
References ctrl_sigqueue_meta_p::count, siginfo::si_pid, sigfillset(), _ctrl_sigqueue::siginfo, _ctrl_sigqueue::signal, sigprocmask(), sigset(), ctrl_sigqueue_meta_p::thisp, UPKLIST_HEAD, UPKLIST_UNLINK, and waitpid().
Referenced by event_loop().
static void init_callback_handlers (upk_conn_handle_meta_t * clients) [static]
setup initial callback handlers
*****************************************************************************************************************
References _upk_net_state::callback_stack, ctrl_req_action_handler(), ctrl_req_disconnect_handler(), ctrl_req_preamble_handler(), upk_net_cb_stk_meta_p::head, _upk_net_cb_stk::msg_handlers, UPK_MSGTYPE_IDX, upk_net_get_global_state(), UPK_REQ_ACTION, UPK_REQ_DISCONNECT, UPK_REQ_PREAMBLE, and UPKLIST_PREPEND.
Referenced by ctrl_init().
void sa_sigaction_func (int signal, siginfo_t * siginfo, void * ucontext)
place received signals into a queue to handle later.
***************************************************************************************************************** Because most signal handling will have fairly significant work to do, all signal handling is done via queuing the receipt to the 'ctrl_signal_queue', and processing is deferred to the event loop; specifically the "handle_signals" function called first in the event loop.
References _ctrl_sigqueue::siginfo, _ctrl_sigqueue::signal, ctrl_sigqueue_meta_p::thisp, and UPKLIST_APPEND.
Referenced by ctrl_setup_sighandlers().
Variable Documentation
upk_conn_handle_meta_t* clients_list_for_cleanup [static]
ctrl_sigqueue_meta_t* ctrl_signal_queue [static]