upkeeper: controller/ctrl_buddy.c File Reference
controller/ctrl_buddy.c File Reference
#include <upkeeper.h>
#include "controller.h"
Functions
static bool create_buddy_statedir (upk_svc_desc_t *buddy)
static bool remove_buddy_statedir (upk_svc_desc_t *buddy)
bool spawn_buddy (upk_svc_desc_t *buddy)
bool kill_buddy (upk_svc_desc_t *buddy)
static bool send_buddy_cmd (int fd, buddy_cmnd_t cmd)
static char * buddy_sock_path (upk_svc_desc_t *buddy, char *pathbuf)
void create_buddy (upk_svc_desc_t *buddy)
void remove_buddy (upk_svc_desc_t *buddy)
int buddy_connect (const char *sockpath)
buddy_info_t * buddy_readstate (int fd)
upk_svc_desc_t * lookup_buddy_from_path (char *buddy_path)
void handle_buddies (void)
bool start_buddy_svc (upk_svc_desc_t *buddy)
bool stop_buddy_svc (upk_svc_desc_t *buddy)
bool reload_buddy_svc (upk_svc_desc_t *buddy)
Function Documentation
int buddy_connect (const char * sockpath)
References connect(), SOCK_STREAM, socket(), sockaddr_un::sun_family, sockaddr_un::sun_path, and upk_alert.
Referenced by handle_buddies(), kill_buddy(), reload_buddy_svc(), start_buddy_svc(), and stop_buddy_svc().
buddy_info_t* buddy_readstate (int fd)
References _buddy_info::command, _buddy_info::desired_state, _buddy_info::remaining, select(), _buddy_info::service_pid, _buddy_info::timestamp, timeval::tv_sec, timeval::tv_usec, UPK_CTRL_ACK, upk_debug0, upk_debug1, upk_uuid_to_string(), _buddy_info::uuid, _buddy_info::wait_pid, and _buddy_info::wait_status.
Referenced by send_buddy_cmd().
static char* buddy_sock_path (upk_svc_desc_t * buddy, char * pathbuf) [inline, static]
References _upk_svc_desc::Name, _upk_controller_config::SvcRunPath, UPK_MAX_PATH_LEN, and upk_runtime_configuration.
Referenced by create_buddy(), kill_buddy(), reload_buddy_svc(), start_buddy_svc(), and stop_buddy_svc().
void create_buddy (upk_svc_desc_t * buddy)
References buddy_sock_path(), create_buddy_statedir(), spawn_buddy(), stat::st_mode, stat(), and UPK_MAX_PATH_LEN.
Referenced by main().
static bool create_buddy_statedir (upk_svc_desc_t * buddy) [static]
References _upk_controller_config::controller_buddy_sock, _upk_controller_config::controller_socket, _upk_svc_desc::CustomActions, fchmod(), _upk_cust_actscr_list::name, _upk_svc_desc::Name, _upk_svc_desc::ReloadScript, _upk_cust_actscr_list::script, _upk_svc_desc::StartScript, _upk_svc_desc::StopScript, _upk_controller_config::SvcRunPath, _upk_cust_actscr_meta_p::thisp, UPK_MAX_PATH_LEN, upk_runtime_configuration, upk_verbose, and UPKLIST_FOREACH.
Referenced by create_buddy().
void handle_buddies (void)
References buddy_connect(), closedir(), lookup_buddy_from_path(), opendir(), readdir(), remove_buddy(), send_buddy_cmd(), _upk_controller_config::SvcRunPath, UPK_CTRL_STATUS_REQ, UPK_MAX_PATH_LEN, upk_rm_rf(), and upk_runtime_configuration.
Referenced by event_loop().
bool kill_buddy (upk_svc_desc_t * buddy)
References buddy_connect(), buddy_sock_path(), send_buddy_cmd(), UPK_CTRL_SHUTDOWN, and UPK_MAX_PATH_LEN.
Referenced by remove_buddy().
upk_svc_desc_t* lookup_buddy_from_path (char * buddy_path)
References _upk_svc_desc::Name, _upk_controller_config::svclist, upk_svc_desc_meta_p::thisp, UPK_MAX_PATH_LEN, upk_runtime_configuration, and UPKLIST_FOREACH.
Referenced by handle_buddies().
bool reload_buddy_svc (upk_svc_desc_t * buddy)
References buddy_connect(), buddy_sock_path(), send_buddy_cmd(), UPK_CTRL_ACTION_RELOAD, and UPK_MAX_PATH_LEN.
Referenced by ctrl_req_action_handler().
void remove_buddy (upk_svc_desc_t * buddy)
References kill_buddy(), and remove_buddy_statedir().
Referenced by handle_buddies().
static bool remove_buddy_statedir (upk_svc_desc_t * buddy) [static]
References closedir(), _upk_controller_config::controller_buddy_sock, _upk_svc_desc::CustomActions, _upk_cust_actscr_list::name, _upk_svc_desc::Name, opendir(), readdir(), _upk_controller_config::SvcRunPath, _upk_cust_actscr_meta_p::thisp, UPK_MAX_PATH_LEN, upk_rm_rf(), upk_runtime_configuration, upk_verbose, and UPKLIST_FOREACH.
Referenced by remove_buddy().
static bool send_buddy_cmd (int fd, buddy_cmnd_t cmd) [static]
References buddy_readstate(), select(), SHUT_RDWR, shutdown(), and timeval::tv_sec.
Referenced by handle_buddies(), kill_buddy(), reload_buddy_svc(), start_buddy_svc(), and stop_buddy_svc().
bool spawn_buddy (upk_svc_desc_t * buddy)
References buddy_path(), buddy_uuid, _upk_controller_config::BuddyVerbosity, _upk_svc_desc::Name, _upk_controller_config::SvcRunPath, timespec::tv_sec, upk_fatal, UPK_MAX_PATH_LEN, upk_runtime_configuration, UPK_UUID_STRING_LEN, upk_uuid_to_string(), upk_verbose, _upk_controller_config::UpkBuddyPath, and _upk_svc_desc::UUID.
Referenced by create_buddy().
bool start_buddy_svc (upk_svc_desc_t * buddy)
References buddy_connect(), buddy_sock_path(), send_buddy_cmd(), UPK_CTRL_ACTION_START, and UPK_MAX_PATH_LEN.
Referenced by ctrl_req_action_handler().
bool stop_buddy_svc (upk_svc_desc_t * buddy)
References buddy_connect(), buddy_sock_path(), send_buddy_cmd(), UPK_CTRL_ACTION_STOP, and UPK_MAX_PATH_LEN.
Referenced by ctrl_req_action_handler().