upkeeper: libupkeeper/tests/dlinked_lists.c File Reference
libupkeeper/tests/dlinked_lists.c File Reference
#include <check.h>
#include <upkeeper.h>
Data Structures
struct _test_foo
Typedefs
typedef struct _test_foo test_foo_t
Functions
START_TEST (test_swap)
START_TEST (test_prepend)
START_TEST (test_append)
START_TEST (test_append_this)
START_TEST (test_unlink)
START_TEST (test_unlink_first)
START_TEST (reverse)
TCase * ll_tcase (void)
Suite * upk_ll_suite (void)
int main (void)
Variables
END_TEST
Typedef Documentation
typedef struct _test_foo test_foo_t
Function Documentation
TCase* ll_tcase (void)
Referenced by upk_ll_suite().
int main (void)
References suite(), and upk_ll_suite().
START_TEST (test_unlink)
References UPKDLIST_APPEND_THIS, UPKDLIST_FOREACH, UPKDLIST_FREE, UPKDLIST_INIT, and UPKDLIST_UNLINK.
START_TEST (test_prepend)
References UPKDLIST_FOREACH, UPKDLIST_FREE, UPKDLIST_INIT, and UPKDLIST_PREPEND.
START_TEST (reverse)
References UPKDLIST_APPEND_THIS, UPKDLIST_FOREACH_REVERSE, UPKDLIST_FREE, and UPKDLIST_INIT.
START_TEST (test_unlink_first)
References UPKDLIST_APPEND_THIS, UPKDLIST_FOREACH, UPKDLIST_FREE, UPKDLIST_INIT, and UPKDLIST_UNLINK.
START_TEST (test_swap)
References UPKDLIST_APPEND, UPKDLIST_FOREACH, UPKDLIST_FREE, UPKDLIST_INIT, and UPKDLIST_SWAP.
START_TEST (test_append_this)
References UPKDLIST_APPEND_THIS, UPKDLIST_FOREACH, UPKDLIST_FREE, and UPKDLIST_INIT.
START_TEST (test_append)
References UPKDLIST_APPEND, UPKDLIST_FOREACH, UPKDLIST_FREE, and UPKDLIST_INIT.
Suite* upk_ll_suite (void)
References ll_tcase(), and suite().
Referenced by main().
Variable Documentation
END_TEST