upkeeper: Uuid_functions
Uuid_functions
Uuid
Functions
void upk_uuid_seed_random (void)
seed random number pool used by upk_gen_uuid_bytes.
int upk_uuid_open_random (void)
open random device, prefering /dev/urandom, but also trying /dev/random if urandom is unavailable.
void upk_gen_uuid_bytes (upk_uuid_t *buf)
collect and/or generate 16 bytes of random data.
void upk_uuid_to_string (char *buf, const upk_uuid_t *uuid)
convert uuid to string and place in buf.
bool is_valid_upk_uuid_string (const char *string)
test if a given string is a valid uuid string.
void upk_string_to_uuid (const char *string, upk_uuid_t *uuid)
convert uuid string into uuid structure.
Function Documentation
bool is_valid_upk_uuid_string (const char * string)
test if a given string is a valid uuid string.
****************************************************************************************************************** verify string is 36 chars long; and consists of a correctly hiphen-separated sequence of hexidecimal digits
Parameters:
[in] string string to check
References c_isxdigit.
Referenced by opt_parse(), START_TEST(), and upk_string_to_uuid().
void upk_gen_uuid_bytes (upk_uuid_t * buf)
collect and/or generate 16 bytes of random data.
****************************************************************************************************************** pack the structure you passed; also sets version correctly on structure to conform with spec
Parameters:
[out] buf uuid structure to populate
References _upk_uuid::clk_seq_high, _upk_uuid::time_high_and_version, UPK_UUID_LEN, and upk_uuid_open_random().
Referenced by START_TEST().
void upk_string_to_uuid (const char * string, upk_uuid_t * uuid)
convert uuid string into uuid structure.
******************************************************************************************************************
Parameters:
[in] string uuid string to convert
[out] uuid pointer to buffer to populate
References _upk_uuid::clk_seq_high, _upk_uuid::clk_seq_low, is_valid_upk_uuid_string(), _upk_uuid::node, _upk_uuid::time_high_and_version, _upk_uuid::time_low, and _upk_uuid::time_mid.
Referenced by main(), opt_parse(), START_TEST(), upk_svc_desc_to_json_obj(), and upk_svcconf_string_handler().
int upk_uuid_open_random (void)
open random device, prefering /dev/urandom, but also trying /dev/random if urandom is unavailable.
******************************************************************************************************************
Returns:
fd of opened device
< 0 on error (check errno)
Referenced by upk_gen_uuid_bytes().
void upk_uuid_seed_random (void)
seed random number pool used by upk_gen_uuid_bytes.
***************************************************************************************************************** Only necessary if /dev/urandom and /dev/random are unavailable; for instance, check upk_uuid_open_random to see if you get a valid fd; if not, call this (unless you have already seeded random elsewhere, in whatever manner you prefer
void upk_uuid_to_string (char * buf, const upk_uuid_t * uuid)
convert uuid to string and place in buf.
******************************************************************************************************************
Parameters:
[out] buf string buffer (must be at least (UPK_UUID_STRING_LEN + 1) bytes long)
[in] uuid uuid structure to convert
References _upk_uuid::clk_seq_high, _upk_uuid::clk_seq_low, _upk_uuid::node, _upk_uuid::time_high_and_version, _upk_uuid::time_low, _upk_uuid::time_mid, and UPK_UUID_STRING_LEN.
Referenced by buddy_readstate(), and START_TEST().