upkeeper: API
API
Functions
char * upk_clientid (void)
bool upk_client_event_hook (void)
Function Documentation
bool upk_client_event_hook (void)
char* upk_clientid (void)
References getpid(), upk_getprogname, and UPK_MAX_STRING_LEN.
Referenced by main(), and upk_clnet_req_preamble().