upkeeper: Config_impl
Config_impl
Modules
Services
Controller
Functions
Defines
#define _joa json_object_object_add
#define jt_string json_type_string
#define jt_int json_type_int
#define jt_boolean json_type_boolean
#define jt_array json_type_array
Enumerations
enum appender_type_t { SVCID_APPENDER = 0, ACTION_APPENDER }
Functions
static void upk_svcconf_svcid_array_appender (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_svcconf_setup_array_handlers (upk_json_handlers_t *handlers)
static void upk_svcconf_array_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_svcconf_customaction_array_appender (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_svcconf_setup_object_handlers (upk_json_handlers_t *handlers)
static void upk_svcconf_nested_object_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_svcconf_setup_handlers (upk_json_handlers_t *handlers)
static void upk_ctrlconf_object_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_ctrlconf_string_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_ctrlconf_double_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_ctrlconf_toplvl_obj (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_svcconf_object_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_svcconf_toplvl_obj (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_ctrlconf_pack (upk_controller_config_t *cfg, const char *json_string)
static void upk_svcconf_bool_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_svcconf_int_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_svcconf_string_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_conf_error_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static char * upk_config_loadfile (const char *filename)
void upk_svc_desc_free (upk_svc_desc_t *svc)
void upk_svclist_free (upk_svc_desc_meta_t *svclist)
void upk_ctrlconf_free (upk_controller_config_t *cfg)
void upk_ctrl_free_config (void)
static void upk_ctrlconf_int_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
void upk_svcconf_pack (upk_controller_config_t *cfg, const char *json_string)
void upk_ctrl_load_config (void)
void upk_svc_desc_clear (upk_svc_desc_t *svc)
static void * upk_json_serialize_or_null (enum json_type type, void *val)
char * upk_concat_svcid (char *dest, const char *pkg, const char *name)
char * upk_svc_id (char *dest, upk_svc_desc_t *svc)
void upk_parse_svc_id (char *key, upk_svc_desc_t *svc)
struct json_object * upk_svclist_to_json_obj (upk_svc_desc_meta_t *svclist)
struct json_object * upk_svc_desc_to_json_obj (upk_svc_desc_t *svc)
char * upk_json_serialize_svc_config (upk_svc_desc_t *svc, upk_json_data_output_opts_t opts)
void upk_overlay_svcconf_values (upk_svc_desc_t *dest, upk_svc_desc_t *high)
void upk_overlay_ctrlconf_values (upk_controller_config_t *dest, upk_controller_config_t *high)
void upk_finalize_svc_desc (upk_svc_desc_t *dest, upk_svc_desc_t *orig)
void upk_load_runtime_service_file (const char *filename)
void upk_load_runtime_services (void)
Variables
char upk_ctrl_configuration_file [UPK_MAX_PATH_LEN] = "/upkeeper.conf"
const char upk_default_configuration_str [] = "}\n"
upk_controller_config_t upk_default_configuration
upk_controller_config_t upk_file_configuration
upk_controller_config_t upk_runtime_configuration
Define Documentation
#define _joa json_object_object_add
Referenced by upk_svc_desc_to_json_obj(), and upk_svclist_to_json_obj().
#define jt_array json_type_array
Referenced by upk_svc_desc_to_json_obj().
#define jt_boolean json_type_boolean
Referenced by upk_svc_desc_to_json_obj().
#define jt_int json_type_int
Referenced by upk_svc_desc_to_json_obj().
#define jt_string json_type_string
Referenced by upk_svc_desc_to_json_obj().
Enumeration Type Documentation
enum appender_type_t
Enumerator:
SVCID_APPENDER
ACTION_APPENDER
Function Documentation
char* upk_concat_svcid (char * dest, const char * pkg, const char * name)
References UPK_MAX_STRING_LEN.
Referenced by upk_db_add_new_service(), upk_db_insert_cfg(), upk_db_upsert(), upk_svc_desc_to_json_obj(), and upk_svc_id().
static void upk_conf_error_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References upk_alert.
Referenced by upk_ctrlconf_pack(), upk_ctrlconf_toplvl_obj(), upk_svcconf_pack(), upk_svcconf_setup_array_handlers(), upk_svcconf_setup_handlers(), upk_svcconf_setup_object_handlers(), and upk_svcconf_toplvl_obj().
static char * upk_config_loadfile (const char * filename) [static]
References calloc(), realloc(), strnlen(), upk_debug1, upk_default_configuration_str, UPK_MAX_STRING_LEN, and upk_warn.
Referenced by upk_ctrl_load_config(), and upk_load_runtime_services().
void upk_ctrl_free_config (void)
References upk_ctrlconf_free().
Referenced by main(), and upk_ctrl_exit().
void upk_ctrl_load_config (void)
References _upk_controller_config::BuddyPollingInterval, _upk_controller_config::controller_buddy_sock, _upk_controller_config::controller_socket, free(), _upk_controller_config::ServiceDefaults, _upk_controller_config::StateDir, upk_config_loadfile(), upk_ctrl_configuration_file, upk_ctrlconf_pack(), upk_default_configuration_str, UPK_MAX_STRING_LEN, upk_overlay_ctrlconf_values(), and upk_svc_desc_clear().
Referenced by main(), and upk_ctrl_init().
static void upk_ctrlconf_double_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_controller_config::BuddyPollingInterval, _upk_json_type::dbl, upk_fatal, and _upk_json_type::val.
Referenced by upk_ctrlconf_toplvl_obj().
void upk_ctrlconf_free (upk_controller_config_t * cfg)
References _upk_controller_config::ServiceDefaults, _upk_controller_config::svclist, upk_svc_desc_free(), and upk_svclist_free().
Referenced by upk_ctrl_free_config().
static void upk_ctrlconf_int_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_controller_config::BuddyPollingInterval, _upk_controller_config::BuddyVerbosity, _upk_json_type::i, upk_fatal, and _upk_json_type::val.
Referenced by upk_ctrlconf_toplvl_obj().
static void upk_ctrlconf_object_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_json_stack_node::data, _upk_json_stack_node::handlers, _upk_controller_config::ServiceDefaults, upk_json_stack_push(), upk_parse_svc_id(), and upk_svcconf_setup_handlers().
Referenced by upk_ctrlconf_toplvl_obj().
static void upk_ctrlconf_pack (upk_controller_config_t * cfg, const char * json_string) [static]
References _upk_json_stack_handlers::after_json_array_pop, _upk_json_stack_handlers::after_json_obj_pop, calloc(), _upk_json_stack_node::data, _upk_json_stack_node::handlers, _upk_json_stack_handlers::json_array, _upk_json_stack_handlers::json_bool, _upk_json_stack_handlers::json_double, _upk_json_stack_handlers::json_int, _upk_json_stack_handlers::json_null, _upk_json_stack_handlers::json_object, _upk_json_stack_handlers::json_string, restrict, upk_conf_error_handler(), upk_ctrlconf_toplvl_obj(), upk_json_parse_node(), upk_json_parse_string(), upk_json_stack_meta_t, upk_json_stack_push(), and UPKLIST_FREE.
Referenced by upk_ctrl_load_config().
static void upk_ctrlconf_string_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_json_string::c_str, _upk_controller_config::StateDir, _upk_json_type::str, _upk_controller_config::SvcConfigPath, _upk_controller_config::SvcRunPath, upk_fatal, UPK_MAX_STRING_LEN, _upk_controller_config::UpkBuddyPath, and _upk_json_type::val.
Referenced by upk_ctrlconf_toplvl_obj().
static void upk_ctrlconf_toplvl_obj (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_json_stack_handlers::after_json_array_pop, _upk_json_stack_handlers::after_json_obj_pop, _upk_json_stack_node::data, _upk_json_stack_node::handlers, _upk_json_stack_handlers::json_array, _upk_json_stack_handlers::json_bool, _upk_json_stack_handlers::json_double, _upk_json_stack_handlers::json_int, _upk_json_stack_handlers::json_null, _upk_json_stack_handlers::json_object, _upk_json_stack_handlers::json_string, restrict, upk_conf_error_handler(), upk_ctrlconf_double_handler(), upk_ctrlconf_int_handler(), upk_ctrlconf_object_handler(), upk_ctrlconf_string_handler(), and upk_json_stack_push().
Referenced by upk_ctrlconf_pack().
void upk_finalize_svc_desc (upk_svc_desc_t * dest, upk_svc_desc_t * orig)
References _upk_svc_desc::ExecReload, _upk_svc_desc::ExecStart, _upk_svc_desc::ExecStop, _upk_svc_desc::ReloadScript, _upk_controller_config::ServiceDefaults, _upk_svc_desc::StartScript, _upk_svc_desc::StopScript, upk_overlay_svcconf_values(), and upk_replace_string().
Referenced by main(), and upk_load_runtime_services().
static void* upk_json_serialize_or_null (enum json_type type, void * val) [inline, static]
Referenced by upk_svc_desc_to_json_obj().
char* upk_json_serialize_svc_config (upk_svc_desc_t * svc, upk_json_data_output_opts_t opts)
References calloc(), _upk_svc_desc::next, upk_svc_desc_meta_p::thisp, upk_json_obj_to_string(), upk_svclist_to_json_obj(), UPKLIST_APPEND, and UPKLIST_FREE.
Referenced by main(), and upk_load_runtime_services().
void upk_load_runtime_service_file (const char * filename)
void upk_load_runtime_services (void)
References calloc(), closedir(), free(), opendir(), readdir(), _upk_json_data_output_options::sep, strnlen(), _upk_controller_config::SvcConfigPath, _upk_controller_config::svclist, upk_svc_desc_meta_p::thisp, upk_config_loadfile(), upk_debug1, upk_diag_verbosity, UPK_DIAGLVL_DEBUG1, upk_finalize_svc_desc(), upk_info, upk_json_serialize_svc_config(), UPK_MAX_PATH_LEN, upk_svc_desc_clear(), upk_svcconf_pack(), UPKLIST_APPEND, UPKLIST_FOREACH, and UPKLIST_FREE.
Referenced by upk_ctrl_init().
void upk_overlay_ctrlconf_values (upk_controller_config_t * dest, upk_controller_config_t * high)
References _upk_controller_config::BuddyPollingInterval, calloc(), _upk_controller_config::controller_buddy_sock, _upk_controller_config::controller_socket, upk_svc_desc_meta_p::count, _upk_svc_desc::Name, _upk_svc_desc::next, _upk_controller_config::ServiceDefaults, _upk_controller_config::StateDir, _upk_controller_config::SvcConfigPath, _upk_controller_config::svclist, _upk_controller_config::SvcRunPath, upk_svc_desc_meta_p::thisp, upk_overlay_svcconf_values(), _upk_controller_config::UpkBuddyPath, UPKLIST_APPEND, UPKLIST_FOREACH, and UPKLIST_FREE.
Referenced by upk_ctrl_load_config().
void upk_overlay_svcconf_values (upk_svc_desc_t * dest, upk_svc_desc_t * high)
References calloc(), _upk_uuid::clk_seq_high, _upk_uuid::clk_seq_low, _upk_cust_actscr_meta_p::count, _upk_svcid_meta_p::count, _upk_svc_desc::CustomActions, _upk_svc_desc::ExecReload, _upk_svc_desc::ExecStart, _upk_svc_desc::ExecStop, free(), _upk_svc_desc::InitialState, _upk_svc_desc::KillTimeout, _upk_svc_desc::LongDescription, _upk_svc_desc::MaxConsecutiveFailures, _upk_svc_desc::Name, _upk_cust_actscr_list::next, _upk_svcid::next, _upk_uuid::node, _upk_svc_desc::Package, _upk_svc_desc::PipeStderrScript, _upk_svc_desc::PipeStdoutScript, _upk_svc_desc::PreferBuddyStateForRunning, _upk_svc_desc::PreferBuddyStateForStopped, _upk_svc_desc::Prerequisites, _upk_svc_desc::Provides, _upk_svc_desc::RandomizeRateLimit, _upk_svc_desc::ReconnectRetries, _upk_svc_desc::RedirectStderr, _upk_svc_desc::RedirectStdout, _upk_svc_desc::ReloadScript, _upk_svc_desc::RingbufferSize, _upk_cust_actscr_list::script, _upk_svc_desc::SetGID, _upk_svc_desc::SetUID, _upk_svc_desc::ShortDescription, _upk_svc_desc::StartPriority, _upk_svc_desc::StartScript, _upk_svc_desc::StopScript, _upk_cust_actscr_meta_p::thisp, _upk_svcid_meta_p::thisp, _upk_uuid::time_high_and_version, _upk_uuid::time_low, _upk_uuid::time_mid, _upk_svc_desc::UnconfigureOnFileRemoval, UPKLIST_APPEND, UPKLIST_FOREACH, UPKLIST_UNLINK, _upk_svc_desc::UserMaxRestarts, _upk_svc_desc::UserRateLimit, _upk_svc_desc::UserRestartWindow, and _upk_svc_desc::UUID.
Referenced by upk_finalize_svc_desc(), and upk_overlay_ctrlconf_values().
void upk_parse_svc_id (char * key, upk_svc_desc_t * svc)
References _upk_svc_desc::Name, and _upk_svc_desc::Package.
Referenced by upk_ctrlconf_object_handler(), and upk_svcconf_object_handler().
void upk_svc_desc_clear (upk_svc_desc_t * svc)
References _upk_svc_desc::next, and _upk_svc_desc::StartPriority.
Referenced by main(), upk_ctrl_load_config(), upk_load_runtime_services(), and upk_svcconf_object_handler().
void upk_svc_desc_free (upk_svc_desc_t * svc)
References _upk_svc_desc::CustomActions, free(), _upk_svc_desc::LongDescription, _upk_svc_desc::PipeStderrScript, _upk_svc_desc::PipeStdoutScript, _upk_svc_desc::Prerequisites, _upk_svc_desc::Provides, _upk_svc_desc::ReloadScript, _upk_cust_actscr_list::script, _upk_svc_desc::StartScript, _upk_svc_desc::StopScript, _upk_cust_actscr_meta_p::thisp, UPKLIST_FOREACH, UPKLIST_FREE, and UPKLIST_UNLINK.
Referenced by main(), upk_ctrlconf_free(), and upk_svclist_free().
struct json_object* upk_svc_desc_to_json_obj (upk_svc_desc_t * svc) [read]
References _joa, _upk_svc_desc::CustomActions, _upk_svc_desc::ExecReload, _upk_svc_desc::ExecStart, _upk_svc_desc::ExecStop, _upk_svc_desc::InitialState, jt_array, jt_boolean, jt_int, jt_string, _upk_svc_desc::KillTimeout, _upk_svc_desc::LongDescription, _upk_svc_desc::MaxConsecutiveFailures, _upk_cust_actscr_list::name, _upk_svcid::name, _upk_svc_desc::Package, _upk_svc_desc::PipeStderrScript, _upk_svc_desc::PipeStdoutScript, _upk_svcid::pkg, _upk_svc_desc::PreferBuddyStateForRunning, _upk_svc_desc::PreferBuddyStateForStopped, _upk_svc_desc::Prerequisites, _upk_svc_desc::Provides, _upk_svc_desc::RandomizeRateLimit, _upk_svc_desc::ReconnectRetries, _upk_svc_desc::RedirectStderr, _upk_svc_desc::RedirectStdout, _upk_svc_desc::ReloadScript, _upk_svc_desc::RingbufferSize, _upk_cust_actscr_list::script, _upk_svc_desc::SetGID, _upk_svc_desc::SetUID, _upk_svc_desc::ShortDescription, _upk_svc_desc::StartPriority, _upk_svc_desc::StartScript, _upk_svc_desc::StopScript, _upk_cust_actscr_meta_p::thisp, _upk_svcid_meta_p::thisp, _upk_svc_desc::UnconfigureOnFileRemoval, upk_concat_svcid(), upk_json_serialize_or_null(), UPK_MAX_STRING_LEN, UPK_STATE_RUNNING, UPK_STATE_STOPPED, upk_string_to_uuid(), UPKLIST_FOREACH, _upk_svc_desc::UserMaxRestarts, _upk_svc_desc::UserRateLimit, _upk_svc_desc::UserRestartWindow, and _upk_svc_desc::UUID.
Referenced by upk_svclist_to_json_obj().
char* upk_svc_id (char * dest, upk_svc_desc_t * svc)
References _upk_svc_desc::Name, _upk_svc_desc::Package, and upk_concat_svcid().
Referenced by upk_svclist_to_json_obj().
static void upk_svcconf_array_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References calloc(), _upk_json_stack_node::data, _upk_json_stack_node::handlers, _upk_svc_desc::Prerequisites, _upk_svc_desc::Provides, upk_json_stack_push(), and upk_svcconf_setup_array_handlers().
Referenced by upk_svcconf_setup_handlers().
static void upk_svcconf_bool_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_json_type::bl, _upk_svc_desc::PreferBuddyStateForRunning, _upk_svc_desc::PreferBuddyStateForStopped, _upk_svc_desc::RandomizeRateLimit, _upk_svc_desc::UnconfigureOnFileRemoval, upk_alert, and _upk_json_type::val.
Referenced by upk_svcconf_setup_handlers().
static void upk_svcconf_customaction_array_appender (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_json_string::c_str, calloc(), _upk_cust_actscr_list::name, _upk_cust_actscr_list::script, _upk_json_type::str, _upk_cust_actscr_meta_p::thisp, UPK_MAX_STRING_LEN, UPKLIST_APPEND, and _upk_json_type::val.
Referenced by upk_svcconf_setup_object_handlers().
static void upk_svcconf_int_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_json_type::i, _upk_svc_desc::KillTimeout, _upk_svc_desc::MaxConsecutiveFailures, _upk_svc_desc::ReconnectRetries, _upk_svc_desc::RingbufferSize, _upk_svc_desc::SetGID, _upk_svc_desc::SetUID, _upk_svc_desc::StartPriority, upk_alert, _upk_svc_desc::UserMaxRestarts, _upk_svc_desc::UserRateLimit, _upk_svc_desc::UserRestartWindow, and _upk_json_type::val.
Referenced by upk_svcconf_setup_handlers().
static void upk_svcconf_nested_object_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References calloc(), _upk_svc_desc::CustomActions, _upk_json_stack_node::data, _upk_json_stack_node::handlers, upk_json_stack_push(), and upk_svcconf_setup_object_handlers().
Referenced by upk_svcconf_setup_handlers().
static void upk_svcconf_object_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References calloc(), _upk_json_stack_node::data, _upk_json_stack_node::handlers, _upk_controller_config::svclist, upk_svc_desc_meta_p::thisp, upk_json_stack_push(), upk_parse_svc_id(), upk_svc_desc_clear(), upk_svcconf_setup_handlers(), and UPKLIST_APPEND.
Referenced by upk_svcconf_toplvl_obj().
void upk_svcconf_pack (upk_controller_config_t * cfg, const char * json_string)
References _upk_json_stack_handlers::after_json_array_pop, _upk_json_stack_handlers::after_json_obj_pop, calloc(), _upk_json_stack_node::data, _upk_json_stack_node::handlers, _upk_json_stack_handlers::json_array, _upk_json_stack_handlers::json_bool, _upk_json_stack_handlers::json_double, _upk_json_stack_handlers::json_int, _upk_json_stack_handlers::json_null, _upk_json_stack_handlers::json_object, _upk_json_stack_handlers::json_string, restrict, upk_conf_error_handler(), upk_json_parse_node(), upk_json_parse_string(), upk_json_stack_meta_t, upk_json_stack_push(), upk_svcconf_toplvl_obj(), and UPKLIST_FREE.
Referenced by upk_load_runtime_services().
static void upk_svcconf_setup_array_handlers (upk_json_handlers_t * handlers) [inline, static]
References _upk_json_stack_handlers::after_json_array_pop, _upk_json_stack_handlers::after_json_obj_pop, _upk_json_stack_handlers::json_array, _upk_json_stack_handlers::json_bool, _upk_json_stack_handlers::json_double, _upk_json_stack_handlers::json_int, _upk_json_stack_handlers::json_null, _upk_json_stack_handlers::json_object, _upk_json_stack_handlers::json_string, restrict, upk_conf_error_handler(), and upk_svcconf_svcid_array_appender().
Referenced by upk_svcconf_array_handler().
static void upk_svcconf_setup_handlers (upk_json_handlers_t * handlers) [inline, static]
References _upk_json_stack_handlers::after_json_array_pop, _upk_json_stack_handlers::after_json_obj_pop, _upk_json_stack_handlers::json_array, _upk_json_stack_handlers::json_bool, _upk_json_stack_handlers::json_double, _upk_json_stack_handlers::json_int, _upk_json_stack_handlers::json_null, _upk_json_stack_handlers::json_object, _upk_json_stack_handlers::json_string, restrict, upk_conf_error_handler(), upk_svcconf_array_handler(), upk_svcconf_bool_handler(), upk_svcconf_int_handler(), upk_svcconf_nested_object_handler(), and upk_svcconf_string_handler().
Referenced by upk_ctrlconf_object_handler(), and upk_svcconf_object_handler().
static void upk_svcconf_setup_object_handlers (upk_json_handlers_t * handlers) [inline, static]
References _upk_json_stack_handlers::after_json_array_pop, _upk_json_stack_handlers::after_json_obj_pop, _upk_json_stack_handlers::json_array, _upk_json_stack_handlers::json_bool, _upk_json_stack_handlers::json_double, _upk_json_stack_handlers::json_int, _upk_json_stack_handlers::json_null, _upk_json_stack_handlers::json_object, _upk_json_stack_handlers::json_string, restrict, upk_conf_error_handler(), and upk_svcconf_customaction_array_appender().
Referenced by upk_svcconf_nested_object_handler().
static void upk_svcconf_string_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _SC_GETPW_R_SIZE_MAX, _upk_json_string::c_str, calloc(), _upk_svc_desc::ExecReload, _upk_svc_desc::ExecStart, _upk_svc_desc::ExecStop, free(), getpwnam_r(), _upk_svc_desc::InitialState, _upk_svc_desc::LongDescription, _upk_svc_desc::Name, _upk_svc_desc::Package, _upk_svc_desc::PipeStderrScript, _upk_svc_desc::PipeStdoutScript, _upk_svc_desc::RedirectStderr, _upk_svc_desc::RedirectStdout, _upk_svc_desc::ReloadScript, _upk_svc_desc::SetGID, _upk_svc_desc::SetUID, _upk_svc_desc::ShortDescription, _upk_svc_desc::StartScript, _upk_svc_desc::StopScript, _upk_json_type::str, strnlen(), sysconf(), upk_alert, UPK_MAX_PATH_LEN, UPK_MAX_STRING_LEN, UPK_STATE_RUNNING, UPK_STATE_SHUTDOWN, upk_string_to_uuid(), _upk_svc_desc::UUID, and _upk_json_type::val.
Referenced by upk_svcconf_setup_handlers().
static void upk_svcconf_svcid_array_appender (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_json_string::c_str, _upk_svcid::name, _upk_svcid::pkg, _upk_json_type::str, _upk_svcid_meta_p::thisp, UPK_MAX_STRING_LEN, UPKLIST_APPEND, and _upk_json_type::val.
Referenced by upk_svcconf_setup_array_handlers().
static void upk_svcconf_toplvl_obj (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_json_stack_handlers::after_json_array_pop, _upk_json_stack_handlers::after_json_obj_pop, _upk_json_stack_node::data, _upk_json_stack_node::handlers, _upk_json_stack_handlers::json_array, _upk_json_stack_handlers::json_bool, _upk_json_stack_handlers::json_double, _upk_json_stack_handlers::json_int, _upk_json_stack_handlers::json_null, _upk_json_stack_handlers::json_object, _upk_json_stack_handlers::json_string, restrict, upk_conf_error_handler(), upk_json_stack_push(), and upk_svcconf_object_handler().
Referenced by upk_svcconf_pack().
void upk_svclist_free (upk_svc_desc_meta_t * svclist)
References upk_svc_desc_meta_p::thisp, upk_svc_desc_free(), UPKLIST_FOREACH, and UPKLIST_FREE.
Referenced by upk_ctrlconf_free().
struct json_object* upk_svclist_to_json_obj (upk_svc_desc_meta_t * svclist) [read]
References _joa, upk_svc_desc_meta_p::thisp, UPK_MAX_STRING_LEN, upk_svc_desc_to_json_obj(), upk_svc_id(), and UPKLIST_FOREACH.
Referenced by upk_json_serialize_svc_config().
Variable Documentation
char upk_ctrl_configuration_file[UPK_MAX_PATH_LEN] = "/upkeeper.conf"
Referenced by upk_ctrl_load_config().
upk_controller_config_t upk_default_configuration
const char upk_default_configuration_str[] = "}\n"
Referenced by main(), upk_config_loadfile(), and upk_ctrl_load_config().
upk_controller_config_t upk_file_configuration
Referenced by upk_ctrl_init().
upk_controller_config_t upk_runtime_configuration
Referenced by buddy_sock_path(), create_buddy_statedir(), ctrl_req_action_handler(), ctrl_sock_setup(), event_loop(), handle_buddies(), lookup_buddy_from_path(), main(), remove_buddy_statedir(), spawn_buddy(), upk_clnet_ctrl_connect(), upk_db_path(), and upk_state_init().