upkeeper: Controller
Controller
Config_impl
Data Structures
struct _buddy_info
information buddy returns.
struct _upk_controller_config
controller configuration.
Defines
#define UPSERT_TEXT(A)
insert or update a list option.
#define UPSERT_INT(A, NMIN)
#define LIST_UPSERT_TEXT(A, B, C)
Typedefs
typedef enum _buddy_cmnd buddy_cmnd_t
controller side of buddy protocol.
typedef struct _buddy_info buddy_info_t
information buddy returns.
typedef struct
_upk_controller_config upk_controller_config_t
controller configuration.
Enumerations
enum _buddy_cmnd {
UPK_CTRL_NONE = 0, UPK_CTRL_ACK = 1, UPK_CTRL_SHUTDOWN, UPK_CTRL_STATUS_REQ,
UPK_CTRL_ACTION_START, UPK_CTRL_ACTION_STOP, UPK_CTRL_ACTION_RELOAD, UPK_CTRL_ACTION_RUNONCE,
UPK_CTRL_CUSTOM_ACTION_00, UPK_CTRL_CUSTOM_ACTION_01, UPK_CTRL_CUSTOM_ACTION_02, UPK_CTRL_CUSTOM_ACTION_03,
UPK_CTRL_CUSTOM_ACTION_04, UPK_CTRL_CUSTOM_ACTION_05, UPK_CTRL_CUSTOM_ACTION_06, UPK_CTRL_CUSTOM_ACTION_07,
UPK_CTRL_CUSTOM_ACTION_08, UPK_CTRL_CUSTOM_ACTION_09, UPK_CTRL_CUSTOM_ACTION_10, UPK_CTRL_CUSTOM_ACTION_11,
UPK_CTRL_CUSTOM_ACTION_12, UPK_CTRL_CUSTOM_ACTION_13, UPK_CTRL_CUSTOM_ACTION_14, UPK_CTRL_CUSTOM_ACTION_15,
UPK_CTRL_CUSTOM_ACTION_16, UPK_CTRL_CUSTOM_ACTION_17, UPK_CTRL_CUSTOM_ACTION_18, UPK_CTRL_CUSTOM_ACTION_19,
UPK_CTRL_CUSTOM_ACTION_20, UPK_CTRL_CUSTOM_ACTION_21, UPK_CTRL_CUSTOM_ACTION_22, UPK_CTRL_CUSTOM_ACTION_23,
UPK_CTRL_CUSTOM_ACTION_24, UPK_CTRL_CUSTOM_ACTION_25, UPK_CTRL_CUSTOM_ACTION_26, UPK_CTRL_CUSTOM_ACTION_27,
UPK_CTRL_CUSTOM_ACTION_28, UPK_CTRL_CUSTOM_ACTION_29, UPK_CTRL_CUSTOM_ACTION_30, UPK_CTRL_CUSTOM_ACTION_31,
UPK_CTRL_SIGNAL_01, UPK_CTRL_SIGNAL_02, UPK_CTRL_SIGNAL_03, UPK_CTRL_SIGNAL_04,
UPK_CTRL_SIGNAL_05, UPK_CTRL_SIGNAL_06, UPK_CTRL_SIGNAL_07, UPK_CTRL_SIGNAL_08,
UPK_CTRL_SIGNAL_09, UPK_CTRL_SIGNAL_10, UPK_CTRL_SIGNAL_11, UPK_CTRL_SIGNAL_12,
UPK_CTRL_SIGNAL_13, UPK_CTRL_SIGNAL_14, UPK_CTRL_SIGNAL_15, UPK_CTRL_SIGNAL_16,
UPK_CTRL_SIGNAL_17, UPK_CTRL_SIGNAL_18, UPK_CTRL_SIGNAL_19, UPK_CTRL_SIGNAL_20,
UPK_CTRL_SIGNAL_21, UPK_CTRL_SIGNAL_22, UPK_CTRL_SIGNAL_23, UPK_CTRL_SIGNAL_24,
UPK_CTRL_SIGNAL_25, UPK_CTRL_SIGNAL_26, UPK_CTRL_SIGNAL_27, UPK_CTRL_SIGNAL_28,
UPK_CTRL_SIGNAL_29, UPK_CTRL_SIGNAL_30, UPK_CTRL_SIGNAL_31, UPK_CTRL_SIGNAL_32,
UPK_CTRL_NONE = 0, UPK_CTRL_ACK = 1, UPK_CTRL_SHUTDOWN, UPK_CTRL_STATUS_REQ,
UPK_CTRL_ACTION_START, UPK_CTRL_ACTION_STOP, UPK_CTRL_ACTION_RELOAD, UPK_CTRL_ACTION_RUNONCE,
UPK_CTRL_CUSTOM_ACTION_00, UPK_CTRL_CUSTOM_ACTION_01, UPK_CTRL_CUSTOM_ACTION_02, UPK_CTRL_CUSTOM_ACTION_03,
UPK_CTRL_CUSTOM_ACTION_04, UPK_CTRL_CUSTOM_ACTION_05, UPK_CTRL_CUSTOM_ACTION_06, UPK_CTRL_CUSTOM_ACTION_07,
UPK_CTRL_CUSTOM_ACTION_08, UPK_CTRL_CUSTOM_ACTION_09, UPK_CTRL_CUSTOM_ACTION_10, UPK_CTRL_CUSTOM_ACTION_11,
UPK_CTRL_CUSTOM_ACTION_12, UPK_CTRL_CUSTOM_ACTION_13, UPK_CTRL_CUSTOM_ACTION_14, UPK_CTRL_CUSTOM_ACTION_15,
UPK_CTRL_CUSTOM_ACTION_16, UPK_CTRL_CUSTOM_ACTION_17, UPK_CTRL_CUSTOM_ACTION_18, UPK_CTRL_CUSTOM_ACTION_19,
UPK_CTRL_CUSTOM_ACTION_20, UPK_CTRL_CUSTOM_ACTION_21, UPK_CTRL_CUSTOM_ACTION_22, UPK_CTRL_CUSTOM_ACTION_23,
UPK_CTRL_CUSTOM_ACTION_24, UPK_CTRL_CUSTOM_ACTION_25, UPK_CTRL_CUSTOM_ACTION_26, UPK_CTRL_CUSTOM_ACTION_27,
UPK_CTRL_CUSTOM_ACTION_28, UPK_CTRL_CUSTOM_ACTION_29, UPK_CTRL_CUSTOM_ACTION_30, UPK_CTRL_CUSTOM_ACTION_31,
UPK_CTRL_SIGNAL_01, UPK_CTRL_SIGNAL_02, UPK_CTRL_SIGNAL_03, UPK_CTRL_SIGNAL_04,
UPK_CTRL_SIGNAL_05, UPK_CTRL_SIGNAL_06, UPK_CTRL_SIGNAL_07, UPK_CTRL_SIGNAL_08,
UPK_CTRL_SIGNAL_09, UPK_CTRL_SIGNAL_10, UPK_CTRL_SIGNAL_11, UPK_CTRL_SIGNAL_12,
UPK_CTRL_SIGNAL_13, UPK_CTRL_SIGNAL_14, UPK_CTRL_SIGNAL_15, UPK_CTRL_SIGNAL_16,
UPK_CTRL_SIGNAL_17, UPK_CTRL_SIGNAL_18, UPK_CTRL_SIGNAL_19, UPK_CTRL_SIGNAL_20,
UPK_CTRL_SIGNAL_21, UPK_CTRL_SIGNAL_22, UPK_CTRL_SIGNAL_23, UPK_CTRL_SIGNAL_24,
UPK_CTRL_SIGNAL_25, UPK_CTRL_SIGNAL_26, UPK_CTRL_SIGNAL_27, UPK_CTRL_SIGNAL_28,
UPK_CTRL_SIGNAL_29, UPK_CTRL_SIGNAL_30, UPK_CTRL_SIGNAL_31, UPK_CTRL_SIGNAL_32,
UPK_CTRL_NONE = 0, UPK_CTRL_ACK = 1, UPK_CTRL_SHUTDOWN, UPK_CTRL_STATUS_REQ,
UPK_CTRL_ACTION_START, UPK_CTRL_ACTION_STOP, UPK_CTRL_ACTION_RELOAD, UPK_CTRL_ACTION_RUNONCE,
UPK_CTRL_CUSTOM_ACTION_00, UPK_CTRL_CUSTOM_ACTION_01, UPK_CTRL_CUSTOM_ACTION_02, UPK_CTRL_CUSTOM_ACTION_03,
UPK_CTRL_CUSTOM_ACTION_04, UPK_CTRL_CUSTOM_ACTION_05, UPK_CTRL_CUSTOM_ACTION_06, UPK_CTRL_CUSTOM_ACTION_07,
UPK_CTRL_CUSTOM_ACTION_08, UPK_CTRL_CUSTOM_ACTION_09, UPK_CTRL_CUSTOM_ACTION_10, UPK_CTRL_CUSTOM_ACTION_11,
UPK_CTRL_CUSTOM_ACTION_12, UPK_CTRL_CUSTOM_ACTION_13, UPK_CTRL_CUSTOM_ACTION_14, UPK_CTRL_CUSTOM_ACTION_15,
UPK_CTRL_CUSTOM_ACTION_16, UPK_CTRL_CUSTOM_ACTION_17, UPK_CTRL_CUSTOM_ACTION_18, UPK_CTRL_CUSTOM_ACTION_19,
UPK_CTRL_CUSTOM_ACTION_20, UPK_CTRL_CUSTOM_ACTION_21, UPK_CTRL_CUSTOM_ACTION_22, UPK_CTRL_CUSTOM_ACTION_23,
UPK_CTRL_CUSTOM_ACTION_24, UPK_CTRL_CUSTOM_ACTION_25, UPK_CTRL_CUSTOM_ACTION_26, UPK_CTRL_CUSTOM_ACTION_27,
UPK_CTRL_CUSTOM_ACTION_28, UPK_CTRL_CUSTOM_ACTION_29, UPK_CTRL_CUSTOM_ACTION_30, UPK_CTRL_CUSTOM_ACTION_31,
UPK_CTRL_SIGNAL_01, UPK_CTRL_SIGNAL_02, UPK_CTRL_SIGNAL_03, UPK_CTRL_SIGNAL_04,
UPK_CTRL_SIGNAL_05, UPK_CTRL_SIGNAL_06, UPK_CTRL_SIGNAL_07, UPK_CTRL_SIGNAL_08,
UPK_CTRL_SIGNAL_09, UPK_CTRL_SIGNAL_10, UPK_CTRL_SIGNAL_11, UPK_CTRL_SIGNAL_12,
UPK_CTRL_SIGNAL_13, UPK_CTRL_SIGNAL_14, UPK_CTRL_SIGNAL_15, UPK_CTRL_SIGNAL_16,
UPK_CTRL_SIGNAL_17, UPK_CTRL_SIGNAL_18, UPK_CTRL_SIGNAL_19, UPK_CTRL_SIGNAL_20,
UPK_CTRL_SIGNAL_21, UPK_CTRL_SIGNAL_22, UPK_CTRL_SIGNAL_23, UPK_CTRL_SIGNAL_24,
UPK_CTRL_SIGNAL_25, UPK_CTRL_SIGNAL_26, UPK_CTRL_SIGNAL_27, UPK_CTRL_SIGNAL_28,
UPK_CTRL_SIGNAL_29, UPK_CTRL_SIGNAL_30, UPK_CTRL_SIGNAL_31, UPK_CTRL_SIGNAL_32
}
controller side of buddy protocol.
enum buddy_runstate_t {
BUDDY_UNKNOWN = 0, BUDDY_STOPPED = 1, BUDDY_RUNNING, BUDDY_RANONCE,
BUDDY_UNKNOWN = 0, BUDDY_STOPPED = 1, BUDDY_RUNNING, BUDDY_RANONCE,
BUDDY_UNKNOWN = 0, BUDDY_STOPPED = 1, BUDDY_RUNNING, BUDDY_RANONCE
}
states for buddy
Functions
int upk_db_get_single_text (sqlite3 *dbh, char *value, const char *sql,...)
lookup a table_id from the schema table.
static int upk_db_get_table_id (sqlite3 *dbh, const char *db, const char *table_name, char *table_id)
lookup a table_id from the schema table.
int upk_db_get_audit_service_table (sqlite3 *dbh, char *table_id)
lookup the table_id for upk_audit.service from the schema table.
int upk_db_get_cfg_services_table (sqlite3 *dbh, char *table_id)
lookup the table_id for upk_cfg.services from the schema table.
int upk_db_get_cfg_svc_options_table (sqlite3 *dbh, char *table_id)
lookup the table_id for upk_cfg.svc_optionsfrom the schema table.
int upk_db_get_cfg_svc_list_options_table (sqlite3 *dbh, char *table_id)
lookup the table_id for upk_cfg.svc_list_options from the schema table.
char * upk_db_svc_uuid_lookup (sqlite3 *dbh, const char *svcid, const char *package)
lookup a service <package>-<name>
char * upk_db_gen_uuid (sqlite3 *dbh)
generate new unique service UUID.
bool upk_db_add_new_service (sqlite3 *dbh, upk_svc_desc_t *svc)
Create new service definition.
static int upk_db_try_insert (sqlite3 *dbh, char *table_id, upk_svc_desc_t *svc, int type, char *optkey, void *optval, size_t len, char *section, char *id)
try to insert an option
static int upk_db_try_update (sqlite3 *dbh, char *table_id, upk_svc_desc_t *svc, int type, char *optkey, void *optval, size_t len, char *section, char *id)
try to update an option
bool upk_db_upsert (sqlite3 *dbh, char *table_id, upk_svc_desc_t *svc, int type, char *optkey, void *optval, size_t len, char *section, char *id)
insert or update a option.
int32_t upk_db_upsert_options (sqlite3 *dbh, upk_svc_desc_t *svc)
Insert options into database;.
bool upk_db_insert_cfg (sqlite3 *dbh, upk_svc_desc_t *svc)
Insert a configuration into the database.
Define Documentation
#define LIST_UPSERT_TEXT (A, B, C)
Value:
do { \
            if(svc->A && svc->A->thisp && svc->A->thisp->B && strnlen(svc->A->thisp->B, UPK_MAX_STRING_LEN) > 0) { \
                n = strnlen(svc->A->thisp->B, UPK_MAX_STRING_LEN); \
                upk_db_upsert(dbh, table_id, svc, SQLITE_TEXT, stringify(B), svc->A->thisp->B, -1, stringify(A), C); \
                if(n > 0) { \
                    hash_buffer_len += n; \
                    hash_buffer = realloc(hash_buffer, hash_buffer_len); \
                    strncat(hash_buffer, svc->A->thisp->B, n); \
                } \
            } \
        } while(0)
Referenced by upk_db_upsert_options().
#define UPSERT_INT (A, NMIN)
Value:
do { \
            if(svc->A != NMIN) { \
                upk_db_upsert(dbh, table_id, svc, SQLITE_INTEGER, stringify(A), &svc->A, 0, NULL, NULL); \
                n = snprintf(tmp_buffer, UPK_MAX_STRING_LEN - 1, "%ld", (long int) svc->A); \
                if(n > 0) { \
                    hash_buffer_len += n;  \
                    hash_buffer = realloc(hash_buffer, hash_buffer_len); \
                    strncat(hash_buffer, tmp_buffer, n); \
                } \
            } \
        } while(0)
Referenced by upk_db_upsert_options().
#define UPSERT_TEXT (A)
Value:
do { \
            if(svc->A && strnlen(svc->A, UPK_MAX_STRING_LEN) > 0) { \
                n = strnlen(svc->A, UPK_MAX_STRING_LEN); \
                upk_db_upsert(dbh, table_id, svc, SQLITE_TEXT, stringify(A), svc->A, -1, NULL, NULL); \
                hash_buffer_len += n; \
                hash_buffer = realloc(hash_buffer, hash_buffer_len); \
                strncat(hash_buffer, svc->A, n); \
            } \
        } while(0)
insert or update a list option.
******************************************************************************************************************
Parameters:
[in] dbh The database handle.
[in] svc The service description to insert.
[in] type The type to use for bind.
[in] optkey The name of the option to insert/update.
[in] optval The value to insert/update.
Returns:
true on success, false on failure.
Referenced by upk_db_upsert_options().
Typedef Documentation
typedef enum _buddy_cmnd buddy_cmnd_t
controller side of buddy protocol.
This is what controller sends to buddy
typedef struct _buddy_info buddy_info_t
information buddy returns.
typedef struct _upk_controller_config upk_controller_config_t
controller configuration.
Enumeration Type Documentation
enum _buddy_cmnd
controller side of buddy protocol.
This is what controller sends to buddy
Enumerator:
UPK_CTRL_NONE
unset
UPK_CTRL_ACK
controller received the last msg buddy sent it
UPK_CTRL_SHUTDOWN
buddy shutdown
UPK_CTRL_STATUS_REQ
report status to controller
UPK_CTRL_ACTION_START
UPK_CTRL_ACTION_STOP
run stop script, which should kill the monitored process
UPK_CTRL_ACTION_RELOAD
run reload script, which could, for example, send SIGHUP
UPK_CTRL_ACTION_RUNONCE
run a monitored process in a restarter... only once... ???
UPK_CTRL_CUSTOM_ACTION_00
run user-defined action 00
UPK_CTRL_CUSTOM_ACTION_01
run user-defined action 01
UPK_CTRL_CUSTOM_ACTION_02
run user-defined action 02
UPK_CTRL_CUSTOM_ACTION_03
run user-defined action 03
UPK_CTRL_CUSTOM_ACTION_04
run user-defined action 04
UPK_CTRL_CUSTOM_ACTION_05
run user-defined action 05
UPK_CTRL_CUSTOM_ACTION_06
run user-defined action 06
UPK_CTRL_CUSTOM_ACTION_07
run user-defined action 07
UPK_CTRL_CUSTOM_ACTION_08
run user-defined action 08
UPK_CTRL_CUSTOM_ACTION_09
run user-defined action 09
UPK_CTRL_CUSTOM_ACTION_10
run user-defined action 10
UPK_CTRL_CUSTOM_ACTION_11
run user-defined action 11
UPK_CTRL_CUSTOM_ACTION_12
run user-defined action 12
UPK_CTRL_CUSTOM_ACTION_13
run user-defined action 13
UPK_CTRL_CUSTOM_ACTION_14
run user-defined action 14
UPK_CTRL_CUSTOM_ACTION_15
run user-defined action 15
UPK_CTRL_CUSTOM_ACTION_16
run user-defined action 16
UPK_CTRL_CUSTOM_ACTION_17
run user-defined action 17
UPK_CTRL_CUSTOM_ACTION_18
run user-defined action 18
UPK_CTRL_CUSTOM_ACTION_19
run user-defined action 19
UPK_CTRL_CUSTOM_ACTION_20
run user-defined action 20
UPK_CTRL_CUSTOM_ACTION_21
run user-defined action 21
UPK_CTRL_CUSTOM_ACTION_22
run user-defined action 22
UPK_CTRL_CUSTOM_ACTION_23
run user-defined action 23
UPK_CTRL_CUSTOM_ACTION_24
run user-defined action 24
UPK_CTRL_CUSTOM_ACTION_25
run user-defined action 25
UPK_CTRL_CUSTOM_ACTION_26
run user-defined action 26
UPK_CTRL_CUSTOM_ACTION_27
run user-defined action 27
UPK_CTRL_CUSTOM_ACTION_28
run user-defined action 28
UPK_CTRL_CUSTOM_ACTION_29
run user-defined action 29
UPK_CTRL_CUSTOM_ACTION_30
run user-defined action 30
UPK_CTRL_CUSTOM_ACTION_31
run user-defined action 31
UPK_CTRL_SIGNAL_01
send managed process signal 01
UPK_CTRL_SIGNAL_02
send managed process signal 02
UPK_CTRL_SIGNAL_03
send managed process signal 03
UPK_CTRL_SIGNAL_04
send managed process signal 04
UPK_CTRL_SIGNAL_05
send managed process signal 05
UPK_CTRL_SIGNAL_06
send managed process signal 06
UPK_CTRL_SIGNAL_07
send managed process signal 07
UPK_CTRL_SIGNAL_08
send managed process signal 08
UPK_CTRL_SIGNAL_09
send managed process signal 09
UPK_CTRL_SIGNAL_10
send managed process signal 10
UPK_CTRL_SIGNAL_11
send managed process signal 11
UPK_CTRL_SIGNAL_12
send managed process signal 12
UPK_CTRL_SIGNAL_13
send managed process signal 13
UPK_CTRL_SIGNAL_14
send managed process signal 14
UPK_CTRL_SIGNAL_15
send managed process signal 15
UPK_CTRL_SIGNAL_16
send managed process signal 16
UPK_CTRL_SIGNAL_17
send managed process signal 17
UPK_CTRL_SIGNAL_18
send managed process signal 18
UPK_CTRL_SIGNAL_19
send managed process signal 19
UPK_CTRL_SIGNAL_20
send managed process signal 20
UPK_CTRL_SIGNAL_21
send managed process signal 21
UPK_CTRL_SIGNAL_22
send managed process signal 22
UPK_CTRL_SIGNAL_23
send managed process signal 23
UPK_CTRL_SIGNAL_24
send managed process signal 24
UPK_CTRL_SIGNAL_25
send managed process signal 25
UPK_CTRL_SIGNAL_26
send managed process signal 26
UPK_CTRL_SIGNAL_27
send managed process signal 27
UPK_CTRL_SIGNAL_28
send managed process signal 28
UPK_CTRL_SIGNAL_29
send managed process signal 29
UPK_CTRL_SIGNAL_30
send managed process signal 30
UPK_CTRL_SIGNAL_31
send managed process signal 31
UPK_CTRL_SIGNAL_32
send managed process signal 32
UPK_CTRL_NONE
UPK_CTRL_ACK
UPK_CTRL_SHUTDOWN
UPK_CTRL_STATUS_REQ
UPK_CTRL_ACTION_START
UPK_CTRL_ACTION_STOP
UPK_CTRL_ACTION_RELOAD
UPK_CTRL_ACTION_RUNONCE
UPK_CTRL_CUSTOM_ACTION_00
UPK_CTRL_CUSTOM_ACTION_01
UPK_CTRL_CUSTOM_ACTION_02
UPK_CTRL_CUSTOM_ACTION_03
UPK_CTRL_CUSTOM_ACTION_04
UPK_CTRL_CUSTOM_ACTION_05
UPK_CTRL_CUSTOM_ACTION_06
UPK_CTRL_CUSTOM_ACTION_07
UPK_CTRL_CUSTOM_ACTION_08
UPK_CTRL_CUSTOM_ACTION_09
UPK_CTRL_CUSTOM_ACTION_10
UPK_CTRL_CUSTOM_ACTION_11
UPK_CTRL_CUSTOM_ACTION_12
UPK_CTRL_CUSTOM_ACTION_13
UPK_CTRL_CUSTOM_ACTION_14
UPK_CTRL_CUSTOM_ACTION_15
UPK_CTRL_CUSTOM_ACTION_16
UPK_CTRL_CUSTOM_ACTION_17
UPK_CTRL_CUSTOM_ACTION_18
UPK_CTRL_CUSTOM_ACTION_19
UPK_CTRL_CUSTOM_ACTION_20
UPK_CTRL_CUSTOM_ACTION_21
UPK_CTRL_CUSTOM_ACTION_22
UPK_CTRL_CUSTOM_ACTION_23
UPK_CTRL_CUSTOM_ACTION_24
UPK_CTRL_CUSTOM_ACTION_25
UPK_CTRL_CUSTOM_ACTION_26
UPK_CTRL_CUSTOM_ACTION_27
UPK_CTRL_CUSTOM_ACTION_28
UPK_CTRL_CUSTOM_ACTION_29
UPK_CTRL_CUSTOM_ACTION_30
UPK_CTRL_CUSTOM_ACTION_31
UPK_CTRL_SIGNAL_01
UPK_CTRL_SIGNAL_02
UPK_CTRL_SIGNAL_03
UPK_CTRL_SIGNAL_04
UPK_CTRL_SIGNAL_05
UPK_CTRL_SIGNAL_06
UPK_CTRL_SIGNAL_07
UPK_CTRL_SIGNAL_08
UPK_CTRL_SIGNAL_09
UPK_CTRL_SIGNAL_10
UPK_CTRL_SIGNAL_11
UPK_CTRL_SIGNAL_12
UPK_CTRL_SIGNAL_13
UPK_CTRL_SIGNAL_14
UPK_CTRL_SIGNAL_15
UPK_CTRL_SIGNAL_16
UPK_CTRL_SIGNAL_17
UPK_CTRL_SIGNAL_18
UPK_CTRL_SIGNAL_19
UPK_CTRL_SIGNAL_20
UPK_CTRL_SIGNAL_21
UPK_CTRL_SIGNAL_22
UPK_CTRL_SIGNAL_23
UPK_CTRL_SIGNAL_24
UPK_CTRL_SIGNAL_25
UPK_CTRL_SIGNAL_26
UPK_CTRL_SIGNAL_27
UPK_CTRL_SIGNAL_28
UPK_CTRL_SIGNAL_29
UPK_CTRL_SIGNAL_30
UPK_CTRL_SIGNAL_31
UPK_CTRL_SIGNAL_32
UPK_CTRL_NONE
UPK_CTRL_ACK
UPK_CTRL_SHUTDOWN
UPK_CTRL_STATUS_REQ
UPK_CTRL_ACTION_START
UPK_CTRL_ACTION_STOP
UPK_CTRL_ACTION_RELOAD
UPK_CTRL_ACTION_RUNONCE
UPK_CTRL_CUSTOM_ACTION_00
UPK_CTRL_CUSTOM_ACTION_01
UPK_CTRL_CUSTOM_ACTION_02
UPK_CTRL_CUSTOM_ACTION_03
UPK_CTRL_CUSTOM_ACTION_04
UPK_CTRL_CUSTOM_ACTION_05
UPK_CTRL_CUSTOM_ACTION_06
UPK_CTRL_CUSTOM_ACTION_07
UPK_CTRL_CUSTOM_ACTION_08
UPK_CTRL_CUSTOM_ACTION_09
UPK_CTRL_CUSTOM_ACTION_10
UPK_CTRL_CUSTOM_ACTION_11
UPK_CTRL_CUSTOM_ACTION_12
UPK_CTRL_CUSTOM_ACTION_13
UPK_CTRL_CUSTOM_ACTION_14
UPK_CTRL_CUSTOM_ACTION_15
UPK_CTRL_CUSTOM_ACTION_16
UPK_CTRL_CUSTOM_ACTION_17
UPK_CTRL_CUSTOM_ACTION_18
UPK_CTRL_CUSTOM_ACTION_19
UPK_CTRL_CUSTOM_ACTION_20
UPK_CTRL_CUSTOM_ACTION_21
UPK_CTRL_CUSTOM_ACTION_22
UPK_CTRL_CUSTOM_ACTION_23
UPK_CTRL_CUSTOM_ACTION_24
UPK_CTRL_CUSTOM_ACTION_25
UPK_CTRL_CUSTOM_ACTION_26
UPK_CTRL_CUSTOM_ACTION_27
UPK_CTRL_CUSTOM_ACTION_28
UPK_CTRL_CUSTOM_ACTION_29
UPK_CTRL_CUSTOM_ACTION_30
UPK_CTRL_CUSTOM_ACTION_31
UPK_CTRL_SIGNAL_01
UPK_CTRL_SIGNAL_02
UPK_CTRL_SIGNAL_03
UPK_CTRL_SIGNAL_04
UPK_CTRL_SIGNAL_05
UPK_CTRL_SIGNAL_06
UPK_CTRL_SIGNAL_07
UPK_CTRL_SIGNAL_08
UPK_CTRL_SIGNAL_09
UPK_CTRL_SIGNAL_10
UPK_CTRL_SIGNAL_11
UPK_CTRL_SIGNAL_12
UPK_CTRL_SIGNAL_13
UPK_CTRL_SIGNAL_14
UPK_CTRL_SIGNAL_15
UPK_CTRL_SIGNAL_16
UPK_CTRL_SIGNAL_17
UPK_CTRL_SIGNAL_18
UPK_CTRL_SIGNAL_19
UPK_CTRL_SIGNAL_20
UPK_CTRL_SIGNAL_21
UPK_CTRL_SIGNAL_22
UPK_CTRL_SIGNAL_23
UPK_CTRL_SIGNAL_24
UPK_CTRL_SIGNAL_25
UPK_CTRL_SIGNAL_26
UPK_CTRL_SIGNAL_27
UPK_CTRL_SIGNAL_28
UPK_CTRL_SIGNAL_29
UPK_CTRL_SIGNAL_30
UPK_CTRL_SIGNAL_31
UPK_CTRL_SIGNAL_32
enum buddy_runstate_t
states for buddy
Enumerator:
BUDDY_UNKNOWN
BUDDY_STOPPED
the current state of the managed process is stopped
BUDDY_RUNNING
the current state of the managed process is running
BUDDY_RANONCE
the current state of the managed process was that it ran once
BUDDY_UNKNOWN
BUDDY_STOPPED
BUDDY_RUNNING
BUDDY_RANONCE
BUDDY_UNKNOWN
BUDDY_STOPPED
BUDDY_RUNNING
BUDDY_RANONCE
Function Documentation
bool upk_db_add_new_service (sqlite3 * dbh, upk_svc_desc_t * svc)
Create new service definition.
******************************************************************************************************************
Parameters:
[in] dbh The database handle.
[in] svc The service description to insert.
Returns:
true on success, false on failure.
References IF_UPK_ERROR, _upk_svc_desc::Name, _upk_svc_desc::Package, sqlite3_exec(), sqlite3_free(), upk_concat_svcid(), UPK_CONF_ERROR, upk_db_gen_uuid(), upk_db_get_cfg_services_table(), upk_db_get_single_text(), UPK_FUNC_ASSERT_MSG, UPK_MAX_STRING_LEN, UPK_SQL_ERROR, upk_string_to_uuid(), UPK_UUID_STRING_LEN, upk_uuid_to_string(), and _upk_svc_desc::UUID.
Referenced by upk_db_insert_cfg().
char* upk_db_gen_uuid (sqlite3 * dbh)
generate new unique service UUID.
******************************************************************************************************************
Parameters:
[in] dbh The database handle.
Returns:
uuid
References strnlen(), upk_db_get_cfg_services_table(), upk_db_get_single_text(), upk_gen_uuid_bytes(), UPK_MAX_STRING_LEN, upk_uuid_open_random(), upk_uuid_seed_random(), UPK_UUID_STRING_LEN, and upk_uuid_to_string().
Referenced by upk_db_add_new_service().
int upk_db_get_audit_service_table (sqlite3 * dbh, char * table_id)
lookup the table_id for upk_audit.service from the schema table.
******************************************************************************************************************
Parameters:
[in] dbh The database handle.
[out] table_id The result of looking up the table id.
Returns:
0 on success, -1 if table-name not found, and the result code if there was a sql error
int upk_db_get_cfg_services_table (sqlite3 * dbh, char * table_id)
lookup the table_id for upk_cfg.services from the schema table.
******************************************************************************************************************
Parameters:
[in] dbh The database handle.
[out] table_id The result of looking up the table id.
Returns:
0 on success, -1 if table-name not found, and the result code if there was a sql error
Referenced by upk_db_add_new_service(), upk_db_gen_uuid(), and upk_db_svc_uuid_lookup().
int upk_db_get_cfg_svc_list_options_table (sqlite3 * dbh, char * table_id)
lookup the table_id for upk_cfg.svc_list_options from the schema table.
******************************************************************************************************************
Parameters:
[in] dbh The database handle.
[out] table_id The result of looking up the table id.
Returns:
0 on success, -1 if table-name not found, and the result code if there was a sql error
References upk_db_get_table_id().
Referenced by upk_db_upsert_options().
int upk_db_get_cfg_svc_options_table (sqlite3 * dbh, char * table_id)
lookup the table_id for upk_cfg.svc_optionsfrom the schema table.
******************************************************************************************************************
Parameters:
[in] dbh The database handle.
[out] table_id The result of looking up the table id.
Returns:
0 on success, -1 if table-name not found, and the result code if there was a sql error
Referenced by upk_db_try_insert(), upk_db_try_update(), and upk_db_upsert_options().
int upk_db_get_single_text (sqlite3 * dbh, char * value, const char * sql, ...)
lookup a table_id from the schema table.
******************************************************************************************************************
Parameters:
[in] dbh The database handle.
[out] value The place to store the single value.
[in] sql The table to query.
[in] ... Values to substitute via bind (terminate with (char *) NULL) - If there are 0 arguments, you must still include a (char *) NULL).
Returns:
0 on success, -1 if table-name not found, and the result code if there was a sql error
Referenced by upk_db_add_new_service(), upk_db_gen_uuid(), upk_db_get_table_id(), and upk_db_svc_uuid_lookup().
static int upk_db_get_table_id (sqlite3 * dbh, const char * db, const char * table_name, char * table_id) [static]
lookup a table_id from the schema table.
******************************************************************************************************************
Parameters:
[in] dbh The database handle.
[in] db The name of the database to search in.
[in] table_name The name of the table you are lookin for.
[out] table_id The result of looking up the table id.
Returns:
0 on success, -1 if table-name not found, and the result code if there was a sql error
References upk_db_get_single_text(), and UPK_MAX_STRING_LEN.
Referenced by upk_db_get_audit_service_table(), upk_db_get_cfg_services_table(), upk_db_get_cfg_svc_list_options_table(), and upk_db_get_cfg_svc_options_table().
bool upk_db_insert_cfg (sqlite3 * dbh, upk_svc_desc_t * svc)
Insert a configuration into the database.
******************************************************************************************************************
Parameters:
[in] dbh The database handle.
[in] svc The service description to insert.
Returns:
true on success, false on failure.
Referenced by upk_ctrl_init().
char* upk_db_svc_uuid_lookup (sqlite3 * dbh, const char * svcid, const char * package)
lookup a service <package>-<name>
******************************************************************************************************************
Parameters:
[in] dbh The database handle.
[in] svc_id The service description to lookup.
[in] package The package to lookup.
Returns:
the UUID of the service if found, NULL if not found.
Referenced by upk_db_insert_cfg().
static int upk_db_try_insert (sqlite3 * dbh, char * table_id, upk_svc_desc_t * svc, int type, char * optkey, void * optval, size_t len, char * section, char * id) [inline, static]
try to insert an option
******************************************************************************************************************
Parameters:
[in] dbh The database handle.
[in] svc The service description to insert.
[in] type The type to use for bind.
[in] optkey The name of the option to insert/update.
[in] optval The value to insert/update.
Returns:
0 on success, ! 0 on error.
References IF_UPK_ERROR, sqlite3_bind_blob(), sqlite3_bind_double(), sqlite3_bind_int(), sqlite3_bind_null(), sqlite3_bind_text(), sqlite3_errmsg(), sqlite3_finalize(), sqlite3_prepare(), sqlite3_reset(), sqlite3_step(), upk_debug1, upk_error, UPK_FUNC_ASSERT_MSG, UPK_MAX_STRING_LEN, UPK_SQL_ERROR, UPK_UUID_STRING_LEN, upk_uuid_to_string(), and _upk_svc_desc::UUID.
Referenced by upk_db_upsert().
static int upk_db_try_update (sqlite3 * dbh, char * table_id, upk_svc_desc_t * svc, int type, char * optkey, void * optval, size_t len, char * section, char * id) [inline, static]
try to update an option
******************************************************************************************************************
Parameters:
[in] dbh The database handle.
[in] svc The service description to insert.
[in] type The type to use for bind.
[in] optkey The name of the option to insert/update.
[in] optval The value to insert/update.
Returns:
0 on success, ! 0 on error.
References IF_UPK_ERROR, sqlite3_bind_blob(), sqlite3_bind_double(), sqlite3_bind_int(), sqlite3_bind_null(), sqlite3_bind_text(), sqlite3_errmsg(), sqlite3_finalize(), sqlite3_prepare(), sqlite3_reset(), sqlite3_step(), upk_error, UPK_FUNC_ASSERT_MSG, UPK_MAX_STRING_LEN, UPK_SQL_ERROR, UPK_UUID_STRING_LEN, upk_uuid_to_string(), and _upk_svc_desc::UUID.
Referenced by upk_db_upsert().
bool upk_db_upsert (sqlite3 * dbh, char * table_id, upk_svc_desc_t * svc, int type, char * optkey, void * optval, size_t len, char * section, char * id)
insert or update a option.
******************************************************************************************************************
Parameters:
[in] dbh The database handle.
[in] svc The service description to insert.
[in] type The type to use for bind.
[in] optkey The name of the option to insert/update.
[in] optval The value to insert/update.
Returns:
true on success, false on failure.
References _upk_svc_desc::Name, _upk_svc_desc::Package, upk_concat_svcid(), upk_db_try_insert(), upk_db_try_update(), UPK_MAX_STRING_LEN, UPK_UUID_STRING_LEN, upk_uuid_to_string(), upk_verbose, and _upk_svc_desc::UUID.
Referenced by upk_db_upsert_options().
int32_t upk_db_upsert_options (sqlite3 * dbh, upk_svc_desc_t * svc)
Insert options into database;.
******************************************************************************************************************
Parameters:
[in] dbh The database handle.
[in] svc The service description to insert.
Returns:
the hash of the added options on success, 0 on failure.
References calloc(), _upk_cust_actscr_meta_p::count, _upk_svcid_meta_p::count, _upk_svc_desc::CustomActions, free(), LIST_UPSERT_TEXT, _upk_svc_desc::Provides, _upk_svc_desc::RestartOnNamedPrereqRestart, sqlite3_exec(), sqlite3_free(), _upk_svc_desc::StartAfter, upk_crc32(), upk_db_get_cfg_svc_list_options_table(), upk_db_get_cfg_svc_options_table(), upk_debug1, UPK_MAX_STRING_LEN, upk_uuid_to_string(), UPKLIST_FOREACH, UPSERT_INT, UPSERT_TEXT, and _upk_svc_desc::UUID.
Referenced by upk_db_insert_cfg().