upkeeper: Upk_network
Upk_network
Data Structures
struct _upk_netmsg_queue
this is a tailq for network message queuing
struct _upk_net_cb_stk
a callback-stack for use in nesting/branching expectations in a conversation
struct _upk_net_state
struct _upklist_userdata_state_partition
a struct to use as 'userdata' to be passed around, which partitions the 'userdata' segment into global state and then any other userdata you might care about.
struct _upk_conn_handle
Defines
#define TOTAL_N_MSG_TYPES (UPK_N_REQ_TYPES + UPK_N_REPL_TYPES + UPK_N_PUB_TYPES)
Typedefs
typedef struct _upk_conn_handle upk_conn_handle_t
typedef void(* upk_net_callback_t)(upk_conn_handle_meta_t *handles, upk_payload_t *msg)
typedef for callback functions.
typedef struct _upk_netmsg_queue upk_netmsg_queue_t
this is a tailq for network message queuing
typedef struct _upk_net_cb_stk upk_net_cb_stk_t
a callback-stack for use in nesting/branching expectations in a conversation
typedef struct _upk_net_state upk_net_state_t
global state data for this client/connection
typedef struct
_upklist_userdata_state_partition upklist_userdata_state_partition_t
a struct to use as 'userdata' to be passed around, which partitions the 'userdata' segment into global state and then any other userdata you might care about.
Functions
static void upk_call_received_packet_callbacks (upk_conn_handle_meta_t *handles, upk_packet_t *pkt)
call callback for received packet based on type.
static int upk_build_fd_sets (upk_conn_handle_meta_t *handles, fd_set *readfds, fd_set *writefds, fd_set *exceptfds)
initialize file-descriptor sets
static void upk_partitioned_userdata_free (void *ptr)
userdata cleanup callback
upk_conn_handle_meta_t * upk_net_conn_handles_init (void *userdata, void(*userdata_free_func)(void *ptr))
initialize connection handles
upk_net_state_t * upk_net_get_global_state (upk_conn_handle_meta_t *handles)
extract the nested global_state component from the generic (void *) userdata element
void * upk_net_get_global_userdata (upk_conn_handle_meta_t *handles)
extract nested the global_userdata component from the generic (void *) userdata element
bool upk_net_add_socket_handle (upk_conn_handle_meta_t *handles, int fd)
add a new socket handle to the handles list
void upk_net_flush_closed_sockets (upk_conn_handle_meta_t *handles)
iterate through the list of handles, and prune any that are no longer valid.
void upk_net_event_dispatcher (upk_conn_handle_meta_t *handles, double sel_ival)
The event dispatcher, called via an event-loop.
int upk_net_block_until_msg (upk_conn_handle_meta_t *handles, double sel_ival, struct timeval *timeout)
block until a complete message is received, up to timeout.
void upk_disconnect_handle (upk_conn_handle_meta_t *handles)
disconnect the ->thisp handle in handles.
void upk_net_shutdown_callback (upk_conn_handle_meta_t *handles, upk_payload_t *msg)
wrapper around upk-disconnect_handle for use as a callback.
void upk_queue_packet (upk_conn_handle_meta_t *handles, upk_conn_handle_t *handle, upk_packet_t *pkt, upk_net_callback_t after_write_callback)
enqueue a packet for sending
void upk_write_packets (upk_conn_handle_meta_t *handles)
write the packets in the writeq for handles->thisp, and call any write callbacks
void upk_read_packets (upk_conn_handle_meta_t *handles)
read any packets from the handle handles->thisp, and call read-callbacks.
int upk_domain_socket_connect (const char *sockpath)
connect to a domain socket.
void upk_callback_stack_push (upk_conn_handle_t *handle, upk_net_cb_stk_t *state)
push a callback-stack state element onto the callback stack for a handle.
void upk_callback_stack_pop (upk_conn_handle_t *handle)
pop the top element off the callback-stack for a handle.
typedef UPKLIST_METANODE (upk_conn_handle_t, upk_conn_handle_meta_p)
typedef UPKLIST_METANODE (upk_netmsg_queue_t, upk_netmsg_queue_meta_p)
typedef UPKLIST_METANODE (upk_net_cb_stk_t, upk_net_cb_stk_meta_p)
metanode for the callback stack
upk_packet_t * upk_create_pkt (void *payload, uint32_t payload_len, upk_pkttype_t pkttype, uint32_t proto_ver)
static uint32_t req_preamble_len (upk_req_preamble_t *preamble)
upk_packet_t * upk_create_req_preamble (upk_protocol_handle_t *handle, char *client_name)
upk_packet_t * upk_create_repl_preamble (upk_protocol_handle_t *handle, uint32_t best_version)
static void upk_free_payload (upk_packet_t *pkt)
void upk_pkt_free (upk_packet_t *pkt)
upk_packet_t * upk_create_req_seq_start (upk_protocol_handle_t *handle, upk_msgtype_t seq_type, uint32_t count)
upk_packet_t * upk_create_req_seq_end (upk_protocol_handle_t *handle, bool commit)
upk_packet_t * upk_create_req_action (upk_protocol_handle_t *handle, char *svc_id, char *action)
upk_packet_t * upk_create_req_signal (upk_protocol_handle_t *handle, char *svc_id, upk_signal_t signal, bool signal_sid, bool signal_pgrp)
upk_packet_t * upk_create_req_list (upk_protocol_handle_t *handle)
upk_packet_t * upk_create_req_status (upk_protocol_handle_t *handle, char *svc_id, uint32_t restart_window_seconds)
upk_packet_t * upk_create_req_subscribe (upk_protocol_handle_t *handle, char *svc_id, bool all_svcs)
upk_packet_t * upk_create_req_unsubscribe (upk_protocol_handle_t *handle, char *svc_id, bool all_svcs)
upk_packet_t * upk_create_req_disconnect (upk_protocol_handle_t *handle)
upk_packet_t * upk_create_repl_seq_start (upk_protocol_handle_t *handle, upk_msgtype_t seq_type, uint32_t count)
upk_packet_t * upk_create_repl_seq_end (upk_protocol_handle_t *handle, bool commit)
upk_packet_t * upk_create_repl_result (upk_protocol_handle_t *handle, char *msg, bool successful)
upk_packet_t * upk_create_repl_listing (upk_protocol_handle_t *handle, char *svc_id)
upk_packet_t * upk_create_repl_svcinfo (upk_protocol_handle_t *handle, char *svc_id, upk_svcinfo_t *svcinfo)
upk_packet_t * upk_create_repl_ack (upk_protocol_handle_t *handle)
upk_packet_t * upk_create_repl_error (upk_protocol_handle_t *handle, char *svc_id, upk_errno_t uerrno, char *errmsg, upk_errlevel_t errlvl)
upk_packet_t * upk_create_pub_publication (upk_protocol_handle_t *handle)
upk_packet_t * upk_create_pub_cancelation (upk_protocol_handle_t *handle)
upk_msgtype_t upk_get_msgtype (upk_packet_t *pkt)
size_t upk_get_msgsize (upk_msgtype_t type)
Variables
typedef upk_conn_handle_meta_t
typedef upk_netmsg_queue_meta_t
typedef upk_net_cb_stk_meta_t
Define Documentation
#define TOTAL_N_MSG_TYPES (UPK_N_REQ_TYPES + UPK_N_REPL_TYPES + UPK_N_PUB_TYPES)
Typedef Documentation
typedef struct _upk_conn_handle upk_conn_handle_t
typedef void(* upk_net_callback_t)(upk_conn_handle_meta_t *handles, upk_payload_t *msg)
typedef for callback functions.
Parameters:
[in] handles - the handle list, where thisp is the handle that generated the event for the callback.
[in,out] data - used to pass data you specify to the callbacks.
[in] msg - the deserialized message.
typedef struct _upk_net_cb_stk upk_net_cb_stk_t
a callback-stack for use in nesting/branching expectations in a conversation
typedef struct _upk_net_state upk_net_state_t
global state data for this client/connection
typedef struct _upk_netmsg_queue upk_netmsg_queue_t
this is a tailq for network message queuing
typedef struct _upklist_userdata_state_partition upklist_userdata_state_partition_t
a struct to use as 'userdata' to be passed around, which partitions the 'userdata' segment into global state and then any other userdata you might care about.
Function Documentation
static uint32_t req_preamble_len (upk_req_preamble_t * preamble) [inline, static]
References upk_req_preamble_t::client_name, and upk_req_preamble_t::client_name_len.
Referenced by upk_create_req_preamble().
static int upk_build_fd_sets (upk_conn_handle_meta_t * handles, fd_set * readfds, fd_set * writefds, fd_set * exceptfds) [inline, static]
initialize file-descriptor sets
*****************************************************************************************************************
Parameters:
[in] handles the list of client handles
[out] readfds the read fdset
[out] writefds the write fdset
[out] exceptfds the exception fdset
Returns:
highest fd in any set. (for select)
FIXME: this does not presently handle fdset partitioning, which is necessary for poll-like behavior; this should be fixed if we want to support more than a small number of concurent clients (<= 1024 on many platforms; limited to FD_SETSIZE)
References fcntl(), _upk_conn_handle::fd, upk_conn_handle_meta_p::thisp, and UPKLIST_FOREACH.
Referenced by upk_net_event_dispatcher().
static void upk_call_received_packet_callbacks (upk_conn_handle_meta_t * handles, upk_packet_t * pkt) [static]
call callback for received packet based on type.
***************************************************************************************************************** Will call the appropriate msg_handler for the packet type if availble.
Parameters:
[in] handles connection handle llist
[in] pkt the packet itself
References _upk_net_state::callback_stack, upk_net_cb_stk_meta_p::head, _upk_conn_handle::last_pkt_data, _upk_net_cb_stk::msg_handlers, upk_packet_t::payload, _upk_payload::payload, _upk_conn_handle::state, upk_conn_handle_meta_p::thisp, _upk_payload::type, upk_get_msgsize(), upk_get_msgtype(), and UPK_MSGTYPE_IDX.
Referenced by upk_read_packets().
void upk_callback_stack_pop (upk_conn_handle_t * handle)
pop the top element off the callback-stack for a handle.
*****************************************************************************************************************
Parameters:
[in] handle The handle to pop the state from.
Note that the element popped will be freed, and should not be referenced after popping. This does not return the popped element; it just discards it.
References _upk_net_state::callback_stack, _upk_conn_handle::state, UPKLIST_HEAD, and UPKLIST_UNLINK.
void upk_callback_stack_push (upk_conn_handle_t * handle, upk_net_cb_stk_t * state)
push a callback-stack state element onto the callback stack for a handle.
*****************************************************************************************************************
Parameters:
[in] handle the handle to push the state onto.
[in] state The state element to push.
References _upk_net_state::callback_stack, _upk_conn_handle::state, upk_net_cb_stk_meta_p::thisp, and UPKLIST_PREPEND.
Referenced by upk_net_add_socket_handle().
upk_packet_t* upk_create_pkt (void * payload, uint32_t payload_len, upk_pkttype_t pkttype, uint32_t proto_ver)
References calloc(), upk_packet_t::crc32, upk_packet_t::payload, upk_packet_t::payload_len, upk_packet_t::pkttype, upk_packet_t::seq_num, and upk_packet_t::version_id.
Referenced by upk_create_repl_preamble(), and upk_create_req_preamble().
upk_packet_t* upk_create_pub_cancelation (upk_protocol_handle_t * handle)
References v0_create_pub_cancelation(), and _upk_conn_handle::version_id.
upk_packet_t* upk_create_pub_publication (upk_protocol_handle_t * handle)
References v0_create_pub_publication(), and _upk_conn_handle::version_id.
upk_packet_t* upk_create_repl_ack (upk_protocol_handle_t * handle)
References v0_create_repl_ack(), and _upk_conn_handle::version_id.
upk_packet_t* upk_create_repl_error (upk_protocol_handle_t * handle, char * svc_id, upk_errno_t uerrno, char * errmsg, upk_errlevel_t errlvl)
References v0_create_repl_error(), and _upk_conn_handle::version_id.
upk_packet_t* upk_create_repl_listing (upk_protocol_handle_t * handle, char * svc_id)
References v0_create_repl_listing(), and _upk_conn_handle::version_id.
upk_packet_t* upk_create_repl_preamble (upk_protocol_handle_t * handle, uint32_t best_version)
References upk_repl_preamble_t::best_version, calloc(), upk_repl_preamble_t::msgtype, PKT_REPLY, upk_create_pkt(), and UPK_REPL_PREAMBLE.
Referenced by ctrl_req_preamble_handler().
upk_packet_t* upk_create_repl_result (upk_protocol_handle_t * handle, char * msg, bool successful)
References v0_create_repl_result(), and _upk_conn_handle::version_id.
upk_packet_t* upk_create_repl_seq_end (upk_protocol_handle_t * handle, bool commit)
References v0_create_repl_seq_end(), and _upk_conn_handle::version_id.
upk_packet_t* upk_create_repl_seq_start (upk_protocol_handle_t * handle, upk_msgtype_t seq_type, uint32_t count)
References v0_create_repl_seq_start(), and _upk_conn_handle::version_id.
upk_packet_t* upk_create_repl_svcinfo (upk_protocol_handle_t * handle, char * svc_id, upk_svcinfo_t * svcinfo)
References v0_create_repl_svcinfo(), and _upk_conn_handle::version_id.
upk_packet_t* upk_create_req_action (upk_protocol_handle_t * handle, char * svc_id, char * action)
References v0_create_req_action(), and _upk_conn_handle::version_id.
Referenced by main(), and upk_clnet_req_action().
upk_packet_t* upk_create_req_disconnect (upk_protocol_handle_t * handle)
References v0_create_req_disconnect(), and _upk_conn_handle::version_id.
Referenced by ctrl_req_disconnect_handler(), and upk_clnet_req_disconnect().
upk_packet_t* upk_create_req_list (upk_protocol_handle_t * handle)
References v0_create_req_list(), and _upk_conn_handle::version_id.
upk_packet_t* upk_create_req_preamble (upk_protocol_handle_t * handle, char * client_name)
References calloc(), upk_req_preamble_t::client_name, upk_req_preamble_t::client_name_len, upk_req_preamble_t::max_supported_ver, upk_req_preamble_t::min_supported_ver, upk_req_preamble_t::msgtype, PKT_REQUEST, req_preamble_len(), strnlen(), upk_create_pkt(), UPK_MAX_STRING_LEN, UPK_MAX_SUPPORTED_PROTO, UPK_MIN_SUPPORTED_PROTO, and UPK_REQ_PREAMBLE.
Referenced by main(), and upk_clnet_req_preamble().
upk_packet_t* upk_create_req_seq_end (upk_protocol_handle_t * handle, bool commit)
References v0_create_req_seq_end(), and _upk_conn_handle::version_id.
upk_packet_t* upk_create_req_seq_start (upk_protocol_handle_t * handle, upk_msgtype_t seq_type, uint32_t count)
References v0_create_req_seq_start(), and _upk_conn_handle::version_id.
upk_packet_t* upk_create_req_signal (upk_protocol_handle_t * handle, char * svc_id, upk_signal_t signal, bool signal_sid, bool signal_pgrp)
References v0_create_req_signal(), and _upk_conn_handle::version_id.
upk_packet_t* upk_create_req_status (upk_protocol_handle_t * handle, char * svc_id, uint32_t restart_window_seconds)
References v0_create_req_status(), and _upk_conn_handle::version_id.
Referenced by upk_clnet_req_status().
upk_packet_t* upk_create_req_subscribe (upk_protocol_handle_t * handle, char * svc_id, bool all_svcs)
References v0_create_req_subscribe(), and _upk_conn_handle::version_id.
upk_packet_t* upk_create_req_unsubscribe (upk_protocol_handle_t * handle, char * svc_id, bool all_svcs)
References v0_create_req_unsubscribe(), and _upk_conn_handle::version_id.
void upk_disconnect_handle (upk_conn_handle_meta_t * handles)
disconnect the ->thisp handle in handles.
*****************************************************************************************************************
Parameters:
[in] handles connection handles llist.
References _upk_conn_handle::fd, SHUT_RDWR, shutdown(), and upk_conn_handle_meta_p::thisp.
Referenced by upk_clnet_req_disconnect(), upk_net_event_dispatcher(), upk_net_shutdown_callback(), upk_read_packets(), and upk_write_packets().
int upk_domain_socket_connect (const char * sockpath)
connect to a domain socket.
*****************************************************************************************************************
Parameters:
[in] sockpath Path to the socket in question.
Returns:
the fd of the socket, or -2 on connect error (-1 if socket() error, errno may be checked)
References connect(), SOCK_STREAM, socket(), sockaddr_un::sun_family, and sockaddr_un::sun_path.
Referenced by upk_clnet_ctrl_connect().
static void upk_free_payload (upk_packet_t * pkt) [inline, static]
References free(), upk_packet_t::payload, and v0_free_payload().
Referenced by upk_pkt_free().
size_t upk_get_msgsize (upk_msgtype_t type)
References UPK_MSGTYPE_IDX.
Referenced by upk_call_received_packet_callbacks().
upk_msgtype_t upk_get_msgtype (upk_packet_t * pkt)
References upk_generic_msg_t::msgtype, and upk_packet_t::payload.
Referenced by upk_call_received_packet_callbacks().
bool upk_net_add_socket_handle (upk_conn_handle_meta_t * handles, int fd)
add a new socket handle to the handles list
*****************************************************************************************************************
Parameters:
[in,out] handles connection handles llist, will be modified by appending a connection handle.
[in] fd fd number of socket for new connection.
Returns:
true if socket is valid and connection handle appended, false otherwise
References _upk_net_state::callback_stack, calloc(), fcntl(), _upk_conn_handle::fd, upk_net_cb_stk_meta_p::head, sockopts, _upk_conn_handle::state, upk_conn_handle_meta_p::thisp, upk_callback_stack_push(), upk_net_get_global_state(), upk_net_get_global_userdata(), UPKLIST_APPEND, and _upk_conn_handle::userdata.
Referenced by ctrl_accept_conn(), main(), and upk_clnet_ctrl_connect().
int upk_net_block_until_msg (upk_conn_handle_meta_t * handles, double sel_ival, struct timeval * timeout)
block until a complete message is received, up to timeout.
***************************************************************************************************************** Make the underlying asynchronous network communication model behave like a synchronous one by blocking.
Parameters:
[in] handles The llist of connection handles.
[in] sel_ival The select timeout value.
[in] timeout Global timeout to block for; distinct from the sel_ival in that if a partial packet is received, select would trigger, but the global timeout would still play.
Returns:
message type or error. (msgtype >= 0 if valid, < 0 if invalid; if < -1, then it represents the fd value, which may be useful in debugging)
References _upk_conn_handle::fd, gettimeofday(), _upk_conn_handle::last_pkt_data, upk_conn_handle_meta_p::thisp, timeval::tv_sec, timeval::tv_usec, _upk_payload::type, and upk_net_event_dispatcher().
Referenced by upk_clnet_serial_request().
upk_conn_handle_meta_t* upk_net_conn_handles_init (void * userdata, void(*)(void *ptr) userdata_free_func)
initialize connection handles
*****************************************************************************************************************
Parameters:
[in] userdata pointer to any data you want to have available to connection handles
[in] userdata_free_func the function to free userdata
Returns:
an initialized connection handles llist metanode
References _upk_net_state::callback_stack, calloc(), _upklist_userdata_state_partition::global_state, _upklist_userdata_state_partition::global_userdata, upk_partitioned_userdata_free(), upk_conn_handle_meta_p::userdata, upk_conn_handle_meta_p::userdata_free_func, and _upklist_userdata_state_partition::userdata_free_func.
Referenced by ctrl_init(), main(), and upk_clnet_ctrl_connect().
void upk_net_event_dispatcher (upk_conn_handle_meta_t * handles, double sel_ival)
The event dispatcher, called via an event-loop.
***************************************************************************************************************** This is where events in either the state-stack are calledis invoked
Parameters:
[in] handles the list of handles
[in] sel_ival the wait time for select to wait
References _upk_net_state::callback_stack, fcntl(), _upk_conn_handle::fd, upk_net_cb_stk_meta_p::head, _upk_net_cb_stk::net_dispatch_foreach, _upk_net_cb_stk::net_dispatch_post, _upk_net_cb_stk::net_dispatch_pre, _upk_net_state::pending_writeq, select(), sigfillset(), sigprocmask(), _upk_conn_handle::state, upk_conn_handle_meta_p::thisp, upk_build_fd_sets(), upk_disconnect_handle(), upk_double_to_timeval(), upk_net_get_global_state(), upk_read_packets(), upk_write_packets(), and UPKLIST_FOREACH.
Referenced by event_loop(), main(), and upk_net_block_until_msg().
void upk_net_flush_closed_sockets (upk_conn_handle_meta_t * handles)
iterate through the list of handles, and prune any that are no longer valid.
***************************************************************************************************************** free callback stacks, userdata, and state. Unlink node from list.
Parameters:
[in,out] handles connection handles llist, will be modified by removing closed connection handles.
References _upk_net_state::callback_stack, _upk_conn_handle::fd, free(), _upk_conn_handle::state, upk_conn_handle_meta_p::thisp, UPKLIST_FOREACH, UPKLIST_FREE, UPKLIST_UNLINK, _upk_conn_handle::userdata, and _upk_conn_handle::userdata_free_func.
Referenced by event_loop(), upk_clnet_req_disconnect(), and upk_clnet_serial_request().
upk_net_state_t* upk_net_get_global_state (upk_conn_handle_meta_t * handles)
extract the nested global_state component from the generic (void *) userdata element
*****************************************************************************************************************
Parameters:
handles connection handle llist
Returns:
global state.
References _upklist_userdata_state_partition::global_state, and upk_conn_handle_meta_p::userdata.
Referenced by init_callback_handlers(), upk_net_add_socket_handle(), upk_net_event_dispatcher(), upk_queue_packet(), and upk_write_packets().
void* upk_net_get_global_userdata (upk_conn_handle_meta_t * handles) [inline]
extract nested the global_userdata component from the generic (void *) userdata element
*****************************************************************************************************************
Parameters:
[in] handles connection handles llist.
Returns:
the global_userdata element from handles->userdata (handles->userdata is split into two pieces)
References _upklist_userdata_state_partition::global_userdata, and upk_conn_handle_meta_p::userdata.
Referenced by upk_net_add_socket_handle().
void upk_net_shutdown_callback (upk_conn_handle_meta_t * handles, upk_payload_t * msg)
wrapper around upk-disconnect_handle for use as a callback.
*****************************************************************************************************************
References upk_disconnect_handle().
Referenced by ctrl_req_disconnect_handler().
static void upk_partitioned_userdata_free (void * ptr) [static]
userdata cleanup callback
*****************************************************************************************************************
Parameters:
ptr the userdata object to free
References _upk_net_state::callback_stack, free(), _upklist_userdata_state_partition::global_state, _upklist_userdata_state_partition::global_userdata, UPKLIST_FREE, and _upklist_userdata_state_partition::userdata_free_func.
Referenced by upk_net_conn_handles_init().
void upk_pkt_free (upk_packet_t * pkt)
References free(), and upk_free_payload().
Referenced by ctrl_req_action_handler(), ctrl_req_disconnect_handler(), ctrl_req_preamble_handler(), upk_clnet_req_action(), upk_clnet_req_disconnect(), upk_clnet_req_preamble(), upk_clnet_req_signal(), upk_clnet_req_status(), and upk_read_packets().
void upk_queue_packet (upk_conn_handle_meta_t * handles, upk_conn_handle_t * handle, upk_packet_t * pkt, upk_net_callback_t after_write_callback)
enqueue a packet for sending
***************************************************************************************************************** This takes a packet and places it on the writeq for handle.
Parameters:
[in] handles connection handles llist
[in] handle the handle to update the writeq for.
[in] pkt the packet to enqueue
[in] after_write_callback a callback to call after successfully writing the packet, usually to setup the receive callback stack.
pkt will be copied, so that the copy may be freed after it's been sent. You must free the pkt you pass yourself.
References _upk_netmsg_queue::after_write_callback, free(), _upk_netmsg_queue::msg, _upk_netmsg_queue::msg_len, upk_packet_t::payload_len, _upk_net_state::pending_writeq, upk_netmsg_queue_meta_p::thisp, upk_net_get_global_state(), UPK_PACKET_FOOTER_LEN, UPK_PACKET_HEADER_LEN, upk_serialize_packet(), UPKLIST_APPEND, and _upk_conn_handle::writeq.
Referenced by ctrl_req_action_handler(), ctrl_req_disconnect_handler(), ctrl_req_preamble_handler(), main(), and upk_clnet_serial_request().
void upk_read_packets (upk_conn_handle_meta_t * handles)
read any packets from the handle handles->thisp, and call read-callbacks.
******************************************************************************************************************
Parameters:
[in] handles connection handles llist.
References _upk_conn_handle::fd, _upk_conn_handle::n_hdr_bytes_read, _upk_conn_handle::n_remaining_read, ntohl(), _upk_conn_handle::readbuf, upk_conn_handle_meta_p::thisp, upk_call_received_packet_callbacks(), upk_debug1, upk_deserialize_packet(), upk_disconnect_handle(), upk_error, UPK_MAX_PACKET_SIZE, UPK_MAX_SUPPORTED_PROTO, UPK_MIN_SUPPORTED_PROTO, UPK_PACKET_FOOTER_LEN, UPK_PACKET_HEADER_LEN, and upk_pkt_free().
Referenced by upk_net_event_dispatcher().
void upk_write_packets (upk_conn_handle_meta_t * handles)
write the packets in the writeq for handles->thisp, and call any write callbacks
*****************************************************************************************************************
Parameters:
[in] handles connection handles llist; uses thisp
References _upk_netmsg_queue::after_write_callback, upk_netmsg_queue_meta_p::count, _upk_conn_handle::fd, _upk_netmsg_queue::msg, _upk_netmsg_queue::msg_len, _upk_netmsg_queue::n_bytes_written, _upk_net_state::pending_writeq, upk_netmsg_queue_meta_p::thisp, upk_conn_handle_meta_p::thisp, upk_disconnect_handle(), upk_net_get_global_state(), UPKLIST_UNLINK, and _upk_conn_handle::writeq.
Referenced by upk_net_event_dispatcher().
typedef UPKLIST_METANODE (upk_net_cb_stk_t , upk_net_cb_stk_meta_p)
metanode for the callback stack
typedef UPKLIST_METANODE (upk_netmsg_queue_t , upk_netmsg_queue_meta_p)
typedef UPKLIST_METANODE (upk_conn_handle_t , upk_conn_handle_meta_p)
Variable Documentation
typedef upk_conn_handle_meta_t
typedef upk_net_cb_stk_meta_t
typedef upk_netmsg_queue_meta_t