upkeeper: Functions
Functions
Config_impl
Functions
void upk_svc_desc_free (upk_svc_desc_t *svc)
void upk_svclist_free (upk_svc_desc_meta_t *svclist)
void upk_ctrlconf_free (upk_controller_config_t *cfg)
void upk_ctrl_free_config (void)
void upk_svcconf_pack (upk_controller_config_t *cfg, const char *json_string)
void upk_ctrl_load_config (void)
void upk_svc_desc_clear (upk_svc_desc_t *svc)
char * upk_concat_svcid (char *dest, const char *pkg, const char *name)
char * upk_svc_id (char *dest, upk_svc_desc_t *svc)
void upk_parse_svc_id (char *key, upk_svc_desc_t *svc)
struct json_object * upk_svclist_to_json_obj (upk_svc_desc_meta_t *svclist)
struct json_object * upk_svc_desc_to_json_obj (upk_svc_desc_t *svc)
char * upk_json_serialize_svc_config (upk_svc_desc_t *svc, upk_json_data_output_opts_t opts)
void upk_overlay_svcconf_values (upk_svc_desc_t *dest, upk_svc_desc_t *high)
void upk_overlay_ctrlconf_values (upk_controller_config_t *dest, upk_controller_config_t *high)
void upk_finalize_svc_desc (upk_svc_desc_t *dest, upk_svc_desc_t *orig)
void upk_load_runtime_service_file (const char *filename)
void upk_load_runtime_services (void)
Variables
char upk_ctrl_configuration_file [UPK_MAX_PATH_LEN]
const char upk_default_configuration_vec []
upk_controller_config_t upk_default_configuration
upk_controller_config_t upk_file_configuration
upk_controller_config_t upk_runtime_configuration
Function Documentation
char* upk_concat_svcid (char * dest, const char * pkg, const char * name)
References UPK_MAX_STRING_LEN.
Referenced by upk_svc_desc_to_json_obj(), and upk_svc_id().
void upk_ctrl_free_config (void)
References upk_ctrlconf_free().
Referenced by main().
void upk_ctrl_load_config (void)
References _upk_controller_config::BuddyPollingInterval, _upk_controller_config::controller_buddy_sock, _upk_controller_config::controller_socket, _upk_controller_config::ServiceDefaults, _upk_controller_config::StateDir, upk_config_loadfile(), upk_ctrl_configuration_file, upk_ctrlconf_pack(), upk_default_configuration_vec, UPK_MAX_STRING_LEN, upk_overlay_ctrlconf_values(), and upk_svc_desc_clear().
Referenced by main(), and upk_ctrl_init().
void upk_ctrlconf_free (upk_controller_config_t * cfg)
References _upk_controller_config::ServiceDefaults, _upk_controller_config::svclist, upk_svc_desc_free(), and upk_svclist_free().
Referenced by upk_ctrl_free_config().
void upk_finalize_svc_desc (upk_svc_desc_t * dest, upk_svc_desc_t * orig)
References _upk_svc_desc::ExecReload, _upk_svc_desc::ExecStart, _upk_svc_desc::ExecStop, _upk_svc_desc::ReloadScript, _upk_controller_config::ServiceDefaults, _upk_svc_desc::StartScript, _upk_svc_desc::StopScript, upk_overlay_svcconf_values(), and upk_replace_string().
Referenced by upk_load_runtime_services().
char* upk_json_serialize_svc_config (upk_svc_desc_t * svc, upk_json_data_output_opts_t opts)
References _upk_svc_desc::next, upk_json_obj_to_string(), upk_svc_desc_meta_t, upk_svclist_to_json_obj(), UPKLIST_APPEND, and UPKLIST_FREE.
Referenced by main(), and upk_load_runtime_services().
void upk_load_runtime_service_file (const char * filename)
void upk_load_runtime_services (void)
References _upk_json_data_output_options::sep, strnlen(), _upk_controller_config::SvcConfigPath, _upk_controller_config::svclist, upk_config_loadfile(), upk_debug1, upk_diag_verbosity, UPK_DIAGLVL_DEBUG1, upk_finalize_svc_desc(), upk_info, upk_json_serialize_svc_config(), UPK_MAX_PATH_LEN, upk_svc_desc_clear(), upk_svcconf_pack(), UPKLIST_APPEND, UPKLIST_FOREACH, and UPKLIST_FREE.
Referenced by upk_ctrl_init().
void upk_overlay_ctrlconf_values (upk_controller_config_t * dest, upk_controller_config_t * high)
References _upk_controller_config::BuddyPollingInterval, _upk_controller_config::controller_buddy_sock, _upk_controller_config::controller_socket, _upk_svc_desc::Name, _upk_controller_config::ServiceDefaults, _upk_controller_config::StateDir, _upk_controller_config::SvcConfigPath, _upk_controller_config::svclist, _upk_controller_config::SvcRunPath, upk_overlay_svcconf_values(), _upk_controller_config::UpkBuddyPath, UPKLIST_APPEND, UPKLIST_FOREACH, and UPKLIST_FREE.
Referenced by upk_ctrl_load_config().
void upk_overlay_svcconf_values (upk_svc_desc_t * dest, upk_svc_desc_t * high)
References _upk_svc_desc::BuddyShutdownTimeout, _upk_uuid::clk_seq_high, _upk_uuid::clk_seq_low, _upk_svc_desc::custom_action_scripts, _upk_svc_desc::ExecReload, _upk_svc_desc::ExecStart, _upk_svc_desc::ExecStop, _upk_svc_desc::InitialState, _upk_svc_desc::KillTimeout, _upk_svc_desc::LongDescription, _upk_svc_desc::MaxConsecutiveFailures, _upk_svc_desc::Name, _upk_uuid::node, _upk_svc_desc::Package, _upk_svc_desc::PipeStderrScript, _upk_svc_desc::PipeStdoutScript, _upk_svc_desc::PreferBuddyStateForRunning, _upk_svc_desc::PreferBuddyStateForStopped, _upk_svc_desc::Prerequisites, _upk_svc_desc::Provides, _upk_svc_desc::RandomizeRateLimit, _upk_svc_desc::ReconnectRetries, _upk_svc_desc::RedirectStderr, _upk_svc_desc::RedirectStdout, _upk_svc_desc::ReloadScript, _upk_svc_desc::RingbufferSize, _upk_svc_desc::SetGID, _upk_svc_desc::SetUID, _upk_svc_desc::ShortDescription, _upk_svc_desc::StartPriority, _upk_svc_desc::StartScript, _upk_svc_desc::StopScript, _upk_uuid::time_high_and_version, _upk_uuid::time_low, _upk_uuid::time_mid, _upk_svc_desc::UnconfigureOnFileRemoval, UPKLIST_APPEND, UPKLIST_FOREACH, UPKLIST_FREE, _upk_svc_desc::UserMaxRestarts, _upk_svc_desc::UserRateLimit, _upk_svc_desc::UserRestartWindow, and _upk_svc_desc::UUID.
Referenced by upk_finalize_svc_desc(), and upk_overlay_ctrlconf_values().
void upk_parse_svc_id (char * key, upk_svc_desc_t * svc)
References _upk_svc_desc::Name, and _upk_svc_desc::Package.
Referenced by upk_ctrlconf_object_handler(), and upk_svcconf_object_handler().
void upk_svc_desc_clear (upk_svc_desc_t * svc)
References _upk_svc_desc::next, and _upk_svc_desc::StartPriority.
Referenced by main(), upk_ctrl_load_config(), upk_load_runtime_services(), and upk_svcconf_object_handler().
void upk_svc_desc_free (upk_svc_desc_t * svc)
References _upk_svc_desc::custom_action_scripts, _upk_svc_desc::LongDescription, _upk_svc_desc::PipeStderrScript, _upk_svc_desc::PipeStdoutScript, _upk_svc_desc::ReloadScript, _upk_svc_desc::StartScript, _upk_svc_desc::StopScript, and UPKLIST_FREE.
Referenced by upk_ctrlconf_free(), and upk_svclist_free().
struct json_object* upk_svc_desc_to_json_obj (upk_svc_desc_t * svc) [read]
References _joa, _upk_svc_desc::BuddyShutdownTimeout, _upk_svc_desc::custom_action_scripts, _upk_svc_desc::ExecReload, _upk_svc_desc::ExecStart, _upk_svc_desc::ExecStop, _upk_svc_desc::InitialState, jt_array, jt_boolean, jt_int, jt_string, _upk_svc_desc::KillTimeout, _upk_svc_desc::LongDescription, _upk_svc_desc::MaxConsecutiveFailures, _upk_svc_desc::PipeStderrScript, _upk_svc_desc::PipeStdoutScript, _upk_svc_desc::PreferBuddyStateForRunning, _upk_svc_desc::PreferBuddyStateForStopped, _upk_svc_desc::Prerequisites, _upk_svc_desc::Provides, _upk_svc_desc::RandomizeRateLimit, _upk_svc_desc::ReconnectRetries, _upk_svc_desc::RedirectStderr, _upk_svc_desc::RedirectStdout, _upk_svc_desc::ReloadScript, _upk_svc_desc::RingbufferSize, _upk_svc_desc::SetGID, _upk_svc_desc::SetUID, _upk_svc_desc::ShortDescription, _upk_svc_desc::StartPriority, _upk_svc_desc::StartScript, _upk_svc_desc::StopScript, _upk_svc_desc::UnconfigureOnFileRemoval, upk_concat_svcid(), upk_json_serialize_or_null(), UPK_MAX_STRING_LEN, UPK_STATE_RUNNING, UPK_STATE_STOPPED, upk_string_to_uuid(), UPKLIST_FOREACH, _upk_svc_desc::UserMaxRestarts, _upk_svc_desc::UserRateLimit, _upk_svc_desc::UserRestartWindow, and _upk_svc_desc::UUID.
Referenced by upk_svclist_to_json_obj().
char* upk_svc_id (char * dest, upk_svc_desc_t * svc)
References _upk_svc_desc::Name, _upk_svc_desc::Package, and upk_concat_svcid().
Referenced by upk_svclist_to_json_obj().
void upk_svcconf_pack (upk_controller_config_t * cfg, const char * json_string)
References _upk_json_stack_node::data, upk_conf_error_handler(), upk_json_parse_node(), upk_json_parse_string(), upk_json_stack_meta_t, upk_json_stack_push(), upk_svcconf_toplvl_obj(), and UPKLIST_FREE.
Referenced by upk_load_runtime_services().
void upk_svclist_free (upk_svc_desc_meta_t * svclist)
References upk_svc_desc_free(), UPKLIST_FOREACH, and UPKLIST_FREE.
Referenced by upk_ctrlconf_free().
struct json_object* upk_svclist_to_json_obj (upk_svc_desc_meta_t * svclist) [read]
References _joa, UPK_MAX_STRING_LEN, upk_svc_desc_to_json_obj(), upk_svc_id(), and UPKLIST_FOREACH.
Referenced by upk_json_serialize_svc_config().
Variable Documentation
char upk_ctrl_configuration_file[UPK_MAX_PATH_LEN]
Referenced by upk_ctrl_load_config().
upk_controller_config_t upk_default_configuration
const char upk_default_configuration_vec[]
Referenced by upk_ctrl_load_config().
upk_controller_config_t upk_file_configuration
upk_controller_config_t upk_runtime_configuration
Referenced by controller_packet_callback(), create_buddy_statedir(), ctrl_sock_setup(), event_loop(), main(), upk_clnet_ctrl_connect(), and upk_db_path().