upkeeper: libupkeeper/tests/config.c File Reference
libupkeeper/tests/config.c File Reference
#include <check.h>
#include <upkeeper.h>
Defines
#define test_config_file test.conf
Functions
Suite * upk_proto_helpers_suite (void)
int main (void)
Define Documentation
#define test_config_file test.conf
Function Documentation
int main (void)
References suite(), and upk_proto_helpers_suite().
Suite* upk_proto_helpers_suite (void)
References suite(), v0_proto_pubmsgs(), v0_proto_replies(), and v0_proto_requests().
Referenced by main().