upkeeper: libupkeeper/tests/linked_lists.c File Reference
libupkeeper/tests/linked_lists.c File Reference
#include <check.h>
#include <upkeeper.h>
Data Structures
struct _test_foo
Typedefs
typedef struct _test_foo test_foo_t
Functions
START_TEST (test_swap)
START_TEST (test_prepend)
START_TEST (test_append)
START_TEST (test_append_this)
START_TEST (test_unlink)
START_TEST (test_unlink_first)
TCase * ll_tcase (void)
Suite * upk_ll_suite (void)
int main (void)
Variables
END_TEST
Typedef Documentation
typedef struct _test_foo test_foo_t
Function Documentation
TCase* ll_tcase (void)
int main (void)
References suite(), and upk_ll_suite().
START_TEST (test_append_this)
References UPKLIST_APPEND_THIS, UPKLIST_FOREACH, UPKLIST_FREE, and UPKLIST_INIT.
START_TEST (test_append)
References UPKLIST_APPEND, UPKLIST_FOREACH, UPKLIST_FREE, and UPKLIST_INIT.
START_TEST (test_unlink_first)
References UPKLIST_APPEND_THIS, UPKLIST_FOREACH, UPKLIST_FREE, UPKLIST_INIT, and UPKLIST_UNLINK.
START_TEST (test_unlink)
References UPKLIST_APPEND_THIS, UPKLIST_FOREACH, UPKLIST_FREE, UPKLIST_INIT, and UPKLIST_UNLINK.
START_TEST (test_prepend)
References UPKLIST_FOREACH, UPKLIST_FREE, UPKLIST_INIT, and UPKLIST_PREPEND.
START_TEST (test_swap)
References UPKLIST_APPEND, UPKLIST_FOREACH, UPKLIST_FREE, UPKLIST_INIT, and UPKLIST_SWAP.
Suite* upk_ll_suite (void)
References ll_tcase(), and suite().
Variable Documentation
END_TEST