upkeeper: libupkeeper/s.c File Reference
libupkeeper/s.c File Reference
#include <upkeeper.h>
Defines
#define n_protos (1 + UPK_MAX_SUPPORTED_PROTO - UPK_MIN_SUPPORTED_PROTO)
#define n_per(A) (UPK_##A##_LIMIT - UPK_##A##_ORIGIN - n_protos)
#define t_scs(A, B) (type < UPK_##A##_LIMIT) ? (type - UPK_##A##_ORIGIN) + B
#define t_idx t_scs(REQ, 0) : t_scs(REPL, n_per(REQ)) : t_scs(PUB, n_per(REQ) + n_per(REPL)) : -1
Functions
int crap (upk_msgtype_t type)
int main (int argc, char **argv, char **envp)
Define Documentation
#define n_per (A) (UPK_##A##_LIMIT - UPK_##A##_ORIGIN - n_protos)
#define n_protos (1 + UPK_MAX_SUPPORTED_PROTO - UPK_MIN_SUPPORTED_PROTO)
#define t_idx t_scs(REQ, 0) : t_scs(REPL, n_per(REQ)) : t_scs(PUB, n_per(REQ) + n_per(REPL)) : -1
Referenced by crap().
#define t_scs (A, B) (type < UPK_##A##_LIMIT) ? (type - UPK_##A##_ORIGIN) + B
Function Documentation
int crap (upk_msgtype_t type)
References t_idx.
int main (int argc, char ** argv, char ** envp)
References upk_req_preamble_t::client_name, upk_conn_handle_meta_p::head, _upk_conn_handle::last_pkt_data, _upk_payload::payload, _upk_payload_types::req_preamble, SOCK_STREAM, socketpair(), _upk_payload::type, upk_clientid(), upk_create_req_action(), upk_create_req_preamble(), upk_fatal, upk_net_add_socket_handle(), upk_net_conn_handles_init(), upk_net_event_dispatcher(), and upk_queue_packet().