upkeeper: libupkeeper/tests/uuid.c File Reference
libupkeeper/tests/uuid.c File Reference
#include <check.h>
#include <upkeeper.h>
#include <stdio.h>
Defines
#define TESTCASE_NAME "uuid"
#define SUITE_NAME "uuid"
Functions
START_TEST (test_string_to_uuid)
START_TEST (test_uuid_to_string)
START_TEST (test_is_valid)
START_TEST (test_gen_uuid)
TCase * upk_tcase (void)
Suite * upk_suite (void)
int main (void)
Variables
END_TEST
Define Documentation
#define SUITE_NAME "uuid"
Referenced by upk_suite().
#define TESTCASE_NAME "uuid"
Referenced by upk_tcase().
Function Documentation
int main (void)
References suite(), and upk_suite().
START_TEST (test_is_valid)
References is_valid_upk_uuid_string().
START_TEST (test_uuid_to_string)
References _upk_uuid::time_low, and upk_uuid_to_string().
START_TEST (test_gen_uuid)
References _upk_uuid::clk_seq_high, _upk_uuid::time_high_and_version, and upk_gen_uuid_bytes().
START_TEST (test_string_to_uuid)
References _upk_uuid::clk_seq_high, _upk_uuid::clk_seq_low, _upk_uuid::node, _upk_uuid::time_high_and_version, _upk_uuid::time_low, _upk_uuid::time_mid, and upk_string_to_uuid().
Suite* upk_suite (void)
References suite(), SUITE_NAME, and upk_tcase().
Referenced by main().
TCase* upk_tcase (void)
References tcase(), and TESTCASE_NAME.
Referenced by upk_suite().
Variable Documentation
END_TEST