upkeeper: libupkeeper/tests/tskel.c File Reference
libupkeeper/tests/tskel.c File Reference
#include <check.h>
#include <upkeeper.h>
Defines
#define TESTCASE_NAME "uuid"
#define SUITE_NAME "uuid"
Functions
START_TEST (test_gen_uuid)
TCase * tcase (void)
Suite * suite (void)
int main (void)
Variables
END_TEST
Define Documentation
#define SUITE_NAME "uuid"
Referenced by suite().
#define TESTCASE_NAME "uuid"
Referenced by tcase().
Function Documentation
int main (void)
References suite().
START_TEST (test_gen_uuid)
Suite* suite (void)
References SUITE_NAME, and tcase().
Referenced by main(), test_suite(), upk_ll_suite(), upk_proto_helpers_suite(), upk_proto_serializers_suite(), upk_suite(), v0_proto_helpers_suite(), and v0_proto_serializers_suite().
TCase* tcase (void)
References TESTCASE_NAME.
Referenced by suite(), test_tcase(), and upk_tcase().
Variable Documentation
END_TEST