upkeeper: libupkeeper/upkeeper/upk_error.c File Reference
libupkeeper/upkeeper/upk_error.c File Reference
#include "upk_error.h"
#include <stdio.h>
#include <stdarg.h>
Defines
#define UPK_STATIC_ERR_DECL
Functions
static void _upk_default_diag_output (upk_diaglvl_t diaglvl, const char *label, const char *loc, const char *fmt, va_list ap)
static int32_t _upk_diagnostic (upk_diaglvl_t diaglvl, const char *loc, const char *fmt, va_list ap)
const char * upk_strerror (upk_errno_t err)
diag_output_callback_t upk_reg_diag_callback (diag_output_callback_t func)
int32_t _upk_fatal (const char *loc, const char *fmt,...)
int32_t _upk_alert (const char *loc, const char *fmt,...)
int32_t _upk_crit (const char *loc, const char *fmt,...)
int32_t _upk_error (const char *loc, const char *fmt,...)
int32_t _upk_warn (const char *loc, const char *fmt,...)
int32_t _upk_notice (const char *loc, const char *fmt,...)
int32_t _upk_info (const char *loc, const char *fmt,...)
int32_t _upk_verbose (const char *loc, const char *fmt,...)
int32_t _upk_debug0 (const char *loc, const char *fmt,...)
int32_t _upk_debug1 (const char *loc, const char *fmt,...)
Variables
int32_t upk_diag_verbosity = UPK_DIAGLVL_NOTICE
char __upk_err_buf [4096] = ""
upk_errno_t __upk_errno_type = 0
diag_output_callback_t __upk_diag_output_callback = _upk_default_diag_output
Define Documentation
#define UPK_STATIC_ERR_DECL
Referenced by _upk_alert(), _upk_crit(), _upk_debug0(), _upk_debug1(), _upk_default_diag_output(), _upk_error(), _upk_fatal(), _upk_info(), _upk_notice(), _upk_verbose(), and _upk_warn().
Function Documentation
static void _upk_default_diag_output (upk_diaglvl_t diaglvl, const char * label, const char * loc, const char * fmt, va_list ap) [static]
References upk_diag_verbosity, UPK_DIAGLVL_ALERT, UPK_DIAGLVL_CRIT, UPK_DIAGLVL_ERROR, UPK_DIAGLVL_FATAL, UPK_DIAGLVL_INFO, and UPK_STATIC_ERR_DECL.
static int32_t _upk_diagnostic (upk_diaglvl_t diaglvl, const char * loc, const char * fmt, va_list ap) [static]
References __upk_diag_output_callback, upk_diag_label_idx, upk_diag_verbosity, and UPK_DIAGLVL_FATAL.
Referenced by _upk_alert(), _upk_crit(), _upk_debug0(), _upk_debug1(), _upk_error(), _upk_fatal(), _upk_info(), _upk_notice(), _upk_verbose(), and _upk_warn().
Variable Documentation
diag_output_callback_t __upk_diag_output_callback = _upk_default_diag_output
Referenced by _upk_diagnostic(), and upk_reg_diag_callback().