upkeeper: libupkeeper/upkeeper/upk_v0_protocol_serializer.c File Reference
libupkeeper/upkeeper/upk_v0_protocol_serializer.c File Reference
#include "upk_v0_protocol.h"
#include "upk_error.h"
#include <assert.h>
Defines
#define UPK_MSG_IDENTIFIER msgtype
#define UPK_MSG_IDENTIFIER_TYPEDEF upk_msgtype_t
#define UPK_MSG_IDENTIFIER_TYPEDEF upk_msgtype_t
#define UPK_MSG_IDENTIFIER_TYPEDEF upk_msgtype_t
#define UPK_MSG_IDENTIFIER_TYPEDEF upk_msgtype_t
#define UPK_MSG_IDENTIFIER_TYPEDEF upk_msgtype_t
#define UPK_MSG_IDENTIFIER_TYPEDEF upk_msgtype_t
Typedefs
typedef void *(* deserialize_payload_t)(upk_pkt_buf_t *)
typedef upk_pkt_buf_t *(* serialize_payload_t)(void *, size_t)
Functions
static upk_pkt_buf_t * serialize_req_payload (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serialize_repl_payload (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serialize_pub_payload (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static void * deserialize_req_payload (upk_pkt_buf_t *UPK_BUF)
static void * deserialize_repl_payload (upk_pkt_buf_t *UPK_BUF)
static void * deserialize_pub_payload (upk_pkt_buf_t *UPK_BUF)
static void * deserial_req_seq_start (upk_pkt_buf_t *UPK_BUF)
static void * deserial_req_seq_end (upk_pkt_buf_t *UPK_BUF)
static void * deserial_req_action (upk_pkt_buf_t *UPK_BUF)
static void * deserial_req_signal (upk_pkt_buf_t *UPK_BUF)
static void * deserial_req_list (upk_pkt_buf_t *UPK_BUF)
static void * deserial_req_status (upk_pkt_buf_t *UPK_BUF)
static void * deserial_req_subscribe (upk_pkt_buf_t *UPK_BUF)
static void * deserial_req_unsub (upk_pkt_buf_t *UPK_BUF)
static void * deserial_req_disconnect (upk_pkt_buf_t *UPK_BUF)
static void * deserial_repl_seq_start (upk_pkt_buf_t *UPK_BUF)
static void * deserial_repl_seq_end (upk_pkt_buf_t *UPK_BUF)
static void * deserial_repl_result (upk_pkt_buf_t *UPK_BUF)
static void * deserial_repl_listing (upk_pkt_buf_t *UPK_BUF)
static v0_svcinfo_t * deserial_svcinfo_data (upk_pkt_buf_t *UPK_BUF)
static void * deserial_repl_svcinfo (upk_pkt_buf_t *UPK_BUF)
static void * deserial_repl_ack (upk_pkt_buf_t *UPK_BUF)
static void * deserial_repl_err (upk_pkt_buf_t *UPK_BUF)
static void * deserial_pub_pub (upk_pkt_buf_t *UPK_BUF)
static void * deserial_pub_cancel (upk_pkt_buf_t *UPK_BUF)
static upk_pkt_buf_t * serial_req_seq_start (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_req_seq_end (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_req_action (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_req_signal (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_req_list (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_req_status (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_req_subscribe (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_req_unsub (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_req_disconnect (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_repl_seq_start (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_repl_seq_end (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_repl_result (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_repl_listing (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_svcinfo_data (v0_svcinfo_t *data, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_repl_svcinfo (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_repl_ack (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_repl_err (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_pub_pub (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static upk_pkt_buf_t * serial_pub_cancel (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
void * v0_deserialize_payload (upk_pkt_buf_t *UPK_BUF, upk_pkttype_t pkttype)
upk_pkt_buf_t * v0_serialize_payload (upk_packet_t *pkt)
Variables
upk_pkttype_t upk_pkt_proto_limit []
upk_msgtype_t upk_req_proto_limit []
upk_msgtype_t upk_repl_proto_limit []
upk_msgtype_t upk_pub_proto_limit []
static deserialize_payload_t deserial_pkt_dispatch []
static deserialize_payload_t deserial_req_dispatch []
static deserialize_payload_t deserial_repl_dispatch []
static deserialize_payload_t deserial_pub_dispatch []
static serialize_payload_t serial_pkt_dispatch []
static serialize_payload_t serial_req_dispatch []
static serialize_payload_t serial_repl_dispatch []
static serialize_payload_t serial_pub_dispatch []
Define Documentation
#define UPK_MSG_IDENTIFIER msgtype
#define UPK_MSG_IDENTIFIER_TYPEDEF upk_msgtype_t
#define UPK_MSG_IDENTIFIER_TYPEDEF upk_msgtype_t
#define UPK_MSG_IDENTIFIER_TYPEDEF upk_msgtype_t
#define UPK_MSG_IDENTIFIER_TYPEDEF upk_msgtype_t
#define UPK_MSG_IDENTIFIER_TYPEDEF upk_msgtype_t
#define UPK_MSG_IDENTIFIER_TYPEDEF upk_msgtype_t
Typedef Documentation
typedef void*(* deserialize_payload_t)(upk_pkt_buf_t *)
typedef upk_pkt_buf_t*(* serialize_payload_t)(void *, size_t)
Function Documentation
static void * deserial_pub_cancel (upk_pkt_buf_t * UPK_BUF) [static]
References UPK_DATA, and UPK_INIT_DESERIALIZE_MSG.
static void * deserial_pub_pub (upk_pkt_buf_t * UPK_BUF) [static]
References UPK_DATA, and UPK_INIT_DESERIALIZE_MSG.
static void * deserial_repl_ack (upk_pkt_buf_t * UPK_BUF) [static]
References UPK_DATA, and UPK_INIT_DESERIALIZE_MSG.
static void * deserial_repl_err (upk_pkt_buf_t * UPK_BUF) [static]
References UPK_DATA, UPK_FETCH_ENUM, UPK_FETCH_STRING, UPK_FETCH_UINT32, and UPK_INIT_DESERIALIZE_MSG.
static void * deserial_repl_listing (upk_pkt_buf_t * UPK_BUF) [static]
References UPK_DATA, UPK_FETCH_STRING, UPK_FETCH_UINT32, and UPK_INIT_DESERIALIZE_MSG.
static void * deserial_repl_result (upk_pkt_buf_t * UPK_BUF) [static]
References UPK_DATA, UPK_FETCH_BOOL, UPK_FETCH_STRING, UPK_FETCH_UINT32, and UPK_INIT_DESERIALIZE_MSG.
static void * deserial_repl_seq_end (upk_pkt_buf_t * UPK_BUF) [static]
References UPK_DATA, UPK_FETCH_BOOL, and UPK_INIT_DESERIALIZE_MSG.
static void * deserial_repl_seq_start (upk_pkt_buf_t * UPK_BUF) [static]
References UPK_DATA, UPK_FETCH_ENUM, UPK_FETCH_UINT32, and UPK_INIT_DESERIALIZE_MSG.
static void * deserial_repl_svcinfo (upk_pkt_buf_t * UPK_BUF) [static]
References deserial_svcinfo_data(), UPK_DATA, UPK_FETCH_DATA_TO_BUF, UPK_FETCH_STRING, UPK_FETCH_UINT32, and UPK_INIT_DESERIALIZE_MSG.
static void * deserial_req_action (upk_pkt_buf_t * UPK_BUF) [static]
References UPK_DATA, UPK_FETCH_STRING, UPK_FETCH_UINT32, and UPK_INIT_DESERIALIZE_MSG.
static void * deserial_req_disconnect (upk_pkt_buf_t * UPK_BUF) [static]
References UPK_DATA, and UPK_INIT_DESERIALIZE_MSG.
static void * deserial_req_list (upk_pkt_buf_t * UPK_BUF) [static]
References UPK_DATA, and UPK_INIT_DESERIALIZE_MSG.
static void * deserial_req_seq_end (upk_pkt_buf_t * UPK_BUF) [static]
References UPK_DATA, UPK_FETCH_BOOL, and UPK_INIT_DESERIALIZE_MSG.
static void * deserial_req_seq_start (upk_pkt_buf_t * UPK_BUF) [static]
References UPK_DATA, UPK_FETCH_ENUM, UPK_FETCH_UINT32, and UPK_INIT_DESERIALIZE_MSG.
static void * deserial_req_signal (upk_pkt_buf_t * UPK_BUF) [static]
References UPK_DATA, UPK_FETCH_BOOL, UPK_FETCH_ENUM, UPK_FETCH_STRING, UPK_FETCH_UINT32, and UPK_INIT_DESERIALIZE_MSG.
static void * deserial_req_status (upk_pkt_buf_t * UPK_BUF) [static]
References UPK_DATA, UPK_FETCH_STRING, UPK_FETCH_UINT32, and UPK_INIT_DESERIALIZE_MSG.
static void * deserial_req_subscribe (upk_pkt_buf_t * UPK_BUF) [static]
References UPK_DATA, UPK_FETCH_BOOL, UPK_FETCH_STRING, UPK_FETCH_UINT32, and UPK_INIT_DESERIALIZE_MSG.
static void * deserial_req_unsub (upk_pkt_buf_t * UPK_BUF) [static]
References UPK_DATA, UPK_FETCH_BOOL, UPK_FETCH_STRING, UPK_FETCH_UINT32, and UPK_INIT_DESERIALIZE_MSG.
static v0_svcinfo_t * deserial_svcinfo_data (upk_pkt_buf_t * UPK_BUF) [inline, static]
References proc_pid, UPK_DATA, UPK_FETCH_ARRAY, UPK_FETCH_ENUM, UPK_FETCH_UINT32, and UPK_INIT_DESERIALIZE.
Referenced by deserial_repl_svcinfo().
static void * deserialize_pub_payload (upk_pkt_buf_t * UPK_BUF) [static]
References deserial_pub_dispatch, UPK_BUF, and UPK_PUB_ORIGIN.
static void * deserialize_repl_payload (upk_pkt_buf_t * UPK_BUF) [static]
References deserial_repl_dispatch, UPK_BUF, and UPK_REPL_ORIGIN.
static void * deserialize_req_payload (upk_pkt_buf_t * UPK_BUF) [static]
References deserial_req_dispatch, UPK_BUF, and UPK_REQ_ORIGIN.
static upk_pkt_buf_t * serial_pub_cancel (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References UPK_BUF, and UPK_INIT_SERIALIZE_MSG.
static upk_pkt_buf_t * serial_pub_pub (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References UPK_BUF, and UPK_INIT_SERIALIZE_MSG.
static upk_pkt_buf_t * serial_repl_ack (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References UPK_BUF, and UPK_INIT_SERIALIZE_MSG.
static upk_pkt_buf_t * serial_repl_err (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References UPK_BUF, UPK_INIT_SERIALIZE_MSG, UPK_PUT_ENUM, UPK_PUT_STRING, and UPK_PUT_UINT32.
static upk_pkt_buf_t * serial_repl_listing (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References UPK_BUF, UPK_INIT_SERIALIZE_MSG, UPK_PUT_STRING, and UPK_PUT_UINT32.
static upk_pkt_buf_t * serial_repl_result (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References UPK_BUF, UPK_INIT_SERIALIZE_MSG, UPK_PUT_BOOL, UPK_PUT_STRING, and UPK_PUT_UINT32.
static upk_pkt_buf_t * serial_repl_seq_end (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References UPK_BUF, UPK_INIT_SERIALIZE_MSG, and UPK_PUT_BOOL.
static upk_pkt_buf_t * serial_repl_seq_start (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References UPK_BUF, UPK_INIT_SERIALIZE_MSG, UPK_PUT_ENUM, and UPK_PUT_UINT32.
static upk_pkt_buf_t * serial_repl_svcinfo (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References serial_svcinfo_data(), UPK_BUF, UPK_DATA, UPK_INIT_SERIALIZE_MSG, UPK_PUT_DATA_FROM_BUF, UPK_PUT_STRING, and UPK_PUT_UINT32.
static upk_pkt_buf_t * serial_req_action (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References UPK_BUF, UPK_INIT_SERIALIZE_MSG, UPK_PUT_STRING, and UPK_PUT_UINT32.
static upk_pkt_buf_t * serial_req_disconnect (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References UPK_BUF, and UPK_INIT_SERIALIZE_MSG.
static upk_pkt_buf_t * serial_req_list (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References UPK_BUF, and UPK_INIT_SERIALIZE_MSG.
static upk_pkt_buf_t * serial_req_seq_end (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References UPK_BUF, UPK_INIT_SERIALIZE_MSG, and UPK_PUT_BOOL.
static upk_pkt_buf_t * serial_req_seq_start (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References UPK_BUF, UPK_INIT_SERIALIZE_MSG, UPK_PUT_ENUM, and UPK_PUT_UINT32.
static upk_pkt_buf_t * serial_req_signal (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References UPK_BUF, UPK_INIT_SERIALIZE_MSG, UPK_PUT_BOOL, UPK_PUT_ENUM, UPK_PUT_STRING, and UPK_PUT_UINT32.
static upk_pkt_buf_t * serial_req_status (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References UPK_BUF, UPK_INIT_SERIALIZE_MSG, UPK_PUT_STRING, and UPK_PUT_UINT32.
static upk_pkt_buf_t * serial_req_subscribe (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References UPK_BUF, UPK_INIT_SERIALIZE_MSG, UPK_PUT_BOOL, UPK_PUT_STRING, and UPK_PUT_UINT32.
static upk_pkt_buf_t * serial_req_unsub (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References UPK_BUF, UPK_INIT_SERIALIZE_MSG, UPK_PUT_BOOL, UPK_PUT_STRING, and UPK_PUT_UINT32.
static upk_pkt_buf_t * serial_svcinfo_data (v0_svcinfo_t * data, size_t UPK_DATA_LEN) [inline, static]
References proc_pid, UPK_BUF, UPK_DATA, UPK_INIT_SERIALIZE_BUF, UPK_PUT_ARRAY, UPK_PUT_ENUM, and UPK_PUT_UINT32.
Referenced by serial_repl_svcinfo().
static upk_pkt_buf_t * serialize_pub_payload (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References upk_generic_msg_t::msgtype, serial_pub_dispatch, UPK_DATA_LEN, UPK_DATA_PTR, and UPK_PUB_ORIGIN.
static upk_pkt_buf_t * serialize_repl_payload (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References upk_generic_msg_t::msgtype, serial_repl_dispatch, UPK_DATA_LEN, UPK_DATA_PTR, and UPK_REPL_ORIGIN.
static upk_pkt_buf_t * serialize_req_payload (void * UPK_DATA_PTR, size_t UPK_DATA_LEN) [static]
References upk_generic_msg_t::msgtype, serial_req_dispatch, UPK_DATA_LEN, UPK_DATA_PTR, and UPK_REQ_ORIGIN.
void* v0_deserialize_payload (upk_pkt_buf_t * UPK_BUF, upk_pkttype_t pkttype)
References deserial_pkt_dispatch, and UPK_BUF.
Referenced by upk_deserialize_payload().
upk_pkt_buf_t* v0_serialize_payload (upk_packet_t * pkt)
References upk_packet_t::payload, upk_packet_t::payload_len, upk_packet_t::pkttype, and serial_pkt_dispatch.
Referenced by upk_serialize_payload().
Variable Documentation
deserialize_payload_t deserial_pkt_dispatch[] [static]
Initial value:
 {
    [PKT_REQUEST] = deserialize_req_payload,
    [PKT_REPLY] = deserialize_repl_payload,
    [PKT_PUBMSG] = deserialize_pub_payload,
}
Referenced by v0_deserialize_payload().
deserialize_payload_t deserial_pub_dispatch[] [static]
Initial value:
 {
    [UPK_PUB_PUBLICATION-UPK_PUB_ORIGIN] = deserial_pub_pub,
    [UPK_PUB_CANCELATION-UPK_PUB_ORIGIN] = deserial_pub_cancel,
}
Referenced by deserialize_pub_payload().
deserialize_payload_t deserial_repl_dispatch[] [static]
Initial value:
 {
    [UPK_REPL_PREAMBLE-UPK_REPL_ORIGIN] = upk_deserialize_repl_preamble,
    [UPK_REPL_SEQ_START-UPK_REPL_ORIGIN] = deserial_repl_seq_start,
    [UPK_REPL_SEQ_END-UPK_REPL_ORIGIN] = deserial_repl_seq_end,
    [UPK_REPL_RESULT-UPK_REPL_ORIGIN] = deserial_repl_result,
    [UPK_REPL_LISTING-UPK_REPL_ORIGIN] = deserial_repl_listing,
    [UPK_REPL_SVCINFO-UPK_REPL_ORIGIN] = deserial_repl_svcinfo,
    [UPK_REPL_ACK-UPK_REPL_ORIGIN] = deserial_repl_ack,
    [UPK_REPL_ERROR-UPK_REPL_ORIGIN] = deserial_repl_err,
}
Referenced by deserialize_repl_payload().
deserialize_payload_t deserial_req_dispatch[] [static]
Initial value:
 {
    [UPK_REQ_PREAMBLE-UPK_REQ_ORIGIN] = upk_deserialize_req_preamble,
    [UPK_REQ_SEQ_START-UPK_REQ_ORIGIN] = deserial_req_seq_start,
    [UPK_REQ_SEQ_END-UPK_REQ_ORIGIN] = deserial_req_seq_end,
    [UPK_REQ_ACTION-UPK_REQ_ORIGIN] = deserial_req_action,
    [UPK_REQ_SIGNAL-UPK_REQ_ORIGIN] = deserial_req_signal,
    [UPK_REQ_LIST-UPK_REQ_ORIGIN] = deserial_req_list,
    [UPK_REQ_STATUS-UPK_REQ_ORIGIN] = deserial_req_status,
    [UPK_REQ_SUBSCRIBE-UPK_REQ_ORIGIN] = deserial_req_subscribe,
    [UPK_REQ_UNSUBSCRIBE-UPK_REQ_ORIGIN] = deserial_req_unsub,
    [UPK_REQ_DISCONNECT-UPK_REQ_ORIGIN] = deserial_req_disconnect,
}
Referenced by deserialize_req_payload().
serialize_payload_t serial_pkt_dispatch[] [static]
Initial value:
 {
    [PKT_REQUEST] = serialize_req_payload,
    [PKT_REPLY] = serialize_repl_payload,
    [PKT_PUBMSG] = serialize_pub_payload,
}
Referenced by v0_serialize_payload().
serialize_payload_t serial_pub_dispatch[] [static]
Initial value:
 {
    [UPK_PUB_PUBLICATION - UPK_PUB_ORIGIN] = serial_pub_pub,
    [UPK_PUB_CANCELATION - UPK_PUB_ORIGIN] = serial_pub_cancel,
}
Referenced by serialize_pub_payload().
serialize_payload_t serial_repl_dispatch[] [static]
Initial value:
 {
    [UPK_REPL_PREAMBLE - UPK_REPL_ORIGIN] = upk_serialize_repl_preamble,
    [UPK_REPL_SEQ_START - UPK_REPL_ORIGIN] = serial_repl_seq_start,
    [UPK_REPL_SEQ_END - UPK_REPL_ORIGIN] = serial_repl_seq_end,
    [UPK_REPL_RESULT - UPK_REPL_ORIGIN] = serial_repl_result,
    [UPK_REPL_LISTING - UPK_REPL_ORIGIN] = serial_repl_listing,
    [UPK_REPL_SVCINFO - UPK_REPL_ORIGIN] = serial_repl_svcinfo,
    [UPK_REPL_ACK - UPK_REPL_ORIGIN] = serial_repl_ack,
    [UPK_REPL_ERROR - UPK_REPL_ORIGIN] = serial_repl_err,
}
Referenced by serialize_repl_payload().
serialize_payload_t serial_req_dispatch[] [static]
Initial value:
 {
    [UPK_REQ_PREAMBLE - UPK_REQ_ORIGIN] = upk_serialize_req_preamble,
    [UPK_REQ_SEQ_START - UPK_REQ_ORIGIN] = serial_req_seq_start,
    [UPK_REQ_SEQ_END - UPK_REQ_ORIGIN] = serial_req_seq_end,
    [UPK_REQ_ACTION - UPK_REQ_ORIGIN] = serial_req_action,
    [UPK_REQ_SIGNAL - UPK_REQ_ORIGIN] = serial_req_signal,
    [UPK_REQ_LIST - UPK_REQ_ORIGIN] = serial_req_list,
    [UPK_REQ_STATUS - UPK_REQ_ORIGIN] = serial_req_status,
    [UPK_REQ_SUBSCRIBE - UPK_REQ_ORIGIN] = serial_req_subscribe,
    [UPK_REQ_UNSUBSCRIBE - UPK_REQ_ORIGIN] = serial_req_unsub,
    [UPK_REQ_DISCONNECT - UPK_REQ_ORIGIN] = serial_req_disconnect,
}
Referenced by serialize_req_payload().
upk_pkttype_t upk_pkt_proto_limit[]
Referenced by upk_deserialize_packet().
upk_msgtype_t upk_pub_proto_limit[]
upk_msgtype_t upk_repl_proto_limit[]
upk_msgtype_t upk_req_proto_limit[]