upkeeper: libupkeeper/upkeeper/upk_compat.c File Reference
libupkeeper/upkeeper/upk_compat.c File Reference
Functions
size_t strnlen (const char *restrict string, size_t maxlen)
Function Documentation
size_t strnlen (const char *restrict string, size_t maxlen)
Referenced by buddy_init_paths(), opt_parse(), upk_config_loadfile(), upk_create_req_preamble(), upk_json_append_string(), upk_json_output_array_handler(), upk_json_output_object_handler(), upk_load_runtime_services(), upk_svcconf_string_handler(), and v0_create_repl_svcinfo().