upkeeper: libupkeeper/upkeeper/upk_json.h File Reference
libupkeeper/upkeeper/upk_json.h File Reference
#include "upk_include.h"
#include <json/json.h>
#include <stdio.h>
Data Structures
struct _upk_json_string
struct _upk_json_type
struct _upk_json_stack_handlers
struct _upk_json_stack_node
Typedefs
typedef struct _upk_json_string upk_json_string_t
typedef struct _upk_json_type upk_json_val_t
typedef struct _upk_json_stack_node upk_json_stack_node_t
typedef void(* upk_json_handler_t)(upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
typedef struct
_upk_json_stack_handlers upk_json_handlers_t
Functions
typedef UPKLIST_METANODE (upk_json_stack_node_t, upk_json_stack_meta_p)
void upk_json_stack_pop (upk_json_stack_meta_t *meta)
void upk_json_stack_push (upk_json_stack_meta_t *meta, upk_json_stack_node_t *node)
void upk_json_parse_node (upk_json_stack_meta_t *meta, char *key, struct json_object *jobj)
struct json_object * upk_json_parse_string (const char *string)
char * upk_json_obj_to_string (struct json_object *obj, upk_json_data_output_opts_t opts)
void upk_json_obj_to_stream (struct json_object *obj, FILE *stream, upk_json_data_output_opts_t opts)
Variables
typedef upk_json_stack_meta_t
Typedef Documentation
typedef void(* upk_json_handler_t)(upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
typedef struct _upk_json_stack_handlers upk_json_handlers_t
typedef struct _upk_json_stack_node upk_json_stack_node_t
typedef struct _upk_json_string upk_json_string_t
typedef struct _upk_json_type upk_json_val_t
Function Documentation
void upk_json_obj_to_stream (struct json_object * obj, FILE * stream, upk_json_data_output_opts_t opts)
References data_type_stream, _upk_json_output_data::type, and upk_json_obj_serializer().
char* upk_json_obj_to_string (struct json_object * obj, upk_json_data_output_opts_t opts)
References _upk_json_output_data::d, data_type_string, _upk_stream_string::p, _upk_stream_string::str, _upk_json_output_data::type, and upk_json_obj_serializer().
Referenced by upk_json_serialize_svc_config().
void upk_json_parse_node (upk_json_stack_meta_t * meta, char * key, struct json_object * jobj)
References _upk_json_parse_node().
Referenced by upk_ctrlconf_pack(), upk_json_obj_serializer(), and upk_svcconf_pack().
struct json_object* upk_json_parse_string (const char * string) [read]
References IF_UPK_ERROR, UPK_ERR_INIT, UPK_FUNC_ASSERT_MSG, and UPK_JSON_PARSE_ERROR.
Referenced by main(), upk_ctrlconf_pack(), and upk_svcconf_pack().
void upk_json_stack_pop (upk_json_stack_meta_t * meta)
References UPKLIST_FOREACH, and UPKLIST_UNLINK.
Referenced by _upk_json_parse_node().
void upk_json_stack_push (upk_json_stack_meta_t * meta, upk_json_stack_node_t * node)
References UPKLIST_PREPEND.
Referenced by upk_ctrlconf_object_handler(), upk_ctrlconf_pack(), upk_ctrlconf_toplvl_obj(), upk_json_obj_serializer(), upk_json_output_array_handler(), upk_json_output_object_handler(), upk_svcconf_array_handler(), upk_svcconf_nested_object_handler(), upk_svcconf_object_handler(), upk_svcconf_pack(), and upk_svcconf_toplvl_obj().
typedef UPKLIST_METANODE (upk_json_stack_node_t , upk_json_stack_meta_p)
Variable Documentation
typedef upk_json_stack_meta_t
Referenced by upk_ctrlconf_pack(), upk_json_obj_serializer(), and upk_svcconf_pack().