upkeeper: libupkeeper/upkeeper/upk_util.h File Reference
libupkeeper/upkeeper/upk_util.h File Reference
Defines
#define _stringify(A) #A
#define stringify(A) _stringify(A)
Functions
bool upk_numeric_string (const char *string, long *num)
bool upk_boolean_string (const char *string, bool *val)
void upk_replace_string (char **haystack, const char *needle, const char *repl)
struct timeval upk_double_to_timeval (long double rational)
Define Documentation
#define _stringify (A) #A
#define stringify (A) _stringify(A)
Function Documentation
bool upk_boolean_string (const char * string, bool * val)
References upk_numeric_string().
Referenced by main().
struct timeval upk_double_to_timeval (long double rational) [read]
Referenced by upk_net_event_dispatcher().
bool upk_numeric_string (const char * string, long * num)
Referenced by main(), and upk_boolean_string().
void upk_replace_string (char ** haystack, const char * needle, const char * repl)
Referenced by START_TEST(), and upk_finalize_svc_desc().