upkeeper: libupkeeper/upkeeper/upk_client_net.c File Reference
libupkeeper/upkeeper/upk_client_net.c File Reference
#include "upk_include.h"
Functions
upk_payload_t * upk_clnet_serial_request (upk_conn_handle_meta_t *ctrl, upk_packet_t *pkt)
void upk_clnet_req_preamble (upk_conn_handle_meta_t *ctrl)
upk_conn_handle_meta_t * upk_clnet_ctrl_connect (void)
void upk_clnet_req_disconnect (upk_conn_handle_meta_t *ctrl)
void upk_clnet_ctrl_disconnect (upk_conn_handle_meta_t *ctrl)
bool upk_clnet_req_action (upk_conn_handle_meta_t *ctrl, char *svc_id, char *action)
bool upk_clnet_req_signal (upk_conn_handle_meta_t *ctrl, char *svc_id, upk_signal_t signal, bool should_signal_sid, bool should_signal_pgrp)
upk_svcinfo_t * upk_clnet_req_status (upk_conn_handle_meta_t *ctrl, char *svc_id, uint32_t restart_window_seconds)
Function Documentation
upk_conn_handle_meta_t* upk_clnet_ctrl_connect (void)
****************************************************************************************************************
References _upk_controller_config::controller_socket, upk_clnet_req_preamble(), upk_domain_socket_connect(), upk_net_add_socket_handle(), upk_net_conn_handles_init(), upk_runtime_configuration, and UPKLIST_HEAD.
Referenced by main().
void upk_clnet_ctrl_disconnect (upk_conn_handle_meta_t * ctrl)
****************************************************************************************************************
References upk_clnet_req_disconnect(), and UPKLIST_FREE.
Referenced by main().
bool upk_clnet_req_action (upk_conn_handle_meta_t * ctrl, char * svc_id, char * action)
****************************************************************************************************************
References upk_repl_error_t::errlevel, free(), upk_conn_handle_meta_p::head, upk_repl_error_t::msg, upk_repl_result_t::msg, _upk_payload::payload, _upk_payload_types::repl_error, _upk_payload_types::repl_result, upk_repl_result_t::successful, _upk_payload::type, upk_clnet_serial_request(), upk_create_req_action(), upk_diag_verbosity, upk_error, upk_notice, upk_pkt_free(), UPK_REPL_ERROR, UPK_REPL_RESULT, and upk_warn.
Referenced by main().
void upk_clnet_req_disconnect (upk_conn_handle_meta_t * ctrl)
****************************************************************************************************************
References free(), upk_conn_handle_meta_p::head, _upk_payload::type, upk_clnet_serial_request(), upk_create_req_disconnect(), upk_debug1, upk_disconnect_handle(), upk_net_flush_closed_sockets(), upk_pkt_free(), UPK_REQ_DISCONNECT, and UPKLIST_HEAD.
Referenced by upk_clnet_ctrl_disconnect().
void upk_clnet_req_preamble (upk_conn_handle_meta_t * ctrl)
****************************************************************************************************************
References upk_repl_preamble_t::best_version, free(), upk_conn_handle_meta_p::head, _upk_conn_handle::last_pkt_data, _upk_payload::payload, _upk_payload_types::repl_preamble, _upk_payload::type, upk_clientid(), upk_clnet_serial_request(), upk_create_req_preamble(), upk_fatal, upk_notice, upk_pkt_free(), UPK_REPL_PREAMBLE, and _upk_conn_handle::version_id.
Referenced by upk_clnet_ctrl_connect().
bool upk_clnet_req_signal (upk_conn_handle_meta_t * ctrl, char * svc_id, upk_signal_t signal, bool should_signal_sid, bool should_signal_pgrp)
****************************************************************************************************************
References upk_repl_error_t::errlevel, free(), upk_conn_handle_meta_p::head, upk_repl_error_t::msg, upk_repl_result_t::msg, _upk_payload::payload, _upk_payload_types::repl_error, _upk_payload_types::repl_result, upk_repl_result_t::successful, _upk_payload::type, upk_clnet_serial_request(), upk_create_req_signal(), upk_diag_verbosity, upk_error, upk_notice, upk_pkt_free(), UPK_REPL_ERROR, UPK_REPL_RESULT, and upk_warn.
upk_svcinfo_t* upk_clnet_req_status (upk_conn_handle_meta_t * ctrl, char * svc_id, uint32_t restart_window_seconds)
****************************************************************************************************************
References calloc(), upk_repl_error_t::errlevel, free(), upk_conn_handle_meta_p::head, upk_repl_error_t::msg, _upk_payload::payload, _upk_payload_types::repl_error, _upk_payload_types::repl_svcinfo, upk_repl_svcinfo_t::svcinfo, _upk_payload::type, upk_clnet_serial_request(), upk_create_req_status(), upk_diag_verbosity, upk_error, upk_pkt_free(), UPK_REPL_ERROR, UPK_REPL_SVCINFO, and upk_warn.
upk_payload_t* upk_clnet_serial_request (upk_conn_handle_meta_t * ctrl, upk_packet_t * pkt)
****************************************************************************************************************
References calloc(), upk_conn_handle_meta_p::head, _upk_conn_handle::last_pkt_data, upk_net_block_until_msg(), upk_net_flush_closed_sockets(), upk_queue_packet(), and UPKLIST_HEAD.
Referenced by upk_clnet_req_action(), upk_clnet_req_disconnect(), upk_clnet_req_preamble(), upk_clnet_req_signal(), and upk_clnet_req_status().