upkeeper: libupkeeper/upkeeper/upk_protocol.c File Reference
libupkeeper/upkeeper/upk_protocol.c File Reference
#include "upk_protocol.h"
#include "upk_v0_protocol.h"
Functions
upk_packet_t * upk_create_pkt (void *payload, uint32_t payload_len, upk_pkttype_t pkttype, uint32_t proto_ver)
static uint32_t req_preamble_len (upk_req_preamble_t *preamble)
upk_packet_t * upk_create_req_preamble (upk_protocol_handle_t *handle, char *client_name)
upk_packet_t * upk_create_repl_preamble (upk_protocol_handle_t *handle, uint32_t best_version)
static void upk_free_payload (upk_packet_t *pkt)
void upk_pkt_free (upk_packet_t *pkt)
upk_packet_t * upk_create_req_seq_start (upk_protocol_handle_t *handle, upk_msgtype_t seq_type, uint32_t count)
upk_packet_t * upk_create_req_seq_end (upk_protocol_handle_t *handle, bool commit)
upk_packet_t * upk_create_req_action (upk_protocol_handle_t *handle, char *svc_id, char *action)
upk_packet_t * upk_create_req_signal (upk_protocol_handle_t *handle, char *svc_id, upk_signal_t signal, bool signal_sid, bool signal_pgrp)
upk_packet_t * upk_create_req_list (upk_protocol_handle_t *handle)
upk_packet_t * upk_create_req_status (upk_protocol_handle_t *handle, char *svc_id)
upk_packet_t * upk_create_req_subscribe (upk_protocol_handle_t *handle, char *svc_id, bool all_svcs)
upk_packet_t * upk_create_req_unsubscribe (upk_protocol_handle_t *handle, char *svc_id, bool all_svcs)
upk_packet_t * upk_create_req_disconnect (upk_protocol_handle_t *handle)
upk_packet_t * upk_create_repl_seq_start (upk_protocol_handle_t *handle, upk_msgtype_t seq_type, uint32_t count)
upk_packet_t * upk_create_repl_seq_end (upk_protocol_handle_t *handle, bool commit)
upk_packet_t * upk_create_repl_result (upk_protocol_handle_t *handle, char *msg, bool successful)
upk_packet_t * upk_create_repl_listing (upk_protocol_handle_t *handle, char *svc_id)
upk_packet_t * upk_create_repl_svcinfo (upk_protocol_handle_t *handle, char *svc_id, upk_svcinfo_t *svcinfo)
upk_packet_t * upk_create_repl_ack (upk_protocol_handle_t *handle)
upk_packet_t * upk_create_repl_error (upk_protocol_handle_t *handle, char *svc_id, upk_errno_t uerrno, char *errmsg, upk_errlevel_t errlvl)
upk_packet_t * upk_create_pub_publication (upk_protocol_handle_t *handle)
upk_packet_t * upk_create_pub_cancelation (upk_protocol_handle_t *handle)
upk_msgtype_t upk_get_msgtype (upk_packet_t *pkt)
size_t upk_get_msgsize (upk_msgtype_t type)
Function Documentation
static uint32_t req_preamble_len (upk_req_preamble_t * preamble) [inline, static]
References upk_req_preamble_t::client_name, and upk_req_preamble_t::client_name_len.
Referenced by upk_create_req_preamble().
static void upk_free_payload (upk_packet_t * pkt) [inline, static]
References upk_packet_t::payload, and v0_free_payload().
Referenced by upk_pkt_free().