upkeeper: libupkeeper/upkeeper/upk_v0_protocol.h File Reference
libupkeeper/upkeeper/upk_v0_protocol.h File Reference
#include "upk_protocol.h"
#include "upk_v0_protocol_structs.h"
Data Structures
struct v0_req_seq_start_t
struct v0_req_seq_end_t
struct v0_req_action_t
struct v0_req_signal_t
struct v0_req_list_t
struct v0_req_status_t
struct v0_req_subscribe_t
struct v0_req_unsubscribe_t
struct v0_req_disconnect_t
struct v0_repl_seq_start_t
struct v0_repl_seq_end_t
struct v0_repl_result_t
struct v0_repl_listing_t
struct v0_svcinfo_t
struct v0_repl_svcinfo_t
struct v0_repl_ack_t
struct v0_repl_error_t
struct v0_pub_publication_t
struct v0_pub_cancelation_t
Functions
upk_pkt_buf_t * v0_serialize_payload (upk_packet_t *pkt)
void * v0_deserialize_payload (upk_pkt_buf_t *UPK_BUF, upk_pkttype_t pkttype)
upk_packet_t * v0_create_req_seq_start (upk_msgtype_t msg_seq_type, uint32_t msg_seq_count)
upk_packet_t * v0_create_req_seq_end (bool commit)
upk_packet_t * v0_create_req_action (char *svc_id, char *action)
upk_packet_t * v0_create_req_signal (char *svc_id, upk_signal_t signal, bool signal_sid, bool signal_pgrp)
upk_packet_t * v0_create_req_list (void)
upk_packet_t * v0_create_req_status (char *svc_id)
upk_packet_t * v0_create_req_subscribe (char *svc_id, bool all_svcs)
upk_packet_t * v0_create_req_unsubscribe (char *svc_id, bool all_svcs)
upk_packet_t * v0_create_req_disconnect (void)
upk_packet_t * v0_create_repl_seq_start (upk_msgtype_t msg_seq_type, uint32_t msg_seq_count)
upk_packet_t * v0_create_repl_seq_end (bool commit)
upk_packet_t * v0_create_repl_result (char *msg, bool successful)
upk_packet_t * v0_create_repl_listing (char *svc_id)
upk_packet_t * v0_create_repl_svcinfo (char *svc_id, v0_svcinfo_t *svcinfo)
upk_packet_t * v0_create_repl_ack (void)
upk_packet_t * v0_create_repl_error (char *svc_id, upk_errno_t uerrno, char *errmsg, upk_errlevel_t errlvl)
upk_packet_t * v0_create_pub_publication (void)
upk_packet_t * v0_create_pub_cancelation (void)
void v0_free_payload (upk_packet_t *pkt)
Function Documentation
upk_packet_t* v0_create_pub_cancelation (void)
References PKT_PUBMSG, UPK_END_HELPER, UPK_INIT_HELPER, and UPK_PUB_CANCELATION.
Referenced by upk_create_pub_cancelation().
upk_packet_t* v0_create_pub_publication (void)
References PKT_PUBMSG, UPK_END_HELPER, UPK_INIT_HELPER, and UPK_PUB_PUBLICATION.
Referenced by upk_create_pub_publication().
upk_packet_t* v0_create_repl_ack (void)
References PKT_REPLY, UPK_END_HELPER, UPK_INIT_HELPER, and UPK_REPL_ACK.
Referenced by upk_create_repl_ack().
upk_packet_t* v0_create_repl_error (char * svc_id, upk_errno_t uerrno, char * errmsg, upk_errlevel_t errlvl)
References PKT_REPLY, UPK_END_HELPER, UPK_HELPER_ENUM, UPK_HELPER_STRING, UPK_INIT_HELPER, and UPK_REPL_ERROR.
Referenced by upk_create_repl_error().
upk_packet_t* v0_create_repl_listing (char * svc_id)
References PKT_REPLY, UPK_END_HELPER, UPK_HELPER_STRING, UPK_INIT_HELPER, and UPK_REPL_LISTING.
Referenced by upk_create_repl_listing().
upk_packet_t* v0_create_repl_result (char * msg, bool successful)
References PKT_REPLY, UPK_END_HELPER, UPK_HELPER_BOOL, UPK_HELPER_STRING, UPK_INIT_HELPER, and UPK_REPL_RESULT.
Referenced by upk_create_repl_result().
upk_packet_t* v0_create_repl_seq_end (bool commit)
References PKT_REPLY, UPK_END_HELPER, UPK_HELPER_BOOL, UPK_INIT_HELPER, and UPK_REPL_SEQ_END.
Referenced by upk_create_repl_seq_end().
upk_packet_t* v0_create_repl_seq_start (upk_msgtype_t msg_seq_type, uint32_t msg_seq_count)
References PKT_REPLY, UPK_END_HELPER, UPK_HELPER_ENUM, UPK_HELPER_UINT32, UPK_INIT_HELPER, and UPK_REPL_SEQ_START.
Referenced by upk_create_repl_seq_start().
upk_packet_t* v0_create_repl_svcinfo (char * svc_id, v0_svcinfo_t * svcinfo)
References get_svcinfo_len(), PKT_REPLY, strnlen(), UPK_DATA, UPK_DATA_LEN, UPK_END_HELPER, UPK_HELPER_STRING, UPK_HELPER_UINT32_EXPLICIT, UPK_INIT_HELPER, UPK_MAX_STRING_LEN, UPK_REPL_SVCINFO, and UPK_STRING_LENGTH.
Referenced by upk_create_repl_svcinfo().
upk_packet_t* v0_create_req_action (char * svc_id, char * action)
References PKT_REQUEST, UPK_END_HELPER, UPK_HELPER_STRING, UPK_INIT_HELPER, and UPK_REQ_ACTION.
Referenced by upk_create_req_action().
upk_packet_t* v0_create_req_disconnect (void)
References PKT_REQUEST, UPK_END_HELPER, UPK_INIT_HELPER, and UPK_REQ_DISCONNECT.
Referenced by upk_create_req_disconnect().
upk_packet_t* v0_create_req_list (void)
References PKT_REQUEST, UPK_END_HELPER, UPK_INIT_HELPER, and UPK_REQ_LIST.
Referenced by upk_create_req_list().
upk_packet_t* v0_create_req_seq_end (bool commit)
References PKT_REQUEST, UPK_END_HELPER, UPK_HELPER_BOOL, UPK_INIT_HELPER, and UPK_REQ_SEQ_END.
Referenced by upk_create_req_seq_end().
upk_packet_t* v0_create_req_seq_start (upk_msgtype_t msg_seq_type, uint32_t msg_seq_count)
References PKT_REQUEST, UPK_END_HELPER, UPK_HELPER_ENUM, UPK_HELPER_UINT32, UPK_INIT_HELPER, and UPK_REQ_SEQ_START.
Referenced by upk_create_req_seq_start().
upk_packet_t* v0_create_req_signal (char * svc_id, upk_signal_t signal, bool signal_sid, bool signal_pgrp)
References PKT_REQUEST, UPK_END_HELPER, UPK_HELPER_BOOL, UPK_HELPER_ENUM, UPK_HELPER_STRING, UPK_INIT_HELPER, and UPK_REQ_SIGNAL.
Referenced by upk_create_req_signal().
upk_packet_t* v0_create_req_status (char * svc_id)
References PKT_REQUEST, UPK_END_HELPER, UPK_HELPER_STRING, UPK_INIT_HELPER, and UPK_REQ_STATUS.
Referenced by upk_create_req_status().
upk_packet_t* v0_create_req_subscribe (char * svc_id, bool all_svcs)
References PKT_REQUEST, UPK_END_HELPER, UPK_HELPER_BOOL, UPK_HELPER_STRING, UPK_INIT_HELPER, and UPK_REQ_SUBSCRIBE.
Referenced by upk_create_req_subscribe().
upk_packet_t* v0_create_req_unsubscribe (char * svc_id, bool all_svcs)
References PKT_REQUEST, UPK_END_HELPER, UPK_HELPER_BOOL, UPK_HELPER_STRING, UPK_INIT_HELPER, and UPK_REQ_UNSUBSCRIBE.
Referenced by upk_create_req_unsubscribe().
void* v0_deserialize_payload (upk_pkt_buf_t * UPK_BUF, upk_pkttype_t pkttype)
References deserial_pkt_dispatch, and UPK_BUF.
Referenced by upk_deserialize_payload().
void v0_free_payload (upk_packet_t * pkt)
References free_pkt_dispatch, upk_packet_t::payload, and upk_packet_t::pkttype.
Referenced by upk_free_payload().
upk_pkt_buf_t* v0_serialize_payload (upk_packet_t * pkt)
References upk_packet_t::payload, upk_packet_t::payload_len, upk_packet_t::pkttype, and serial_pkt_dispatch.
Referenced by upk_serialize_payload().