upkeeper: libupkeeper/tests/upk_protocol_serializers.c File Reference
libupkeeper/tests/upk_protocol_serializers.c File Reference
#include <check.h>
#include <upkeeper/upk_protocol.h>
#include "v0_protocol_generic_value_checks.inc.c"
Defines
#define NAME_TO_FUNC(A) upk_create_ ## A
#define NAME_TO_TYPE(A) upk_ ## A ## _t
#define TEST_SETUP(NAME,...)
#define TEST_SETUP_NOARGS(NAME)
#define TEST_TEARDOWN
#define v0_svcinfo_t upk_svcinfo_t
#define CHECK_PREAMBLE
Functions
Suite * upk_proto_serializers_suite (void)
int main (void)
Define Documentation
#define CHECK_PREAMBLE
#define NAME_TO_FUNC (A) upk_create_ ## A
#define NAME_TO_TYPE (A) upk_ ## A ## _t
#define TEST_SETUP (NAME, ...)
Value:
upk_packet_t *pkt = NULL; \
    NAME_TO_TYPE(NAME) t = { 0 }; \
    upk_protocol_handle_t handle = { 0 }; \
    pkt = NAME_TO_FUNC(NAME)(&handle,__VA_ARGS__); \
    upk_pkt_buf_t * buf = upk_serialize_packet(pkt); \
    upk_pkt_free(pkt); \
    pkt = upk_deserialize_packet(buf); \
    t = *((NAME_TO_TYPE(NAME) *) pkt->payload)
#define TEST_SETUP_NOARGS (NAME)
Value:
upk_packet_t *pkt = NULL; \
    NAME_TO_TYPE(NAME) t = { 0 }; \
    upk_protocol_handle_t handle = { 0 }; \
    pkt = NAME_TO_FUNC(NAME)(&handle); \
    upk_pkt_buf_t * buf = upk_serialize_packet(pkt); \
    upk_pkt_free(pkt); \
    pkt = upk_deserialize_packet(buf); \
    t = *((NAME_TO_TYPE(NAME) *) pkt->payload)
#define TEST_TEARDOWN
Value:
upk_pkt_free(pkt); \
    free(buf)
#define v0_svcinfo_t upk_svcinfo_t
Function Documentation
int main (void)
References suite(), and upk_proto_serializers_suite().
Suite* upk_proto_serializers_suite (void)
References suite(), v0_proto_pubmsgs(), v0_proto_replies(), and v0_proto_requests().
Referenced by main().