upkeeper: clients/upk_reload.c File Reference
clients/upk_reload.c File Reference
#include <upkeeper.h>
#include <sys/un.h>
#include <stdio.h>
Functions
int main (int argc, char **argv, char **envp)
Function Documentation
int main (int argc, char ** argv, char ** envp)
References _upk_controller_config::controller_socket, upk_packet_t::payload, upk_packet_t::payload_len, upk_create_req_action(), upk_ctrl_load_config(), upk_debug1, upk_deserialize_packet(), upk_diag_verbosity, UPK_DIAGLVL_DEBUG1, upk_fatal, UPK_MAX_PACKET_SIZE, upk_notice, upk_pkt_free(), upk_runtime_configuration, upk_serialize_packet(), upk_verbose, and upk_packet_t::version_id.