upkeeper: libupkeeper/upkeeper/upk_compat.h File Reference
libupkeeper/upkeeper/upk_compat.h File Reference
#include "upkeeper_config.h"
#include <sys/types.h>
Defines
#define _GNU_SOURCE
#define c_isxdigit(c) ((c >= '0' && c <= '9') || (c >= 'A' && c <= 'F') || (c >= 'a' && c <= 'f'))
Functions
size_t strnlen (const char *restrict string, size_t maxlen)
Define Documentation
#define _GNU_SOURCE
#define c_isxdigit (c) ((c >= '0' && c <= '9') || (c >= 'A' && c <= 'F') || (c >= 'a' && c <= 'f'))
Referenced by is_valid_upk_uuid_string().
Function Documentation
size_t strnlen (const char *restrict string, size_t maxlen)
Referenced by buddy_init_paths(), opt_parse(), upk_config_loadfile(), upk_create_req_preamble(), upk_json_append_string(), upk_json_output_array_handler(), upk_json_output_object_handler(), upk_load_runtime_services(), upk_svcconf_string_handler(), and v0_create_repl_svcinfo().