upkeeper: libupkeeper/upkeeper/upk_util.c File Reference
libupkeeper/upkeeper/upk_util.c File Reference
#include "upk_include.h"
#include <stdio.h>
Functions
bool upk_numeric_string (const char *string, long *num)
bool upk_boolean_string (const char *string, bool *val)
void upk_replace_string (char **haystack, const char *needle, const char *repl)
struct timeval upk_double_to_timeval (long double r)
int upk_rm_rf (char *start_path)
int upk_mkdir_p (const char *path)
create a directory and any path components leading up to it.
Function Documentation
bool upk_boolean_string (const char * string, bool * val)
***************************************************************************
References upk_numeric_string().
struct timeval upk_double_to_timeval (long double r) [read]
***************************************************************************
Referenced by upk_net_event_dispatcher().
int upk_mkdir_p (const char * path)
create a directory and any path components leading up to it.
***************************************************************************
Parameters:
[in] path directory to create.
Returns:
the number of directories successfully created.
References calloc(), dirname(), stat(), _upk_stringlist::string, _upk_stringlist_meta_p::thisp, UPK_MAX_STRING_LEN, upk_warn, UPKLIST_FOREACH, UPKLIST_FREE, and UPKLIST_PREPEND.
Referenced by upk_state_init().
bool upk_numeric_string (const char * string, long * num)
***************************************************************************
Referenced by main(), and upk_boolean_string().
void upk_replace_string (char ** haystack, const char * needle, const char * repl)
***************************************************************************
References realloc().
Referenced by START_TEST(), and upk_finalize_svc_desc().
int upk_rm_rf (char * start_path)
***************************************************************************
References closedir(), opendir(), readdir(), stat::st_mode, stat(), UPK_MAX_PATH_LEN, upk_rm_rf(), and upk_warn.
Referenced by handle_buddies(), main(), remove_buddy_statedir(), and upk_rm_rf().