upkeeper: libupkeeper/upkeeper/upk_protocol_serializer.c File Reference
libupkeeper/upkeeper/upk_protocol_serializer.c File Reference
#include "upk_protocol.h"
#include "upk_v0_protocol.h"
#include "upk_error.h"
#include "upk_crc32.h"
Defines
#define UPK_MSG_IDENTIFIER_TYPEDEF upk_msgtype_t
#define UPK_MSG_IDENTIFIER msgtype
#define UPK_MSG_IDENTIFIER_TYPEDEF upk_pkttype_t
#define UPK_MSG_IDENTIFIER pkttype
Functions
void * upk_deserialize_req_preamble (upk_pkt_buf_t *UPK_BUF)
upk_pkt_buf_t * upk_serialize_req_preamble (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
void * upk_deserialize_repl_preamble (upk_pkt_buf_t *UPK_BUF)
upk_pkt_buf_t * upk_serialize_repl_preamble (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)
static void * upk_deserialize_payload (upk_pkt_buf_t *payload_buf, upk_pkttype_t pkttype, uint32_t version_id)
static upk_pkt_buf_t * upk_serialize_payload (upk_packet_t *pkt)
upk_packet_t * upk_deserialize_packet (upk_pkt_buf_t *UPK_BUF)
upk_pkt_buf_t * upk_serialize_packet (upk_packet_t *UPK_DATA_PTR)
Variables
upk_pkttype_t upk_pkt_proto_limit []
upk_msgtype_t upk_req_proto_limit []
upk_msgtype_t upk_repl_proto_limit []
upk_msgtype_t upk_pub_proto_limit []
Define Documentation
#define UPK_MSG_IDENTIFIER msgtype
#define UPK_MSG_IDENTIFIER pkttype
#define UPK_MSG_IDENTIFIER_TYPEDEF upk_pkttype_t
#define UPK_MSG_IDENTIFIER_TYPEDEF upk_msgtype_t
Function Documentation
static void* upk_deserialize_payload (upk_pkt_buf_t * payload_buf, upk_pkttype_t pkttype, uint32_t version_id) [inline, static]
References v0_deserialize_payload().
Referenced by upk_deserialize_packet().
static upk_pkt_buf_t* upk_serialize_payload (upk_packet_t * pkt) [inline, static]
References v0_serialize_payload(), and upk_packet_t::version_id.
Referenced by upk_serialize_packet().
Variable Documentation
upk_pkttype_t upk_pkt_proto_limit[]
Initial value:
 {
    PKT_V0_PROTO_LIMIT,
}
Referenced by upk_deserialize_packet().
upk_msgtype_t upk_pub_proto_limit[]
Initial value:
 {
    UPK_PUB_V0_PROTO_LIMIT,
}
upk_msgtype_t upk_repl_proto_limit[]
Initial value:
 {
    UPK_REPL_V0_PROTO_LIMIT,
}
upk_msgtype_t upk_req_proto_limit[]
Initial value:
 {
    UPK_REQ_V0_PROTO_LIMIT,
}