upkeeper: clients/upk.c File Reference
clients/upk.c File Reference
#include <upkeeper.h>
#include <upkeeper/upk_json.h>
#include <getopt.h>
Functions
int main (int argc, char **argv, char **envp)
Variables
static struct option longopts []
Function Documentation
int main (int argc, char ** argv, char ** envp)
References calloc(), _upk_svc_desc::ExecReload, _upk_svc_desc::ExecStart, _upk_svc_desc::ExecStop, free(), _upk_json_data_output_options::indent, _upk_svc_desc::InitialState, _upk_svc_desc::KillTimeout, _upk_svc_desc::LongDescription, longopts, _upk_svc_desc::MaxConsecutiveFailures, _upk_svc_desc::Name, _upk_svc_desc::Package, _upk_json_data_output_options::pad, _upk_svc_desc::PreferBuddyStateForRunning, _upk_svc_desc::PreferBuddyStateForStopped, _upk_svc_desc::ReconnectRetries, _upk_svc_desc::ReloadScript, _upk_svc_desc::RingbufferSize, _upk_json_data_output_options::sep, _upk_svc_desc::SetGID, _upk_svc_desc::SetUID, _upk_svc_desc::ShortDescription, _upk_svc_desc::StartPriority, _upk_svc_desc::StartScript, _upk_svc_desc::StopScript, _upk_json_data_output_options::suppress_null_values, upk_boolean_string(), upk_ctrl_free_config(), upk_ctrl_load_config(), upk_default_configuration_str, upk_finalize_svc_desc(), upk_json_serialize_svc_config(), upk_numeric_string(), UPK_STATE_RUNNING, UPK_STATE_STOPPED, upk_string_to_uuid(), upk_svc_desc_clear(), upk_svc_desc_free(), _upk_svc_desc::UserMaxRestarts, _upk_svc_desc::UserRateLimit, _upk_svc_desc::UserRestartWindow, and _upk_svc_desc::UUID.
Variable Documentation
struct option longopts[] [static]
Referenced by main().