upkeeper: libupkeeper/upkeeper/upk_crc32.c File Reference
libupkeeper/upkeeper/upk_crc32.c File Reference
#include "upk_crc32.h"
Functions
void upk_create_crc32_table (uint32_t crc_table[256])
uint32_t upk_crc32 (unsigned char *block, uint32_t len)
bool upk_verify_crc32 (unsigned char *block, uint32_t crc32, uint32_t len)
Function Documentation
uint32_t upk_crc32 (unsigned char * block, uint32_t len)
Referenced by upk_db_upsert_options(), upk_serialize_packet(), and upk_verify_crc32().
void upk_create_crc32_table (uint32_t crc_table[256])
bool upk_verify_crc32 (unsigned char * block, uint32_t crc32, uint32_t len)
References upk_crc32().
Referenced by upk_deserialize_packet().