upkeeper: libupkeeper/upkeeper/upk_network.c File Reference
libupkeeper/upkeeper/upk_network.c File Reference
#include "upk_include.h"
Functions
static int upk_build_fd_sets (fd_set *readfds, fd_set *writefds, fd_set *exceptfds, upk_conn_handle_meta_t *handles)
static void upk_partitioned_userdata_free (void *ptr)
upk_conn_handle_meta_t * upk_net_conn_handle_init (void *userdata, void(*userdata_free_func)(void *ptr))
upk_net_gstate_t * upk_net_get_gstate (upk_conn_handle_meta_t *handles)
void * upk_net_get_userdata (upk_conn_handle_meta_t *handles)
void upk_net_add_socket_handle (upk_conn_handle_meta_t *handles, int fd, upk_net_callback_t pkt_callback)
void upk_net_flush_closed_sockets (upk_conn_handle_meta_t *handles)
void upk_net_event_dispatcher (upk_conn_handle_meta_t *handles, double sel_ival)
int upk_net_block_until_msg (upk_conn_handle_meta_t *handles, double sel_ival, struct timeval *timeout)
static void upk_call_received_packet_callbacks (upk_conn_handle_meta_t *handles, upk_packet_t *pkt)
void upk_disconnect_handle (upk_conn_handle_meta_t *handles)
close the connection on a given handle and remove the handle from the list of connection handles.
void upk_net_shutdown_callback (upk_conn_handle_meta_t *handles, upk_payload_t *msg)
void upk_queue_packet (upk_conn_handle_t *handle, upk_packet_t *pkt, upk_net_callback_t after_write_callback, upk_net_callback_t set_after_read_callback)
queue a packet to send, will be sent via upk_write_packet.
void upk_write_packets (upk_conn_handle_meta_t *handles)
write packets from queue async and nonblocking.
void upk_read_packets (upk_conn_handle_meta_t *handles)
retry socket connection, pausing between each retry.
int upk_domain_socket_connect (const char *sockpath)
make unix-domain socket connection.
Function Documentation
static int upk_build_fd_sets (fd_set * readfds, fd_set * writefds, fd_set * exceptfds, upk_conn_handle_meta_t * handles) [inline, static]
References UPKLIST_FOREACH.
Referenced by upk_net_event_dispatcher().
static void upk_call_received_packet_callbacks (upk_conn_handle_meta_t * handles, upk_packet_t * pkt) [static]
References _upk_conn_handle::after_read_callback, _upk_net_gstate::callback_stack, _upk_conn_handle::last_pkt_data, upk_packet_t::payload, _upk_payload::payload, _upk_payload::type, upk_get_msgsize(), upk_get_msgtype(), UPK_MSGTYPE_IDX, upk_net_cb_stk_meta_t, and upk_net_get_gstate().
Referenced by upk_read_packets().
upk_net_gstate_t* upk_net_get_gstate (upk_conn_handle_meta_t * handles)
References _upklist_userdata_state_partition::gstate, and _upklist_userdata_state_partition::userdata.
Referenced by upk_call_received_packet_callbacks(), upk_net_add_socket_handle(), upk_net_event_dispatcher(), and upk_write_packets().
void* upk_net_get_userdata (upk_conn_handle_meta_t * handles)
References _upklist_userdata_state_partition::userdata.
Referenced by upk_net_add_socket_handle().
static void upk_partitioned_userdata_free (void * ptr) [static]
References _upk_net_gstate::callback_stack, _upklist_userdata_state_partition::gstate, UPKLIST_FREE, _upklist_userdata_state_partition::userdata, and _upklist_userdata_state_partition::userdata_free_func.
Referenced by upk_net_conn_handle_init().