upkeeper: clients/upk_start.c File Reference
clients/upk_start.c File Reference
#include <upkeeper.h>
#include <sys/un.h>
#include <stdio.h>
Functions
int main (int argc, char **argv, char **envp)
Function Documentation
int main (int argc, char ** argv, char ** envp)
References upk_conn_handle_meta_p::thisp, upk_clnet_ctrl_connect(), upk_clnet_ctrl_disconnect(), upk_clnet_req_action(), upk_ctrl_free_config(), upk_ctrl_load_config(), upk_diag_verbosity, UPK_DIAGLVL_DEBUG1, and upk_fatal.