upkeeper: clients/upk_start.b.c File Reference
clients/upk_start.b.c File Reference
#include <upkeeper.h>
#include <sys/un.h>
#include <stdio.h>
Functions
void received_packet_callback (upk_conn_handle_meta_t *controller, upk_payload_t *msg)
int main (int argc, char **argv, char **envp)
Function Documentation
int main (int argc, char ** argv, char ** envp)
References _upk_controller_config::controller_socket, received_packet_callback(), upk_conn_handle_meta_t, upk_create_req_action(), upk_ctrl_load_config(), upk_diag_verbosity, UPK_DIAGLVL_DEBUG1, upk_fatal, upk_net_add_socket_handle(), upk_net_event_dispatcher(), upk_pkt_free(), upk_queue_packet(), upk_runtime_configuration, and upk_verbose.
void received_packet_callback (upk_conn_handle_meta_t * controller, upk_payload_t * msg)
References _upk_payload::payload, _upk_payload_types::repl_result, _upk_payload::type, upk_notice, and UPK_REPL_RESULT.
Referenced by main().