upkeeper: libupkeeper/upkeeper/upk_json.c File Reference
libupkeeper/upkeeper/upk_json.c File Reference
#include "upk_json.h"
#include <stdarg.h>
Data Structures
union _upk_stream_string
struct _upk_json_output_data
struct upk_json_obj_iter
Typedefs
typedef union _upk_stream_string upk_stream_string_t
typedef struct
_upk_json_output_data upk_json_output_data_t
typedef struct upk_json_obj_iter upk_json_obj_iter_t
Enumerations
enum upk_json_output_type_t { data_type_stream, data_type_string }
Functions
static void upk_json_print_indent (upk_json_stack_meta_t *meta, upk_json_output_data_t *data)
static void upk_json_output_null_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_json_output_bool_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_json_output_double_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_json_output_int_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_json_output_string_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_json_output_array_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_json_output_object_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_json_output_after_json_obj_pop_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_json_output_after_json_array_pop_handler (upk_json_stack_meta_t *meta, void *data, char *key, upk_json_val_t v)
static void upk_json_value (upk_json_stack_meta_t *meta, char *key, struct json_object *jobj)
static void upk_json_parse_array (upk_json_stack_meta_t *meta, char *key, struct json_object *jarray)
static void _upk_json_parse_node (upk_json_stack_meta_t *meta, char *key, struct json_object *obj)
static void upk_json_append_string (upk_json_output_data_t *data, char *string)
static void upk_output_json_string (upk_json_output_data_t *data, char *fmt,...)
void upk_json_stack_pop (upk_json_stack_meta_t *meta)
void upk_json_stack_push (upk_json_stack_meta_t *meta, upk_json_stack_node_t *node)
static char * upk_json_unescape_forwardslash (char *str)
static void upk_json_parse_obj (upk_json_stack_meta_t *meta, char *key, struct json_object *jobj)
void upk_json_parse_node (upk_json_stack_meta_t *meta, char *key, struct json_object *obj)
struct json_object * upk_json_parse_string (const char *string)
static void upk_json_obj_serializer (struct json_object *obj, upk_json_output_data_t *data)
char * upk_json_obj_to_string (struct json_object *obj, upk_json_data_output_opts_t opts)
void upk_json_obj_to_stream (struct json_object *obj, FILE *stream, upk_json_data_output_opts_t opts)
Typedef Documentation
typedef struct upk_json_obj_iter upk_json_obj_iter_t
typedef struct _upk_json_output_data upk_json_output_data_t
typedef union _upk_stream_string upk_stream_string_t
Enumeration Type Documentation
enum upk_json_output_type_t
Enumerator:
data_type_stream
data_type_string
Function Documentation
static void _upk_json_parse_node (upk_json_stack_meta_t * meta, char * key, struct json_object * obj) [inline, static]
References _upk_json_type::obj, _upk_json_type::type, upk_json_parse_array(), upk_json_parse_obj(), upk_json_stack_pop(), upk_json_value(), and _upk_json_type::val.
Referenced by upk_json_parse_array(), upk_json_parse_node(), and upk_json_parse_obj().
static void upk_json_append_string (upk_json_output_data_t * data, char * string) [inline, static]
References calloc(), _upk_json_output_data::d, _upk_stream_string::len, _upk_stream_string::p, realloc(), _upk_stream_string::str, strnlen(), and UPK_MAX_STRING_LEN.
Referenced by upk_output_json_string().
static void upk_json_obj_serializer (struct json_object * obj, upk_json_output_data_t * data) [static]
References calloc(), _upk_json_stack_node::data, upk_json_output_after_json_array_pop_handler(), upk_json_output_after_json_obj_pop_handler(), upk_json_output_array_handler(), upk_json_output_bool_handler(), upk_json_output_double_handler(), upk_json_output_int_handler(), upk_json_output_null_handler(), upk_json_output_object_handler(), upk_json_output_string_handler(), upk_json_parse_node(), upk_json_stack_meta_t, upk_json_stack_push(), and UPKLIST_FREE.
Referenced by upk_json_obj_to_stream(), and upk_json_obj_to_string().
void upk_json_obj_to_stream (struct json_object * obj, FILE * stream, upk_json_data_output_opts_t opts)
References data_type_stream, _upk_json_output_data::type, and upk_json_obj_serializer().
char* upk_json_obj_to_string (struct json_object * obj, upk_json_data_output_opts_t opts)
References _upk_json_output_data::d, data_type_string, _upk_stream_string::p, _upk_stream_string::str, _upk_json_output_data::type, and upk_json_obj_serializer().
Referenced by upk_json_serialize_svc_config().
static void upk_json_output_after_json_array_pop_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_json_output_data::opts, _upk_json_data_output_options::sep, upk_json_print_indent(), and upk_output_json_string().
Referenced by upk_json_obj_serializer().
static void upk_json_output_after_json_obj_pop_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_json_output_data::opts, _upk_json_data_output_options::sep, upk_json_print_indent(), and upk_output_json_string().
Referenced by upk_json_obj_serializer().
static void upk_json_output_array_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_json_output_data::opts, _upk_json_data_output_options::pad, _upk_json_data_output_options::sep, strnlen(), upk_json_print_indent(), upk_json_stack_push(), UPK_MAX_STRING_LEN, and upk_output_json_string().
Referenced by upk_json_obj_serializer().
static void upk_json_output_bool_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_json_type::bl, _upk_json_output_data::opts, _upk_json_data_output_options::pad, _upk_json_data_output_options::sep, upk_json_print_indent(), upk_output_json_string(), and _upk_json_type::val.
Referenced by upk_json_obj_serializer().
static void upk_json_output_double_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_json_type::dbl, _upk_json_output_data::opts, _upk_json_data_output_options::pad, _upk_json_data_output_options::sep, upk_json_print_indent(), upk_output_json_string(), and _upk_json_type::val.
Referenced by upk_json_obj_serializer().
static void upk_json_output_int_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_json_type::i, _upk_json_output_data::opts, _upk_json_data_output_options::pad, _upk_json_data_output_options::sep, upk_json_print_indent(), upk_output_json_string(), and _upk_json_type::val.
Referenced by upk_json_obj_serializer().
static void upk_json_output_null_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_json_output_data::opts, _upk_json_data_output_options::pad, _upk_json_data_output_options::sep, _upk_json_data_output_options::suppress_null_values, upk_json_print_indent(), and upk_output_json_string().
Referenced by upk_json_obj_serializer().
static void upk_json_output_object_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_json_output_data::opts, _upk_json_data_output_options::pad, _upk_json_data_output_options::sep, strnlen(), upk_json_print_indent(), upk_json_stack_push(), UPK_MAX_STRING_LEN, and upk_output_json_string().
Referenced by upk_json_obj_serializer().
static void upk_json_output_string_handler (upk_json_stack_meta_t * meta, void * data, char * key, upk_json_val_t v) [static]
References _upk_json_string::esc_str, _upk_json_output_data::opts, _upk_json_data_output_options::pad, _upk_json_data_output_options::sep, _upk_json_type::str, upk_json_print_indent(), upk_output_json_string(), and _upk_json_type::val.
Referenced by upk_json_obj_serializer().
static void upk_json_parse_array (upk_json_stack_meta_t * meta, char * key, struct json_object * jarray) [inline, static]
References _upk_json_parse_node().
Referenced by _upk_json_parse_node().
void upk_json_parse_node (upk_json_stack_meta_t * meta, char * key, struct json_object * obj)
References _upk_json_parse_node().
Referenced by upk_ctrlconf_pack(), upk_json_obj_serializer(), and upk_svcconf_pack().
static void upk_json_parse_obj (upk_json_stack_meta_t * meta, char * key, struct json_object * jobj) [inline, static]
References _upk_json_parse_node(), upk_json_obj_iter::key, and upk_json_obj_iter::val.
Referenced by _upk_json_parse_node().
struct json_object* upk_json_parse_string (const char * string) [read]
References IF_UPK_ERROR, UPK_ERR_INIT, UPK_FUNC_ASSERT_MSG, and UPK_JSON_PARSE_ERROR.
Referenced by main(), upk_ctrlconf_pack(), and upk_svcconf_pack().
static void upk_json_print_indent (upk_json_stack_meta_t * meta, upk_json_output_data_t * data) [inline, static]
References _upk_json_data_output_options::indent, _upk_json_output_data::opts, and upk_output_json_string().
Referenced by upk_json_output_after_json_array_pop_handler(), upk_json_output_after_json_obj_pop_handler(), upk_json_output_array_handler(), upk_json_output_bool_handler(), upk_json_output_double_handler(), upk_json_output_int_handler(), upk_json_output_null_handler(), upk_json_output_object_handler(), and upk_json_output_string_handler().
void upk_json_stack_pop (upk_json_stack_meta_t * meta)
References UPKLIST_FOREACH, and UPKLIST_UNLINK.
Referenced by _upk_json_parse_node().
void upk_json_stack_push (upk_json_stack_meta_t * meta, upk_json_stack_node_t * node)
References UPKLIST_PREPEND.
Referenced by upk_ctrlconf_object_handler(), upk_ctrlconf_pack(), upk_ctrlconf_toplvl_obj(), upk_json_obj_serializer(), upk_json_output_array_handler(), upk_json_output_object_handler(), upk_svcconf_array_handler(), upk_svcconf_nested_object_handler(), upk_svcconf_object_handler(), upk_svcconf_pack(), and upk_svcconf_toplvl_obj().
static char* upk_json_unescape_forwardslash (char * str) [inline, static]
Referenced by upk_json_value().
static void upk_json_value (upk_json_stack_meta_t * meta, char * key, struct json_object * jobj) [inline, static]
References _upk_json_type::bl, _upk_json_string::c_str, _upk_json_type::dbl, _upk_json_string::esc_str, _upk_json_type::i, _upk_json_type::obj, _upk_json_type::str, _upk_json_type::type, upk_json_unescape_forwardslash(), and _upk_json_type::val.
Referenced by _upk_json_parse_node().
static void upk_output_json_string (upk_json_output_data_t * data, char * fmt, ...) [inline, static]
References _upk_json_output_data::d, data_type_stream, data_type_string, _upk_stream_string::file, _upk_json_output_data::type, upk_json_append_string(), and UPK_MAX_STRING_LEN.
Referenced by upk_json_output_after_json_array_pop_handler(), upk_json_output_after_json_obj_pop_handler(), upk_json_output_array_handler(), upk_json_output_bool_handler(), upk_json_output_double_handler(), upk_json_output_int_handler(), upk_json_output_null_handler(), upk_json_output_object_handler(), upk_json_output_string_handler(), and upk_json_print_indent().