upkeeper: libupkeeper/tests/util.c File Reference
libupkeeper/tests/util.c File Reference
#include <check.h>
#include <upkeeper.h>
Defines
#define TESTCASE_NAME "util"
#define SUITE_NAME "util"
Functions
START_TEST (test_replace_larger)
START_TEST (test_replace_smaller)
TCase * test_tcase (void)
Suite * test_suite (void)
int main (void)
Variables
END_TEST
Define Documentation
#define SUITE_NAME "util"
Referenced by test_suite().
#define TESTCASE_NAME "util"
Referenced by test_tcase().
Function Documentation
int main (void)
References suite(), and test_suite().
START_TEST (test_replace_smaller)
References calloc(), free(), and upk_replace_string().
START_TEST (test_replace_larger)
References calloc(), free(), and upk_replace_string().
Suite* test_suite (void)
References suite(), SUITE_NAME, and test_tcase().
Referenced by main().
TCase* test_tcase (void)
References tcase(), and TESTCASE_NAME.
Referenced by test_suite().
Variable Documentation
END_TEST