upkeeper: libupkeeper/tests/v0_protocol_generic_value_checks.inc.c File Reference
libupkeeper/tests/v0_protocol_generic_value_checks.inc.c File Reference
Defines
#define _stringify(A) #A
#define stringify(A) _stringify(A)
#define _create_fmt(FMT) ": got: " stringify(FMT) ", wanted: " stringify(FMT)
#define check_isequal(A, B, FMT) fail_unless((A == B), stringify(A) _create_fmt(FMT), A, B)
#define check_isequal_str(A, B, FMT) fail_unless(strcmp(A, B) == 0, stringify(A) _create_fmt(FMT), A, B)
#define action_name "svcinfo last action name"
#define service_name "svcinfo service"
#define service_name "service on which error is being reported"
#define errmsg "Some helpful error message telling what happened"
Functions
START_TEST (test_proto_req_seq_start)
START_TEST (test_proto_req_seq_end)
START_TEST (test_proto_req_action)
START_TEST (test_proto_req_signal)
START_TEST (test_proto_req_list)
START_TEST (test_proto_req_status)
START_TEST (test_proto_req_subscribe)
START_TEST (test_proto_req_unsubscribe)
START_TEST (test_proto_req_disconnect)
START_TEST (test_proto_repl_seq_start)
START_TEST (test_proto_repl_seq_end)
START_TEST (test_proto_repl_result)
START_TEST (test_proto_repl_listing)
START_TEST (test_proto_repl_svcinfo)
START_TEST (test_proto_repl_ack)
START_TEST (test_proto_repl_error)
START_TEST (test_proto_pub_publication)
START_TEST (test_proto_pub_cancelation)
TCase * v0_proto_requests (void)
TCase * v0_proto_replies (void)
TCase * v0_proto_pubmsgs (void)
Variables
END_TEST
Define Documentation
#define _create_fmt (FMT) ": got: " stringify(FMT) ", wanted: " stringify(FMT)
#define _stringify (A) #A
#define action_name "svcinfo last action name"
Referenced by START_TEST().
#define check_isequal (A, B, FMT) fail_unless((A == B), stringify(A) _create_fmt(FMT), A, B)
Referenced by START_TEST().
#define check_isequal_str (A, B, FMT) fail_unless(strcmp(A, B) == 0, stringify(A) _create_fmt(FMT), A, B)
#define errmsg "Some helpful error message telling what happened"
Referenced by START_TEST().
#define service_name "svcinfo service"
Referenced by START_TEST().
#define service_name "service on which error is being reported"
#define stringify (A) _stringify(A)
Function Documentation
START_TEST (test_proto_req_seq_start)
References PKT_REQUEST, TEST_SETUP, TEST_TEARDOWN, UPK_REQ_LIST, and UPK_REQ_SEQ_START.
START_TEST (test_proto_req_seq_end)
References PKT_REQUEST, TEST_SETUP, TEST_TEARDOWN, and UPK_REQ_SEQ_END.
START_TEST (test_proto_req_signal)
References PKT_REQUEST, TEST_SETUP, TEST_TEARDOWN, UPK_REQ_SIGNAL, and UPK_SIG_KILL.
START_TEST (test_proto_req_unsubscribe)
References PKT_REQUEST, TEST_SETUP, TEST_TEARDOWN, and UPK_REQ_UNSUBSCRIBE.
START_TEST (test_proto_pub_cancelation)
References PKT_PUBMSG, TEST_SETUP_NOARGS, TEST_TEARDOWN, and UPK_PUB_CANCELATION.
START_TEST (test_proto_repl_error)
References check_isequal, errmsg, PKT_REPLY, service_name, TEST_SETUP, TEST_TEARDOWN, UPK_ERR_UNKNOWN, UPK_ERRLVL_ERROR, and UPK_REPL_ERROR.
START_TEST (test_proto_pub_publication)
References PKT_PUBMSG, TEST_SETUP_NOARGS, TEST_TEARDOWN, and UPK_PUB_PUBLICATION.
START_TEST (test_proto_repl_ack)
References PKT_REPLY, TEST_SETUP_NOARGS, TEST_TEARDOWN, and UPK_REPL_ACK.
START_TEST (test_proto_repl_svcinfo)
References action_name, v0_svcinfo_t::last_action_time, PKT_REPLY, service_name, TEST_SETUP, TEST_TEARDOWN, UPK_REPL_SVCINFO, UPK_SIG_KILL, UPK_STATE_RUNNING, and UPK_STATE_SHUTDOWN.
START_TEST (test_proto_repl_listing)
References PKT_REPLY, TEST_SETUP, TEST_TEARDOWN, and UPK_REPL_LISTING.
START_TEST (test_proto_repl_result)
References PKT_REPLY, TEST_SETUP, TEST_TEARDOWN, and UPK_REPL_RESULT.
START_TEST (test_proto_repl_seq_end)
References PKT_REPLY, TEST_SETUP, TEST_TEARDOWN, and UPK_REPL_SEQ_END.
START_TEST (test_proto_repl_seq_start)
References PKT_REPLY, TEST_SETUP, TEST_TEARDOWN, UPK_REPL_LISTING, and UPK_REPL_SEQ_START.
START_TEST (test_proto_req_disconnect)
References PKT_REQUEST, TEST_SETUP_NOARGS, TEST_TEARDOWN, and UPK_REQ_DISCONNECT.
START_TEST (test_proto_req_list)
References PKT_REQUEST, TEST_SETUP_NOARGS, TEST_TEARDOWN, and UPK_REQ_LIST.
START_TEST (test_proto_req_subscribe)
References PKT_REQUEST, TEST_SETUP, TEST_TEARDOWN, and UPK_REQ_SUBSCRIBE.
START_TEST (test_proto_req_status)
References PKT_REQUEST, TEST_SETUP, TEST_TEARDOWN, and UPK_REQ_STATUS.
START_TEST (test_proto_req_action)
References PKT_REQUEST, TEST_SETUP, TEST_TEARDOWN, and UPK_REQ_ACTION.
TCase* v0_proto_pubmsgs (void)
Referenced by upk_proto_helpers_suite(), upk_proto_serializers_suite(), v0_proto_helpers_suite(), and v0_proto_serializers_suite().
TCase* v0_proto_replies (void)
Referenced by upk_proto_helpers_suite(), upk_proto_serializers_suite(), v0_proto_helpers_suite(), and v0_proto_serializers_suite().
TCase* v0_proto_requests (void)
Referenced by upk_proto_helpers_suite(), upk_proto_serializers_suite(), v0_proto_helpers_suite(), and v0_proto_serializers_suite().
Variable Documentation
END_TEST