.TH "__CONST_SOCKADDR_ARG" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__CONST_SOCKADDR_ARG \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__const struct \fBsockaddr\fP *__restrict \fB__sockaddr__\fP"
.br
.ti -1c
.RI "__const struct sockaddr_at *__restrict \fB__sockaddr_at__\fP"
.br
.ti -1c
.RI "__const struct sockaddr_ax25 *__restrict \fB__sockaddr_ax25__\fP"
.br
.ti -1c
.RI "__const struct sockaddr_dl *__restrict \fB__sockaddr_dl__\fP"
.br
.ti -1c
.RI "__const struct sockaddr_eon *__restrict \fB__sockaddr_eon__\fP"
.br
.ti -1c
.RI "__const struct \fBsockaddr_in\fP *__restrict \fB__sockaddr_in__\fP"
.br
.ti -1c
.RI "__const struct \fBsockaddr_in6\fP *__restrict \fB__sockaddr_in6__\fP"
.br
.ti -1c
.RI "__const struct sockaddr_inarp *__restrict \fB__sockaddr_inarp__\fP"
.br
.ti -1c
.RI "__const struct sockaddr_ipx *__restrict \fB__sockaddr_ipx__\fP"
.br
.ti -1c
.RI "__const struct sockaddr_iso *__restrict \fB__sockaddr_iso__\fP"
.br
.ti -1c
.RI "__const struct sockaddr_ns *__restrict \fB__sockaddr_ns__\fP"
.br
.ti -1c
.RI "__const struct \fBsockaddr_un\fP *__restrict \fB__sockaddr_un__\fP"
.br
.ti -1c
.RI "__const struct sockaddr_x25 *__restrict \fB__sockaddr_x25__\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "__const struct \fBsockaddr\fP *__restrict \fB__CONST_SOCKADDR_ARG::__sockaddr__\fP"
.SS "__const struct sockaddr_at *__restrict \fB__CONST_SOCKADDR_ARG::__sockaddr_at__\fP"
.SS "__const struct sockaddr_ax25 *__restrict \fB__CONST_SOCKADDR_ARG::__sockaddr_ax25__\fP"
.SS "__const struct sockaddr_dl *__restrict \fB__CONST_SOCKADDR_ARG::__sockaddr_dl__\fP"
.SS "__const struct sockaddr_eon *__restrict \fB__CONST_SOCKADDR_ARG::__sockaddr_eon__\fP"
.SS "__const struct \fBsockaddr_in6\fP *__restrict \fB__CONST_SOCKADDR_ARG::__sockaddr_in6__\fP"
.SS "__const struct \fBsockaddr_in\fP *__restrict \fB__CONST_SOCKADDR_ARG::__sockaddr_in__\fP"
.SS "__const struct sockaddr_inarp *__restrict \fB__CONST_SOCKADDR_ARG::__sockaddr_inarp__\fP"
.SS "__const struct sockaddr_ipx *__restrict \fB__CONST_SOCKADDR_ARG::__sockaddr_ipx__\fP"
.SS "__const struct sockaddr_iso *__restrict \fB__CONST_SOCKADDR_ARG::__sockaddr_iso__\fP"
.SS "__const struct sockaddr_ns *__restrict \fB__CONST_SOCKADDR_ARG::__sockaddr_ns__\fP"
.SS "__const struct \fBsockaddr_un\fP *__restrict \fB__CONST_SOCKADDR_ARG::__sockaddr_un__\fP"
.SS "__const struct sockaddr_x25 *__restrict \fB__CONST_SOCKADDR_ARG::__sockaddr_x25__\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
