.TH "__gconv_trans_data" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gconv_trans_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__gconv_trans_fct\fP \fB__trans_fct\fP"
.br
.ti -1c
.RI "\fB__gconv_trans_context_fct\fP \fB__trans_context_fct\fP"
.br
.ti -1c
.RI "\fB__gconv_trans_end_fct\fP \fB__trans_end_fct\fP"
.br
.ti -1c
.RI "void * \fB__data\fP"
.br
.ti -1c
.RI "struct \fB__gconv_trans_data\fP * \fB__next\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void * \fB__gconv_trans_data::__data\fP"
.SS "struct \fB__gconv_trans_data\fP * \fB__gconv_trans_data::__next\fP"
.SS "\fB__gconv_trans_context_fct\fP \fB__gconv_trans_data::__trans_context_fct\fP"
.SS "\fB__gconv_trans_end_fct\fP \fB__gconv_trans_data::__trans_end_fct\fP"
.SS "\fB__gconv_trans_fct\fP \fB__gconv_trans_data::__trans_fct\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
