.TH "__gconv_step_data" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gconv_step_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char * \fB__outbuf\fP"
.br
.ti -1c
.RI "unsigned char * \fB__outbufend\fP"
.br
.ti -1c
.RI "int \fB__flags\fP"
.br
.ti -1c
.RI "int \fB__invocation_counter\fP"
.br
.ti -1c
.RI "int \fB__internal_use\fP"
.br
.ti -1c
.RI "\fB__mbstate_t\fP * \fB__statep\fP"
.br
.ti -1c
.RI "\fB__mbstate_t\fP \fB__state\fP"
.br
.ti -1c
.RI "struct \fB__gconv_trans_data\fP * \fB__trans\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fB__gconv_step_data::__flags\fP"
.SS "int \fB__gconv_step_data::__internal_use\fP"
.SS "int \fB__gconv_step_data::__invocation_counter\fP"
.SS "unsigned char * \fB__gconv_step_data::__outbuf\fP"
.SS "unsigned char * \fB__gconv_step_data::__outbufend\fP"
.SS "\fB__mbstate_t\fP \fB__gconv_step_data::__state\fP"
.SS "\fB__mbstate_t\fP * \fB__gconv_step_data::__statep\fP"
.SS "struct \fB__gconv_trans_data\fP * \fB__gconv_step_data::__trans\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
