.TH "__gconv_step" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gconv_step \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct __gconv_loaded_object * \fB__shlib_handle\fP"
.br
.ti -1c
.RI "__const char * \fB__modname\fP"
.br
.ti -1c
.RI "int \fB__counter\fP"
.br
.ti -1c
.RI "char * \fB__from_name\fP"
.br
.ti -1c
.RI "char * \fB__to_name\fP"
.br
.ti -1c
.RI "\fB__gconv_fct\fP \fB__fct\fP"
.br
.ti -1c
.RI "\fB__gconv_btowc_fct\fP \fB__btowc_fct\fP"
.br
.ti -1c
.RI "\fB__gconv_init_fct\fP \fB__init_fct\fP"
.br
.ti -1c
.RI "\fB__gconv_end_fct\fP \fB__end_fct\fP"
.br
.ti -1c
.RI "int \fB__min_needed_from\fP"
.br
.ti -1c
.RI "int \fB__max_needed_from\fP"
.br
.ti -1c
.RI "int \fB__min_needed_to\fP"
.br
.ti -1c
.RI "int \fB__max_needed_to\fP"
.br
.ti -1c
.RI "int \fB__stateful\fP"
.br
.ti -1c
.RI "void * \fB__data\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fB__gconv_btowc_fct\fP \fB__gconv_step::__btowc_fct\fP"
.SS "int \fB__gconv_step::__counter\fP"
.SS "void * \fB__gconv_step::__data\fP"
.SS "\fB__gconv_end_fct\fP \fB__gconv_step::__end_fct\fP"
.SS "\fB__gconv_fct\fP \fB__gconv_step::__fct\fP"
.SS "char * \fB__gconv_step::__from_name\fP"
.SS "\fB__gconv_init_fct\fP \fB__gconv_step::__init_fct\fP"
.SS "int \fB__gconv_step::__max_needed_from\fP"
.SS "int \fB__gconv_step::__max_needed_to\fP"
.SS "int \fB__gconv_step::__min_needed_from\fP"
.SS "int \fB__gconv_step::__min_needed_to\fP"
.SS "__const char * \fB__gconv_step::__modname\fP"
.SS "struct __gconv_loaded_object * \fB__gconv_step::__shlib_handle\fP"
.SS "int \fB__gconv_step::__stateful\fP"
.SS "char * \fB__gconv_step::__to_name\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
