.TH "__gconv_info" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gconv_info \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsize_t\fP \fB__nsteps\fP"
.br
.ti -1c
.RI "struct \fB__gconv_step\fP * \fB__steps\fP"
.br
.ti -1c
.RI "__extension__ struct \fB__gconv_step_data\fP \fB__data\fP []"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "__extension__ struct \fB__gconv_step_data\fP \fB__gconv_info::__data\fP"
.SS "\fBsize_t\fP \fB__gconv_info::__nsteps\fP"
.SS "struct \fB__gconv_step\fP * \fB__gconv_info::__steps\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
