.TH "__mbstate_t" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__mbstate_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fB__count\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBwint_t\fP \fB__wch\fP"
.br
.ti -1c
.RI "   char \fB__wchb\fP [4]"
.br
.ti -1c
.RI "} \fB__value\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBwint_t\fP \fB__wch\fP"
.br
.ti -1c
.RI "   char \fB__wchb\fP [4]"
.br
.ti -1c
.RI "} \fB__value\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fB__mbstate_t::__count\fP"
.SS "union { ... }   \fB__mbstate_t::__value\fP"
.SS "union { ... }   \fB__mbstate_t::__value\fP"
.SS "\fBwint_t\fP \fB__mbstate_t::__wch\fP"
.SS "char \fB__mbstate_t::__wchb\fP[4]"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
