.TH "__sigset_t" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__sigset_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long int \fB__val\fP [(1024/(8 *sizeof(unsigned long int)))]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned long int \fB__sigset_t::__val\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
