.TH "__WAIT_STATUS" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__WAIT_STATUS \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union \fBwait\fP * \fB__uptr\fP"
.br
.ti -1c
.RI "int * \fB__iptr\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int * \fB__WAIT_STATUS::__iptr\fP"
.SS "union \fBwait\fP * \fB__WAIT_STATUS::__uptr\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
