.TH "_fpxreg" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_fpxreg \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned short \fBsignificand\fP [4]"
.br
.ti -1c
.RI "unsigned short \fBexponent\fP"
.br
.ti -1c
.RI "unsigned short \fBpadding\fP [3]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned short \fB_fpxreg::exponent\fP"
.SS "unsigned short \fB_fpxreg::padding\fP"
.SS "unsigned short \fB_fpxreg::significand\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
