.TH "_G_fpos_t" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_G_fpos_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__off_t\fP \fB__pos\fP"
.br
.ti -1c
.RI "\fB__mbstate_t\fP \fB__state\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fB__off_t\fP \fB_G_fpos_t::__pos\fP"
.SS "\fB__mbstate_t\fP \fB_G_fpos_t::__state\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
