.TH "_G_iconv_t" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_G_iconv_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fB__gconv_info\fP \fB__cd\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct \fB__gconv_info\fP \fB__cd\fP"
.br
.ti -1c
.RI "   struct \fB__gconv_step_data\fP \fB__data\fP"
.br
.ti -1c
.RI "} \fB__combined\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct \fB__gconv_info\fP \fB__cd\fP"
.br
.ti -1c
.RI "   struct \fB__gconv_step_data\fP \fB__data\fP"
.br
.ti -1c
.RI "} \fB__combined\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fB__gconv_info\fP \fB_G_iconv_t::__cd\fP"
.SS "struct { ... }   \fB_G_iconv_t::__combined\fP"
.SS "struct { ... }   \fB_G_iconv_t::__combined\fP"
.SS "struct \fB__gconv_step_data\fP \fB_G_iconv_t::__data\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
