.TH "_IO_cookie_io_functions_t" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_IO_cookie_io_functions_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__io_read_fn\fP * \fBread\fP"
.br
.ti -1c
.RI "\fB__io_write_fn\fP * \fBwrite\fP"
.br
.ti -1c
.RI "\fB__io_seek_fn\fP * \fBseek\fP"
.br
.ti -1c
.RI "\fB__io_close_fn\fP * \fBclose\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fB__io_close_fn\fP * \fB_IO_cookie_io_functions_t::close\fP"
.SS "\fB__io_read_fn\fP * \fB_IO_cookie_io_functions_t::read\fP"
.SS "\fB__io_seek_fn\fP * \fB_IO_cookie_io_functions_t::seek\fP"
.SS "\fB__io_write_fn\fP * \fB_IO_cookie_io_functions_t::write\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
