.TH "_IO_marker" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_IO_marker \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fB_IO_marker\fP * \fB_next\fP"
.br
.ti -1c
.RI "struct \fB_IO_FILE\fP * \fB_sbuf\fP"
.br
.ti -1c
.RI "int \fB_pos\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fB_IO_marker\fP * \fB_IO_marker::_next\fP"
.SS "int \fB_IO_marker::_pos\fP"
.SS "struct \fB_IO_FILE\fP * \fB_IO_marker::_sbuf\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
