.TH "_IO_FILE" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_IO_FILE \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fB_flags\fP"
.br
.ti -1c
.RI "char * \fB_IO_read_ptr\fP"
.br
.ti -1c
.RI "char * \fB_IO_read_end\fP"
.br
.ti -1c
.RI "char * \fB_IO_read_base\fP"
.br
.ti -1c
.RI "char * \fB_IO_write_base\fP"
.br
.ti -1c
.RI "char * \fB_IO_write_ptr\fP"
.br
.ti -1c
.RI "char * \fB_IO_write_end\fP"
.br
.ti -1c
.RI "char * \fB_IO_buf_base\fP"
.br
.ti -1c
.RI "char * \fB_IO_buf_end\fP"
.br
.ti -1c
.RI "char * \fB_IO_save_base\fP"
.br
.ti -1c
.RI "char * \fB_IO_backup_base\fP"
.br
.ti -1c
.RI "char * \fB_IO_save_end\fP"
.br
.ti -1c
.RI "struct \fB_IO_marker\fP * \fB_markers\fP"
.br
.ti -1c
.RI "struct \fB_IO_FILE\fP * \fB_chain\fP"
.br
.ti -1c
.RI "int \fB_fileno\fP"
.br
.ti -1c
.RI "int \fB_flags2\fP"
.br
.ti -1c
.RI "\fB__off_t\fP \fB_old_offset\fP"
.br
.ti -1c
.RI "unsigned short \fB_cur_column\fP"
.br
.ti -1c
.RI "signed char \fB_vtable_offset\fP"
.br
.ti -1c
.RI "char \fB_shortbuf\fP [1]"
.br
.ti -1c
.RI "\fB_IO_lock_t\fP * \fB_lock\fP"
.br
.ti -1c
.RI "\fB__off64_t\fP \fB_offset\fP"
.br
.ti -1c
.RI "void * \fB__pad1\fP"
.br
.ti -1c
.RI "void * \fB__pad2\fP"
.br
.ti -1c
.RI "void * \fB__pad3\fP"
.br
.ti -1c
.RI "void * \fB__pad4\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fB__pad5\fP"
.br
.ti -1c
.RI "int \fB_mode\fP"
.br
.ti -1c
.RI "char \fB_unused2\fP [15 *sizeof(int)-4 *sizeof(void *)-sizeof(\fBsize_t\fP)]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void * \fB_IO_FILE::__pad1\fP"
.SS "void * \fB_IO_FILE::__pad2\fP"
.SS "void * \fB_IO_FILE::__pad3\fP"
.SS "void * \fB_IO_FILE::__pad4\fP"
.SS "\fBsize_t\fP \fB_IO_FILE::__pad5\fP"
.SS "struct \fB_IO_FILE\fP * \fB_IO_FILE::_chain\fP"
.SS "unsigned short \fB_IO_FILE::_cur_column\fP"
.SS "int \fB_IO_FILE::_fileno\fP"
.SS "int \fB_IO_FILE::_flags\fP"
.SS "int \fB_IO_FILE::_flags2\fP"
.SS "char * \fB_IO_FILE::_IO_backup_base\fP"
.SS "char * \fB_IO_FILE::_IO_buf_base\fP"
.SS "char * \fB_IO_FILE::_IO_buf_end\fP"
.SS "char * \fB_IO_FILE::_IO_read_base\fP"
.SS "char * \fB_IO_FILE::_IO_read_end\fP"
.SS "char * \fB_IO_FILE::_IO_read_ptr\fP"
.SS "char * \fB_IO_FILE::_IO_save_base\fP"
.SS "char * \fB_IO_FILE::_IO_save_end\fP"
.SS "char * \fB_IO_FILE::_IO_write_base\fP"
.SS "char * \fB_IO_FILE::_IO_write_end\fP"
.SS "char * \fB_IO_FILE::_IO_write_ptr\fP"
.SS "\fB_IO_lock_t\fP * \fB_IO_FILE::_lock\fP"
.SS "struct \fB_IO_marker\fP * \fB_IO_FILE::_markers\fP"
.SS "int \fB_IO_FILE::_mode\fP"
.SS "\fB__off64_t\fP \fB_IO_FILE::_offset\fP"
.SS "\fB__off_t\fP \fB_IO_FILE::_old_offset\fP"
.SS "char \fB_IO_FILE::_shortbuf\fP"
.SS "char \fB_IO_FILE::_unused2\fP"
.SS "signed char \fB_IO_FILE::_vtable_offset\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
