.TH "_libc_fpxreg" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_libc_fpxreg \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned short int \fBsignificand\fP [4]"
.br
.ti -1c
.RI "unsigned short int \fBexponent\fP"
.br
.ti -1c
.RI "unsigned short int \fBpadding\fP [3]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned short int \fB_libc_fpxreg::exponent\fP"
.SS "unsigned short int \fB_libc_fpxreg::padding\fP"
.SS "unsigned short int \fB_libc_fpxreg::significand\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
