.TH "_upk_cust_actscr_list" 3 "Wed Sep 14 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_upk_cust_actscr_list \- 
.PP
linked list of custom action scripts.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <upk_types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [UPK_MAX_STRING_LEN]"
.br
.ti -1c
.RI "char * \fBscript\fP"
.br
.ti -1c
.RI "\fBupk_cust_actscr_list_t\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
linked list of custom action scripts. 
.SH "Field Documentation"
.PP 
.SS "char \fB_upk_cust_actscr_list::name\fP[UPK_MAX_STRING_LEN]"name of custom action 
.SS "\fBupk_cust_actscr_list_t\fP* \fB_upk_cust_actscr_list::next\fP"next, for use in lists 
.SS "char* \fB_upk_cust_actscr_list::script\fP"script to run for action 

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
