.TH "_upk_json_data_output_options" 3 "Tue Nov 1 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_upk_json_data_output_options \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <upk_json_fmt.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBpad\fP"
.br
.ti -1c
.RI "char * \fBindent\fP"
.br
.ti -1c
.RI "char * \fBsep\fP"
.br
.ti -1c
.RI "bool \fBsuppress_null_values\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* \fB_upk_json_data_output_options::indent\fP"
.PP
Referenced by main(), and upk_json_print_indent().
.SS "char* \fB_upk_json_data_output_options::pad\fP"
.PP
Referenced by main(), upk_json_output_array_handler(), upk_json_output_bool_handler(), upk_json_output_double_handler(), upk_json_output_int_handler(), upk_json_output_null_handler(), upk_json_output_object_handler(), and upk_json_output_string_handler().
.SS "char* \fB_upk_json_data_output_options::sep\fP"
.PP
Referenced by main(), upk_json_output_after_json_array_pop_handler(), upk_json_output_after_json_obj_pop_handler(), upk_json_output_array_handler(), upk_json_output_bool_handler(), upk_json_output_double_handler(), upk_json_output_int_handler(), upk_json_output_null_handler(), upk_json_output_object_handler(), upk_json_output_string_handler(), and upk_load_runtime_services().
.SS "bool \fB_upk_json_data_output_options::suppress_null_values\fP"
.PP
Referenced by main(), and upk_json_output_null_handler().

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
