.TH "_upk_json_output_data" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_upk_json_output_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBupk_json_output_type_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBupk_stream_string_t\fP \fBd\fP"
.br
.ti -1c
.RI "\fBupk_json_data_output_opts_t\fP \fBopts\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBupk_stream_string_t\fP \fB_upk_json_output_data::d\fP"
.PP
Referenced by upk_json_append_string(), upk_json_obj_to_string(), and upk_output_json_string().
.SS "\fBupk_json_data_output_opts_t\fP \fB_upk_json_output_data::opts\fP"
.PP
Referenced by upk_json_output_after_json_array_pop_handler(), upk_json_output_after_json_obj_pop_handler(), upk_json_output_array_handler(), upk_json_output_bool_handler(), upk_json_output_double_handler(), upk_json_output_int_handler(), upk_json_output_null_handler(), upk_json_output_object_handler(), upk_json_output_string_handler(), and upk_json_print_indent().
.SS "\fBupk_json_output_type_t\fP \fB_upk_json_output_data::type\fP"
.PP
Referenced by upk_json_obj_to_stream(), upk_json_obj_to_string(), and upk_output_json_string().

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
