.TH "_upk_net_cb_stk" 3 "Wed Sep 14 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_upk_net_cb_stk \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <upk_network_types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBupk_net_callback_t\fP \fBmsg_handlers\fP [UPK_N_REQ_TYPES+UPK_N_REPL_TYPES+UPK_N_PUB_TYPES]"
.br
.ti -1c
.RI "\fBupk_net_callback_t\fP \fBnet_dispatch_pre\fP"
.br
.ti -1c
.RI "\fBupk_net_callback_t\fP \fBnet_dispatch_foreach\fP"
.br
.ti -1c
.RI "\fBupk_net_callback_t\fP \fBnet_dispatch_post\fP"
.br
.ti -1c
.RI "\fBupk_net_cb_stk_t\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBupk_net_callback_t\fP \fB_upk_net_cb_stk::msg_handlers\fP[UPK_N_REQ_TYPES+UPK_N_REPL_TYPES+UPK_N_PUB_TYPES]"
.SS "\fBupk_net_callback_t\fP \fB_upk_net_cb_stk::net_dispatch_foreach\fP"
.SS "\fBupk_net_callback_t\fP \fB_upk_net_cb_stk::net_dispatch_post\fP"
.SS "\fBupk_net_callback_t\fP \fB_upk_net_cb_stk::net_dispatch_pre\fP"
.SS "\fBupk_net_cb_stk_t\fP* \fB_upk_net_cb_stk::next\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
