.TH "_upk_controller_config" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_upk_controller_config \- 
.PP
controller configuration.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <upk_config.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBStateDir\fP [8192]"
.br
.ti -1c
.RI "char \fBSvcConfigPath\fP [8192]"
.br
.ti -1c
.RI "char \fBSvcRunPath\fP [8192]"
.br
.ti -1c
.RI "char \fBUpkBuddyPath\fP [8192]"
.br
.ti -1c
.RI "int32_t \fBAuditMaxAge\fP"
.br
.ti -1c
.RI "int32_t \fBAuditMaxRecords\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBBuddyVerbosity\fP"
.br
.ti -1c
.RI "double \fBBuddyPollingInterval\fP"
.br
.ti -1c
.RI "char \fBcontroller_socket\fP [8192]"
.br
.ti -1c
.RI "char \fBcontroller_buddy_sock\fP [8192]"
.br
.ti -1c
.RI "\fBupk_svc_desc_t\fP \fBServiceDefaults\fP"
.br
.ti -1c
.RI "\fBupk_svc_desc_meta_t\fP * \fBsvclist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
controller configuration. 
.SH "Field Documentation"
.PP 
.SS "int32_t \fB_upk_controller_config::AuditMaxAge\fP"specified in seconds, the longest duration to keep audit records for, or a value <= 0 if they should be kept forever 
.SS "int32_t \fB_upk_controller_config::AuditMaxRecords\fP"maximum number of audit records to keep. In addition to MaxAge, this provides a way to ensure audit records to not exhaust disk space and/or grow excessively 
.SS "double \fB_upk_controller_config::BuddyPollingInterval\fP"duration in seconds, or fractions of seconds, to wait between polling buddy sockets for updates; note that for longer durations, larger buddy ringbuffers should be prescribed 
.PP
Referenced by event_loop(), upk_ctrl_load_config(), upk_ctrlconf_double_handler(), upk_ctrlconf_int_handler(), and upk_overlay_ctrlconf_values().
.SS "\fBuint32_t\fP \fB_upk_controller_config::BuddyVerbosity\fP"level of verbosity to run buddy at 
.PP
Referenced by spawn_buddy(), and upk_ctrlconf_int_handler().
.SS "char \fB_upk_controller_config::controller_buddy_sock\fP"path to buddy socket; used internally 
.PP
Referenced by create_buddy_statedir(), remove_buddy_statedir(), upk_ctrl_load_config(), and upk_overlay_ctrlconf_values().
.SS "char \fB_upk_controller_config::controller_socket\fP"path to the controller socket, used internally 
.PP
Referenced by create_buddy_statedir(), ctrl_sock_setup(), upk_clnet_ctrl_connect(), upk_ctrl_load_config(), and upk_overlay_ctrlconf_values().
.SS "\fBupk_svc_desc_t\fP \fB_upk_controller_config::ServiceDefaults\fP"default service configuration parameters; used whenever an individual service omits something 
.PP
Referenced by upk_ctrl_load_config(), upk_ctrlconf_free(), upk_ctrlconf_object_handler(), upk_finalize_svc_desc(), and upk_overlay_ctrlconf_values().
.SS "char \fB_upk_controller_config::StateDir\fP"path to variable state-dir for controller and buddies 
.PP
Referenced by upk_ctrl_load_config(), upk_ctrlconf_string_handler(), upk_db_path(), upk_overlay_ctrlconf_values(), and upk_state_init().
.SS "char \fB_upk_controller_config::SvcConfigPath\fP"path to service configuration files 
.PP
Referenced by upk_ctrlconf_string_handler(), upk_load_runtime_services(), and upk_overlay_ctrlconf_values().
.SS "\fBupk_svc_desc_meta_t\fP * \fB_upk_controller_config::svclist\fP"meta-pointer to list of service descriptions 
.PP
Referenced by ctrl_req_action_handler(), lookup_buddy_from_path(), main(), upk_ctrl_init(), upk_ctrlconf_free(), upk_load_runtime_services(), upk_overlay_ctrlconf_values(), and upk_svcconf_object_handler().
.SS "char \fB_upk_controller_config::SvcRunPath\fP"path where buddy's will be created and run, usually ${statedir}/buddies 
.PP
Referenced by buddy_sock_path(), create_buddy_statedir(), handle_buddies(), remove_buddy_statedir(), spawn_buddy(), upk_ctrlconf_string_handler(), and upk_overlay_ctrlconf_values().
.SS "char \fB_upk_controller_config::UpkBuddyPath\fP"path to upk_buddy executable, usually ${libexecdir}/upk_buddy 
.PP
Referenced by spawn_buddy(), upk_ctrlconf_string_handler(), and upk_overlay_ctrlconf_values().

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
