.TH "_upk_json_stack_handlers" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_upk_json_stack_handlers \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <upk_json.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBupk_json_handler_t\fP \fBjson_null\fP"
.br
.ti -1c
.RI "\fBupk_json_handler_t\fP \fBjson_bool\fP"
.br
.ti -1c
.RI "\fBupk_json_handler_t\fP \fBjson_double\fP"
.br
.ti -1c
.RI "\fBupk_json_handler_t\fP \fBjson_int\fP"
.br
.ti -1c
.RI "\fBupk_json_handler_t\fP \fBjson_string\fP"
.br
.ti -1c
.RI "\fBupk_json_handler_t\fP \fBjson_array\fP"
.br
.ti -1c
.RI "\fBupk_json_handler_t\fP \fBjson_object\fP"
.br
.ti -1c
.RI "\fBupk_json_handler_t\fP \fBafter_json_obj_pop\fP"
.br
.ti -1c
.RI "\fBupk_json_handler_t\fP \fBafter_json_array_pop\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBupk_json_handler_t\fP \fB_upk_json_stack_handlers::after_json_array_pop\fP"
.PP
Referenced by upk_ctrlconf_pack(), upk_ctrlconf_toplvl_obj(), upk_svcconf_pack(), upk_svcconf_setup_array_handlers(), upk_svcconf_setup_handlers(), upk_svcconf_setup_object_handlers(), and upk_svcconf_toplvl_obj().
.SS "\fBupk_json_handler_t\fP \fB_upk_json_stack_handlers::after_json_obj_pop\fP"
.PP
Referenced by upk_ctrlconf_pack(), upk_ctrlconf_toplvl_obj(), upk_svcconf_pack(), upk_svcconf_setup_array_handlers(), upk_svcconf_setup_handlers(), upk_svcconf_setup_object_handlers(), and upk_svcconf_toplvl_obj().
.SS "\fBupk_json_handler_t\fP \fB_upk_json_stack_handlers::json_array\fP"
.PP
Referenced by upk_ctrlconf_pack(), upk_ctrlconf_toplvl_obj(), upk_svcconf_pack(), upk_svcconf_setup_array_handlers(), upk_svcconf_setup_handlers(), upk_svcconf_setup_object_handlers(), and upk_svcconf_toplvl_obj().
.SS "\fBupk_json_handler_t\fP \fB_upk_json_stack_handlers::json_bool\fP"
.PP
Referenced by upk_ctrlconf_pack(), upk_ctrlconf_toplvl_obj(), upk_svcconf_pack(), upk_svcconf_setup_array_handlers(), upk_svcconf_setup_handlers(), upk_svcconf_setup_object_handlers(), and upk_svcconf_toplvl_obj().
.SS "\fBupk_json_handler_t\fP \fB_upk_json_stack_handlers::json_double\fP"
.PP
Referenced by upk_ctrlconf_pack(), upk_ctrlconf_toplvl_obj(), upk_svcconf_pack(), upk_svcconf_setup_array_handlers(), upk_svcconf_setup_handlers(), upk_svcconf_setup_object_handlers(), and upk_svcconf_toplvl_obj().
.SS "\fBupk_json_handler_t\fP \fB_upk_json_stack_handlers::json_int\fP"
.PP
Referenced by upk_ctrlconf_pack(), upk_ctrlconf_toplvl_obj(), upk_svcconf_pack(), upk_svcconf_setup_array_handlers(), upk_svcconf_setup_handlers(), upk_svcconf_setup_object_handlers(), and upk_svcconf_toplvl_obj().
.SS "\fBupk_json_handler_t\fP \fB_upk_json_stack_handlers::json_null\fP"
.PP
Referenced by upk_ctrlconf_pack(), upk_ctrlconf_toplvl_obj(), upk_svcconf_pack(), upk_svcconf_setup_array_handlers(), upk_svcconf_setup_handlers(), upk_svcconf_setup_object_handlers(), and upk_svcconf_toplvl_obj().
.SS "\fBupk_json_handler_t\fP \fB_upk_json_stack_handlers::json_object\fP"
.PP
Referenced by upk_ctrlconf_pack(), upk_ctrlconf_toplvl_obj(), upk_svcconf_pack(), upk_svcconf_setup_array_handlers(), upk_svcconf_setup_handlers(), upk_svcconf_setup_object_handlers(), and upk_svcconf_toplvl_obj().
.SS "\fBupk_json_handler_t\fP \fB_upk_json_stack_handlers::json_string\fP"
.PP
Referenced by upk_ctrlconf_pack(), upk_ctrlconf_toplvl_obj(), upk_svcconf_pack(), upk_svcconf_setup_array_handlers(), upk_svcconf_setup_handlers(), upk_svcconf_setup_object_handlers(), and upk_svcconf_toplvl_obj().

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
