.TH "_upk_svcid" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_upk_svcid \- 
.PP
linked list of service identifiers.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <upk_types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBpkg\fP [2048]"
.br
.ti -1c
.RI "char \fBname\fP [2048]"
.br
.ti -1c
.RI "\fBupk_uuid_t\fP \fBuuid\fP"
.br
.ti -1c
.RI "\fBupk_svcid_t\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
linked list of service identifiers. 
.SH "Field Documentation"
.PP 
.SS "char \fB_upk_svcid::name\fP"service name 
.PP
Referenced by upk_db_upsert_options(), upk_svc_desc_to_json_obj(), and upk_svcconf_svcid_array_appender().
.SS "\fBupk_svcid_t\fP * \fB_upk_svcid::next\fP"next, for use in lists 
.PP
Referenced by upk_db_upsert_options(), and upk_overlay_svcconf_values().
.SS "char \fB_upk_svcid::pkg\fP"service package-prefix 
.PP
Referenced by upk_db_upsert_options(), upk_svc_desc_to_json_obj(), and upk_svcconf_svcid_array_appender().
.SS "\fBupk_uuid_t\fP \fB_upk_svcid::uuid\fP"not sure I need this here; but just in case for now 

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
