.TH "_upk_stringlist" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_upk_stringlist \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <upk_types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBstring\fP [2048]"
.br
.ti -1c
.RI "\fBupk_stringlist_t\fP * \fBprev\fP"
.br
.ti -1c
.RI "\fBupk_stringlist_t\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBupk_stringlist_t\fP * \fB_upk_stringlist::next\fP"
.SS "\fBupk_stringlist_t\fP * \fB_upk_stringlist::prev\fP"
.SS "char \fB_upk_stringlist::string\fP"
.PP
Referenced by upk_mkdir_p().

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
