.TH "_upk_net_gstate" 3 "Tue Nov 1 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_upk_net_gstate \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <upk_network_types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBpending_writeq\fP"
.br
.ti -1c
.RI "\fBupk_net_cb_stk_meta_t\fP * \fBcallback_stack\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBupk_net_cb_stk_meta_t\fP* \fB_upk_net_gstate::callback_stack\fP"
.PP
Referenced by upk_call_received_packet_callbacks(), upk_net_event_dispatcher(), and upk_partitioned_userdata_free().
.SS "size_t \fB_upk_net_gstate::pending_writeq\fP"
.PP
Referenced by upk_net_event_dispatcher(), upk_queue_packet(), and upk_write_packets().

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
