.TH "_upk_stream_string" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_upk_stream_string \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBFILE\fP * \fBfile\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   char * \fBp\fP"
.br
.ti -1c
.RI "   \fBsize_t\fP \fBlen\fP"
.br
.ti -1c
.RI "} \fBstr\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBFILE\fP* \fB_upk_stream_string::file\fP"
.PP
Referenced by upk_output_json_string().
.SS "\fBsize_t\fP \fB_upk_stream_string::len\fP"
.PP
Referenced by upk_json_append_string().
.SS "char* \fB_upk_stream_string::p\fP"
.PP
Referenced by upk_json_append_string(), and upk_json_obj_to_string().
.SS "struct { ... }   \fB_upk_stream_string::str\fP"
.PP
Referenced by upk_json_append_string(), and upk_json_obj_to_string().

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
