.TH "_upk_json_string" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_upk_json_string \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <upk_json.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBc_str\fP"
.br
.ti -1c
.RI "char * \fBesc_str\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* \fB_upk_json_string::c_str\fP"
.PP
Referenced by upk_ctrlconf_string_handler(), upk_json_value(), upk_svcconf_customaction_array_appender(), upk_svcconf_string_handler(), and upk_svcconf_svcid_array_appender().
.SS "char* \fB_upk_json_string::esc_str\fP"
.PP
Referenced by upk_json_output_string_handler(), and upk_json_value().

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
