.TH "_upk_json_stack_node" 3 "Tue Nov 1 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_upk_json_stack_node \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <upk_json.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "\fBupk_json_handlers_t\fP \fBhandlers\fP"
.br
.ti -1c
.RI "\fBupk_json_stack_node_t\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* \fB_upk_json_stack_node::data\fP"
.PP
Referenced by upk_ctrlconf_object_handler(), upk_ctrlconf_pack(), upk_ctrlconf_toplvl_obj(), upk_json_obj_serializer(), upk_svcconf_object_handler(), upk_svcconf_pack(), and upk_svcconf_toplvl_obj().
.SS "\fBupk_json_handlers_t\fP \fB_upk_json_stack_node::handlers\fP"
.PP
Referenced by upk_ctrlconf_object_handler(), and upk_svcconf_object_handler().
.SS "\fBupk_json_stack_node_t\fP* \fB_upk_json_stack_node::next\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
