.TH "_upk_payload" 3 "Tue Nov 1 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_upk_payload \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <upk_protocol.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBupk_msgtype_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBupk_payload_types_u\fP \fBpayload\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBupk_payload_types_u\fP \fB_upk_payload::payload\fP"
.PP
Referenced by controller_packet_callback(), received_packet_callback(), upk_call_received_packet_callbacks(), and upk_clnet_req_action().
.SS "\fBupk_msgtype_t\fP \fB_upk_payload::type\fP"
.PP
Referenced by controller_packet_callback(), received_packet_callback(), upk_call_received_packet_callbacks(), upk_clnet_req_action(), upk_clnet_req_disconnect(), upk_clnet_req_preamble(), and upk_net_block_until_msg().

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
