.TH "_upk_net_event_queue" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_upk_net_event_queue \- this is a tailq for network message queuing  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <upk_network.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBupk_pkt_buf_t\fP * \fBmsg\fP"
.br
.ti -1c
.RI "\fBupk_net_event_queue_t\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
this is a tailq for network message queuing 
.PP
.SH "Field Documentation"
.PP 
.SS "\fBupk_pkt_buf_t\fP* \fB_upk_net_event_queue::msg\fP"
.PP
.SS "\fBupk_net_event_queue_t\fP* \fB_upk_net_event_queue::next\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
