.TH "_xmmreg" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xmmreg \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__uint32_t\fP \fBelement\fP [4]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fB__uint32_t\fP \fB_xmmreg::element\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
