.TH "AggInfo" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AggInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBdirectMode\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBuseSortingIdx\fP"
.br
.ti -1c
.RI "int \fBsortingIdx\fP"
.br
.ti -1c
.RI "\fBExprList\fP * \fBpGroupBy\fP"
.br
.ti -1c
.RI "int \fBnSortingColumn\fP"
.br
.ti -1c
.RI "\fBAggInfo::AggInfo_col\fP * \fBaCol\fP"
.br
.ti -1c
.RI "int \fBnColumn\fP"
.br
.ti -1c
.RI "int \fBnColumnAlloc\fP"
.br
.ti -1c
.RI "int \fBnAccumulator\fP"
.br
.ti -1c
.RI "\fBAggInfo::AggInfo_func\fP * \fBaFunc\fP"
.br
.ti -1c
.RI "int \fBnFunc\fP"
.br
.ti -1c
.RI "int \fBnFuncAlloc\fP"
.br
.ti -1c
.RI "\fBExprList\fP * \fBpGroupBy\fP"
.br
.ti -1c
.RI "\fBAggInfo::AggInfo_col\fP * \fBaCol\fP"
.br
.ti -1c
.RI "\fBAggInfo::AggInfo_func\fP * \fBaFunc\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBAggInfo_col\fP"
.br
.ti -1c
.RI "struct \fBAggInfo_col\fP"
.br
.ti -1c
.RI "struct \fBAggInfo_func\fP"
.br
.ti -1c
.RI "struct \fBAggInfo_func\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBAggInfo::AggInfo_col\fP * \fBAggInfo::aCol\fP"
.PP
.SS "struct \fBAggInfo::AggInfo_col\fP * \fBAggInfo::aCol\fP"
.PP
.SS "struct \fBAggInfo::AggInfo_func\fP * \fBAggInfo::aFunc\fP"
.PP
.SS "struct \fBAggInfo::AggInfo_func\fP * \fBAggInfo::aFunc\fP"
.PP
.SS "\fBu8\fP \fBAggInfo::directMode\fP"
.PP
.SS "int \fBAggInfo::nAccumulator\fP"
.PP
.SS "int \fBAggInfo::nColumn\fP"
.PP
.SS "int \fBAggInfo::nColumnAlloc\fP"
.PP
.SS "int \fBAggInfo::nFunc\fP"
.PP
.SS "int \fBAggInfo::nFuncAlloc\fP"
.PP
.SS "int \fBAggInfo::nSortingColumn\fP"
.PP
.SS "\fBExprList\fP* \fBAggInfo::pGroupBy\fP"
.PP
.SS "\fBExprList\fP* \fBAggInfo::pGroupBy\fP"
.PP
.SS "int \fBAggInfo::sortingIdx\fP"
.PP
.SS "\fBu8\fP \fBAggInfo::useSortingIdx\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
