.TH "analysisInfo" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
analysisInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.ti -1c
.RI "const char * \fBzDatabase\fP"
.br
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.ti -1c
.RI "const char * \fBzDatabase\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBsqlite3\fP* \fBanalysisInfo::db\fP"
.PP
.SS "\fBsqlite3\fP* \fBanalysisInfo::db\fP"
.PP
.SS "const char* \fBanalysisInfo::zDatabase\fP"
.PP
.SS "const char* \fBanalysisInfo::zDatabase\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
