.TH "API" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
API \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBupk_clientid\fP (void)"
.br
.ti -1c
.RI "bool \fBupk_client_event_hook\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool upk_client_event_hook (void)"
.SS "char* upk_clientid (void)"
.PP
References getpid(), upk_getprogname, and UPK_MAX_STRING_LEN.
.PP
Referenced by main(), and upk_clnet_req_preamble().
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
