.TH "AutoincInfo" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoincInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBAutoincInfo\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBTable\fP * \fBpTab\fP"
.br
.ti -1c
.RI "int \fBiDb\fP"
.br
.ti -1c
.RI "int \fBregCtr\fP"
.br
.ti -1c
.RI "\fBAutoincInfo\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBTable\fP * \fBpTab\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBAutoincInfo::iDb\fP"
.PP
.SS "\fBAutoincInfo\fP* \fBAutoincInfo::pNext\fP"
.PP
.SS "\fBAutoincInfo\fP* \fBAutoincInfo::pNext\fP"
.PP
.SS "\fBTable\fP* \fBAutoincInfo::pTab\fP"
.PP
.SS "\fBTable\fP* \fBAutoincInfo::pTab\fP"
.PP
.SS "int \fBAutoincInfo::regCtr\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
