.TH "BtLock" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BtLock \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBtree\fP * \fBpBtree\fP"
.br
.ti -1c
.RI "\fBPgno\fP \fBiTable\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBeLock\fP"
.br
.ti -1c
.RI "\fBBtLock\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBBtree\fP * \fBpBtree\fP"
.br
.ti -1c
.RI "\fBBtLock\fP * \fBpNext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu8\fP \fBBtLock::eLock\fP"
.PP
.SS "\fBPgno\fP \fBBtLock::iTable\fP"
.PP
.SS "\fBBtree\fP* \fBBtLock::pBtree\fP"
.PP
.SS "\fBBtree\fP* \fBBtLock::pBtree\fP"
.PP
.SS "\fBBtLock\fP* \fBBtLock::pNext\fP"
.PP
.SS "\fBBtLock\fP* \fBBtLock::pNext\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
