.TH "BtreeMutexArray" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BtreeMutexArray \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnMutex\fP"
.br
.ti -1c
.RI "\fBBtree\fP * \fBaBtree\fP [SQLITE_MAX_ATTACHED+1]"
.br
.ti -1c
.RI "\fBBtree\fP * \fBaBtree\fP [SQLITE_MAX_ATTACHED+1]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBBtree\fP* \fBBtreeMutexArray::aBtree\fP[SQLITE_MAX_ATTACHED+1]"
.PP
.SS "\fBBtree\fP* \fBBtreeMutexArray::aBtree\fP[SQLITE_MAX_ATTACHED+1]"
.PP
.SS "int \fBBtreeMutexArray::nMutex\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
