.TH "Btree" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Btree \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.ti -1c
.RI "\fBBtShared\fP * \fBpBt\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBinTrans\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBsharable\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBlocked\fP"
.br
.ti -1c
.RI "int \fBwantToLock\fP"
.br
.ti -1c
.RI "int \fBnBackup\fP"
.br
.ti -1c
.RI "\fBBtree\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBBtree\fP * \fBpPrev\fP"
.br
.ti -1c
.RI "\fBBtLock\fP \fBlock\fP"
.br
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.ti -1c
.RI "\fBBtShared\fP * \fBpBt\fP"
.br
.ti -1c
.RI "\fBBtree\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBBtree\fP * \fBpPrev\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBsqlite3\fP* \fBBtree::db\fP"
.PP
.SS "\fBsqlite3\fP* \fBBtree::db\fP"
.PP
.SS "\fBu8\fP \fBBtree::inTrans\fP"
.PP
.SS "\fBBtLock\fP \fBBtree::lock\fP"
.PP
.SS "\fBu8\fP \fBBtree::locked\fP"
.PP
.SS "int \fBBtree::nBackup\fP"
.PP
.SS "\fBBtShared\fP* \fBBtree::pBt\fP"
.PP
.SS "\fBBtShared\fP* \fBBtree::pBt\fP"
.PP
.SS "\fBBtree\fP* \fBBtree::pNext\fP"
.PP
.SS "\fBBtree\fP* \fBBtree::pNext\fP"
.PP
.SS "\fBBtree\fP* \fBBtree::pPrev\fP"
.PP
.SS "\fBBtree\fP* \fBBtree::pPrev\fP"
.PP
.SS "\fBu8\fP \fBBtree::sharable\fP"
.PP
.SS "int \fBBtree::wantToLock\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
