.TH "controller/buddyinc.h" 3 "Wed Sep 14 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controller/buddyinc.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <upkeeper_config.h>\fP
.br
\fC#include <upkeeper/upk_uuid.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <stdint.h>\fP
.br
\fC#include <stdbool.h>\fP
.br
\fC#include <signal.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <sys/wait.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/un.h>\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <sys/stat.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <fcntl.h>\fP
.br
\fC#include <errno.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
