.TH "controller/buddy.c" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controller/buddy.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'buddy.h'\fP
.br
\fC#include <assert.h>\fP
.br
\fC#include <stdarg.h>\fP
.br
\fC#include <upkeeper/upk_error.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBUDDY_RETRY_TIMEOUT_SEC\fP   1"
.br
.ti -1c
.RI "#define \fBBUDDY_RETRY_TIMEOUT_NSEC\fP   0"
.br
.ti -1c
.RI "#define \fBBUDDY_SELECT_TIMEOUT_SEC\fP   1"
.br
.ti -1c
.RI "#define \fBBUDDY_SELECT_TIMEOUT_USEC\fP   0"
.br
.ti -1c
.RI "#define \fBRESPAWN_WINDOW\fP   5"
.br
.ti -1c
.RI "#define \fBMAX_RESPAWN_COUNT\fP   10"
.br
.ti -1c
.RI "#define \fBRESPAWN_RATELIMIT\fP   300"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbuddy_init\fP (\fBdiag_output_callback_t\fP logger)"
.br
.ti -1c
.RI "int32_t \fBbuddy_event_loop\fP (void)"
.br
.ti -1c
.RI "void \fBbuddy_cleanup\fP (void)"
.br
.ti -1c
.RI "static void \fBbuddy_init_paths\fP (void)"
.br
.ti -1c
.RI "static char * \fBbuddy_path\fP (const char *suffixfmt,...)"
.br
.ti -1c
.RI "static void \fBbuddy_init_socket\fP (void)"
.br
.ti -1c
.RI "static bool \fBbuddy_phone_home\fP (void)"
.br
.ti -1c
.RI "static void \fBbuddy_record_state\fP (void)"
.br
.ti -1c
.RI "static void \fBbuddy_zero_info\fP (void)"
.br
.ti -1c
.RI "static void \fBbuddy_init_ringbuffer\fP (void)"
.br
.ti -1c
.RI "static void \fBbuddy_free_ringbuffer\fP (void)"
.br
.ti -1c
.RI "static void \fBbuddy_accept\fP (void)"
.br
.ti -1c
.RI "static int \fBbuddy_build_fd_set\fP (\fBfd_set\fP *socks, bool listen_sock)"
.br
.ti -1c
.RI "static bool \fBbuddy_handle_flags\fP (void)"
.br
.ti -1c
.RI "static void \fBbuddy_stop_proc\fP (void)"
.br
.ti -1c
.RI "static void \fBbuddy_reload_proc\fP (void)"
.br
.ti -1c
.RI "static void \fBbuddy_cust_action\fP (\fBuint32_t\fP act_num)"
.br
.ti -1c
.RI "static void \fBbuddy_handle_command\fP (void)"
.br
.ti -1c
.RI "static void \fBbuddy_setreguid\fP (void)"
.br
.ti -1c
.RI "static void \fBbuddy_setup_fds\fP (void)"
.br
.ti -1c
.RI "static int32_t \fBread_ctrl\fP (\fBbuddy_cmnd_t\fP *buf)"
.br
.ti -1c
.RI "static int32_t \fBwrite_ctrl\fP (\fBbuddy_info_t\fP *buf)"
.br
.ti -1c
.RI "static \fBpid_t\fP \fBbuddy_exec_action\fP (void)"
.br
.ti -1c
.RI "static bool \fBbuddy_start_proc\fP (void)"
.br
.ti -1c
.RI "static void \fBresolve_symlink\fP (void)"
.br
.ti -1c
.RI "static void \fBbuddy_flush_ringbuffer\fP (void)"
.br
.ti -1c
.RI "static void \fBsa_sigaction_func\fP (int signal, \fBsiginfo_t\fP *\fBsiginfo\fP, void *\fBucontext\fP)"
.br
.ti -1c
.RI "void \fBcommit_buddycide\fP (int32_t signum)"
.br
.ti -1c
.RI "static bool \fBbuddy_disconnect\fP (\fBsize_t\fP count)"
.br
.ti -1c
.RI "static void \fBbuddy_supp_groups\fP (void)"
.br
.ti -1c
.RI "static void \fBphone_home_if_appropriate\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBupk_uuid_t\fP \fBbuddy_uuid\fP"
.br
.ti -1c
.RI "char * \fBbuddy_service_name\fP = NULL"
.br
.ti -1c
.RI "char \fBbuddy_root_path\fP [BUDDY_MAX_PATH_LEN] = ''"
.br
.ti -1c
.RI "\fBuid_t\fP \fBbuddy_setuid\fP"
.br
.ti -1c
.RI "\fBgid_t\fP \fBbuddy_setgid\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBringbuffer_size\fP = 32"
.br
.ti -1c
.RI "char ** \fBproc_envp\fP = NULL"
.br
.ti -1c
.RI "long \fBreconnect_retries\fP = 5"
.br
.ti -1c
.RI "bool \fBrandomize_ratelimit\fP = false"
.br
.ti -1c
.RI "bool \fBinitialize_supplemental_groups\fP = false"
.br
.ti -1c
.RI "bool \fBclear_supplemental_groups\fP = false"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBuser_ratelimit\fP = 0"
.br
.ti -1c
.RI "static \fBtime_t\fP \fBrespawn_timestamp\fP = 0"
.br
.ti -1c
.RI "static \fBuint32_t\fP \fBrapid_respawn_count\fP = 0"
.br
.ti -1c
.RI "static bool \fBforce_ratelimit\fP = false"
.br
.ti -1c
.RI "static \fBsize_t\fP \fBringbuffer_pending\fP = 0"
.br
.ti -1c
.RI "static bool \fBchld_terminated\fP = false"
.br
.ti -1c
.RI "static \fBpid_t\fP \fBproc_pid\fP = 0"
.br
.ti -1c
.RI "static \fBbuddy_cmnd_t\fP \fBlast_command\fP = UPK_CTRL_NONE"
.br
.ti -1c
.RI "static \fBbuddy_cmnd_t\fP \fBthis_command\fP = UPK_CTRL_NONE"
.br
.ti -1c
.RI "static int \fBbuddy_shutdown\fP = 0"
.br
.ti -1c
.RI "static \fBbuddy_info_t\fP * \fBinfo_ringbuffer\fP = NULL"
.br
.ti -1c
.RI "static int \fBbuddy_sockfd\fP = -1"
.br
.ti -1c
.RI "static int \fBbuddy_ctrlfd\fP = -1"
.br
.ti -1c
.RI "static char \fBbuddy_path_buf\fP [BUDDY_MAX_PATH_LEN] = ''"
.br
.ti -1c
.RI "static char \fBbuddy_path_prefix\fP [BUDDY_MAX_PATH_LEN] = ''"
.br
.ti -1c
.RI "static char \fBbuddy_string_buf\fP [BUDDY_MAX_PATH_LEN] = ''"
.br
.ti -1c
.RI "static struct \fBsockaddr_un\fP \fBbuddy_sockaddr\fP = { 0 }"
.br
.ti -1c
.RI "static socklen_t \fBbuddy_sockaddr_len\fP = 0"
.br
.ti -1c
.RI "static int \fBsockopts\fP = 0"
.br
.ti -1c
.RI "static int \fBhighest_fd\fP = 0"
.br
.ti -1c
.RI "static struct \fBtimeval\fP \fBtimeout\fP = {.tv_sec = BUDDY_SELECT_TIMEOUT_SEC,.tv_usec = BUDDY_SELECT_TIMEOUT_USEC }"
.br
.ti -1c
.RI "static struct \fBtimespec\fP \fBnanotimeout\fP"
.br
.ti -1c
.RI "static \fBsize_t\fP \fBncount\fP = 0"
.br
.ti -1c
.RI "static \fBbuddy_runstate_t\fP \fBdesired_state\fP = BUDDY_STOPPED"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define BUDDY_RETRY_TIMEOUT_NSEC   0"
.SS "#define BUDDY_RETRY_TIMEOUT_SEC   1"
.SS "#define BUDDY_SELECT_TIMEOUT_SEC   1"
.PP
Referenced by buddy_event_loop(), read_ctrl(), and write_ctrl().
.SS "#define BUDDY_SELECT_TIMEOUT_USEC   0"
.PP
Referenced by buddy_event_loop(), read_ctrl(), and write_ctrl().
.SS "#define MAX_RESPAWN_COUNT   10"
.PP
Referenced by buddy_start_proc().
.SS "#define RESPAWN_RATELIMIT   300"
.PP
Referenced by buddy_handle_flags(), and buddy_start_proc().
.SS "#define RESPAWN_WINDOW   5"
.PP
Referenced by buddy_start_proc().
.SH "Function Documentation"
.PP 
.SS "static void buddy_accept (void)\fC [inline, static]\fP"
.PP
References accept(), buddy_ctrlfd, buddy_sockaddr_len, buddy_sockfd, fcntl(), sockopts, and upk_debug1.
.PP
Referenced by buddy_event_loop().
.SS "static int buddy_build_fd_set (\fBfd_set\fP *socks, boollisten_sock)\fC [inline, static]\fP"
.PP
References buddy_ctrlfd, and buddy_sockfd.
.PP
Referenced by buddy_event_loop(), read_ctrl(), and write_ctrl().
.SS "void buddy_cleanup (void)"
.PP
References buddy_flush_ringbuffer(), buddy_free_ringbuffer(), buddy_path(), buddy_service_name, buddy_stop_proc(), free(), and proc_pid.
.PP
Referenced by buddy_init(), commit_buddycide(), and main().
.SS "static void buddy_cust_action (\fBuint32_t\fPact_num)\fC [inline, static]\fP"
.PP
References buddy_exec_action(), and buddy_path().
.PP
Referenced by buddy_handle_command().
.SS "static bool buddy_disconnect (\fBsize_t\fPcount)\fC [inline, static]\fP"
.PP
References buddy_ctrlfd, SHUT_RDWR, shutdown(), and upk_debug1.
.PP
Referenced by buddy_flush_ringbuffer(), read_ctrl(), and write_ctrl().
.SS "int32_t buddy_event_loop (void)"
.PP
References buddy_accept(), buddy_build_fd_set(), buddy_ctrlfd, buddy_flush_ringbuffer(), buddy_handle_command(), buddy_handle_flags(), BUDDY_SELECT_TIMEOUT_SEC, BUDDY_SELECT_TIMEOUT_USEC, buddy_shutdown, buddy_sockfd, commit_buddycide(), highest_fd, read_ctrl(), select(), this_command, timeval::tv_sec, timeval::tv_usec, and upk_debug1.
.PP
Referenced by main().
.SS "static \fBpid_t\fP buddy_exec_action (void)\fC [static]\fP"
.PP
References BUDDY_MAX_PATH_LEN, buddy_path_buf, buddy_setreguid(), buddy_setup_fds(), buddy_string_buf, buddy_supp_groups(), proc_envp, proc_pid, sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, sigaction(), sigemptyset(), sigfillset(), sigprocmask(), sigset(), stat::st_mode, stat(), upk_alert, upk_debug0, and upk_notice.
.PP
Referenced by buddy_cust_action(), buddy_reload_proc(), buddy_start_proc(), and buddy_stop_proc().
.SS "static void buddy_flush_ringbuffer (void)\fC [static]\fP"
.PP
References buddy_ctrlfd, buddy_disconnect(), buddy_zero_info(), info_ringbuffer, _buddy_info::next, phone_home_if_appropriate(), _buddy_info::populated, read_ctrl(), _buddy_info::remaining, ringbuffer_pending, sigfillset(), sigprocmask(), sigset(), this_command, UPK_CTRL_ACK, upk_debug1, and write_ctrl().
.PP
Referenced by buddy_cleanup(), and buddy_event_loop().
.SS "static void buddy_free_ringbuffer (void)\fC [inline, static]\fP"
.PP
References free(), _buddy_info::next, and ringbuffer_size.
.PP
Referenced by buddy_cleanup().
.SS "static void buddy_handle_command (void)\fC [inline, static]\fP"
.PP
References buddy_cust_action(), BUDDY_RANONCE, buddy_reload_proc(), BUDDY_RUNNING, buddy_shutdown, buddy_start_proc(), buddy_stop_proc(), BUDDY_STOPPED, desired_state, last_command, proc_pid, this_command, UPK_CTRL_ACTION_RELOAD, UPK_CTRL_ACTION_RUNONCE, UPK_CTRL_ACTION_START, UPK_CTRL_ACTION_STOP, UPK_CTRL_CUSTOM_ACTION_00, UPK_CTRL_CUSTOM_ACTION_31, UPK_CTRL_SHUTDOWN, UPK_CTRL_SIGNAL_01, UPK_CTRL_SIGNAL_32, UPK_CTRL_STATUS_REQ, upk_debug1, and upk_verbose.
.PP
Referenced by buddy_event_loop().
.SS "static bool buddy_handle_flags (void)\fC [inline, static]\fP"
.PP
References BUDDY_RUNNING, buddy_shutdown, buddy_start_proc(), chld_terminated, desired_state, force_ratelimit, RESPAWN_RATELIMIT, respawn_timestamp, and upk_notice.
.PP
Referenced by buddy_event_loop().
.SS "void buddy_init (\fBdiag_output_callback_t\fPlogger)"
.PP
References buddy_cleanup(), buddy_ctrlfd, buddy_init_paths(), buddy_init_ringbuffer(), buddy_init_socket(), buddy_path(), buddy_setgid, buddy_setuid, buddy_sockfd, sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, sigaction::sa_sigaction, sa_sigaction_func(), sigaction(), sigaddset(), sigemptyset(), sigfillset(), sigset(), upk_notice, upk_reg_diag_callback(), upk_verbose, and upk_warn.
.PP
Referenced by main().
.SS "static void buddy_init_paths (void)\fC [inline, static]\fP"
.PP
References BUDDY_MAX_PATH_LEN, buddy_path_prefix, buddy_root_path, buddy_service_name, strnlen(), upk_fatal, and UPK_MAX_STRING_LEN.
.PP
Referenced by buddy_init().
.SS "static void buddy_init_ringbuffer (void)\fC [inline, static]\fP"
.PP
References calloc(), _buddy_info::next, ringbuffer_size, and _buddy_info::slot_n.
.PP
Referenced by buddy_init().
.SS "static void buddy_init_socket (void)\fC [inline, static]\fP"
.PP
References bind(), buddy_path(), buddy_sockaddr, buddy_sockaddr_len, buddy_sockfd, fcntl(), listen(), SOCK_STREAM, socket(), sockaddr_un::sun_family, sockaddr_un::sun_path, umask(), and upk_debug0.
.PP
Referenced by buddy_init().
.SS "static char * buddy_path (const char *suffixfmt, ...)\fC [inline, static]\fP"
.PP
References buddy_path_buf, buddy_path_prefix, and buddy_string_buf.
.PP
Referenced by buddy_cleanup(), buddy_cust_action(), buddy_init(), buddy_init_socket(), buddy_phone_home(), buddy_reload_proc(), buddy_setup_fds(), buddy_start_proc(), buddy_stop_proc(), and spawn_buddy().
.SS "static bool buddy_phone_home (void)\fC [inline, static]\fP"
.PP
References buddy_ctrlfd, buddy_path(), buddy_sockaddr_len, buddy_string_buf, connect(), resolve_symlink(), SOCK_STREAM, socket(), sockaddr_un::sun_family, and sockaddr_un::sun_path.
.PP
Referenced by phone_home_if_appropriate().
.SS "static void buddy_record_state (void)\fC [inline, static]\fP"
.PP
References buddy_uuid, buddy_zero_info(), _buddy_info::command, desired_state, _buddy_info::desired_state, last_command, _buddy_info::populated, proc_pid, ringbuffer_pending, ringbuffer_size, _buddy_info::service_pid, _buddy_info::timestamp, upk_debug1, and _buddy_info::uuid.
.PP
Referenced by buddy_start_proc(), and sa_sigaction_func().
.SS "static void buddy_reload_proc (void)\fC [inline, static]\fP"
.PP
References buddy_exec_action(), buddy_path(), and proc_pid.
.PP
Referenced by buddy_handle_command().
.SS "static void buddy_setreguid (void)\fC [inline, static]\fP"
.PP
References buddy_setgid, and buddy_setuid.
.PP
Referenced by buddy_exec_action().
.SS "static void buddy_setup_fds (void)\fC [inline, static]\fP"
.PP
References buddy_path().
.PP
Referenced by buddy_exec_action().
.SS "static bool buddy_start_proc (void)\fC [static]\fP"
.PP
References buddy_exec_action(), buddy_path(), buddy_record_state(), buddy_service_name, force_ratelimit, MAX_RESPAWN_COUNT, _buddy_info::next, proc_pid, rapid_respawn_count, RESPAWN_RATELIMIT, respawn_timestamp, RESPAWN_WINDOW, sigaddset(), sigemptyset(), sigprocmask(), sigset(), upk_debug0, and upk_notice.
.PP
Referenced by buddy_handle_command(), and buddy_handle_flags().
.SS "static void buddy_stop_proc (void)\fC [inline, static]\fP"
.PP
References buddy_exec_action(), buddy_path(), proc_pid, timespec::tv_nsec, and timespec::tv_sec.
.PP
Referenced by buddy_cleanup(), and buddy_handle_command().
.SS "static void buddy_supp_groups (void)\fC [inline, static]\fP"
.PP
References buddy_setuid, clear_supplemental_groups, getpwuid(), initgroups(), initialize_supplemental_groups, and setgroups().
.PP
Referenced by buddy_exec_action().
.SS "static void buddy_zero_info (void)\fC [inline, static]\fP"
.PP
References _buddy_info::next, _buddy_info::populated, ringbuffer_pending, _buddy_info::slot_n, and upk_debug1.
.PP
Referenced by buddy_flush_ringbuffer(), and buddy_record_state().
.SS "void commit_buddycide (int32_tsignum)"
.PP
References buddy_cleanup(), getpid(), sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, sigaction(), sigemptyset(), sigfillset(), sigprocmask(), sigset(), and upk_debug1.
.PP
Referenced by buddy_event_loop().
.SS "static void phone_home_if_appropriate (void)\fC [inline, static]\fP"
.PP
References buddy_phone_home(), buddy_shutdown, reconnect_retries, ringbuffer_pending, ringbuffer_size, timespec::tv_nsec, timespec::tv_sec, and upk_verbose.
.PP
Referenced by buddy_flush_ringbuffer().
.SS "static int32_t read_ctrl (\fBbuddy_cmnd_t\fP *buf)\fC [inline, static]\fP"
.PP
References buddy_build_fd_set(), buddy_ctrlfd, buddy_disconnect(), BUDDY_SELECT_TIMEOUT_SEC, BUDDY_SELECT_TIMEOUT_USEC, highest_fd, ncount, select(), timeval::tv_sec, and timeval::tv_usec.
.PP
Referenced by buddy_event_loop(), and buddy_flush_ringbuffer().
.SS "static void resolve_symlink (void)\fC [static]\fP"
.PP
References buddy_path_buf, buddy_string_buf, lstat(), and stat::st_mode.
.PP
Referenced by buddy_phone_home().
.SS "static void sa_sigaction_func (intsignal, \fBsiginfo_t\fP *siginfo, void *ucontext)\fC [static]\fP"
.PP
References buddy_record_state(), buddy_shutdown, chld_terminated, _buddy_info::next, proc_pid, _buddy_info::siginfo, upk_debug1, _buddy_info::wait_pid, _buddy_info::wait_status, and waitpid().
.PP
Referenced by buddy_init().
.SS "static int32_t write_ctrl (\fBbuddy_info_t\fP *buf)\fC [inline, static]\fP"
.PP
References buddy_build_fd_set(), buddy_ctrlfd, buddy_disconnect(), BUDDY_SELECT_TIMEOUT_SEC, BUDDY_SELECT_TIMEOUT_USEC, highest_fd, ncount, select(), timeval::tv_sec, and timeval::tv_usec.
.PP
Referenced by buddy_flush_ringbuffer().
.SH "Variable Documentation"
.PP 
.SS "int \fBbuddy_ctrlfd\fP = -1\fC [static]\fP"
.PP
Referenced by buddy_accept(), buddy_build_fd_set(), buddy_disconnect(), buddy_event_loop(), buddy_flush_ringbuffer(), buddy_init(), buddy_phone_home(), read_ctrl(), and write_ctrl().
.SS "char \fBbuddy_path_buf\fP[BUDDY_MAX_PATH_LEN] = ''\fC [static]\fP"
.PP
Referenced by buddy_exec_action(), buddy_path(), and resolve_symlink().
.SS "char \fBbuddy_path_prefix\fP[BUDDY_MAX_PATH_LEN] = ''\fC [static]\fP"
.PP
Referenced by buddy_init_paths(), and buddy_path().
.SS "char \fBbuddy_root_path\fP[BUDDY_MAX_PATH_LEN] = ''"
.PP
Referenced by buddy_init_paths(), and opt_parse().
.SS "char* \fBbuddy_service_name\fP = NULL"
.PP
Referenced by buddy_cleanup(), buddy_init_paths(), buddy_start_proc(), and opt_parse().
.SS "\fBgid_t\fP \fBbuddy_setgid\fP"
.PP
Referenced by buddy_init(), buddy_setreguid(), and opt_parse().
.SS "\fBuid_t\fP \fBbuddy_setuid\fP"
.PP
Referenced by buddy_init(), buddy_setreguid(), buddy_supp_groups(), and opt_parse().
.SS "int \fBbuddy_shutdown\fP = 0\fC [static]\fP"
.PP
Referenced by buddy_event_loop(), buddy_handle_command(), buddy_handle_flags(), phone_home_if_appropriate(), and sa_sigaction_func().
.SS "struct \fBsockaddr_un\fP \fBbuddy_sockaddr\fP = { 0 }\fC [static]\fP"
.PP
Referenced by buddy_init_socket().
.SS "socklen_t \fBbuddy_sockaddr_len\fP = 0\fC [static]\fP"
.PP
Referenced by buddy_accept(), buddy_init_socket(), and buddy_phone_home().
.SS "int \fBbuddy_sockfd\fP = -1\fC [static]\fP"
.PP
Referenced by buddy_accept(), buddy_build_fd_set(), buddy_event_loop(), buddy_init(), and buddy_init_socket().
.SS "char \fBbuddy_string_buf\fP[BUDDY_MAX_PATH_LEN] = ''\fC [static]\fP"
.PP
Referenced by buddy_exec_action(), buddy_path(), buddy_phone_home(), and resolve_symlink().
.SS "\fBupk_uuid_t\fP \fBbuddy_uuid\fP"
.PP
Referenced by buddy_record_state(), opt_parse(), and spawn_buddy().
.SS "bool \fBchld_terminated\fP = false\fC [static]\fP"
.PP
Referenced by buddy_handle_flags(), and sa_sigaction_func().
.SS "bool \fBclear_supplemental_groups\fP = false"
.PP
Referenced by buddy_supp_groups(), and opt_parse().
.SS "\fBbuddy_runstate_t\fP \fBdesired_state\fP = BUDDY_STOPPED\fC [static]\fP"
.PP
Referenced by buddy_handle_command(), buddy_handle_flags(), and buddy_record_state().
.SS "bool \fBforce_ratelimit\fP = false\fC [static]\fP"
.PP
Referenced by buddy_handle_flags(), and buddy_start_proc().
.SS "int \fBhighest_fd\fP = 0\fC [static]\fP"
.PP
Referenced by buddy_event_loop(), read_ctrl(), and write_ctrl().
.SS "\fBbuddy_info_t\fP* \fBinfo_ringbuffer\fP = NULL\fC [static]\fP"
.PP
Referenced by buddy_flush_ringbuffer().
.SS "bool \fBinitialize_supplemental_groups\fP = false"
.PP
Referenced by buddy_supp_groups(), and opt_parse().
.SS "\fBbuddy_cmnd_t\fP \fBlast_command\fP = UPK_CTRL_NONE\fC [static]\fP"
.PP
Referenced by buddy_handle_command(), and buddy_record_state().
.SS "struct \fBtimespec\fP \fBnanotimeout\fP\fC [static]\fP"\fBInitial value:\fP
.PP
.nf
 {.tv_sec = BUDDY_RETRY_TIMEOUT_SEC,.tv_nsec =
        BUDDY_RETRY_TIMEOUT_NSEC }
.fi
.SS "\fBsize_t\fP \fBncount\fP = 0\fC [static]\fP"
.PP
Referenced by read_ctrl(), and write_ctrl().
.SS "char** \fBproc_envp\fP = NULL"
.PP
Referenced by buddy_exec_action(), and main().
.SS "\fBpid_t\fP \fBproc_pid\fP = 0\fC [static]\fP"
.PP
Referenced by buddy_cleanup(), buddy_exec_action(), buddy_handle_command(), buddy_record_state(), buddy_reload_proc(), buddy_start_proc(), buddy_stop_proc(), deserial_svcinfo_data(), sa_sigaction_func(), and serial_svcinfo_data().
.SS "bool \fBrandomize_ratelimit\fP = false"
.SS "\fBuint32_t\fP \fBrapid_respawn_count\fP = 0\fC [static]\fP"
.PP
Referenced by buddy_start_proc().
.SS "long \fBreconnect_retries\fP = 5"
.PP
Referenced by opt_parse(), and phone_home_if_appropriate().
.SS "\fBtime_t\fP \fBrespawn_timestamp\fP = 0\fC [static]\fP"
.PP
Referenced by buddy_handle_flags(), and buddy_start_proc().
.SS "\fBsize_t\fP \fBringbuffer_pending\fP = 0\fC [static]\fP"
.PP
Referenced by buddy_flush_ringbuffer(), buddy_record_state(), buddy_zero_info(), and phone_home_if_appropriate().
.SS "\fBsize_t\fP \fBringbuffer_size\fP = 32"
.PP
Referenced by buddy_free_ringbuffer(), buddy_init_ringbuffer(), buddy_record_state(), main(), opt_parse(), and phone_home_if_appropriate().
.SS "int \fBsockopts\fP = 0\fC [static]\fP"
.PP
Referenced by buddy_accept(), and upk_net_add_socket_handle().
.SS "\fBbuddy_cmnd_t\fP \fBthis_command\fP = UPK_CTRL_NONE\fC [static]\fP"
.PP
Referenced by buddy_event_loop(), buddy_flush_ringbuffer(), and buddy_handle_command().
.SS "struct \fBtimeval\fP \fBtimeout\fP = {.tv_sec = BUDDY_SELECT_TIMEOUT_SEC,.tv_usec = BUDDY_SELECT_TIMEOUT_USEC }\fC [static]\fP"
.SS "\fBuint32_t\fP \fBuser_ratelimit\fP = 0"
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
