.TH "callback_data" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
callback_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.ti -1c
.RI "int \fBechoOn\fP"
.br
.ti -1c
.RI "int \fBstatsOn\fP"
.br
.ti -1c
.RI "int \fBcnt\fP"
.br
.ti -1c
.RI "FILE * \fBout\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "int \fBwritableSchema\fP"
.br
.ti -1c
.RI "int \fBshowHeader\fP"
.br
.ti -1c
.RI "char * \fBzDestTable\fP"
.br
.ti -1c
.RI "char \fBseparator\fP [20]"
.br
.ti -1c
.RI "int \fBcolWidth\fP [100]"
.br
.ti -1c
.RI "int \fBactualWidth\fP [100]"
.br
.ti -1c
.RI "char \fBnullvalue\fP [20]"
.br
.ti -1c
.RI "\fBprevious_mode_data\fP \fBexplainPrev\fP"
.br
.ti -1c
.RI "char \fBoutfile\fP [FILENAME_MAX]"
.br
.ti -1c
.RI "const char * \fBzDbFilename\fP"
.br
.ti -1c
.RI "\fBsqlite3_stmt\fP * \fBpStmt\fP"
.br
.ti -1c
.RI "FILE * \fBpLog\fP"
.br
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.ti -1c
.RI "FILE * \fBout\fP"
.br
.ti -1c
.RI "char * \fBzDestTable\fP"
.br
.ti -1c
.RI "\fBprevious_mode_data\fP \fBexplainPrev\fP"
.br
.ti -1c
.RI "const char * \fBzDbFilename\fP"
.br
.ti -1c
.RI "\fBsqlite3_stmt\fP * \fBpStmt\fP"
.br
.ti -1c
.RI "FILE * \fBpLog\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBcallback_data::actualWidth\fP"
.PP
.SS "int \fBcallback_data::cnt\fP"
.PP
.SS "int \fBcallback_data::colWidth\fP"
.PP
.SS "\fBsqlite3\fP* \fBcallback_data::db\fP"
.PP
.SS "\fBsqlite3\fP* \fBcallback_data::db\fP"
.PP
.SS "int \fBcallback_data::echoOn\fP"
.PP
.SS "struct \fBprevious_mode_data\fP \fBcallback_data::explainPrev\fP"
.PP
.SS "struct \fBprevious_mode_data\fP \fBcallback_data::explainPrev\fP"
.PP
.SS "int \fBcallback_data::mode\fP"
.PP
.SS "char \fBcallback_data::nullvalue\fP"
.PP
.SS "FILE* \fBcallback_data::out\fP"
.PP
.SS "FILE* \fBcallback_data::out\fP"
.PP
.SS "char \fBcallback_data::outfile\fP"
.PP
.SS "FILE* \fBcallback_data::pLog\fP"
.PP
.SS "FILE* \fBcallback_data::pLog\fP"
.PP
.SS "\fBsqlite3_stmt\fP* \fBcallback_data::pStmt\fP"
.PP
.SS "\fBsqlite3_stmt\fP* \fBcallback_data::pStmt\fP"
.PP
.SS "char \fBcallback_data::separator\fP"
.PP
.SS "int \fBcallback_data::showHeader\fP"
.PP
.SS "int \fBcallback_data::statsOn\fP"
.PP
.SS "int \fBcallback_data::writableSchema\fP"
.PP
.SS "const char* \fBcallback_data::zDbFilename\fP"
.PP
.SS "const char* \fBcallback_data::zDbFilename\fP"
.PP
.SS "char* \fBcallback_data::zDestTable\fP"
.PP
.SS "char* \fBcallback_data::zDestTable\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
