.TH "CellInfo" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CellInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBu8\fP * \fBpCell\fP"
.br
.ti -1c
.RI "\fBi64\fP \fBnKey\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBnData\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBnPayload\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBnHeader\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBnLocal\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBiOverflow\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBnSize\fP"
.br
.ti -1c
.RI "\fBu8\fP * \fBpCell\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu16\fP \fBCellInfo::iOverflow\fP"
.PP
.SS "\fBu32\fP \fBCellInfo::nData\fP"
.PP
.SS "\fBu16\fP \fBCellInfo::nHeader\fP"
.PP
.SS "\fBi64\fP \fBCellInfo::nKey\fP"
.PP
.SS "\fBu16\fP \fBCellInfo::nLocal\fP"
.PP
.SS "\fBu32\fP \fBCellInfo::nPayload\fP"
.PP
.SS "\fBu16\fP \fBCellInfo::nSize\fP"
.PP
.SS "\fBu8\fP* \fBCellInfo::pCell\fP"
.PP
.SS "\fBu8\fP* \fBCellInfo::pCell\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
