.TH "cmsghdr" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmsghdr \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsize_t\fP \fBcmsg_len\fP"
.br
.ti -1c
.RI "int \fBcmsg_level\fP"
.br
.ti -1c
.RI "int \fBcmsg_type\fP"
.br
.ti -1c
.RI "__extension__ unsigned char \fB__cmsg_data\fP []"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "__extension__ unsigned char \fBcmsghdr::__cmsg_data\fP"
.SS "\fBsize_t\fP \fBcmsghdr::cmsg_len\fP"
.SS "int \fBcmsghdr::cmsg_level\fP"
.SS "int \fBcmsghdr::cmsg_type\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
