.TH "common/coe.test.c" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/coe.test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/wait.h>\fP
.br
\fC#include 'coe.h'\fP
.br
\fC#include 'nonblock.h'\fP
.br
\fC#include 'test.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int ac, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int ac, char ** argv)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
