.TH "common/coe.c" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/coe.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unistd.h>\fP
.br
\fC#include <fcntl.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcoe\fP (int fd)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int coe (int fd)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
