.TH "CollSeq" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CollSeq \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBzName\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBenc\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBtype\fP"
.br
.ti -1c
.RI "void * \fBpUser\fP"
.br
.ti -1c
.RI "int(* \fBxCmp\fP )(void *, int, const void *, int, const void *)"
.br
.ti -1c
.RI "void(* \fBxDel\fP )(void *)"
.br
.ti -1c
.RI "char * \fBzName\fP"
.br
.ti -1c
.RI "void * \fBpUser\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu8\fP \fBCollSeq::enc\fP"
.PP
.SS "void* \fBCollSeq::pUser\fP"
.PP
.SS "void* \fBCollSeq::pUser\fP"
.PP
.SS "\fBu8\fP \fBCollSeq::type\fP"
.PP
.SS "int(* \fBCollSeq::xCmp\fP"
.PP
.SS "void(* \fBCollSeq::xDel\fP"
.PP
.SS "char* \fBCollSeq::zName\fP"
.PP
.SS "char* \fBCollSeq::zName\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
