.TH "Column" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Column \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBzName\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpDflt\fP"
.br
.ti -1c
.RI "char * \fBzDflt\fP"
.br
.ti -1c
.RI "char * \fBzType\fP"
.br
.ti -1c
.RI "char * \fBzColl\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBnotNull\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBisPrimKey\fP"
.br
.ti -1c
.RI "char \fBaffinity\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBisHidden\fP"
.br
.ti -1c
.RI "char * \fBzName\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpDflt\fP"
.br
.ti -1c
.RI "char * \fBzDflt\fP"
.br
.ti -1c
.RI "char * \fBzType\fP"
.br
.ti -1c
.RI "char * \fBzColl\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char \fBColumn::affinity\fP"
.PP
.SS "\fBu8\fP \fBColumn::isHidden\fP"
.PP
.SS "\fBu8\fP \fBColumn::isPrimKey\fP"
.PP
.SS "\fBu8\fP \fBColumn::notNull\fP"
.PP
.SS "\fBExpr\fP* \fBColumn::pDflt\fP"
.PP
.SS "\fBExpr\fP* \fBColumn::pDflt\fP"
.PP
.SS "char* \fBColumn::zColl\fP"
.PP
.SS "char* \fBColumn::zColl\fP"
.PP
.SS "char* \fBColumn::zDflt\fP"
.PP
.SS "char* \fBColumn::zDflt\fP"
.PP
.SS "char* \fBColumn::zName\fP"
.PP
.SS "char* \fBColumn::zName\fP"
.PP
.SS "char* \fBColumn::zType\fP"
.PP
.SS "char* \fBColumn::zType\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
