.TH "compareInfo" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
compareInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBmatchAll\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBmatchOne\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBmatchSet\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBnoCase\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu8\fP \fBcompareInfo::matchAll\fP"
.PP
.SS "\fBu8\fP \fBcompareInfo::matchOne\fP"
.PP
.SS "\fBu8\fP \fBcompareInfo::matchSet\fP"
.PP
.SS "\fBu8\fP \fBcompareInfo::noCase\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
