.TH "libupkeeper/tests/config.c" 3 "Tue Nov 1 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libupkeeper/tests/config.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <check.h>\fP
.br
\fC#include <upkeeper.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBtest_config_file\fP   test.conf"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Suite * \fBupk_proto_helpers_suite\fP (void)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define test_config_file   test.conf"
.SH "Function Documentation"
.PP 
.SS "int main (void)"
.PP
References suite(), and upk_proto_helpers_suite().
.SS "Suite* upk_proto_helpers_suite (void)"
.PP
References suite(), v0_proto_pubmsgs(), v0_proto_replies(), and v0_proto_requests().
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
