.TH "controller/controller_main.c" 3 "Tue Nov 1 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controller/controller_main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'controller.h'\fP
.br
\fC#include 'ctrl_protocol.h'\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <errno.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv, char **envp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv, char **envp)"
.PP
References create_buddy(), ctrl_sock_setup(), event_loop(), _upk_controller_config::svclist, upk_ctrl_free_config(), upk_ctrl_init(), upk_diag_verbosity, UPK_DIAGLVL_DEBUG1, upk_runtime_configuration, and UPKLIST_FOREACH.
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
