.TH "libupkeeper/upkeeper/controller.c" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libupkeeper/upkeeper/controller.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'upk_std_include.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBCONTROLLER\fP   yay"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define CONTROLLER   yay"
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
