.TH "controller/ctrl_sql.h" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controller/ctrl_sql.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBctrl_create_audit_sql\fP [] = 'INSERT INTO upk_audit._schema (version, create_date, table_name, table_id) VALUES (1, 1312914180, \\'service\\', \\'service_s1\\');\\n'"
.br
.ti -1c
.RI "const char \fBctrl_create_cfg_sql\fP [] = '\\n'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char \fBctrl_create_audit_sql\fP[] = 'INSERT INTO upk_audit._schema (version, create_date, table_name, table_id) VALUES (1, 1312914180, \\'service\\', \\'service_s1\\');\\n'"
.PP
Referenced by upk_ctrl_init_db().
.SS "const char \fBctrl_create_cfg_sql\fP[] = '\\n'"
.PP
Referenced by upk_ctrl_init_db().
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
