.TH "controller/ctrl_data.h" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controller/ctrl_data.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBupk_db_get_single_text\fP (\fBsqlite3\fP *dbh, char *value, const char *sql,...)"
.br
.RI "\fIlookup a table_id from the schema table. \fP"
.ti -1c
.RI "int \fBupk_db_get_audit_service_table\fP (\fBsqlite3\fP *dbh, char *table_id)"
.br
.RI "\fIlookup the table_id for upk_audit.service from the schema table. \fP"
.ti -1c
.RI "int \fBupk_db_get_cfg_services_table\fP (\fBsqlite3\fP *dbh, char *table_id)"
.br
.RI "\fIlookup the table_id for upk_cfg.services from the schema table. \fP"
.ti -1c
.RI "int \fBupk_db_get_cfg_svc_options_table\fP (\fBsqlite3\fP *dbh, char *table_id)"
.br
.RI "\fIlookup the table_id for upk_cfg.svc_optionsfrom the schema table. \fP"
.ti -1c
.RI "char * \fBupk_db_svc_uuid_lookup\fP (\fBsqlite3\fP *dbh, const char *svcid, const char *package)"
.br
.RI "\fIlookup a service <package>-<name> \fP"
.ti -1c
.RI "_Bool \fBupk_db_insert_cfg\fP (\fBsqlite3\fP *dbh, \fBupk_svc_desc_t\fP *svc)"
.br
.RI "\fIInsert a configuration into the database. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
