.TH "controller/ctrl_eventloop.c" 3 "Tue Nov 1 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controller/ctrl_eventloop.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'controller.h'\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <errno.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcontroller_packet_callback\fP (\fBupk_conn_handle_meta_t\fP *clients, \fBupk_payload_t\fP *)"
.br
.ti -1c
.RI "static void \fBaccept_conn\fP (int32_t listen_sock, \fBupk_conn_handle_meta_t\fP *clients)"
.br
.ti -1c
.RI "void \fBevent_loop\fP (int32_t listen_sock)"
.br
.ti -1c
.RI "int32_t \fBctrl_sock_setup\fP ()"
.br
.ti -1c
.RI "void \fBhandle_signals\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void accept_conn (int32_tlisten_sock, \fBupk_conn_handle_meta_t\fP *clients)\fC [static]\fP"
.PP
References controller_packet_callback(), and upk_net_add_socket_handle().
.PP
Referenced by event_loop().
.SS "void controller_packet_callback (\fBupk_conn_handle_meta_t\fP *clients, \fBupk_payload_t\fP *msg)"
.PP
References _upk_conn_handle::cl_name, upk_req_preamble_t::client_name, upk_req_preamble_t::max_supported_ver, upk_req_preamble_t::min_supported_ver, upk_packet_t::payload, _upk_payload::payload, reload_buddy_svc(), _upk_payload_types::req_action, _upk_payload_types::req_preamble, start_buddy_svc(), stop_buddy_svc(), _upk_controller_config::svclist, _upk_payload::type, upk_create_repl_preamble(), upk_create_repl_result(), upk_create_req_disconnect(), upk_debug1, UPK_MAX_STRING_LEN, UPK_MAX_SUPPORTED_PROTO, UPK_MIN_SUPPORTED_PROTO, upk_net_shutdown_callback(), upk_pkt_free(), upk_queue_packet(), UPK_REQ_ACTION, UPK_REQ_DISCONNECT, UPK_REQ_PREAMBLE, upk_runtime_configuration, upk_svc_desc_meta_t, and UPKLIST_FOREACH.
.PP
Referenced by accept_conn().
.SS "int32_t ctrl_sock_setup (void)"
.PP
References _upk_controller_config::controller_socket, IF_UPK_ERROR, UPK_ERR_INIT, UPK_FUNC_ASSERT, UPK_FUNC_ASSERT_MSG, upk_runtime_configuration, and UPK_SOCKET_FAILURE.
.PP
Referenced by main().
.SS "void event_loop (int32_tlisten_sock)"
.PP
References accept_conn(), _upk_controller_config::BuddyPollingInterval, handle_buddies(), handle_signals(), upk_conn_handle_meta_t, upk_debug1, upk_net_conn_handle_init(), upk_net_event_dispatcher(), upk_net_flush_closed_sockets(), upk_runtime_configuration, and UPKLIST_FREE.
.PP
Referenced by main().
.SS "void handle_signals (void)"
.PP
Referenced by event_loop().
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
