.TH "controller/ctrl_protocol.c" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controller/ctrl_protocol.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'controller.h'\fP
.br
\fC#include <stdio.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
