.TH "DateTime" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DateTime \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsqlite3_int64\fP \fBiJD\fP"
.br
.ti -1c
.RI "int \fBY\fP"
.br
.ti -1c
.RI "int \fBM\fP"
.br
.ti -1c
.RI "int \fBD\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "int \fBm\fP"
.br
.ti -1c
.RI "int \fBtz\fP"
.br
.ti -1c
.RI "double \fBs\fP"
.br
.ti -1c
.RI "char \fBvalidYMD\fP"
.br
.ti -1c
.RI "char \fBvalidHMS\fP"
.br
.ti -1c
.RI "char \fBvalidJD\fP"
.br
.ti -1c
.RI "char \fBvalidTZ\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBDateTime::D\fP"
.PP
.SS "int \fBDateTime::h\fP"
.PP
.SS "\fBsqlite3_int64\fP \fBDateTime::iJD\fP"
.PP
.SS "int \fBDateTime::m\fP"
.PP
.SS "int \fBDateTime::M\fP"
.PP
.SS "double \fBDateTime::s\fP"
.PP
.SS "int \fBDateTime::tz\fP"
.PP
.SS "char \fBDateTime::validHMS\fP"
.PP
.SS "char \fBDateTime::validJD\fP"
.PP
.SS "char \fBDateTime::validTZ\fP"
.PP
.SS "char \fBDateTime::validYMD\fP"
.PP
.SS "int \fBDateTime::Y\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
