.TH "dirent64" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dirent64 \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__ino64_t\fP \fBd_ino\fP"
.br
.ti -1c
.RI "\fB__off64_t\fP \fBd_off\fP"
.br
.ti -1c
.RI "unsigned short int \fBd_reclen\fP"
.br
.ti -1c
.RI "unsigned char \fBd_type\fP"
.br
.ti -1c
.RI "char \fBd_name\fP [256]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fB__ino64_t\fP \fBdirent64::d_ino\fP"
.SS "char \fBdirent64::d_name\fP"
.SS "\fB__off64_t\fP \fBdirent64::d_off\fP"
.SS "unsigned short int \fBdirent64::d_reclen\fP"
.SS "unsigned char \fBdirent64::d_type\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
