.TH "div_t" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
div_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBquot\fP"
.br
.ti -1c
.RI "int \fBrem\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBdiv_t::quot\fP"
.SS "int \fBdiv_t::rem\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
