.TH "common/err.h" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/err.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsysdie3\fP (int e, const char *a, const char *b, const char *c)"
.br
.ti -1c
.RI "void \fBsysdie2\fP (int e, const char *a, const char *b)"
.br
.ti -1c
.RI "void \fBsyswarn3\fP (const char *a, const char *b, const char *c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void sysdie2 (int e, const char * a, const char * b)"
.PP
.SS "void sysdie3 (int e, const char * a, const char * b, const char * c)"
.PP
.SS "void syswarn3 (const char * a, const char * b, const char * c)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
