.TH "common/err.c" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/err.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <sys/uio.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsyswarn3\fP (char *a, char *b, char *c)"
.br
.ti -1c
.RI "void \fBsysdie2\fP (int e, char *a, char *b)"
.br
.ti -1c
.RI "void \fBsysdie3\fP (int e, char *a, char *b, char *c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void sysdie2 (int e, char * a, char * b)"
.PP
.SS "void sysdie3 (int e, char * a, char * b, char * c)"
.PP
.SS "void syswarn3 (char * a, char * b, char * c)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
