.TH "et_info" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
et_info \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBfmttype\fP"
.br
.ti -1c
.RI "\fBetByte\fP \fBbase\fP"
.br
.ti -1c
.RI "\fBetByte\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBetByte\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBetByte\fP \fBcharset\fP"
.br
.ti -1c
.RI "\fBetByte\fP \fBprefix\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBetByte\fP \fBet_info::base\fP"
.PP
.SS "\fBetByte\fP \fBet_info::charset\fP"
.PP
.SS "\fBetByte\fP \fBet_info::flags\fP"
.PP
.SS "char \fBet_info::fmttype\fP"
.PP
.SS "\fBetByte\fP \fBet_info::prefix\fP"
.PP
.SS "\fBetByte\fP \fBet_info::type\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
