.TH "ExprList" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExprList \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnExpr\fP"
.br
.ti -1c
.RI "int \fBnAlloc\fP"
.br
.ti -1c
.RI "int \fBiECursor\fP"
.br
.ti -1c
.RI "\fBExprList::ExprList_item\fP * \fBa\fP"
.br
.ti -1c
.RI "\fBExprList::ExprList_item\fP * \fBa\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBExprList_item\fP"
.br
.ti -1c
.RI "struct \fBExprList_item\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBExprList::ExprList_item\fP * \fBExprList::a\fP"
.PP
.SS "struct \fBExprList::ExprList_item\fP * \fBExprList::a\fP"
.PP
.SS "int \fBExprList::iECursor\fP"
.PP
.SS "int \fBExprList::nAlloc\fP"
.PP
.SS "int \fBExprList::nExpr\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
