.TH "ExprSpan" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExprSpan \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBExpr\fP * \fBpExpr\fP"
.br
.ti -1c
.RI "const char * \fBzStart\fP"
.br
.ti -1c
.RI "const char * \fBzEnd\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpExpr\fP"
.br
.ti -1c
.RI "const char * \fBzStart\fP"
.br
.ti -1c
.RI "const char * \fBzEnd\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBExpr\fP* \fBExprSpan::pExpr\fP"
.PP
.SS "\fBExpr\fP* \fBExprSpan::pExpr\fP"
.PP
.SS "const char* \fBExprSpan::zEnd\fP"
.PP
.SS "const char* \fBExprSpan::zEnd\fP"
.PP
.SS "const char* \fBExprSpan::zStart\fP"
.PP
.SS "const char* \fBExprSpan::zStart\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
