.TH "fd_set" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fd_set \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__fd_mask\fP \fBfds_bits\fP [1024/(8 *sizeof(\fB__fd_mask\fP))]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fB__fd_mask\fP \fBfd_set::fds_bits\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
