.TH "FileChunk" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileChunk \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBFileChunk\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBzChunk\fP [JOURNAL_CHUNKSIZE]"
.br
.ti -1c
.RI "\fBFileChunk\fP * \fBpNext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBFileChunk\fP* \fBFileChunk::pNext\fP"
.PP
.SS "\fBFileChunk\fP* \fBFileChunk::pNext\fP"
.PP
.SS "\fBu8\fP \fBFileChunk::zChunk\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
