.TH "FKey" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FKey \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTable\fP * \fBpFrom\fP"
.br
.ti -1c
.RI "\fBFKey\fP * \fBpNextFrom\fP"
.br
.ti -1c
.RI "char * \fBzTo\fP"
.br
.ti -1c
.RI "\fBFKey\fP * \fBpNextTo\fP"
.br
.ti -1c
.RI "\fBFKey\fP * \fBpPrevTo\fP"
.br
.ti -1c
.RI "int \fBnCol\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBisDeferred\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBaAction\fP [2]"
.br
.ti -1c
.RI "\fBTrigger\fP * \fBapTrigger\fP [2]"
.br
.ti -1c
.RI "\fBFKey::sColMap\fP \fBaCol\fP [1]"
.br
.ti -1c
.RI "\fBTable\fP * \fBpFrom\fP"
.br
.ti -1c
.RI "\fBFKey\fP * \fBpNextFrom\fP"
.br
.ti -1c
.RI "char * \fBzTo\fP"
.br
.ti -1c
.RI "\fBFKey\fP * \fBpNextTo\fP"
.br
.ti -1c
.RI "\fBFKey\fP * \fBpPrevTo\fP"
.br
.ti -1c
.RI "\fBTrigger\fP * \fBapTrigger\fP [2]"
.br
.ti -1c
.RI "\fBFKey::sColMap\fP \fBaCol\fP [1]"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBsColMap\fP"
.br
.ti -1c
.RI "struct \fBsColMap\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu8\fP \fBFKey::aAction\fP"
.PP
.SS "struct \fBFKey::sColMap\fP  \fBFKey::aCol\fP[1]"
.PP
.SS "struct \fBFKey::sColMap\fP  \fBFKey::aCol\fP[1]"
.PP
.SS "\fBTrigger\fP* \fBFKey::apTrigger\fP[2]"
.PP
.SS "\fBTrigger\fP* \fBFKey::apTrigger\fP[2]"
.PP
.SS "\fBu8\fP \fBFKey::isDeferred\fP"
.PP
.SS "int \fBFKey::nCol\fP"
.PP
.SS "\fBTable\fP* \fBFKey::pFrom\fP"
.PP
.SS "\fBTable\fP* \fBFKey::pFrom\fP"
.PP
.SS "\fBFKey\fP* \fBFKey::pNextFrom\fP"
.PP
.SS "\fBFKey\fP* \fBFKey::pNextFrom\fP"
.PP
.SS "\fBFKey\fP* \fBFKey::pNextTo\fP"
.PP
.SS "\fBFKey\fP* \fBFKey::pNextTo\fP"
.PP
.SS "\fBFKey\fP* \fBFKey::pPrevTo\fP"
.PP
.SS "\fBFKey\fP* \fBFKey::pPrevTo\fP"
.PP
.SS "char* \fBFKey::zTo\fP"
.PP
.SS "char* \fBFKey::zTo\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
