.TH "flock" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
flock \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "short int \fBl_type\fP"
.br
.ti -1c
.RI "short int \fBl_whence\fP"
.br
.ti -1c
.RI "\fB__off_t\fP \fBl_start\fP"
.br
.ti -1c
.RI "\fB__off_t\fP \fBl_len\fP"
.br
.ti -1c
.RI "\fB__pid_t\fP \fBl_pid\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fB__off_t\fP \fBflock::l_len\fP"
.SS "\fB__pid_t\fP \fBflock::l_pid\fP"
.SS "\fB__off_t\fP \fBflock::l_start\fP"
.SS "short int \fBflock::l_type\fP"
.SS "short int \fBflock::l_whence\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
