.TH "FuncDestructor" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FuncDestructor \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnRef\fP"
.br
.ti -1c
.RI "void(* \fBxDestroy\fP )(void *)"
.br
.ti -1c
.RI "void * \fBpUserData\fP"
.br
.ti -1c
.RI "void * \fBpUserData\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBFuncDestructor::nRef\fP"
.PP
.SS "void* \fBFuncDestructor::pUserData\fP"
.PP
.SS "void* \fBFuncDestructor::pUserData\fP"
.PP
.SS "void(* \fBFuncDestructor::xDestroy\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
