.TH "FuncDef" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FuncDef \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBi16\fP \fBnArg\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBiPrefEnc\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBflags\fP"
.br
.ti -1c
.RI "void * \fBpUserData\fP"
.br
.ti -1c
.RI "\fBFuncDef\fP * \fBpNext\fP"
.br
.ti -1c
.RI "void(* \fBxFunc\fP )(\fBsqlite3_context\fP *, int, \fBsqlite3_value\fP **)"
.br
.ti -1c
.RI "void(* \fBxStep\fP )(\fBsqlite3_context\fP *, int, \fBsqlite3_value\fP **)"
.br
.ti -1c
.RI "void(* \fBxFinalize\fP )(\fBsqlite3_context\fP *)"
.br
.ti -1c
.RI "char * \fBzName\fP"
.br
.ti -1c
.RI "\fBFuncDef\fP * \fBpHash\fP"
.br
.ti -1c
.RI "\fBFuncDestructor\fP * \fBpDestructor\fP"
.br
.ti -1c
.RI "void * \fBpUserData\fP"
.br
.ti -1c
.RI "\fBFuncDef\fP * \fBpNext\fP"
.br
.ti -1c
.RI "char * \fBzName\fP"
.br
.ti -1c
.RI "\fBFuncDef\fP * \fBpHash\fP"
.br
.ti -1c
.RI "\fBFuncDestructor\fP * \fBpDestructor\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu8\fP \fBFuncDef::flags\fP"
.PP
.SS "\fBu8\fP \fBFuncDef::iPrefEnc\fP"
.PP
.SS "\fBi16\fP \fBFuncDef::nArg\fP"
.PP
.SS "\fBFuncDestructor\fP* \fBFuncDef::pDestructor\fP"
.PP
.SS "\fBFuncDestructor\fP* \fBFuncDef::pDestructor\fP"
.PP
.SS "\fBFuncDef\fP* \fBFuncDef::pHash\fP"
.PP
.SS "\fBFuncDef\fP* \fBFuncDef::pHash\fP"
.PP
.SS "\fBFuncDef\fP* \fBFuncDef::pNext\fP"
.PP
.SS "\fBFuncDef\fP* \fBFuncDef::pNext\fP"
.PP
.SS "void* \fBFuncDef::pUserData\fP"
.PP
.SS "void* \fBFuncDef::pUserData\fP"
.PP
.SS "void(* \fBFuncDef::xFinalize\fP"
.PP
.SS "void(* \fBFuncDef::xFunc\fP"
.PP
.SS "void(* \fBFuncDef::xStep\fP"
.PP
.SS "char* \fBFuncDef::zName\fP"
.PP
.SS "char* \fBFuncDef::zName\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
