.TH "group_filter" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
group_filter \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP \fBgf_interface\fP"
.br
.ti -1c
.RI "struct \fBsockaddr_storage\fP \fBgf_group\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBgf_fmode\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBgf_numsrc\fP"
.br
.ti -1c
.RI "struct \fBsockaddr_storage\fP \fBgf_slist\fP [1]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint32_t\fP \fBgroup_filter::gf_fmode\fP"
.SS "struct \fBsockaddr_storage\fP \fBgroup_filter::gf_group\fP"
.SS "\fBuint32_t\fP \fBgroup_filter::gf_interface\fP"
.SS "\fBuint32_t\fP \fBgroup_filter::gf_numsrc\fP"
.SS "struct \fBsockaddr_storage\fP \fBgroup_filter::gf_slist\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
