.TH "group_source_req" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
group_source_req \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP \fBgsr_interface\fP"
.br
.ti -1c
.RI "struct \fBsockaddr_storage\fP \fBgsr_group\fP"
.br
.ti -1c
.RI "struct \fBsockaddr_storage\fP \fBgsr_source\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBsockaddr_storage\fP \fBgroup_source_req::gsr_group\fP"
.SS "\fBuint32_t\fP \fBgroup_source_req::gsr_interface\fP"
.SS "struct \fBsockaddr_storage\fP \fBgroup_source_req::gsr_source\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
