.TH "group_req" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
group_req \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP \fBgr_interface\fP"
.br
.ti -1c
.RI "struct \fBsockaddr_storage\fP \fBgr_group\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBsockaddr_storage\fP \fBgroup_req::gr_group\fP"
.SS "\fBuint32_t\fP \fBgroup_req::gr_interface\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
