.TH "HashElem" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HashElem \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBHashElem\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBHashElem\fP * \fBprev\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "const char * \fBpKey\fP"
.br
.ti -1c
.RI "int \fBnKey\fP"
.br
.ti -1c
.RI "\fBHashElem\fP * \fBnext\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "const char * \fBpKey\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* \fBHashElem::data\fP"
.PP
.SS "void* \fBHashElem::data\fP"
.PP
.SS "\fBHashElem\fP* \fBHashElem::next\fP"
.PP
.SS "\fBHashElem\fP* \fBHashElem::next\fP"
.PP
.SS "int \fBHashElem::nKey\fP"
.PP
.SS "const char* \fBHashElem::pKey\fP"
.PP
.SS "const char* \fBHashElem::pKey\fP"
.PP
.SS "\fBHashElem\fP * \fBHashElem::prev\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
