.TH "in6_pktinfo" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
in6_pktinfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBin6_addr\fP \fBipi6_addr\fP"
.br
.ti -1c
.RI "unsigned int \fBipi6_ifindex\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBin6_addr\fP \fBin6_pktinfo::ipi6_addr\fP"
.SS "unsigned int \fBin6_pktinfo::ipi6_ifindex\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
