.TH "in6_addr" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
in6_addr \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBuint8_t\fP \fBu6_addr8\fP [16]"
.br
.ti -1c
.RI "   \fBuint16_t\fP \fBu6_addr16\fP [8]"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBu6_addr32\fP [4]"
.br
.ti -1c
.RI "} \fBin6_u\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBuint8_t\fP \fBu6_addr8\fP [16]"
.br
.ti -1c
.RI "   \fBuint16_t\fP \fBu6_addr16\fP [8]"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBu6_addr32\fP [4]"
.br
.ti -1c
.RI "} \fBin6_u\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "union { ... }   \fBin6_addr::in6_u\fP"
.SS "union { ... }   \fBin6_addr::in6_u\fP"
.SS "\fBuint16_t\fP \fBin6_addr::u6_addr16\fP[8]"
.SS "\fBuint32_t\fP \fBin6_addr::u6_addr32\fP[4]"
.SS "\fBuint8_t\fP \fBin6_addr::u6_addr8\fP[16]"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
