.TH "in_addr" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
in_addr \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBin_addr_t\fP \fBs_addr\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBin_addr_t\fP \fBin_addr::s_addr\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
