.TH "in_pktinfo" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
in_pktinfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBipi_ifindex\fP"
.br
.ti -1c
.RI "struct \fBin_addr\fP \fBipi_spec_dst\fP"
.br
.ti -1c
.RI "struct \fBin_addr\fP \fBipi_addr\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBin_addr\fP \fBin_pktinfo::ipi_addr\fP"
.SS "int \fBin_pktinfo::ipi_ifindex\fP"
.SS "struct \fBin_addr\fP \fBin_pktinfo::ipi_spec_dst\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
