.TH "Incrblob" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Incrblob \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "int \fBnByte\fP"
.br
.ti -1c
.RI "int \fBiOffset\fP"
.br
.ti -1c
.RI "\fBBtCursor\fP * \fBpCsr\fP"
.br
.ti -1c
.RI "\fBsqlite3_stmt\fP * \fBpStmt\fP"
.br
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.ti -1c
.RI "\fBBtCursor\fP * \fBpCsr\fP"
.br
.ti -1c
.RI "\fBsqlite3_stmt\fP * \fBpStmt\fP"
.br
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBsqlite3\fP* \fBIncrblob::db\fP"
.PP
.SS "\fBsqlite3\fP* \fBIncrblob::db\fP"
.PP
.SS "int \fBIncrblob::flags\fP"
.PP
.SS "int \fBIncrblob::iOffset\fP"
.PP
.SS "int \fBIncrblob::nByte\fP"
.PP
.SS "\fBBtCursor\fP* \fBIncrblob::pCsr\fP"
.PP
.SS "\fBBtCursor\fP* \fBIncrblob::pCsr\fP"
.PP
.SS "\fBsqlite3_stmt\fP* \fBIncrblob::pStmt\fP"
.PP
.SS "\fBsqlite3_stmt\fP* \fBIncrblob::pStmt\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
