.TH "IndexSample" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IndexSample \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   char * \fBz\fP"
.br
.ti -1c
.RI "   double \fBr\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBeType\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBnByte\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   char * \fBz\fP"
.br
.ti -1c
.RI "   double \fBr\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu8\fP \fBIndexSample::eType\fP"
.PP
.SS "\fBu8\fP \fBIndexSample::nByte\fP"
.PP
.SS "double \fBIndexSample::r\fP"
.PP
.SS "union { ... }   \fBIndexSample::u\fP"
.PP
.SS "union { ... }   \fBIndexSample::u\fP"
.PP
.SS "char* \fBIndexSample::z\fP"
.PP
.SS "char* \fBIndexSample::z\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
