.TH "Index" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Index \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBzName\fP"
.br
.ti -1c
.RI "int \fBnColumn\fP"
.br
.ti -1c
.RI "int * \fBaiColumn\fP"
.br
.ti -1c
.RI "unsigned * \fBaiRowEst\fP"
.br
.ti -1c
.RI "\fBTable\fP * \fBpTable\fP"
.br
.ti -1c
.RI "int \fBtnum\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBonError\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBautoIndex\fP"
.br
.ti -1c
.RI "char * \fBzColAff\fP"
.br
.ti -1c
.RI "\fBIndex\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBSchema\fP * \fBpSchema\fP"
.br
.ti -1c
.RI "\fBu8\fP * \fBaSortOrder\fP"
.br
.ti -1c
.RI "char ** \fBazColl\fP"
.br
.ti -1c
.RI "\fBIndexSample\fP * \fBaSample\fP"
.br
.ti -1c
.RI "char * \fBzName\fP"
.br
.ti -1c
.RI "int * \fBaiColumn\fP"
.br
.ti -1c
.RI "unsigned * \fBaiRowEst\fP"
.br
.ti -1c
.RI "\fBTable\fP * \fBpTable\fP"
.br
.ti -1c
.RI "char * \fBzColAff\fP"
.br
.ti -1c
.RI "\fBIndex\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBSchema\fP * \fBpSchema\fP"
.br
.ti -1c
.RI "\fBu8\fP * \fBaSortOrder\fP"
.br
.ti -1c
.RI "char ** \fBazColl\fP"
.br
.ti -1c
.RI "\fBIndexSample\fP * \fBaSample\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int* \fBIndex::aiColumn\fP"
.PP
.SS "int* \fBIndex::aiColumn\fP"
.PP
.SS "unsigned* \fBIndex::aiRowEst\fP"
.PP
.SS "unsigned* \fBIndex::aiRowEst\fP"
.PP
.SS "\fBIndexSample\fP* \fBIndex::aSample\fP"
.PP
.SS "\fBIndexSample\fP* \fBIndex::aSample\fP"
.PP
.SS "\fBu8\fP* \fBIndex::aSortOrder\fP"
.PP
.SS "\fBu8\fP* \fBIndex::aSortOrder\fP"
.PP
.SS "\fBu8\fP \fBIndex::autoIndex\fP"
.PP
.SS "char** \fBIndex::azColl\fP"
.PP
.SS "char** \fBIndex::azColl\fP"
.PP
.SS "int \fBIndex::nColumn\fP"
.PP
.SS "\fBu8\fP \fBIndex::onError\fP"
.PP
.SS "\fBIndex\fP* \fBIndex::pNext\fP"
.PP
.SS "\fBIndex\fP* \fBIndex::pNext\fP"
.PP
.SS "\fBSchema\fP* \fBIndex::pSchema\fP"
.PP
.SS "\fBSchema\fP* \fBIndex::pSchema\fP"
.PP
.SS "\fBTable\fP* \fBIndex::pTable\fP"
.PP
.SS "\fBTable\fP* \fBIndex::pTable\fP"
.PP
.SS "int \fBIndex::tnum\fP"
.PP
.SS "char* \fBIndex::zColAff\fP"
.PP
.SS "char* \fBIndex::zColAff\fP"
.PP
.SS "char* \fBIndex::zName\fP"
.PP
.SS "char* \fBIndex::zName\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
