.TH "InitData" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InitData \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.ti -1c
.RI "int \fBiDb\fP"
.br
.ti -1c
.RI "char ** \fBpzErrMsg\fP"
.br
.ti -1c
.RI "int \fBrc\fP"
.br
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.ti -1c
.RI "char ** \fBpzErrMsg\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBsqlite3\fP* \fBInitData::db\fP"
.PP
.SS "\fBsqlite3\fP* \fBInitData::db\fP"
.PP
.SS "int \fBInitData::iDb\fP"
.PP
.SS "char** \fBInitData::pzErrMsg\fP"
.PP
.SS "char** \fBInitData::pzErrMsg\fP"
.PP
.SS "int \fBInitData::rc\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
