.TH "IntegrityCk" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IntegrityCk \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBtShared\fP * \fBpBt\fP"
.br
.ti -1c
.RI "\fBPager\fP * \fBpPager\fP"
.br
.ti -1c
.RI "\fBPgno\fP \fBnPage\fP"
.br
.ti -1c
.RI "int * \fBanRef\fP"
.br
.ti -1c
.RI "int \fBmxErr\fP"
.br
.ti -1c
.RI "int \fBnErr\fP"
.br
.ti -1c
.RI "int \fBmallocFailed\fP"
.br
.ti -1c
.RI "\fBStrAccum\fP \fBerrMsg\fP"
.br
.ti -1c
.RI "\fBBtShared\fP * \fBpBt\fP"
.br
.ti -1c
.RI "\fBPager\fP * \fBpPager\fP"
.br
.ti -1c
.RI "int * \fBanRef\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int* \fBIntegrityCk::anRef\fP"
.PP
.SS "int* \fBIntegrityCk::anRef\fP"
.PP
.SS "\fBStrAccum\fP \fBIntegrityCk::errMsg\fP"
.PP
.SS "int \fBIntegrityCk::mallocFailed\fP"
.PP
.SS "int \fBIntegrityCk::mxErr\fP"
.PP
.SS "int \fBIntegrityCk::nErr\fP"
.PP
.SS "\fBPgno\fP \fBIntegrityCk::nPage\fP"
.PP
.SS "\fBBtShared\fP* \fBIntegrityCk::pBt\fP"
.PP
.SS "\fBBtShared\fP* \fBIntegrityCk::pBt\fP"
.PP
.SS "\fBPager\fP* \fBIntegrityCk::pPager\fP"
.PP
.SS "\fBPager\fP* \fBIntegrityCk::pPager\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
