.TH "iovec" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iovec \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBiov_base\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBiov_len\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void * \fBiovec::iov_base\fP"
.SS "\fBsize_t\fP \fBiovec::iov_len\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
