.TH "ip6_mtuinfo" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ip6_mtuinfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBsockaddr_in6\fP \fBip6m_addr\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBip6m_mtu\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBsockaddr_in6\fP \fBip6_mtuinfo::ip6m_addr\fP"
.SS "\fBuint32_t\fP \fBip6_mtuinfo::ip6m_mtu\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
