.TH "ip_mreq" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ip_mreq \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBin_addr\fP \fBimr_multiaddr\fP"
.br
.ti -1c
.RI "struct \fBin_addr\fP \fBimr_interface\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBin_addr\fP \fBip_mreq::imr_interface\fP"
.SS "struct \fBin_addr\fP \fBip_mreq::imr_multiaddr\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
