.TH "ip_msfilter" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ip_msfilter \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBin_addr\fP \fBimsf_multiaddr\fP"
.br
.ti -1c
.RI "struct \fBin_addr\fP \fBimsf_interface\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBimsf_fmode\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBimsf_numsrc\fP"
.br
.ti -1c
.RI "struct \fBin_addr\fP \fBimsf_slist\fP [1]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint32_t\fP \fBip_msfilter::imsf_fmode\fP"
.SS "struct \fBin_addr\fP \fBip_msfilter::imsf_interface\fP"
.SS "struct \fBin_addr\fP \fBip_msfilter::imsf_multiaddr\fP"
.SS "\fBuint32_t\fP \fBip_msfilter::imsf_numsrc\fP"
.SS "struct \fBin_addr\fP \fBip_msfilter::imsf_slist\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
