.TH "ip_opts" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ip_opts \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBin_addr\fP \fBip_dst\fP"
.br
.ti -1c
.RI "char \fBip_opts\fP [40]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBin_addr\fP \fBip_opts::ip_dst\fP"
.SS "char \fBip_opts::ip_opts\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
