.TH "ipv6_mreq" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ipv6_mreq \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBin6_addr\fP \fBipv6mr_multiaddr\fP"
.br
.ti -1c
.RI "unsigned int \fBipv6mr_interface\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned int \fBipv6_mreq::ipv6mr_interface\fP"
.SS "struct \fBin6_addr\fP \fBipv6_mreq::ipv6mr_multiaddr\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
