.TH "itimerspec" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
itimerspec \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBtimespec\fP \fBit_interval\fP"
.br
.ti -1c
.RI "struct \fBtimespec\fP \fBit_value\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBtimespec\fP \fBitimerspec::it_interval\fP"
.SS "struct \fBtimespec\fP \fBitimerspec::it_value\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
