.TH "KeyInfo" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeyInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBenc\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBnField\fP"
.br
.ti -1c
.RI "\fBu8\fP * \fBaSortOrder\fP"
.br
.ti -1c
.RI "\fBCollSeq\fP * \fBaColl\fP [1]"
.br
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.ti -1c
.RI "\fBu8\fP * \fBaSortOrder\fP"
.br
.ti -1c
.RI "\fBCollSeq\fP * \fBaColl\fP [1]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBCollSeq\fP* \fBKeyInfo::aColl\fP[1]"
.PP
.SS "\fBCollSeq\fP* \fBKeyInfo::aColl\fP[1]"
.PP
.SS "\fBu8\fP* \fBKeyInfo::aSortOrder\fP"
.PP
.SS "\fBu8\fP* \fBKeyInfo::aSortOrder\fP"
.PP
.SS "\fBsqlite3\fP* \fBKeyInfo::db\fP"
.PP
.SS "\fBsqlite3\fP* \fBKeyInfo::db\fP"
.PP
.SS "\fBu8\fP \fBKeyInfo::enc\fP"
.PP
.SS "\fBu16\fP \fBKeyInfo::nField\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
