.TH "ldiv_t" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ldiv_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long int \fBquot\fP"
.br
.ti -1c
.RI "long int \fBrem\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "long int \fBldiv_t::quot\fP"
.SS "long int \fBldiv_t::rem\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
