.TH "LikeOp" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LikeOp \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBToken\fP \fBeOperator\fP"
.br
.ti -1c
.RI "int \fBnot\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBToken\fP \fBLikeOp::eOperator\fP"
.PP
.SS "int \fBLikeOp::not\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
