.TH "LimitVal" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LimitVal \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBExpr\fP * \fBpLimit\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpOffset\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpLimit\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpOffset\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBExpr\fP* \fBLimitVal::pLimit\fP"
.PP
.SS "\fBExpr\fP* \fBLimitVal::pLimit\fP"
.PP
.SS "\fBExpr\fP* \fBLimitVal::pOffset\fP"
.PP
.SS "\fBExpr\fP* \fBLimitVal::pOffset\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
