.TH "linger" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
linger \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBl_onoff\fP"
.br
.ti -1c
.RI "int \fBl_linger\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBlinger::l_linger\fP"
.SS "int \fBlinger::l_onoff\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
