.TH "lldiv_t" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lldiv_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long long int \fBquot\fP"
.br
.ti -1c
.RI "long long int \fBrem\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "long long int \fBlldiv_t::quot\fP"
.SS "long long int \fBlldiv_t::rem\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
