.TH "Lookaside" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lookaside \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBu16\fP \fBsz\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBbEnabled\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBbMalloced\fP"
.br
.ti -1c
.RI "int \fBnOut\fP"
.br
.ti -1c
.RI "int \fBmxOut\fP"
.br
.ti -1c
.RI "\fBLookasideSlot\fP * \fBpFree\fP"
.br
.ti -1c
.RI "void * \fBpStart\fP"
.br
.ti -1c
.RI "void * \fBpEnd\fP"
.br
.ti -1c
.RI "\fBLookasideSlot\fP * \fBpFree\fP"
.br
.ti -1c
.RI "void * \fBpStart\fP"
.br
.ti -1c
.RI "void * \fBpEnd\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu8\fP \fBLookaside::bEnabled\fP"
.PP
.SS "\fBu8\fP \fBLookaside::bMalloced\fP"
.PP
.SS "int \fBLookaside::mxOut\fP"
.PP
.SS "int \fBLookaside::nOut\fP"
.PP
.SS "void* \fBLookaside::pEnd\fP"
.PP
.SS "void* \fBLookaside::pEnd\fP"
.PP
.SS "\fBLookasideSlot\fP* \fBLookaside::pFree\fP"
.PP
.SS "\fBLookasideSlot\fP* \fBLookaside::pFree\fP"
.PP
.SS "void* \fBLookaside::pStart\fP"
.PP
.SS "void* \fBLookaside::pStart\fP"
.PP
.SS "\fBu16\fP \fBLookaside::sz\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
