.TH "Mem" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mem \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBi64\fP \fBi\fP"
.br
.ti -1c
.RI "   int \fBnZero\fP"
.br
.ti -1c
.RI "   \fBFuncDef\fP * \fBpDef\fP"
.br
.ti -1c
.RI "   \fBRowSet\fP * \fBpRowSet\fP"
.br
.ti -1c
.RI "   \fBVdbeFrame\fP * \fBpFrame\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.ti -1c
.RI "double \fBr\fP"
.br
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.ti -1c
.RI "char * \fBz\fP"
.br
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBenc\fP"
.br
.ti -1c
.RI "void(* \fBxDel\fP )(void *)"
.br
.ti -1c
.RI "char * \fBzMalloc\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBi64\fP \fBi\fP"
.br
.ti -1c
.RI "   int \fBnZero\fP"
.br
.ti -1c
.RI "   \fBFuncDef\fP * \fBpDef\fP"
.br
.ti -1c
.RI "   \fBRowSet\fP * \fBpRowSet\fP"
.br
.ti -1c
.RI "   \fBVdbeFrame\fP * \fBpFrame\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.ti -1c
.RI "char * \fBz\fP"
.br
.ti -1c
.RI "char * \fBzMalloc\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBsqlite3\fP* \fBMem::db\fP"
.PP
.SS "\fBsqlite3\fP* \fBMem::db\fP"
.PP
.SS "\fBu8\fP \fBMem::enc\fP"
.PP
.SS "\fBu16\fP \fBMem::flags\fP"
.PP
.SS "\fBi64\fP \fBMem::i\fP"
.PP
.SS "int \fBMem::n\fP"
.PP
.SS "int \fBMem::nZero\fP"
.PP
.SS "\fBFuncDef\fP* \fBMem::pDef\fP"
.PP
.SS "\fBFuncDef\fP* \fBMem::pDef\fP"
.PP
.SS "\fBVdbeFrame\fP* \fBMem::pFrame\fP"
.PP
.SS "\fBVdbeFrame\fP* \fBMem::pFrame\fP"
.PP
.SS "\fBRowSet\fP* \fBMem::pRowSet\fP"
.PP
.SS "\fBRowSet\fP* \fBMem::pRowSet\fP"
.PP
.SS "double \fBMem::r\fP"
.PP
.SS "\fBu8\fP \fBMem::type\fP"
.PP
.SS "union { ... }   \fBMem::u\fP"
.PP
.SS "union { ... }   \fBMem::u\fP"
.PP
.SS "void(* \fBMem::xDel\fP"
.PP
.SS "char* \fBMem::z\fP"
.PP
.SS "char* \fBMem::z\fP"
.PP
.SS "char* \fBMem::zMalloc\fP"
.PP
.SS "char* \fBMem::zMalloc\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
