.TH "Mem0Global" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mem0Global \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsqlite3_mutex\fP * \fBmutex\fP"
.br
.ti -1c
.RI "\fBsqlite3_int64\fP \fBalarmThreshold\fP"
.br
.ti -1c
.RI "void(* \fBalarmCallback\fP )(void *, \fBsqlite3_int64\fP, int)"
.br
.ti -1c
.RI "void * \fBalarmArg\fP"
.br
.ti -1c
.RI "void * \fBpScratchEnd\fP"
.br
.ti -1c
.RI "\fBScratchFreeslot\fP * \fBpScratchFree\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBnScratchFree\fP"
.br
.ti -1c
.RI "int \fBnearlyFull\fP"
.br
.ti -1c
.RI "\fBsqlite3_mutex\fP * \fBmutex\fP"
.br
.ti -1c
.RI "void * \fBalarmArg\fP"
.br
.ti -1c
.RI "void * \fBpScratchEnd\fP"
.br
.ti -1c
.RI "\fBScratchFreeslot\fP * \fBpScratchFree\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* \fBMem0Global::alarmArg\fP"
.PP
.SS "void* \fBMem0Global::alarmArg\fP"
.PP
.SS "void(* \fBMem0Global::alarmCallback\fP"
.PP
.SS "\fBsqlite3_int64\fP \fBMem0Global::alarmThreshold\fP"
.PP
.SS "\fBsqlite3_mutex\fP* \fBMem0Global::mutex\fP"
.PP
.SS "\fBsqlite3_mutex\fP* \fBMem0Global::mutex\fP"
.PP
.SS "int \fBMem0Global::nearlyFull\fP"
.PP
.SS "\fBu32\fP \fBMem0Global::nScratchFree\fP"
.PP
.SS "void* \fBMem0Global::pScratchEnd\fP"
.PP
.SS "void* \fBMem0Global::pScratchEnd\fP"
.PP
.SS "\fBScratchFreeslot\fP* \fBMem0Global::pScratchFree\fP"
.PP
.SS "\fBScratchFreeslot\fP* \fBMem0Global::pScratchFree\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
