.TH "MemJournal" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemJournal \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsqlite3_io_methods\fP * \fBpMethod\fP"
.br
.ti -1c
.RI "\fBFileChunk\fP * \fBpFirst\fP"
.br
.ti -1c
.RI "\fBFilePoint\fP \fBendpoint\fP"
.br
.ti -1c
.RI "\fBFilePoint\fP \fBreadpoint\fP"
.br
.ti -1c
.RI "\fBsqlite3_io_methods\fP * \fBpMethod\fP"
.br
.ti -1c
.RI "\fBFileChunk\fP * \fBpFirst\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBFilePoint\fP \fBMemJournal::endpoint\fP"
.PP
.SS "\fBFileChunk\fP* \fBMemJournal::pFirst\fP"
.PP
.SS "\fBFileChunk\fP* \fBMemJournal::pFirst\fP"
.PP
.SS "\fBsqlite3_io_methods\fP* \fBMemJournal::pMethod\fP"
.PP
.SS "\fBsqlite3_io_methods\fP* \fBMemJournal::pMethod\fP"
.PP
.SS "\fBFilePoint\fP \fBMemJournal::readpoint\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
