.TH "MemPage" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemPage \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBisInit\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBnOverflow\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBintKey\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBleaf\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBhasData\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBhdrOffset\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBchildPtrSize\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBmaxLocal\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBminLocal\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBcellOffset\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBnFree\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBnCell\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBmaskPage\fP"
.br
.ti -1c
.RI "\fBMemPage::_OvflCell\fP \fBaOvfl\fP [5]"
.br
.ti -1c
.RI "\fBBtShared\fP * \fBpBt\fP"
.br
.ti -1c
.RI "\fBu8\fP * \fBaData\fP"
.br
.ti -1c
.RI "\fBDbPage\fP * \fBpDbPage\fP"
.br
.ti -1c
.RI "\fBPgno\fP \fBpgno\fP"
.br
.ti -1c
.RI "\fBMemPage::_OvflCell\fP \fBaOvfl\fP [5]"
.br
.ti -1c
.RI "\fBBtShared\fP * \fBpBt\fP"
.br
.ti -1c
.RI "\fBu8\fP * \fBaData\fP"
.br
.ti -1c
.RI "\fBDbPage\fP * \fBpDbPage\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_OvflCell\fP"
.br
.ti -1c
.RI "struct \fB_OvflCell\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu8\fP* \fBMemPage::aData\fP"
.PP
.SS "\fBu8\fP* \fBMemPage::aData\fP"
.PP
.SS "struct \fBMemPage::_OvflCell\fP  \fBMemPage::aOvfl\fP[5]"
.PP
.SS "struct \fBMemPage::_OvflCell\fP  \fBMemPage::aOvfl\fP[5]"
.PP
.SS "\fBu16\fP \fBMemPage::cellOffset\fP"
.PP
.SS "\fBu8\fP \fBMemPage::childPtrSize\fP"
.PP
.SS "\fBu8\fP \fBMemPage::hasData\fP"
.PP
.SS "\fBu8\fP \fBMemPage::hdrOffset\fP"
.PP
.SS "\fBu8\fP \fBMemPage::intKey\fP"
.PP
.SS "\fBu8\fP \fBMemPage::isInit\fP"
.PP
.SS "\fBu8\fP \fBMemPage::leaf\fP"
.PP
.SS "\fBu16\fP \fBMemPage::maskPage\fP"
.PP
.SS "\fBu16\fP \fBMemPage::maxLocal\fP"
.PP
.SS "\fBu16\fP \fBMemPage::minLocal\fP"
.PP
.SS "\fBu16\fP \fBMemPage::nCell\fP"
.PP
.SS "\fBu16\fP \fBMemPage::nFree\fP"
.PP
.SS "\fBu8\fP \fBMemPage::nOverflow\fP"
.PP
.SS "\fBBtShared\fP* \fBMemPage::pBt\fP"
.PP
.SS "\fBBtShared\fP* \fBMemPage::pBt\fP"
.PP
.SS "\fBDbPage\fP* \fBMemPage::pDbPage\fP"
.PP
.SS "\fBDbPage\fP* \fBMemPage::pDbPage\fP"
.PP
.SS "\fBPgno\fP \fBMemPage::pgno\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
