.TH "Module" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Module \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBsqlite3_module\fP * \fBpModule\fP"
.br
.ti -1c
.RI "const char * \fBzName\fP"
.br
.ti -1c
.RI "void * \fBpAux\fP"
.br
.ti -1c
.RI "void(* \fBxDestroy\fP )(void *)"
.br
.ti -1c
.RI "const \fBsqlite3_module\fP * \fBpModule\fP"
.br
.ti -1c
.RI "const char * \fBzName\fP"
.br
.ti -1c
.RI "void * \fBpAux\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* \fBModule::pAux\fP"
.PP
.SS "void* \fBModule::pAux\fP"
.PP
.SS "const \fBsqlite3_module\fP* \fBModule::pModule\fP"
.PP
.SS "const \fBsqlite3_module\fP* \fBModule::pModule\fP"
.PP
.SS "void(* \fBModule::xDestroy\fP"
.PP
.SS "const char* \fBModule::zName\fP"
.PP
.SS "const char* \fBModule::zName\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
