.TH "msghdr" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
msghdr \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBmsg_name\fP"
.br
.ti -1c
.RI "socklen_t \fBmsg_namelen\fP"
.br
.ti -1c
.RI "struct \fBiovec\fP * \fBmsg_iov\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBmsg_iovlen\fP"
.br
.ti -1c
.RI "void * \fBmsg_control\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBmsg_controllen\fP"
.br
.ti -1c
.RI "int \fBmsg_flags\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void * \fBmsghdr::msg_control\fP"
.SS "\fBsize_t\fP \fBmsghdr::msg_controllen\fP"
.SS "int \fBmsghdr::msg_flags\fP"
.SS "struct \fBiovec\fP * \fBmsghdr::msg_iov\fP"
.SS "\fBsize_t\fP \fBmsghdr::msg_iovlen\fP"
.SS "void * \fBmsghdr::msg_name\fP"
.SS "socklen_t \fBmsghdr::msg_namelen\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
