.TH "PagerSavepoint" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PagerSavepoint \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBi64\fP \fBiOffset\fP"
.br
.ti -1c
.RI "\fBi64\fP \fBiHdrOffset\fP"
.br
.ti -1c
.RI "\fBBitvec\fP * \fBpInSavepoint\fP"
.br
.ti -1c
.RI "\fBPgno\fP \fBnOrig\fP"
.br
.ti -1c
.RI "\fBPgno\fP \fBiSubRec\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBaWalData\fP [WAL_SAVEPOINT_NDATA]"
.br
.ti -1c
.RI "\fBBitvec\fP * \fBpInSavepoint\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu32\fP \fBPagerSavepoint::aWalData\fP"
.PP
.SS "\fBi64\fP \fBPagerSavepoint::iHdrOffset\fP"
.PP
.SS "\fBi64\fP \fBPagerSavepoint::iOffset\fP"
.PP
.SS "\fBPgno\fP \fBPagerSavepoint::iSubRec\fP"
.PP
.SS "\fBPgno\fP \fBPagerSavepoint::nOrig\fP"
.PP
.SS "\fBBitvec\fP* \fBPagerSavepoint::pInSavepoint\fP"
.PP
.SS "\fBBitvec\fP* \fBPagerSavepoint::pInSavepoint\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
