.TH "PCache1" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PCache1 \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBszPage\fP"
.br
.ti -1c
.RI "int \fBbPurgeable\fP"
.br
.ti -1c
.RI "unsigned int \fBnMin\fP"
.br
.ti -1c
.RI "unsigned int \fBnMax\fP"
.br
.ti -1c
.RI "unsigned int \fBnRecyclable\fP"
.br
.ti -1c
.RI "unsigned int \fBnPage\fP"
.br
.ti -1c
.RI "unsigned int \fBnHash\fP"
.br
.ti -1c
.RI "\fBPgHdr1\fP ** \fBapHash\fP"
.br
.ti -1c
.RI "unsigned int \fBiMaxKey\fP"
.br
.ti -1c
.RI "\fBPgHdr1\fP ** \fBapHash\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBPgHdr1\fP** \fBPCache1::apHash\fP"
.PP
.SS "\fBPgHdr1\fP** \fBPCache1::apHash\fP"
.PP
.SS "int \fBPCache1::bPurgeable\fP"
.PP
.SS "unsigned int \fBPCache1::iMaxKey\fP"
.PP
.SS "unsigned int \fBPCache1::nHash\fP"
.PP
.SS "unsigned int \fBPCache1::nMax\fP"
.PP
.SS "unsigned int \fBPCache1::nMin\fP"
.PP
.SS "unsigned int \fBPCache1::nPage\fP"
.PP
.SS "unsigned int \fBPCache1::nRecyclable\fP"
.PP
.SS "int \fBPCache1::szPage\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
