.TH "PCacheGlobal" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PCacheGlobal \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsqlite3_mutex\fP * \fBmutex\fP"
.br
.ti -1c
.RI "int \fBnMaxPage\fP"
.br
.ti -1c
.RI "int \fBnMinPage\fP"
.br
.ti -1c
.RI "int \fBnCurrentPage\fP"
.br
.ti -1c
.RI "\fBPgHdr1\fP * \fBpLruHead\fP"
.br
.ti -1c
.RI "\fBPgHdr1\fP * \fBpLruTail\fP"
.br
.ti -1c
.RI "int \fBszSlot\fP"
.br
.ti -1c
.RI "int \fBnSlot\fP"
.br
.ti -1c
.RI "int \fBnFreeSlot\fP"
.br
.ti -1c
.RI "int \fBnReserve\fP"
.br
.ti -1c
.RI "void * \fBpStart\fP"
.br
.ti -1c
.RI "void * \fBpEnd\fP"
.br
.ti -1c
.RI "\fBPgFreeslot\fP * \fBpFree\fP"
.br
.ti -1c
.RI "int \fBisInit\fP"
.br
.ti -1c
.RI "\fBsqlite3_mutex\fP * \fBmutex\fP"
.br
.ti -1c
.RI "\fBPgHdr1\fP * \fBpLruHead\fP"
.br
.ti -1c
.RI "void * \fBpStart\fP"
.br
.ti -1c
.RI "\fBPgFreeslot\fP * \fBpFree\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBPCacheGlobal::isInit\fP"
.PP
.SS "\fBsqlite3_mutex\fP* \fBPCacheGlobal::mutex\fP"
.PP
.SS "\fBsqlite3_mutex\fP* \fBPCacheGlobal::mutex\fP"
.PP
.SS "int \fBPCacheGlobal::nCurrentPage\fP"
.PP
.SS "int \fBPCacheGlobal::nFreeSlot\fP"
.PP
.SS "int \fBPCacheGlobal::nMaxPage\fP"
.PP
.SS "int \fBPCacheGlobal::nMinPage\fP"
.PP
.SS "int \fBPCacheGlobal::nReserve\fP"
.PP
.SS "int \fBPCacheGlobal::nSlot\fP"
.PP
.SS "void * \fBPCacheGlobal::pEnd\fP"
.PP
.SS "\fBPgFreeslot\fP* \fBPCacheGlobal::pFree\fP"
.PP
.SS "\fBPgFreeslot\fP* \fBPCacheGlobal::pFree\fP"
.PP
.SS "\fBPgHdr1\fP* \fBPCacheGlobal::pLruHead\fP"
.PP
.SS "\fBPgHdr1\fP* \fBPCacheGlobal::pLruHead\fP"
.PP
.SS "\fBPgHdr1\fP * \fBPCacheGlobal::pLruTail\fP"
.PP
.SS "void* \fBPCacheGlobal::pStart\fP"
.PP
.SS "void* \fBPCacheGlobal::pStart\fP"
.PP
.SS "int \fBPCacheGlobal::szSlot\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
