.TH "PCache" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PCache \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBPgHdr\fP * \fBpDirty\fP"
.br
.ti -1c
.RI "\fBPgHdr\fP * \fBpDirtyTail\fP"
.br
.ti -1c
.RI "\fBPgHdr\fP * \fBpSynced\fP"
.br
.ti -1c
.RI "int \fBnRef\fP"
.br
.ti -1c
.RI "int \fBnMax\fP"
.br
.ti -1c
.RI "int \fBszPage\fP"
.br
.ti -1c
.RI "int \fBszExtra\fP"
.br
.ti -1c
.RI "int \fBbPurgeable\fP"
.br
.ti -1c
.RI "int(* \fBxStress\fP )(void *, \fBPgHdr\fP *)"
.br
.ti -1c
.RI "void * \fBpStress\fP"
.br
.ti -1c
.RI "\fBsqlite3_pcache\fP * \fBpCache\fP"
.br
.ti -1c
.RI "\fBPgHdr\fP * \fBpPage1\fP"
.br
.ti -1c
.RI "\fBPgHdr\fP * \fBpDirty\fP"
.br
.ti -1c
.RI "\fBPgHdr\fP * \fBpSynced\fP"
.br
.ti -1c
.RI "void * \fBpStress\fP"
.br
.ti -1c
.RI "\fBsqlite3_pcache\fP * \fBpCache\fP"
.br
.ti -1c
.RI "\fBPgHdr\fP * \fBpPage1\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBPCache::bPurgeable\fP"
.PP
.SS "int \fBPCache::nMax\fP"
.PP
.SS "int \fBPCache::nRef\fP"
.PP
.SS "\fBsqlite3_pcache\fP* \fBPCache::pCache\fP"
.PP
.SS "\fBsqlite3_pcache\fP* \fBPCache::pCache\fP"
.PP
.SS "\fBPgHdr\fP* \fBPCache::pDirty\fP"
.PP
.SS "\fBPgHdr\fP* \fBPCache::pDirty\fP"
.PP
.SS "\fBPgHdr\fP * \fBPCache::pDirtyTail\fP"
.PP
.SS "\fBPgHdr\fP* \fBPCache::pPage1\fP"
.PP
.SS "\fBPgHdr\fP* \fBPCache::pPage1\fP"
.PP
.SS "void* \fBPCache::pStress\fP"
.PP
.SS "void* \fBPCache::pStress\fP"
.PP
.SS "\fBPgHdr\fP* \fBPCache::pSynced\fP"
.PP
.SS "\fBPgHdr\fP* \fBPCache::pSynced\fP"
.PP
.SS "int \fBPCache::szExtra\fP"
.PP
.SS "int \fBPCache::szPage\fP"
.PP
.SS "int(* \fBPCache::xStress\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
