.TH "PgFreeslot" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PgFreeslot \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBPgFreeslot\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBPgFreeslot\fP * \fBpNext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBPgFreeslot\fP* \fBPgFreeslot::pNext\fP"
.PP
.SS "\fBPgFreeslot\fP* \fBPgFreeslot::pNext\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
