.TH "PgHdr" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PgHdr \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBpData\fP"
.br
.ti -1c
.RI "void * \fBpExtra\fP"
.br
.ti -1c
.RI "\fBPgHdr\fP * \fBpDirty\fP"
.br
.ti -1c
.RI "\fBPgno\fP \fBpgno\fP"
.br
.ti -1c
.RI "\fBPager\fP * \fBpPager\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBi16\fP \fBnRef\fP"
.br
.ti -1c
.RI "\fBPCache\fP * \fBpCache\fP"
.br
.ti -1c
.RI "\fBPgHdr\fP * \fBpDirtyNext\fP"
.br
.ti -1c
.RI "\fBPgHdr\fP * \fBpDirtyPrev\fP"
.br
.ti -1c
.RI "void * \fBpData\fP"
.br
.ti -1c
.RI "void * \fBpExtra\fP"
.br
.ti -1c
.RI "\fBPgHdr\fP * \fBpDirty\fP"
.br
.ti -1c
.RI "\fBPager\fP * \fBpPager\fP"
.br
.ti -1c
.RI "\fBPCache\fP * \fBpCache\fP"
.br
.ti -1c
.RI "\fBPgHdr\fP * \fBpDirtyNext\fP"
.br
.ti -1c
.RI "\fBPgHdr\fP * \fBpDirtyPrev\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu16\fP \fBPgHdr::flags\fP"
.PP
.SS "\fBi16\fP \fBPgHdr::nRef\fP"
.PP
.SS "\fBPCache\fP* \fBPgHdr::pCache\fP"
.PP
.SS "\fBPCache\fP* \fBPgHdr::pCache\fP"
.PP
.SS "void* \fBPgHdr::pData\fP"
.PP
.SS "void* \fBPgHdr::pData\fP"
.PP
.SS "\fBPgHdr\fP* \fBPgHdr::pDirty\fP"
.PP
.SS "\fBPgHdr\fP* \fBPgHdr::pDirty\fP"
.PP
.SS "\fBPgHdr\fP* \fBPgHdr::pDirtyNext\fP"
.PP
.SS "\fBPgHdr\fP* \fBPgHdr::pDirtyNext\fP"
.PP
.SS "\fBPgHdr\fP* \fBPgHdr::pDirtyPrev\fP"
.PP
.SS "\fBPgHdr\fP* \fBPgHdr::pDirtyPrev\fP"
.PP
.SS "void* \fBPgHdr::pExtra\fP"
.PP
.SS "void* \fBPgHdr::pExtra\fP"
.PP
.SS "\fBPgno\fP \fBPgHdr::pgno\fP"
.PP
.SS "\fBPager\fP* \fBPgHdr::pPager\fP"
.PP
.SS "\fBPager\fP* \fBPgHdr::pPager\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
