.TH "PgHdr1" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PgHdr1 \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBiKey\fP"
.br
.ti -1c
.RI "\fBPgHdr1\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBPCache1\fP * \fBpCache\fP"
.br
.ti -1c
.RI "\fBPgHdr1\fP * \fBpLruNext\fP"
.br
.ti -1c
.RI "\fBPgHdr1\fP * \fBpLruPrev\fP"
.br
.ti -1c
.RI "\fBPgHdr1\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBPCache1\fP * \fBpCache\fP"
.br
.ti -1c
.RI "\fBPgHdr1\fP * \fBpLruNext\fP"
.br
.ti -1c
.RI "\fBPgHdr1\fP * \fBpLruPrev\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned int \fBPgHdr1::iKey\fP"
.PP
.SS "\fBPCache1\fP* \fBPgHdr1::pCache\fP"
.PP
.SS "\fBPCache1\fP* \fBPgHdr1::pCache\fP"
.PP
.SS "\fBPgHdr1\fP* \fBPgHdr1::pLruNext\fP"
.PP
.SS "\fBPgHdr1\fP* \fBPgHdr1::pLruNext\fP"
.PP
.SS "\fBPgHdr1\fP* \fBPgHdr1::pLruPrev\fP"
.PP
.SS "\fBPgHdr1\fP* \fBPgHdr1::pLruPrev\fP"
.PP
.SS "\fBPgHdr1\fP* \fBPgHdr1::pNext\fP"
.PP
.SS "\fBPgHdr1\fP* \fBPgHdr1::pNext\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
