.TH "previous_mode_data" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
previous_mode_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBvalid\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "int \fBshowHeader\fP"
.br
.ti -1c
.RI "int \fBcolWidth\fP [100]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBprevious_mode_data::colWidth\fP"
.PP
.SS "int \fBprevious_mode_data::mode\fP"
.PP
.SS "int \fBprevious_mode_data::showHeader\fP"
.PP
.SS "int \fBprevious_mode_data::valid\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
