.TH "pthread_mutex_t::__pthread_mutex_s" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pthread_mutex_t::__pthread_mutex_s \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fB__lock\fP"
.br
.ti -1c
.RI "unsigned int \fB__count\fP"
.br
.ti -1c
.RI "int \fB__owner\fP"
.br
.ti -1c
.RI "unsigned int \fB__nusers\fP"
.br
.ti -1c
.RI "int \fB__kind\fP"
.br
.ti -1c
.RI "int \fB__spins\fP"
.br
.ti -1c
.RI "\fB__pthread_list_t\fP \fB__list\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned int \fBpthread_mutex_t::__pthread_mutex_s::__count\fP"
.SS "int \fBpthread_mutex_t::__pthread_mutex_s::__kind\fP"
.SS "\fB__pthread_list_t\fP \fBpthread_mutex_t::__pthread_mutex_s::__list\fP"
.SS "int \fBpthread_mutex_t::__pthread_mutex_s::__lock\fP"
.SS "unsigned int \fBpthread_mutex_t::__pthread_mutex_s::__nusers\fP"
.SS "int \fBpthread_mutex_t::__pthread_mutex_s::__owner\fP"
.SS "int \fBpthread_mutex_t::__pthread_mutex_s::__spins\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
