.TH "pthread_rwlock_t" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pthread_rwlock_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fB__lock\fP"
.br
.ti -1c
.RI "   unsigned int \fB__nr_readers\fP"
.br
.ti -1c
.RI "   unsigned int \fB__readers_wakeup\fP"
.br
.ti -1c
.RI "   unsigned int \fB__writer_wakeup\fP"
.br
.ti -1c
.RI "   unsigned int \fB__nr_readers_queued\fP"
.br
.ti -1c
.RI "   unsigned int \fB__nr_writers_queued\fP"
.br
.ti -1c
.RI "   int \fB__writer\fP"
.br
.ti -1c
.RI "   int \fB__shared\fP"
.br
.ti -1c
.RI "   unsigned long int \fB__pad1\fP"
.br
.ti -1c
.RI "   unsigned long int \fB__pad2\fP"
.br
.ti -1c
.RI "   unsigned int \fB__flags\fP"
.br
.ti -1c
.RI "} \fB__data\fP"
.br
.ti -1c
.RI "char \fB__size\fP [56]"
.br
.ti -1c
.RI "long int \fB__align\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fB__lock\fP"
.br
.ti -1c
.RI "   unsigned int \fB__nr_readers\fP"
.br
.ti -1c
.RI "   unsigned int \fB__readers_wakeup\fP"
.br
.ti -1c
.RI "   unsigned int \fB__writer_wakeup\fP"
.br
.ti -1c
.RI "   unsigned int \fB__nr_readers_queued\fP"
.br
.ti -1c
.RI "   unsigned int \fB__nr_writers_queued\fP"
.br
.ti -1c
.RI "   int \fB__writer\fP"
.br
.ti -1c
.RI "   int \fB__shared\fP"
.br
.ti -1c
.RI "   unsigned long int \fB__pad1\fP"
.br
.ti -1c
.RI "   unsigned long int \fB__pad2\fP"
.br
.ti -1c
.RI "   unsigned int \fB__flags\fP"
.br
.ti -1c
.RI "} \fB__data\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "long int \fBpthread_rwlock_t::__align\fP"
.SS "struct { ... }   \fBpthread_rwlock_t::__data\fP"
.SS "struct { ... }   \fBpthread_rwlock_t::__data\fP"
.SS "unsigned int \fBpthread_rwlock_t::__flags\fP"
.SS "int \fBpthread_rwlock_t::__lock\fP"
.SS "unsigned int \fBpthread_rwlock_t::__nr_readers\fP"
.SS "unsigned int \fBpthread_rwlock_t::__nr_readers_queued\fP"
.SS "unsigned int \fBpthread_rwlock_t::__nr_writers_queued\fP"
.SS "unsigned long int \fBpthread_rwlock_t::__pad1\fP"
.SS "unsigned long int \fBpthread_rwlock_t::__pad2\fP"
.SS "unsigned int \fBpthread_rwlock_t::__readers_wakeup\fP"
.SS "int \fBpthread_rwlock_t::__shared\fP"
.SS "char \fBpthread_rwlock_t::__size\fP"
.SS "int \fBpthread_rwlock_t::__writer\fP"
.SS "unsigned int \fBpthread_rwlock_t::__writer_wakeup\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
