.TH "pthread_mutex_t" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pthread_mutex_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB__pthread_mutex_s\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBpthread_mutex_t::__pthread_mutex_s\fP \fB__data\fP"
.br
.ti -1c
.RI "char \fB__size\fP [40]"
.br
.ti -1c
.RI "long int \fB__align\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "long int \fBpthread_mutex_t::__align\fP"
.SS "struct \fBpthread_mutex_t::__pthread_mutex_s\fP \fBpthread_mutex_t::__data\fP"
.SS "char \fBpthread_mutex_t::__size\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
