.TH "pthread_barrier_t" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pthread_barrier_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fB__size\fP [32]"
.br
.ti -1c
.RI "long int \fB__align\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "long int \fBpthread_barrier_t::__align\fP"
.SS "char \fBpthread_barrier_t::__size\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
