.TH "rlimit" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rlimit \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBrlim_t\fP \fBrlim_cur\fP"
.br
.ti -1c
.RI "\fBrlim_t\fP \fBrlim_max\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBrlim_t\fP \fBrlimit::rlim_cur\fP"
.SS "\fBrlim_t\fP \fBrlimit::rlim_max\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
