.TH "RowSet" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RowSet \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBRowSetChunk\fP * \fBpChunk\fP"
.br
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.ti -1c
.RI "\fBRowSetEntry\fP * \fBpEntry\fP"
.br
.ti -1c
.RI "\fBRowSetEntry\fP * \fBpLast\fP"
.br
.ti -1c
.RI "\fBRowSetEntry\fP * \fBpFresh\fP"
.br
.ti -1c
.RI "\fBRowSetEntry\fP * \fBpTree\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBnFresh\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBisSorted\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBiBatch\fP"
.br
.ti -1c
.RI "\fBRowSetChunk\fP * \fBpChunk\fP"
.br
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.ti -1c
.RI "\fBRowSetEntry\fP * \fBpEntry\fP"
.br
.ti -1c
.RI "\fBRowSetEntry\fP * \fBpLast\fP"
.br
.ti -1c
.RI "\fBRowSetEntry\fP * \fBpFresh\fP"
.br
.ti -1c
.RI "\fBRowSetEntry\fP * \fBpTree\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBsqlite3\fP* \fBRowSet::db\fP"
.PP
.SS "\fBsqlite3\fP* \fBRowSet::db\fP"
.PP
.SS "\fBu8\fP \fBRowSet::iBatch\fP"
.PP
.SS "\fBu8\fP \fBRowSet::isSorted\fP"
.PP
.SS "\fBu16\fP \fBRowSet::nFresh\fP"
.PP
.SS "struct \fBRowSetChunk\fP* \fBRowSet::pChunk\fP"
.PP
.SS "struct \fBRowSetChunk\fP* \fBRowSet::pChunk\fP"
.PP
.SS "struct \fBRowSetEntry\fP* \fBRowSet::pEntry\fP"
.PP
.SS "struct \fBRowSetEntry\fP* \fBRowSet::pEntry\fP"
.PP
.SS "struct \fBRowSetEntry\fP* \fBRowSet::pFresh\fP"
.PP
.SS "struct \fBRowSetEntry\fP* \fBRowSet::pFresh\fP"
.PP
.SS "struct \fBRowSetEntry\fP* \fBRowSet::pLast\fP"
.PP
.SS "struct \fBRowSetEntry\fP* \fBRowSet::pLast\fP"
.PP
.SS "struct \fBRowSetEntry\fP* \fBRowSet::pTree\fP"
.PP
.SS "struct \fBRowSetEntry\fP* \fBRowSet::pTree\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
