.TH "RowSetEntry" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RowSetEntry \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBi64\fP \fBv\fP"
.br
.ti -1c
.RI "\fBRowSetEntry\fP * \fBpRight\fP"
.br
.ti -1c
.RI "\fBRowSetEntry\fP * \fBpLeft\fP"
.br
.ti -1c
.RI "\fBRowSetEntry\fP * \fBpRight\fP"
.br
.ti -1c
.RI "\fBRowSetEntry\fP * \fBpLeft\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBRowSetEntry\fP* \fBRowSetEntry::pLeft\fP"
.PP
.SS "struct \fBRowSetEntry\fP* \fBRowSetEntry::pLeft\fP"
.PP
.SS "struct \fBRowSetEntry\fP* \fBRowSetEntry::pRight\fP"
.PP
.SS "struct \fBRowSetEntry\fP* \fBRowSetEntry::pRight\fP"
.PP
.SS "\fBi64\fP \fBRowSetEntry::v\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
