.TH "RowSetChunk" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RowSetChunk \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBRowSetChunk\fP * \fBpNextChunk\fP"
.br
.ti -1c
.RI "\fBRowSetEntry\fP \fBaEntry\fP [ROWSET_ENTRY_PER_CHUNK]"
.br
.ti -1c
.RI "\fBRowSetChunk\fP * \fBpNextChunk\fP"
.br
.ti -1c
.RI "\fBRowSetEntry\fP \fBaEntry\fP [ROWSET_ENTRY_PER_CHUNK]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBRowSetEntry\fP \fBRowSetChunk::aEntry\fP[ROWSET_ENTRY_PER_CHUNK]"
.PP
.SS "struct \fBRowSetEntry\fP \fBRowSetChunk::aEntry\fP[ROWSET_ENTRY_PER_CHUNK]"
.PP
.SS "struct \fBRowSetChunk\fP* \fBRowSetChunk::pNextChunk\fP"
.PP
.SS "struct \fBRowSetChunk\fP* \fBRowSetChunk::pNextChunk\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
