.TH "common/rptqueue.c" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/rptqueue.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include 'rptqueue.h'\fP
.br
\fC#include 'nonblock.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBrpt_init\fP (struct \fBrptqueue\fP *rpt)"
.br
.ti -1c
.RI "int \fBrpt_status_update\fP (struct \fBrptqueue\fP *rpt)"
.br
.ti -1c
.RI "int \fBrpt_write_status\fP (struct \fBrptqueue\fP *rpt, const char *msg)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void rpt_init (struct \fBrptqueue\fP * rpt)"
.PP
.SS "int rpt_status_update (struct \fBrptqueue\fP * rpt)"
.PP
.SS "int rpt_write_status (struct \fBrptqueue\fP * rpt, const char * msg)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
