.TH "common/rptqueue.test.c" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/rptqueue.test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'rptqueue.h'\fP
.br
\fC#include 'test.h'\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <stdio.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static char \fBdisplay\fP [24] = '.......................'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"
.PP
.SH "Variable Documentation"
.PP 
.SS "char \fBdisplay\fP[24] = '.......................'\fC [static]\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
