.TH "rptqueue" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rptqueue \- 
.SH SYNOPSIS
.br
.PP
\fC#include <rptqueue.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBdisplay\fP"
.br
.ti -1c
.RI "int \fBdlen\fP"
.br
.ti -1c
.RI "char * \fBdpos\fP"
.br
.ti -1c
.RI "int \fBifd\fP"
.br
.ti -1c
.RI "int \fBofd\fP"
.br
.ti -1c
.RI "char \fBbuf\fP [2]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char \fBrptqueue::buf\fP[2]"
.PP
.SS "char* \fBrptqueue::display\fP"
.PP
.SS "int \fBrptqueue::dlen\fP"
.PP
.SS "char* \fBrptqueue::dpos\fP"
.PP
.SS "int \fBrptqueue::ifd\fP"
.PP
.SS "int \fBrptqueue::ofd\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
