.TH "rusage" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rusage \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBtimeval\fP \fBru_utime\fP"
.br
.ti -1c
.RI "struct \fBtimeval\fP \fBru_stime\fP"
.br
.ti -1c
.RI "long int \fBru_maxrss\fP"
.br
.ti -1c
.RI "long int \fBru_ixrss\fP"
.br
.ti -1c
.RI "long int \fBru_idrss\fP"
.br
.ti -1c
.RI "long int \fBru_isrss\fP"
.br
.ti -1c
.RI "long int \fBru_minflt\fP"
.br
.ti -1c
.RI "long int \fBru_majflt\fP"
.br
.ti -1c
.RI "long int \fBru_nswap\fP"
.br
.ti -1c
.RI "long int \fBru_inblock\fP"
.br
.ti -1c
.RI "long int \fBru_oublock\fP"
.br
.ti -1c
.RI "long int \fBru_msgsnd\fP"
.br
.ti -1c
.RI "long int \fBru_msgrcv\fP"
.br
.ti -1c
.RI "long int \fBru_nsignals\fP"
.br
.ti -1c
.RI "long int \fBru_nvcsw\fP"
.br
.ti -1c
.RI "long int \fBru_nivcsw\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "long int \fBrusage::ru_idrss\fP"
.SS "long int \fBrusage::ru_inblock\fP"
.SS "long int \fBrusage::ru_isrss\fP"
.SS "long int \fBrusage::ru_ixrss\fP"
.SS "long int \fBrusage::ru_majflt\fP"
.SS "long int \fBrusage::ru_maxrss\fP"
.SS "long int \fBrusage::ru_minflt\fP"
.SS "long int \fBrusage::ru_msgrcv\fP"
.SS "long int \fBrusage::ru_msgsnd\fP"
.SS "long int \fBrusage::ru_nivcsw\fP"
.SS "long int \fBrusage::ru_nsignals\fP"
.SS "long int \fBrusage::ru_nswap\fP"
.SS "long int \fBrusage::ru_nvcsw\fP"
.SS "long int \fBrusage::ru_oublock\fP"
.SS "struct \fBtimeval\fP \fBrusage::ru_stime\fP"
.SS "struct \fBtimeval\fP \fBrusage::ru_utime\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
