.TH "Savepoint" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Savepoint \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBzName\fP"
.br
.ti -1c
.RI "\fBi64\fP \fBnDeferredCons\fP"
.br
.ti -1c
.RI "\fBSavepoint\fP * \fBpNext\fP"
.br
.ti -1c
.RI "char * \fBzName\fP"
.br
.ti -1c
.RI "\fBSavepoint\fP * \fBpNext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBi64\fP \fBSavepoint::nDeferredCons\fP"
.PP
.SS "\fBSavepoint\fP* \fBSavepoint::pNext\fP"
.PP
.SS "\fBSavepoint\fP* \fBSavepoint::pNext\fP"
.PP
.SS "char* \fBSavepoint::zName\fP"
.PP
.SS "char* \fBSavepoint::zName\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
