.TH "Schema" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Schema \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBschema_cookie\fP"
.br
.ti -1c
.RI "\fBHash\fP \fBtblHash\fP"
.br
.ti -1c
.RI "\fBHash\fP \fBidxHash\fP"
.br
.ti -1c
.RI "\fBHash\fP \fBtrigHash\fP"
.br
.ti -1c
.RI "\fBHash\fP \fBfkeyHash\fP"
.br
.ti -1c
.RI "\fBTable\fP * \fBpSeqTab\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBfile_format\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBenc\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBflags\fP"
.br
.ti -1c
.RI "int \fBcache_size\fP"
.br
.ti -1c
.RI "\fBTable\fP * \fBpSeqTab\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBSchema::cache_size\fP"
.PP
.SS "\fBu8\fP \fBSchema::enc\fP"
.PP
.SS "\fBu8\fP \fBSchema::file_format\fP"
.PP
.SS "\fBHash\fP \fBSchema::fkeyHash\fP"
.PP
.SS "\fBu16\fP \fBSchema::flags\fP"
.PP
.SS "\fBHash\fP \fBSchema::idxHash\fP"
.PP
.SS "\fBTable\fP* \fBSchema::pSeqTab\fP"
.PP
.SS "\fBTable\fP* \fBSchema::pSeqTab\fP"
.PP
.SS "int \fBSchema::schema_cookie\fP"
.PP
.SS "\fBHash\fP \fBSchema::tblHash\fP"
.PP
.SS "\fBHash\fP \fBSchema::trigHash\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
