.TH "Select" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Select \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBExprList\fP * \fBpEList\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBop\fP"
.br
.ti -1c
.RI "char \fBaffinity\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBselFlags\fP"
.br
.ti -1c
.RI "\fBSrcList\fP * \fBpSrc\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpWhere\fP"
.br
.ti -1c
.RI "\fBExprList\fP * \fBpGroupBy\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpHaving\fP"
.br
.ti -1c
.RI "\fBExprList\fP * \fBpOrderBy\fP"
.br
.ti -1c
.RI "\fBSelect\fP * \fBpPrior\fP"
.br
.ti -1c
.RI "\fBSelect\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBSelect\fP * \fBpRightmost\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpLimit\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpOffset\fP"
.br
.ti -1c
.RI "int \fBiLimit\fP"
.br
.ti -1c
.RI "int \fBiOffset\fP"
.br
.ti -1c
.RI "int \fBaddrOpenEphm\fP [3]"
.br
.ti -1c
.RI "\fBExprList\fP * \fBpEList\fP"
.br
.ti -1c
.RI "\fBSrcList\fP * \fBpSrc\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpWhere\fP"
.br
.ti -1c
.RI "\fBExprList\fP * \fBpGroupBy\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpHaving\fP"
.br
.ti -1c
.RI "\fBExprList\fP * \fBpOrderBy\fP"
.br
.ti -1c
.RI "\fBSelect\fP * \fBpPrior\fP"
.br
.ti -1c
.RI "\fBSelect\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBSelect\fP * \fBpRightmost\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpLimit\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpOffset\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBSelect::addrOpenEphm\fP"
.PP
.SS "char \fBSelect::affinity\fP"
.PP
.SS "int \fBSelect::iLimit\fP"
.PP
.SS "int \fBSelect::iOffset\fP"
.PP
.SS "\fBu8\fP \fBSelect::op\fP"
.PP
.SS "\fBExprList\fP* \fBSelect::pEList\fP"
.PP
.SS "\fBExprList\fP* \fBSelect::pEList\fP"
.PP
.SS "\fBExprList\fP* \fBSelect::pGroupBy\fP"
.PP
.SS "\fBExprList\fP* \fBSelect::pGroupBy\fP"
.PP
.SS "\fBExpr\fP* \fBSelect::pHaving\fP"
.PP
.SS "\fBExpr\fP* \fBSelect::pHaving\fP"
.PP
.SS "\fBExpr\fP* \fBSelect::pLimit\fP"
.PP
.SS "\fBExpr\fP* \fBSelect::pLimit\fP"
.PP
.SS "\fBSelect\fP* \fBSelect::pNext\fP"
.PP
.SS "\fBSelect\fP* \fBSelect::pNext\fP"
.PP
.SS "\fBExpr\fP* \fBSelect::pOffset\fP"
.PP
.SS "\fBExpr\fP* \fBSelect::pOffset\fP"
.PP
.SS "\fBExprList\fP* \fBSelect::pOrderBy\fP"
.PP
.SS "\fBExprList\fP* \fBSelect::pOrderBy\fP"
.PP
.SS "\fBSelect\fP* \fBSelect::pPrior\fP"
.PP
.SS "\fBSelect\fP* \fBSelect::pPrior\fP"
.PP
.SS "\fBSelect\fP* \fBSelect::pRightmost\fP"
.PP
.SS "\fBSelect\fP* \fBSelect::pRightmost\fP"
.PP
.SS "\fBSrcList\fP* \fBSelect::pSrc\fP"
.PP
.SS "\fBSrcList\fP* \fBSelect::pSrc\fP"
.PP
.SS "\fBExpr\fP* \fBSelect::pWhere\fP"
.PP
.SS "\fBExpr\fP* \fBSelect::pWhere\fP"
.PP
.SS "\fBu16\fP \fBSelect::selFlags\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
