.TH "SelectDest" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SelectDest \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBeDest\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBaffinity\fP"
.br
.ti -1c
.RI "int \fBiParm\fP"
.br
.ti -1c
.RI "int \fBiMem\fP"
.br
.ti -1c
.RI "int \fBnMem\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu8\fP \fBSelectDest::affinity\fP"
.PP
.SS "\fBu8\fP \fBSelectDest::eDest\fP"
.PP
.SS "int \fBSelectDest::iMem\fP"
.PP
.SS "int \fBSelectDest::iParm\fP"
.PP
.SS "int \fBSelectDest::nMem\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
