.TH "Services" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Services \- 
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_upk_svc_desc\fP"
.br
.RI "\fIservice configuration. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_upk_svc_desc\fP \fBupk_svc_desc_t\fP"
.br
.RI "\fIservice configuration. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "typedef \fBUPKLIST_METANODE\fP (\fBupk_svc_desc_t\fP, \fBupk_svc_desc_meta_p\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "typedef \fBupk_svc_desc_meta_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_upk_svc_desc\fP \fBupk_svc_desc_t\fP"
.PP
service configuration. 
.SH "Function Documentation"
.PP 
.SS "typedef UPKLIST_METANODE (\fBupk_svc_desc_t\fP, \fBupk_svc_desc_meta_p\fP)"
.SH "Variable Documentation"
.PP 
.SS "typedef \fBupk_svc_desc_meta_t\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
