.TH "Set" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Set \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBHash\fP \fBhash\fP"
.br
.ti -1c
.RI "\fBHashElem\fP * \fBprev\fP"
.br
.ti -1c
.RI "\fBHashElem\fP * \fBprev\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBHash\fP \fBSet::hash\fP"
.PP
.SS "\fBHashElem\fP* \fBSet::prev\fP"
.PP
.SS "\fBHashElem\fP* \fBSet::prev\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
