.TH "sigaltstack" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sigaltstack \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBss_sp\fP"
.br
.ti -1c
.RI "int \fBss_flags\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBss_size\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBsigaltstack::ss_flags\fP"
.SS "\fBsize_t\fP \fBsigaltstack::ss_size\fP"
.SS "void * \fBsigaltstack::ss_sp\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
