.TH "common/sigblock.c" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/sigblock.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string.h>\fP
.br
\fC#include <signal.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBupk_block_signal\fP (int signal)"
.br
.ti -1c
.RI "void \fBupk_unblock_signal\fP (int signal)"
.br
.ti -1c
.RI "void \fBupk_catch_signal\fP (int signal, void(*f)(int))"
.br
.ti -1c
.RI "void \fBupk_uncatch_signal\fP (int signal)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void upk_block_signal (int signal)"
.PP
.SS "void upk_catch_signal (int signal, void(*)(int) f)"
.PP
.SS "void upk_unblock_signal (int signal)"
.PP
.SS "void upk_uncatch_signal (int signal)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
