.TH "common/sigblock.test.c" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/sigblock.test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <signal.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include 'sigblock.h'\fP
.br
\fC#include 'test.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtermhandler\fP (int ign)"
.br
.ti -1c
.RI "void \fBchildhandler\fP (int ign)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBchild\fP = 0"
.br
.ti -1c
.RI "int \fBterm\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void childhandler (int ign)"
.PP
.SS "int main (void)"
.PP
.SS "void termhandler (int ign)"
.PP
.SH "Variable Documentation"
.PP 
.SS "int \fBchild\fP = 0"
.PP
.SS "int \fBterm\fP = 0"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
