.TH "sigvec" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sigvec \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__sighandler_t \fBsv_handler\fP"
.br
.ti -1c
.RI "int \fBsv_mask\fP"
.br
.ti -1c
.RI "int \fBsv_flags\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBsigvec::sv_flags\fP"
.SS "__sighandler_t \fBsigvec::sv_handler\fP"
.SS "int \fBsigvec::sv_mask\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
