.TH "sockaddr_un" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sockaddr_un \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsa_family_t\fP \fBsun_family\fP"
.br
.ti -1c
.RI "char \fBsun_path\fP [108]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBsa_family_t\fP \fBsockaddr_un::sun_family\fP"
.PP
Referenced by buddy_connect(), buddy_init_socket(), buddy_phone_home(), ctrl_sock_setup(), and upk_domain_socket_connect().
.SS "char \fBsockaddr_un::sun_path\fP"
.PP
Referenced by buddy_connect(), buddy_init_socket(), buddy_phone_home(), ctrl_sock_setup(), and upk_domain_socket_connect().

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
