.TH "sockaddr" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sockaddr \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsa_family_t\fP \fBsa_family\fP"
.br
.ti -1c
.RI "char \fBsa_data\fP [14]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char \fBsockaddr::sa_data\fP"
.SS "\fBsa_family_t\fP \fBsockaddr::sa_family\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
