.TH "sockaddr_in6" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sockaddr_in6 \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsa_family_t\fP \fBsin6_family\fP"
.br
.ti -1c
.RI "\fBin_port_t\fP \fBsin6_port\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBsin6_flowinfo\fP"
.br
.ti -1c
.RI "struct \fBin6_addr\fP \fBsin6_addr\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBsin6_scope_id\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBin6_addr\fP \fBsockaddr_in6::sin6_addr\fP"
.SS "\fBsa_family_t\fP \fBsockaddr_in6::sin6_family\fP"
.SS "\fBuint32_t\fP \fBsockaddr_in6::sin6_flowinfo\fP"
.SS "\fBin_port_t\fP \fBsockaddr_in6::sin6_port\fP"
.SS "\fBuint32_t\fP \fBsockaddr_in6::sin6_scope_id\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
