.TH "sqlite3_backup" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite3_backup \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsqlite3\fP * \fBpDestDb\fP"
.br
.ti -1c
.RI "\fBBtree\fP * \fBpDest\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBiDestSchema\fP"
.br
.ti -1c
.RI "int \fBbDestLocked\fP"
.br
.ti -1c
.RI "\fBPgno\fP \fBiNext\fP"
.br
.ti -1c
.RI "\fBsqlite3\fP * \fBpSrcDb\fP"
.br
.ti -1c
.RI "\fBBtree\fP * \fBpSrc\fP"
.br
.ti -1c
.RI "int \fBrc\fP"
.br
.ti -1c
.RI "\fBPgno\fP \fBnRemaining\fP"
.br
.ti -1c
.RI "\fBPgno\fP \fBnPagecount\fP"
.br
.ti -1c
.RI "int \fBisAttached\fP"
.br
.ti -1c
.RI "\fBsqlite3_backup\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBsqlite3\fP * \fBpDestDb\fP"
.br
.ti -1c
.RI "\fBBtree\fP * \fBpDest\fP"
.br
.ti -1c
.RI "\fBsqlite3\fP * \fBpSrcDb\fP"
.br
.ti -1c
.RI "\fBBtree\fP * \fBpSrc\fP"
.br
.ti -1c
.RI "\fBsqlite3_backup\fP * \fBpNext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBsqlite3_backup::bDestLocked\fP"
.PP
.SS "\fBu32\fP \fBsqlite3_backup::iDestSchema\fP"
.PP
.SS "\fBPgno\fP \fBsqlite3_backup::iNext\fP"
.PP
.SS "int \fBsqlite3_backup::isAttached\fP"
.PP
.SS "\fBPgno\fP \fBsqlite3_backup::nPagecount\fP"
.PP
.SS "\fBPgno\fP \fBsqlite3_backup::nRemaining\fP"
.PP
.SS "\fBBtree\fP* \fBsqlite3_backup::pDest\fP"
.PP
.SS "\fBBtree\fP* \fBsqlite3_backup::pDest\fP"
.PP
.SS "\fBsqlite3\fP* \fBsqlite3_backup::pDestDb\fP"
.PP
.SS "\fBsqlite3\fP* \fBsqlite3_backup::pDestDb\fP"
.PP
.SS "\fBsqlite3_backup\fP* \fBsqlite3_backup::pNext\fP"
.PP
.SS "\fBsqlite3_backup\fP* \fBsqlite3_backup::pNext\fP"
.PP
.SS "\fBBtree\fP* \fBsqlite3_backup::pSrc\fP"
.PP
.SS "\fBBtree\fP* \fBsqlite3_backup::pSrc\fP"
.PP
.SS "\fBsqlite3\fP* \fBsqlite3_backup::pSrcDb\fP"
.PP
.SS "\fBsqlite3\fP* \fBsqlite3_backup::pSrcDb\fP"
.PP
.SS "int \fBsqlite3_backup::rc\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
