.TH "sqlite3_rtree_geometry" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite3_rtree_geometry \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sqlite3.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBpContext\fP"
.br
.ti -1c
.RI "int \fBnParam\fP"
.br
.ti -1c
.RI "double * \fBaParam\fP"
.br
.ti -1c
.RI "void * \fBpUser\fP"
.br
.ti -1c
.RI "void(* \fBxDelUser\fP )(void *)"
.br
.ti -1c
.RI "void * \fBpContext\fP"
.br
.ti -1c
.RI "double * \fBaParam\fP"
.br
.ti -1c
.RI "void * \fBpUser\fP"
.br
.ti -1c
.RI "void * \fBpContext\fP"
.br
.ti -1c
.RI "double * \fBaParam\fP"
.br
.ti -1c
.RI "void * \fBpUser\fP"
.br
.ti -1c
.RI "void * \fBpContext\fP"
.br
.ti -1c
.RI "double * \fBaParam\fP"
.br
.ti -1c
.RI "void * \fBpUser\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "double* \fBsqlite3_rtree_geometry::aParam\fP"
.PP
.SS "double* \fBsqlite3_rtree_geometry::aParam\fP"
.PP
.SS "double* \fBsqlite3_rtree_geometry::aParam\fP"
.PP
.SS "double* \fBsqlite3_rtree_geometry::aParam\fP"
.PP
.SS "int \fBsqlite3_rtree_geometry::nParam\fP"
.PP
.SS "void* \fBsqlite3_rtree_geometry::pContext\fP"
.PP
.SS "void* \fBsqlite3_rtree_geometry::pContext\fP"
.PP
.SS "void* \fBsqlite3_rtree_geometry::pContext\fP"
.PP
.SS "void* \fBsqlite3_rtree_geometry::pContext\fP"
.PP
.SS "void* \fBsqlite3_rtree_geometry::pUser\fP"
.PP
.SS "void* \fBsqlite3_rtree_geometry::pUser\fP"
.PP
.SS "void* \fBsqlite3_rtree_geometry::pUser\fP"
.PP
.SS "void* \fBsqlite3_rtree_geometry::pUser\fP"
.PP
.SS "void(* \fBsqlite3_rtree_geometry::xDelUser\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
