.TH "sqlite3StatType" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite3StatType \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnowValue\fP [10]"
.br
.ti -1c
.RI "int \fBmxValue\fP [10]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBsqlite3StatType::mxValue\fP"
.PP
.SS "int \fBsqlite3StatType::nowValue\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
