.TH "sqlite3_vtab" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite3_vtab \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sqlite3.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBsqlite3_module\fP * \fBpModule\fP"
.br
.ti -1c
.RI "int \fBnRef\fP"
.br
.ti -1c
.RI "char * \fBzErrMsg\fP"
.br
.ti -1c
.RI "const \fBsqlite3_module\fP * \fBpModule\fP"
.br
.ti -1c
.RI "char * \fBzErrMsg\fP"
.br
.ti -1c
.RI "const \fBsqlite3_module\fP * \fBpModule\fP"
.br
.ti -1c
.RI "char * \fBzErrMsg\fP"
.br
.ti -1c
.RI "const \fBsqlite3_module\fP * \fBpModule\fP"
.br
.ti -1c
.RI "char * \fBzErrMsg\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBsqlite3_vtab::nRef\fP"
.PP
.SS "const \fBsqlite3_module\fP* \fBsqlite3_vtab::pModule\fP"
.PP
.SS "const \fBsqlite3_module\fP* \fBsqlite3_vtab::pModule\fP"
.PP
.SS "const \fBsqlite3_module\fP* \fBsqlite3_vtab::pModule\fP"
.PP
.SS "const \fBsqlite3_module\fP* \fBsqlite3_vtab::pModule\fP"
.PP
.SS "char* \fBsqlite3_vtab::zErrMsg\fP"
.PP
.SS "char* \fBsqlite3_vtab::zErrMsg\fP"
.PP
.SS "char* \fBsqlite3_vtab::zErrMsg\fP"
.PP
.SS "char* \fBsqlite3_vtab::zErrMsg\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
