.TH "sqlite3_vtab_cursor" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite3_vtab_cursor \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sqlite3.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsqlite3_vtab\fP * \fBpVtab\fP"
.br
.ti -1c
.RI "\fBsqlite3_vtab\fP * \fBpVtab\fP"
.br
.ti -1c
.RI "\fBsqlite3_vtab\fP * \fBpVtab\fP"
.br
.ti -1c
.RI "\fBsqlite3_vtab\fP * \fBpVtab\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBsqlite3_vtab\fP* \fBsqlite3_vtab_cursor::pVtab\fP"
.PP
.SS "\fBsqlite3_vtab\fP* \fBsqlite3_vtab_cursor::pVtab\fP"
.PP
.SS "\fBsqlite3_vtab\fP* \fBsqlite3_vtab_cursor::pVtab\fP"
.PP
.SS "\fBsqlite3_vtab\fP* \fBsqlite3_vtab_cursor::pVtab\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
