.TH "SrcList" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SrcList \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBi16\fP \fBnSrc\fP"
.br
.ti -1c
.RI "\fBi16\fP \fBnAlloc\fP"
.br
.ti -1c
.RI "\fBSrcList::SrcList_item\fP \fBa\fP [1]"
.br
.ti -1c
.RI "\fBSrcList::SrcList_item\fP \fBa\fP [1]"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBSrcList_item\fP"
.br
.ti -1c
.RI "struct \fBSrcList_item\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBSrcList::SrcList_item\fP  \fBSrcList::a\fP[1]"
.PP
.SS "struct \fBSrcList::SrcList_item\fP  \fBSrcList::a\fP[1]"
.PP
.SS "\fBi16\fP \fBSrcList::nAlloc\fP"
.PP
.SS "\fBi16\fP \fBSrcList::nSrc\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
