.TH "stat" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stat \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__dev_t\fP \fBst_dev\fP"
.br
.ti -1c
.RI "\fB__ino_t\fP \fBst_ino\fP"
.br
.ti -1c
.RI "\fB__nlink_t\fP \fBst_nlink\fP"
.br
.ti -1c
.RI "\fB__mode_t\fP \fBst_mode\fP"
.br
.ti -1c
.RI "\fB__uid_t\fP \fBst_uid\fP"
.br
.ti -1c
.RI "\fB__gid_t\fP \fBst_gid\fP"
.br
.ti -1c
.RI "int \fBpad0\fP"
.br
.ti -1c
.RI "\fB__dev_t\fP \fBst_rdev\fP"
.br
.ti -1c
.RI "\fB__off_t\fP \fBst_size\fP"
.br
.ti -1c
.RI "\fB__blksize_t\fP \fBst_blksize\fP"
.br
.ti -1c
.RI "\fB__blkcnt_t\fP \fBst_blocks\fP"
.br
.ti -1c
.RI "struct \fBtimespec\fP \fBst_atim\fP"
.br
.ti -1c
.RI "struct \fBtimespec\fP \fBst_mtim\fP"
.br
.ti -1c
.RI "struct \fBtimespec\fP \fBst_ctim\fP"
.br
.ti -1c
.RI "long int \fB__unused\fP [3]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "long int \fBstat::__unused\fP"
.SS "int \fBstat::pad0\fP"
.SS "struct \fBtimespec\fP \fBstat::st_atim\fP"
.SS "\fB__blksize_t\fP \fBstat::st_blksize\fP"
.SS "\fB__blkcnt_t\fP \fBstat::st_blocks\fP"
.SS "struct \fBtimespec\fP \fBstat::st_ctim\fP"
.SS "\fB__dev_t\fP \fBstat::st_dev\fP"
.SS "\fB__gid_t\fP \fBstat::st_gid\fP"
.SS "\fB__ino_t\fP \fBstat::st_ino\fP"
.SS "\fB__mode_t\fP \fBstat::st_mode\fP"
.PP
Referenced by buddy_exec_action(), create_buddy(), resolve_symlink(), upk_rm_rf(), and upk_state_init().
.SS "struct \fBtimespec\fP \fBstat::st_mtim\fP"
.SS "\fB__nlink_t\fP \fBstat::st_nlink\fP"
.SS "\fB__dev_t\fP \fBstat::st_rdev\fP"
.SS "\fB__off_t\fP \fBstat::st_size\fP"
.SS "\fB__uid_t\fP \fBstat::st_uid\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
