.TH "StrAccum" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StrAccum \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.ti -1c
.RI "char * \fBzBase\fP"
.br
.ti -1c
.RI "char * \fBzText\fP"
.br
.ti -1c
.RI "int \fBnChar\fP"
.br
.ti -1c
.RI "int \fBnAlloc\fP"
.br
.ti -1c
.RI "int \fBmxAlloc\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBmallocFailed\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBuseMalloc\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBtooBig\fP"
.br
.ti -1c
.RI "\fBsqlite3\fP * \fBdb\fP"
.br
.ti -1c
.RI "char * \fBzBase\fP"
.br
.ti -1c
.RI "char * \fBzText\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBsqlite3\fP* \fBStrAccum::db\fP"
.PP
.SS "\fBsqlite3\fP* \fBStrAccum::db\fP"
.PP
.SS "\fBu8\fP \fBStrAccum::mallocFailed\fP"
.PP
.SS "int \fBStrAccum::mxAlloc\fP"
.PP
.SS "int \fBStrAccum::nAlloc\fP"
.PP
.SS "int \fBStrAccum::nChar\fP"
.PP
.SS "\fBu8\fP \fBStrAccum::tooBig\fP"
.PP
.SS "\fBu8\fP \fBStrAccum::useMalloc\fP"
.PP
.SS "char* \fBStrAccum::zBase\fP"
.PP
.SS "char* \fBStrAccum::zBase\fP"
.PP
.SS "char* \fBStrAccum::zText\fP"
.PP
.SS "char* \fBStrAccum::zText\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
