.TH "SubProgram" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SubProgram \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBVdbeOp\fP * \fBaOp\fP"
.br
.ti -1c
.RI "int \fBnOp\fP"
.br
.ti -1c
.RI "int \fBnMem\fP"
.br
.ti -1c
.RI "int \fBnCsr\fP"
.br
.ti -1c
.RI "void * \fBtoken\fP"
.br
.ti -1c
.RI "\fBSubProgram\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBVdbeOp\fP * \fBaOp\fP"
.br
.ti -1c
.RI "void * \fBtoken\fP"
.br
.ti -1c
.RI "\fBSubProgram\fP * \fBpNext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBVdbeOp\fP* \fBSubProgram::aOp\fP"
.PP
.SS "\fBVdbeOp\fP* \fBSubProgram::aOp\fP"
.PP
.SS "int \fBSubProgram::nCsr\fP"
.PP
.SS "int \fBSubProgram::nMem\fP"
.PP
.SS "int \fBSubProgram::nOp\fP"
.PP
.SS "\fBSubProgram\fP* \fBSubProgram::pNext\fP"
.PP
.SS "\fBSubProgram\fP* \fBSubProgram::pNext\fP"
.PP
.SS "void* \fBSubProgram::token\fP"
.PP
.SS "void* \fBSubProgram::token\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
