.TH "SumCtx" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SumCtx \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBrSum\fP"
.br
.ti -1c
.RI "\fBi64\fP \fBiSum\fP"
.br
.ti -1c
.RI "\fBi64\fP \fBcnt\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBoverflow\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBapprox\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu8\fP \fBSumCtx::approx\fP"
.PP
.SS "\fBi64\fP \fBSumCtx::cnt\fP"
.PP
.SS "\fBi64\fP \fBSumCtx::iSum\fP"
.PP
.SS "\fBu8\fP \fBSumCtx::overflow\fP"
.PP
.SS "double \fBSumCtx::rSum\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
