.TH "libupkeeper/t.c" 3 "Tue Jul 26 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libupkeeper/t.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <upkeeper.h>\fP
.br
\fC#include 'upkeeper/upk_json.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"
.PP
References _upk_controller_config::BuddyPollingInterval, _upk_json_data_output_options::pad, _upk_controller_config::ServiceDefaults, _upk_controller_config::svclist, upk_ctrl_free_config(), upk_ctrl_load_config(), upk_default_configuration, upk_default_configuration_vec, upk_diag_verbosity, UPK_DIAGLVL_DEBUG1, upk_file_configuration, upk_json_obj_to_stream(), upk_json_obj_to_string(), upk_json_parse_string(), upk_json_serialize_svc_config(), upk_load_runtime_services(), upk_runtime_configuration, upk_svclist_to_json_obj(), and _upk_controller_config::UpkBuddyPath.
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
