.TH "TableLock" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TableLock \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBiDb\fP"
.br
.ti -1c
.RI "int \fBiTab\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBisWriteLock\fP"
.br
.ti -1c
.RI "const char * \fBzName\fP"
.br
.ti -1c
.RI "const char * \fBzName\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBTableLock::iDb\fP"
.PP
.SS "\fBu8\fP \fBTableLock::isWriteLock\fP"
.PP
.SS "int \fBTableLock::iTab\fP"
.PP
.SS "const char* \fBTableLock::zName\fP"
.PP
.SS "const char* \fBTableLock::zName\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
