.TH "TabResult" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TabResult \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char ** \fBazResult\fP"
.br
.ti -1c
.RI "char * \fBzErrMsg\fP"
.br
.ti -1c
.RI "int \fBnAlloc\fP"
.br
.ti -1c
.RI "int \fBnRow\fP"
.br
.ti -1c
.RI "int \fBnColumn\fP"
.br
.ti -1c
.RI "int \fBnData\fP"
.br
.ti -1c
.RI "int \fBrc\fP"
.br
.ti -1c
.RI "char ** \fBazResult\fP"
.br
.ti -1c
.RI "char * \fBzErrMsg\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char** \fBTabResult::azResult\fP"
.PP
.SS "char** \fBTabResult::azResult\fP"
.PP
.SS "int \fBTabResult::nAlloc\fP"
.PP
.SS "int \fBTabResult::nColumn\fP"
.PP
.SS "int \fBTabResult::nData\fP"
.PP
.SS "int \fBTabResult::nRow\fP"
.PP
.SS "int \fBTabResult::rc\fP"
.PP
.SS "char* \fBTabResult::zErrMsg\fP"
.PP
.SS "char* \fBTabResult::zErrMsg\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
