.TH "common/test.c" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <sqlite3.h>\fP
.br
\fC#include <fcntl.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <string.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBupk_test_is\fP (int is, int should, const char *msg)"
.br
.ti -1c
.RI "int \fBupk_test_isnt\fP (int is, int shouldnt, const char *msg)"
.br
.ti -1c
.RI "int \fBupk_test_eq\fP (const char *is, const char *should, const char *msg)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBDEBUG\fP"
.br
.ti -1c
.RI "int \fBTESTS\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int upk_test_eq (const char * is, const char * should, const char * msg)"
.PP
.SS "int upk_test_is (int is, int should, const char * msg)"
.PP
.SS "int upk_test_isnt (int is, int shouldnt, const char * msg)"
.PP
.SH "Variable Documentation"
.PP 
.SS "int \fBDEBUG\fP"
.PP
.SS "int \fBTESTS\fP = 0"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
