.TH "common/test.h" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/test.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBupk_test_is\fP (int is, int should, const char *msg)"
.br
.ti -1c
.RI "int \fBupk_test_eq\fP (const char *is, const char *should, const char *msg)"
.br
.ti -1c
.RI "int \fBupk_test_isnt\fP (int is, int shouldnt, const char *msg)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int upk_test_eq (const char * is, const char * should, const char * msg)"
.PP
.SS "int upk_test_is (int is, int should, const char * msg)"
.PP
.SS "int upk_test_isnt (int is, int shouldnt, const char * msg)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
