.TH "timeval" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timeval \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__time_t\fP \fBtv_sec\fP"
.br
.ti -1c
.RI "\fB__suseconds_t\fP \fBtv_usec\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fB__time_t\fP \fBtimeval::tv_sec\fP"
.PP
Referenced by buddy_event_loop(), buddy_readstate(), read_ctrl(), send_buddy_cmd(), upk_net_block_until_msg(), upk_uuid_seed_random(), and write_ctrl().
.SS "\fB__suseconds_t\fP \fBtimeval::tv_usec\fP"
.PP
Referenced by buddy_event_loop(), buddy_readstate(), read_ctrl(), upk_net_block_until_msg(), upk_uuid_seed_random(), and write_ctrl().

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
