.TH "timezone" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timezone \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtz_minuteswest\fP"
.br
.ti -1c
.RI "int \fBtz_dsttime\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBtimezone::tz_dsttime\fP"
.SS "int \fBtimezone::tz_minuteswest\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
