.TH "timespec" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timespec \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__time_t\fP \fBtv_sec\fP"
.br
.ti -1c
.RI "long int \fBtv_nsec\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "long int \fBtimespec::tv_nsec\fP"
.PP
Referenced by buddy_stop_proc(), and phone_home_if_appropriate().
.SS "\fB__time_t\fP \fBtimespec::tv_sec\fP"
.PP
Referenced by buddy_stop_proc(), phone_home_if_appropriate(), and spawn_buddy().

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
