.TH "tm" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tm \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtm_sec\fP"
.br
.ti -1c
.RI "int \fBtm_min\fP"
.br
.ti -1c
.RI "int \fBtm_hour\fP"
.br
.ti -1c
.RI "int \fBtm_mday\fP"
.br
.ti -1c
.RI "int \fBtm_mon\fP"
.br
.ti -1c
.RI "int \fBtm_year\fP"
.br
.ti -1c
.RI "int \fBtm_wday\fP"
.br
.ti -1c
.RI "int \fBtm_yday\fP"
.br
.ti -1c
.RI "int \fBtm_isdst\fP"
.br
.ti -1c
.RI "long int \fBtm_gmtoff\fP"
.br
.ti -1c
.RI "__const char * \fBtm_zone\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "long int \fBtm::tm_gmtoff\fP"
.SS "int \fBtm::tm_hour\fP"
.SS "int \fBtm::tm_isdst\fP"
.SS "int \fBtm::tm_mday\fP"
.SS "int \fBtm::tm_min\fP"
.SS "int \fBtm::tm_mon\fP"
.SS "int \fBtm::tm_sec\fP"
.SS "int \fBtm::tm_wday\fP"
.SS "int \fBtm::tm_yday\fP"
.SS "int \fBtm::tm_year\fP"
.SS "__const char * \fBtm::tm_zone\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
