.TH "TriggerStep" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TriggerStep \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBop\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBorconf\fP"
.br
.ti -1c
.RI "\fBTrigger\fP * \fBpTrig\fP"
.br
.ti -1c
.RI "\fBSelect\fP * \fBpSelect\fP"
.br
.ti -1c
.RI "\fBToken\fP \fBtarget\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpWhere\fP"
.br
.ti -1c
.RI "\fBExprList\fP * \fBpExprList\fP"
.br
.ti -1c
.RI "\fBIdList\fP * \fBpIdList\fP"
.br
.ti -1c
.RI "\fBTriggerStep\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBTriggerStep\fP * \fBpLast\fP"
.br
.ti -1c
.RI "\fBTrigger\fP * \fBpTrig\fP"
.br
.ti -1c
.RI "\fBSelect\fP * \fBpSelect\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpWhere\fP"
.br
.ti -1c
.RI "\fBExprList\fP * \fBpExprList\fP"
.br
.ti -1c
.RI "\fBIdList\fP * \fBpIdList\fP"
.br
.ti -1c
.RI "\fBTriggerStep\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBTriggerStep\fP * \fBpLast\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu8\fP \fBTriggerStep::op\fP"
.PP
.SS "\fBu8\fP \fBTriggerStep::orconf\fP"
.PP
.SS "\fBExprList\fP* \fBTriggerStep::pExprList\fP"
.PP
.SS "\fBExprList\fP* \fBTriggerStep::pExprList\fP"
.PP
.SS "\fBIdList\fP* \fBTriggerStep::pIdList\fP"
.PP
.SS "\fBIdList\fP* \fBTriggerStep::pIdList\fP"
.PP
.SS "\fBTriggerStep\fP* \fBTriggerStep::pLast\fP"
.PP
.SS "\fBTriggerStep\fP* \fBTriggerStep::pLast\fP"
.PP
.SS "\fBTriggerStep\fP* \fBTriggerStep::pNext\fP"
.PP
.SS "\fBTriggerStep\fP* \fBTriggerStep::pNext\fP"
.PP
.SS "\fBSelect\fP* \fBTriggerStep::pSelect\fP"
.PP
.SS "\fBSelect\fP* \fBTriggerStep::pSelect\fP"
.PP
.SS "\fBTrigger\fP* \fBTriggerStep::pTrig\fP"
.PP
.SS "\fBTrigger\fP* \fBTriggerStep::pTrig\fP"
.PP
.SS "\fBExpr\fP* \fBTriggerStep::pWhere\fP"
.PP
.SS "\fBExpr\fP* \fBTriggerStep::pWhere\fP"
.PP
.SS "\fBToken\fP \fBTriggerStep::target\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
