.TH "Trigger" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Trigger \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBzName\fP"
.br
.ti -1c
.RI "char * \fBtable\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBop\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBtr_tm\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpWhen\fP"
.br
.ti -1c
.RI "\fBIdList\fP * \fBpColumns\fP"
.br
.ti -1c
.RI "\fBSchema\fP * \fBpSchema\fP"
.br
.ti -1c
.RI "\fBSchema\fP * \fBpTabSchema\fP"
.br
.ti -1c
.RI "\fBTriggerStep\fP * \fBstep_list\fP"
.br
.ti -1c
.RI "\fBTrigger\fP * \fBpNext\fP"
.br
.ti -1c
.RI "char * \fBzName\fP"
.br
.ti -1c
.RI "char * \fBtable\fP"
.br
.ti -1c
.RI "\fBExpr\fP * \fBpWhen\fP"
.br
.ti -1c
.RI "\fBIdList\fP * \fBpColumns\fP"
.br
.ti -1c
.RI "\fBSchema\fP * \fBpSchema\fP"
.br
.ti -1c
.RI "\fBSchema\fP * \fBpTabSchema\fP"
.br
.ti -1c
.RI "\fBTriggerStep\fP * \fBstep_list\fP"
.br
.ti -1c
.RI "\fBTrigger\fP * \fBpNext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu8\fP \fBTrigger::op\fP"
.PP
.SS "\fBIdList\fP* \fBTrigger::pColumns\fP"
.PP
.SS "\fBIdList\fP* \fBTrigger::pColumns\fP"
.PP
.SS "\fBTrigger\fP* \fBTrigger::pNext\fP"
.PP
.SS "\fBTrigger\fP* \fBTrigger::pNext\fP"
.PP
.SS "\fBSchema\fP* \fBTrigger::pSchema\fP"
.PP
.SS "\fBSchema\fP* \fBTrigger::pSchema\fP"
.PP
.SS "\fBSchema\fP* \fBTrigger::pTabSchema\fP"
.PP
.SS "\fBSchema\fP* \fBTrigger::pTabSchema\fP"
.PP
.SS "\fBExpr\fP* \fBTrigger::pWhen\fP"
.PP
.SS "\fBExpr\fP* \fBTrigger::pWhen\fP"
.PP
.SS "\fBTriggerStep\fP* \fBTrigger::step_list\fP"
.PP
.SS "\fBTriggerStep\fP* \fBTrigger::step_list\fP"
.PP
.SS "char* \fBTrigger::table\fP"
.PP
.SS "char* \fBTrigger::table\fP"
.PP
.SS "\fBu8\fP \fBTrigger::tr_tm\fP"
.PP
.SS "char* \fBTrigger::zName\fP"
.PP
.SS "char* \fBTrigger::zName\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
