.TH "TriggerPrg" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TriggerPrg \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTrigger\fP * \fBpTrigger\fP"
.br
.ti -1c
.RI "int \fBorconf\fP"
.br
.ti -1c
.RI "\fBSubProgram\fP * \fBpProgram\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBaColmask\fP [2]"
.br
.ti -1c
.RI "\fBTriggerPrg\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBTrigger\fP * \fBpTrigger\fP"
.br
.ti -1c
.RI "\fBSubProgram\fP * \fBpProgram\fP"
.br
.ti -1c
.RI "\fBTriggerPrg\fP * \fBpNext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu32\fP \fBTriggerPrg::aColmask\fP"
.PP
.SS "int \fBTriggerPrg::orconf\fP"
.PP
.SS "\fBTriggerPrg\fP* \fBTriggerPrg::pNext\fP"
.PP
.SS "\fBTriggerPrg\fP* \fBTriggerPrg::pNext\fP"
.PP
.SS "\fBSubProgram\fP* \fBTriggerPrg::pProgram\fP"
.PP
.SS "\fBSubProgram\fP* \fBTriggerPrg::pProgram\fP"
.PP
.SS "\fBTrigger\fP* \fBTriggerPrg::pTrigger\fP"
.PP
.SS "\fBTrigger\fP* \fBTriggerPrg::pTrigger\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
