.TH "ucontext" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ucontext \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long int \fBuc_flags\fP"
.br
.ti -1c
.RI "struct \fBucontext\fP * \fBuc_link\fP"
.br
.ti -1c
.RI "\fBstack_t\fP \fBuc_stack\fP"
.br
.ti -1c
.RI "\fBmcontext_t\fP \fBuc_mcontext\fP"
.br
.ti -1c
.RI "\fB__sigset_t\fP \fBuc_sigmask\fP"
.br
.ti -1c
.RI "struct \fB_libc_fpstate\fP \fB__fpregs_mem\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fB_libc_fpstate\fP \fBucontext::__fpregs_mem\fP"
.SS "unsigned long int \fBucontext::uc_flags\fP"
.SS "struct \fBucontext\fP * \fBucontext::uc_link\fP"
.SS "\fBmcontext_t\fP \fBucontext::uc_mcontext\fP"
.SS "\fB__sigset_t\fP \fBucontext::uc_sigmask\fP"
.SS "\fBstack_t\fP \fBucontext::uc_stack\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
