.TH "ucred" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ucred \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpid_t\fP \fBpid\fP"
.br
.ti -1c
.RI "\fBuid_t\fP \fBuid\fP"
.br
.ti -1c
.RI "\fBgid_t\fP \fBgid\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBgid_t\fP \fBucred::gid\fP"
.SS "\fBpid_t\fP \fBucred::pid\fP"
.SS "\fBuid_t\fP \fBucred::uid\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
