.TH "unixFile" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
unixFile \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsqlite3_io_methods\fP const * \fBpMethod\fP"
.br
.ti -1c
.RI "\fBunixInodeInfo\fP * \fBpInode\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "int \fBdirfd\fP"
.br
.ti -1c
.RI "unsigned char \fBeFileLock\fP"
.br
.ti -1c
.RI "int \fBlastErrno\fP"
.br
.ti -1c
.RI "void * \fBlockingContext\fP"
.br
.ti -1c
.RI "\fBUnixUnusedFd\fP * \fBpUnused\fP"
.br
.ti -1c
.RI "int \fBfileFlags\fP"
.br
.ti -1c
.RI "const char * \fBzPath\fP"
.br
.ti -1c
.RI "\fBunixShm\fP * \fBpShm\fP"
.br
.ti -1c
.RI "int \fBszChunk\fP"
.br
.ti -1c
.RI "\fBsqlite3_io_methods\fP const * \fBpMethod\fP"
.br
.ti -1c
.RI "\fBunixInodeInfo\fP * \fBpInode\fP"
.br
.ti -1c
.RI "void * \fBlockingContext\fP"
.br
.ti -1c
.RI "\fBUnixUnusedFd\fP * \fBpUnused\fP"
.br
.ti -1c
.RI "const char * \fBzPath\fP"
.br
.ti -1c
.RI "\fBunixShm\fP * \fBpShm\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBunixFile::dirfd\fP"
.PP
.SS "unsigned char \fBunixFile::eFileLock\fP"
.PP
.SS "int \fBunixFile::fileFlags\fP"
.PP
.SS "int \fBunixFile::h\fP"
.PP
.SS "int \fBunixFile::lastErrno\fP"
.PP
.SS "void* \fBunixFile::lockingContext\fP"
.PP
.SS "void* \fBunixFile::lockingContext\fP"
.PP
.SS "\fBunixInodeInfo\fP* \fBunixFile::pInode\fP"
.PP
.SS "\fBunixInodeInfo\fP* \fBunixFile::pInode\fP"
.PP
.SS "\fBsqlite3_io_methods\fP const* \fBunixFile::pMethod\fP"
.PP
.SS "\fBsqlite3_io_methods\fP const* \fBunixFile::pMethod\fP"
.PP
.SS "\fBunixShm\fP* \fBunixFile::pShm\fP"
.PP
.SS "\fBunixShm\fP* \fBunixFile::pShm\fP"
.PP
.SS "\fBUnixUnusedFd\fP* \fBunixFile::pUnused\fP"
.PP
.SS "\fBUnixUnusedFd\fP* \fBunixFile::pUnused\fP"
.PP
.SS "int \fBunixFile::szChunk\fP"
.PP
.SS "const char* \fBunixFile::zPath\fP"
.PP
.SS "const char* \fBunixFile::zPath\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
