.TH "unixFileId" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
unixFileId \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "dev_t \fBdev\fP"
.br
.ti -1c
.RI "ino_t \fBino\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "dev_t \fBunixFileId::dev\fP"
.PP
.SS "ino_t \fBunixFileId::ino\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
