.TH "unixShm" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
unixShm \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBunixShmNode\fP * \fBpShmNode\fP"
.br
.ti -1c
.RI "\fBunixShm\fP * \fBpNext\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBhasMutex\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBsharedMask\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBexclMask\fP"
.br
.ti -1c
.RI "\fBunixShmNode\fP * \fBpShmNode\fP"
.br
.ti -1c
.RI "\fBunixShm\fP * \fBpNext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu16\fP \fBunixShm::exclMask\fP"
.PP
.SS "\fBu8\fP \fBunixShm::hasMutex\fP"
.PP
.SS "\fBunixShm\fP* \fBunixShm::pNext\fP"
.PP
.SS "\fBunixShm\fP* \fBunixShm::pNext\fP"
.PP
.SS "\fBunixShmNode\fP* \fBunixShm::pShmNode\fP"
.PP
.SS "\fBunixShmNode\fP* \fBunixShm::pShmNode\fP"
.PP
.SS "\fBu16\fP \fBunixShm::sharedMask\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
