.TH "UnpackedRecord" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnpackedRecord \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKeyInfo\fP * \fBpKeyInfo\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBnField\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBi64\fP \fBrowid\fP"
.br
.ti -1c
.RI "\fBMem\fP * \fBaMem\fP"
.br
.ti -1c
.RI "\fBKeyInfo\fP * \fBpKeyInfo\fP"
.br
.ti -1c
.RI "\fBMem\fP * \fBaMem\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBMem\fP* \fBUnpackedRecord::aMem\fP"
.PP
.SS "\fBMem\fP* \fBUnpackedRecord::aMem\fP"
.PP
.SS "\fBu16\fP \fBUnpackedRecord::flags\fP"
.PP
.SS "\fBu16\fP \fBUnpackedRecord::nField\fP"
.PP
.SS "\fBKeyInfo\fP* \fBUnpackedRecord::pKeyInfo\fP"
.PP
.SS "\fBKeyInfo\fP* \fBUnpackedRecord::pKeyInfo\fP"
.PP
.SS "\fBi64\fP \fBUnpackedRecord::rowid\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
