.TH "libupkeeper/upkeeper/upk_json_fmt.h" 3 "Tue Nov 1 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libupkeeper/upkeeper/upk_json_fmt.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_upk_json_data_output_options\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_upk_json_data_output_options\fP \fBupk_json_data_output_opts_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_upk_json_data_output_options\fP  \fBupk_json_data_output_opts_t\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
