.TH "upk_api_service" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upk_api_service \- 
.SH SYNOPSIS
.br
.PP
\fC#include <upk_api.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBpackage\fP"
.br
.ti -1c
.RI "const char * \fBservice\fP"
.br
.ti -1c
.RI "const char * \fBcmdline\fP"
.br
.ti -1c
.RI "const char * \fBstate_desired\fP"
.br
.ti -1c
.RI "const char * \fBstate_actual\fP"
.br
.ti -1c
.RI "int \fBpid\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "const char* \fBupk_api_service::cmdline\fP"
.PP
.SS "const char* \fBupk_api_service::package\fP"
.PP
.SS "int \fBupk_api_service::pid\fP"
.PP
.SS "const char* \fBupk_api_service::service\fP"
.PP
.SS "const char* \fBupk_api_service::state_actual\fP"
.PP
.SS "const char* \fBupk_api_service::state_desired\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
