.TH "upk_repl_seq_end_t" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upk_repl_seq_end_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <upk_protocol.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBupk_msgtype_t\fP \fBmsgtype\fP"
.br
.ti -1c
.RI "_Bool \fBcommit\fP"
.br
.ti -1c
.RI "\fBUPK_V0_UPK_REPL_SEQ_END_T_FIELDS\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "_Bool \fBupk_repl_seq_end_t::commit\fP"
.SS "\fBupk_msgtype_t\fP \fBupk_repl_seq_end_t::msgtype\fP"
.SS "\fBupk_repl_seq_end_t::UPK_V0_UPK_REPL_SEQ_END_T_FIELDS\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
