.TH "libupkeeper/upkeeper/upk_compat.c" 3 "Tue Nov 1 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libupkeeper/upkeeper/upk_compat.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBstrnlen\fP (const char *restrict string, size_t maxlen)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "size_t strnlen (const char *restrictstring, size_tmaxlen)"
.PP
Referenced by buddy_init_paths(), opt_parse(), upk_config_loadfile(), upk_create_req_preamble(), upk_json_append_string(), upk_json_output_array_handler(), upk_json_output_object_handler(), upk_load_runtime_services(), upk_svcconf_string_handler(), and v0_create_repl_svcinfo().
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
