.TH "libupkeeper/upkeeper/upk_util.h" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libupkeeper/upkeeper/upk_util.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_stringify\fP(A)   #A"
.br
.ti -1c
.RI "#define \fBstringify\fP(A)   _stringify(A)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBupk_numeric_string\fP (const char *string, long *num)"
.br
.ti -1c
.RI "bool \fBupk_boolean_string\fP (const char *string, bool *val)"
.br
.ti -1c
.RI "void \fBupk_replace_string\fP (char **haystack, const char *needle, const char *repl)"
.br
.ti -1c
.RI "struct \fBtimeval\fP \fBupk_double_to_timeval\fP (long double rational)"
.br
.ti -1c
.RI "int \fBupk_rm_rf\fP (char *start_path)"
.br
.ti -1c
.RI "int \fBupk_mkdir_p\fP (const char *path)"
.br
.RI "\fIcreate a directory and any path components leading up to it. \fP"
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _stringify(A)   #A"
.SS "#define stringify(A)   _stringify(A)"
.SH "Function Documentation"
.PP 
.SS "bool upk_boolean_string (const char *string, bool *val)"*************************************************************************** 
.PP
References upk_numeric_string().
.SS "struct \fBtimeval\fP upk_double_to_timeval (long doubler)\fC [read]\fP"*************************************************************************** 
.SS "int upk_mkdir_p (const char *path)"
.PP
create a directory and any path components leading up to it. *************************************************************************** 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP directory to create.
.RE
.PP
\fBReturns:\fP
.RS 4
the number of directories successfully created. 
.RE
.PP

.SS "bool upk_numeric_string (const char *string, long *num)"*************************************************************************** 
.SS "void upk_replace_string (char **haystack, const char *needle, const char *repl)"*************************************************************************** 
.SS "int upk_rm_rf (char *start_path)"*************************************************************************** 
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
