.TH "clients/upk_reload.c" 3 "Tue Nov 1 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clients/upk_reload.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <upkeeper.h>\fP
.br
\fC#include <sys/un.h>\fP
.br
\fC#include <stdio.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv, char **envp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv, char **envp)"
.PP
References upk_clnet_ctrl_connect(), upk_clnet_ctrl_disconnect(), upk_clnet_req_action(), upk_conn_handle_meta_t, upk_ctrl_free_config(), upk_ctrl_load_config(), upk_diag_verbosity, UPK_DIAGLVL_DEBUG1, and upk_fatal.
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
