.TH "libupkeeper/upkeeper/upk_compat.c" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libupkeeper/upkeeper/upk_compat.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsize_t\fP \fBstrnlen\fP (const char *restrict string, \fBsize_t\fP maxlen)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBsize_t\fP strnlen (const char *restrictstring, \fBsize_t\fPmaxlen)"
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
