.TH "upk_generic_msg_t" 3 "Wed Sep 14 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upk_generic_msg_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <upk_protocol.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBupk_msgtype_t\fP \fBmsgtype\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBupk_msgtype_t\fP \fBupk_generic_msg_t::msgtype\fP"
.PP
Referenced by serialize_pub_payload(), serialize_repl_payload(), serialize_req_payload(), and upk_get_msgtype().

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
