.TH "libupkeeper/upkeeper/upk_client.h" 3 "Wed Sep 14 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libupkeeper/upkeeper/upk_client.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'upk_types.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBupkeeper_action_request\fP (char *service_id, char *action_name)"
.br
.ti -1c
.RI "bool \fBupkeeper_signal_request\fP (char *service_id, \fBupk_signal_t\fP signal)"
.br
.ti -1c
.RI "\fBupk_svcid_t\fP * \fBupkeeper_list_services\fP (void)"
.br
.ti -1c
.RI "\fBupk_svcinfo_t\fP \fBupkeeper_get_status\fP (char *service_id)"
.br
.ti -1c
.RI "bool \fBupkeeper_subscribe\fP (const char *svc_id)"
.br
.ti -1c
.RI "bool \fBupkeeper_subscribe_all\fP (void)"
.br
.ti -1c
.RI "char * \fBupk_clientid\fP (void)"
.br
.RI "\fIfill buf with the client_id string. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* upk_clientid (void)"
.PP
fill buf with the client_id string. \fBParameters:\fP
.RS 4
\fIbuf\fP allocated buffer to write clientid into 
.RE
.PP

.PP
References UPK_MAX_STRING_LEN.
.PP
Referenced by main(), and upk_clnet_req_preamble().
.SS "bool upkeeper_action_request (char *service_id, char *action_name)"
.SS "\fBupk_svcinfo_t\fP upkeeper_get_status (char *service_id)"
.SS "\fBupk_svcid_t\fP* upkeeper_list_services (void)"
.SS "bool upkeeper_signal_request (char *service_id, \fBupk_signal_t\fPsignal)"
.SS "bool upkeeper_subscribe (const char *svc_id)"
.SS "bool upkeeper_subscribe_all (void)"
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
