.TH "upk_req_action_t" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upk_req_action_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <upk_protocol.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBupk_msgtype_t\fP \fBmsgtype\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBsvc_id_len\fP"
.br
.ti -1c
.RI "char \fBsvc_id\fP [2048]"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBaction_len\fP"
.br
.ti -1c
.RI "char \fBaction\fP [2048]"
.br
.ti -1c
.RI "\fBUPK_V0_REQ_ACTION_T_FIELDS\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char \fBupk_req_action_t::action\fP"
.PP
Referenced by ctrl_req_action_handler().
.SS "\fBuint32_t\fP \fBupk_req_action_t::action_len\fP"
.SS "\fBupk_msgtype_t\fP \fBupk_req_action_t::msgtype\fP"
.SS "char \fBupk_req_action_t::svc_id\fP"
.PP
Referenced by ctrl_req_action_handler().
.SS "\fBuint32_t\fP \fBupk_req_action_t::svc_id_len\fP"
.SS "\fBupk_req_action_t::UPK_V0_REQ_ACTION_T_FIELDS\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
