.TH "upk_json_obj_iter" 3 "Wed Sep 14 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upk_json_obj_iter \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct lh_entry * \fBentry\fP"
.br
.ti -1c
.RI "char * \fBkey\fP"
.br
.ti -1c
.RI "struct json_object * \fBval\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct lh_entry* \fBupk_json_obj_iter::entry\fP"
.SS "char* \fBupk_json_obj_iter::key\fP"
.PP
Referenced by upk_json_parse_obj().
.SS "struct json_object* \fBupk_json_obj_iter::val\fP"
.PP
Referenced by upk_json_parse_obj().

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
