.TH "upk_repl_ack_t" 3 "Tue Nov 1 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upk_repl_ack_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <upk_protocol.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBUPK_V0_REPL_ACK_T_FIELDS\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBupk_repl_ack_t::UPK_V0_REPL_ACK_T_FIELDS\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
