.TH "upk_protocol_handle_t" 3 "Tue Jul 26 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upk_protocol_handle_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <upk_protocol.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBversion_id\fP"
.br
.ti -1c
.RI "uint32_t \fBseq_num\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t \fBupk_protocol_handle_t::seq_num\fP"
.SS "uint32_t \fBupk_protocol_handle_t::version_id\fP"
.PP
Referenced by upk_create_ack_repl(), upk_create_action_req(), upk_create_cancel_pubmsg(), upk_create_discon_req(), upk_create_error_repl(), upk_create_list_req(), upk_create_listing_repl(), upk_create_pub_pubmsg(), upk_create_repl_seq_end(), upk_create_repl_seq_start(), upk_create_req_seq_end(), upk_create_req_seq_start(), upk_create_result_repl(), upk_create_signal_req(), upk_create_status_req(), upk_create_subscr_req(), upk_create_svcinfo_repl(), and upk_create_unsubs_req().

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
