.TH "uptop/uptop.h" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uptop/uptop.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBuptop_print_callback\fP (void *ignored, upk_srvc_t srvc, const char *status_desired, const char *status_actual)"
.br
.ti -1c
.RI "void \fBuptop_services_print\fP (sqlite3 *pdb)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void uptop_print_callback (void * ignored, upk_srvc_t srvc, const char * status_desired, const char * status_actual)"
.PP
.SS "void uptop_services_print (sqlite3 * pdb)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
