.TH "libupkeeper/upkeeper/uuid.c" 3 "Wed Sep 14 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libupkeeper/upkeeper/uuid.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'upk_uuid.h'\fP
.br
\fC#include <stdio.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBupk_uuid_seed_random\fP (void)"
.br
.RI "\fIseed random number pool used by upk_gen_uuid_bytes. \fP"
.ti -1c
.RI "int \fBupk_uuid_open_random\fP (void)"
.br
.RI "\fIopen random device, prefering /dev/urandom, but also trying /dev/random if urandom is unavailable. \fP"
.ti -1c
.RI "void \fBupk_gen_uuid_bytes\fP (\fBupk_uuid_t\fP *buf)"
.br
.RI "\fIcollect and/or generate 16 bytes of random data. \fP"
.ti -1c
.RI "void \fBupk_uuid_to_string\fP (char *buf, const \fBupk_uuid_t\fP *uuid)"
.br
.RI "\fIconvert uuid to string and place in buf. \fP"
.ti -1c
.RI "bool \fBis_valid_upk_uuid_string\fP (const char *string)"
.br
.RI "\fItest if a given string is a valid uuid string. \fP"
.ti -1c
.RI "void \fBupk_string_to_uuid\fP (const char *string, \fBupk_uuid_t\fP *uuid)"
.br
.RI "\fIconvert uuid string into uuid structure. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
