.TH "libupkeeper/tests/v0_protocol_helpers.c" 3 "Wed Sep 14 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libupkeeper/tests/v0_protocol_helpers.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <check.h>\fP
.br
\fC#include <upkeeper/upk_v0_protocol.h>\fP
.br
\fC#include 'v0_protocol_generic_value_checks.inc.c'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNAME_TO_FUNC\fP(A)   v0_create_ ## A"
.br
.ti -1c
.RI "#define \fBNAME_TO_TYPE\fP(A)   v0_ ## A ## _t"
.br
.ti -1c
.RI "#define \fBTEST_SETUP\fP(NAME,...)"
.br
.ti -1c
.RI "#define \fBTEST_SETUP_NOARGS\fP(NAME)"
.br
.ti -1c
.RI "#define \fBTEST_TEARDOWN\fP   upk_pkt_free(pkt);"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Suite * \fBv0_proto_helpers_suite\fP (void)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define NAME_TO_FUNC(A)   v0_create_ ## A"
.SS "#define NAME_TO_TYPE(A)   v0_ ## A ## _t"
.SS "#define TEST_SETUP(NAME, ...)"\fBValue:\fP
.PP
.nf
upk_packet_t *pkt = NULL; \
    NAME_TO_TYPE(NAME) t = { 0 }; \
    pkt = NAME_TO_FUNC(NAME)(__VA_ARGS__); \
    t = *((NAME_TO_TYPE(NAME) *) pkt->payload)
.fi
.SS "#define TEST_SETUP_NOARGS(NAME)"\fBValue:\fP
.PP
.nf
upk_packet_t *pkt = NULL; \
    NAME_TO_TYPE(NAME) t = { 0 }; \
    pkt = NAME_TO_FUNC(NAME)(); \
    t = *((NAME_TO_TYPE(NAME) *) pkt->payload)
.fi
.SS "#define TEST_TEARDOWN   upk_pkt_free(pkt);"
.SH "Function Documentation"
.PP 
.SS "int main (void)"
.PP
References suite(), and v0_proto_helpers_suite().
.SS "Suite* v0_proto_helpers_suite (void)"
.PP
References suite(), v0_proto_pubmsgs(), v0_proto_replies(), and v0_proto_requests().
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
