.TH "v0_pub_publication_t" 3 "Wed Dec 7 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v0_pub_publication_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <upk_v0_protocol.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBupk_msgtype_t\fP \fBmsgtype\fP"
.br
.ti -1c
.RI "\fBUPK_V0_PUBLICATION_T_FIELDS\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBupk_msgtype_t\fP \fBv0_pub_publication_t::msgtype\fP"
.SS "\fBv0_pub_publication_t::UPK_V0_PUBLICATION_T_FIELDS\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
