.TH "VdbeFunc" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VdbeFunc \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBFuncDef\fP * \fBpFunc\fP"
.br
.ti -1c
.RI "int \fBnAux\fP"
.br
.ti -1c
.RI "\fBVdbeFunc::AuxData\fP \fBapAux\fP [1]"
.br
.ti -1c
.RI "\fBFuncDef\fP * \fBpFunc\fP"
.br
.ti -1c
.RI "\fBVdbeFunc::AuxData\fP \fBapAux\fP [1]"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBAuxData\fP"
.br
.ti -1c
.RI "struct \fBAuxData\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBVdbeFunc::AuxData\fP  \fBVdbeFunc::apAux\fP[1]"
.PP
.SS "struct \fBVdbeFunc::AuxData\fP  \fBVdbeFunc::apAux\fP[1]"
.PP
.SS "int \fBVdbeFunc::nAux\fP"
.PP
.SS "\fBFuncDef\fP* \fBVdbeFunc::pFunc\fP"
.PP
.SS "\fBFuncDef\fP* \fBVdbeFunc::pFunc\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
