.TH "VdbeFrame" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VdbeFrame \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBVdbe\fP * \fBv\fP"
.br
.ti -1c
.RI "int \fBpc\fP"
.br
.ti -1c
.RI "\fBOp\fP * \fBaOp\fP"
.br
.ti -1c
.RI "int \fBnOp\fP"
.br
.ti -1c
.RI "\fBMem\fP * \fBaMem\fP"
.br
.ti -1c
.RI "int \fBnMem\fP"
.br
.ti -1c
.RI "\fBVdbeCursor\fP ** \fBapCsr\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBnCursor\fP"
.br
.ti -1c
.RI "void * \fBtoken\fP"
.br
.ti -1c
.RI "int \fBnChildMem\fP"
.br
.ti -1c
.RI "int \fBnChildCsr\fP"
.br
.ti -1c
.RI "\fBi64\fP \fBlastRowid\fP"
.br
.ti -1c
.RI "int \fBnChange\fP"
.br
.ti -1c
.RI "\fBVdbeFrame\fP * \fBpParent\fP"
.br
.ti -1c
.RI "\fBVdbe\fP * \fBv\fP"
.br
.ti -1c
.RI "\fBOp\fP * \fBaOp\fP"
.br
.ti -1c
.RI "\fBMem\fP * \fBaMem\fP"
.br
.ti -1c
.RI "\fBVdbeCursor\fP ** \fBapCsr\fP"
.br
.ti -1c
.RI "void * \fBtoken\fP"
.br
.ti -1c
.RI "\fBVdbeFrame\fP * \fBpParent\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBMem\fP* \fBVdbeFrame::aMem\fP"
.PP
.SS "\fBMem\fP* \fBVdbeFrame::aMem\fP"
.PP
.SS "\fBOp\fP* \fBVdbeFrame::aOp\fP"
.PP
.SS "\fBOp\fP* \fBVdbeFrame::aOp\fP"
.PP
.SS "\fBVdbeCursor\fP** \fBVdbeFrame::apCsr\fP"
.PP
.SS "\fBVdbeCursor\fP** \fBVdbeFrame::apCsr\fP"
.PP
.SS "\fBi64\fP \fBVdbeFrame::lastRowid\fP"
.PP
.SS "int \fBVdbeFrame::nChange\fP"
.PP
.SS "int \fBVdbeFrame::nChildCsr\fP"
.PP
.SS "int \fBVdbeFrame::nChildMem\fP"
.PP
.SS "\fBu16\fP \fBVdbeFrame::nCursor\fP"
.PP
.SS "int \fBVdbeFrame::nMem\fP"
.PP
.SS "int \fBVdbeFrame::nOp\fP"
.PP
.SS "int \fBVdbeFrame::pc\fP"
.PP
.SS "\fBVdbeFrame\fP* \fBVdbeFrame::pParent\fP"
.PP
.SS "\fBVdbeFrame\fP* \fBVdbeFrame::pParent\fP"
.PP
.SS "void* \fBVdbeFrame::token\fP"
.PP
.SS "void* \fBVdbeFrame::token\fP"
.PP
.SS "\fBVdbe\fP* \fBVdbeFrame::v\fP"
.PP
.SS "\fBVdbe\fP* \fBVdbeFrame::v\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
