.TH "WalCkptInfo" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WalCkptInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBnBackfill\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBaReadMark\fP [WAL_NREADER]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu32\fP \fBWalCkptInfo::aReadMark\fP"
.PP
.SS "\fBu32\fP \fBWalCkptInfo::nBackfill\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
