.TH "WhereMaskSet" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WhereMaskSet \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "int \fBix\fP [BMS]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBWhereMaskSet::ix\fP"
.PP
.SS "int \fBWhereMaskSet::n\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
