.TH "WhereClause" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WhereClause \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBParse\fP * \fBpParse\fP"
.br
.ti -1c
.RI "\fBWhereMaskSet\fP * \fBpMaskSet\fP"
.br
.ti -1c
.RI "\fBBitmask\fP \fBvmask\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBop\fP"
.br
.ti -1c
.RI "int \fBnTerm\fP"
.br
.ti -1c
.RI "int \fBnSlot\fP"
.br
.ti -1c
.RI "\fBWhereTerm\fP * \fBa\fP"
.br
.ti -1c
.RI "\fBWhereTerm\fP \fBaStatic\fP [8]"
.br
.ti -1c
.RI "\fBParse\fP * \fBpParse\fP"
.br
.ti -1c
.RI "\fBWhereMaskSet\fP * \fBpMaskSet\fP"
.br
.ti -1c
.RI "\fBWhereTerm\fP * \fBa\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBWhereTerm\fP* \fBWhereClause::a\fP"
.PP
.SS "\fBWhereTerm\fP* \fBWhereClause::a\fP"
.PP
.SS "\fBWhereTerm\fP \fBWhereClause::aStatic\fP"
.PP
.SS "int \fBWhereClause::nSlot\fP"
.PP
.SS "int \fBWhereClause::nTerm\fP"
.PP
.SS "\fBu8\fP \fBWhereClause::op\fP"
.PP
.SS "\fBWhereMaskSet\fP* \fBWhereClause::pMaskSet\fP"
.PP
.SS "\fBWhereMaskSet\fP* \fBWhereClause::pMaskSet\fP"
.PP
.SS "\fBParse\fP* \fBWhereClause::pParse\fP"
.PP
.SS "\fBParse\fP* \fBWhereClause::pParse\fP"
.PP
.SS "\fBBitmask\fP \fBWhereClause::vmask\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
