.TH "WhereCost" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WhereCost \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBWherePlan\fP \fBplan\fP"
.br
.ti -1c
.RI "double \fBrCost\fP"
.br
.ti -1c
.RI "double \fBnRow\fP"
.br
.ti -1c
.RI "\fBBitmask\fP \fBused\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "double \fBWhereCost::nRow\fP"
.PP
.SS "\fBWherePlan\fP \fBWhereCost::plan\fP"
.PP
.SS "double \fBWhereCost::rCost\fP"
.PP
.SS "\fBBitmask\fP \fBWhereCost::used\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
