.TH "WhereInfo" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WhereInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBParse\fP * \fBpParse\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBwctrlFlags\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBokOnePass\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBuntestedTerms\fP"
.br
.ti -1c
.RI "\fBSrcList\fP * \fBpTabList\fP"
.br
.ti -1c
.RI "int \fBiTop\fP"
.br
.ti -1c
.RI "int \fBiContinue\fP"
.br
.ti -1c
.RI "int \fBiBreak\fP"
.br
.ti -1c
.RI "int \fBnLevel\fP"
.br
.ti -1c
.RI "\fBWhereClause\fP * \fBpWC\fP"
.br
.ti -1c
.RI "double \fBsavedNQueryLoop\fP"
.br
.ti -1c
.RI "\fBWhereLevel\fP \fBa\fP [1]"
.br
.ti -1c
.RI "\fBParse\fP * \fBpParse\fP"
.br
.ti -1c
.RI "\fBSrcList\fP * \fBpTabList\fP"
.br
.ti -1c
.RI "\fBWhereClause\fP * \fBpWC\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBWhereLevel\fP \fBWhereInfo::a\fP"
.PP
.SS "int \fBWhereInfo::iBreak\fP"
.PP
.SS "int \fBWhereInfo::iContinue\fP"
.PP
.SS "int \fBWhereInfo::iTop\fP"
.PP
.SS "int \fBWhereInfo::nLevel\fP"
.PP
.SS "\fBu8\fP \fBWhereInfo::okOnePass\fP"
.PP
.SS "\fBParse\fP* \fBWhereInfo::pParse\fP"
.PP
.SS "\fBParse\fP* \fBWhereInfo::pParse\fP"
.PP
.SS "\fBSrcList\fP* \fBWhereInfo::pTabList\fP"
.PP
.SS "\fBSrcList\fP* \fBWhereInfo::pTabList\fP"
.PP
.SS "struct \fBWhereClause\fP* \fBWhereInfo::pWC\fP"
.PP
.SS "struct \fBWhereClause\fP* \fBWhereInfo::pWC\fP"
.PP
.SS "double \fBWhereInfo::savedNQueryLoop\fP"
.PP
.SS "\fBu8\fP \fBWhereInfo::untestedTerms\fP"
.PP
.SS "\fBu16\fP \fBWhereInfo::wctrlFlags\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
