.TH "yyStackEntry" 3 "20 Jul 2011" "Version 1" "upkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yyStackEntry \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "YYACTIONTYPE \fBstateno\fP"
.br
.ti -1c
.RI "YYCODETYPE \fBmajor\fP"
.br
.ti -1c
.RI "\fBYYMINORTYPE\fP \fBminor\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "YYCODETYPE \fByyStackEntry::major\fP"
.PP
.SS "\fBYYMINORTYPE\fP \fByyStackEntry::minor\fP"
.PP
.SS "YYACTIONTYPE \fByyStackEntry::stateno\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for upkeeper from the source code.
