#!/bin/sh
#
# Start the buddy controller. Use the buddy (!) to make sure it comes back
# up should it fall down for any reason.
#
DIR=`dirname $(which $0)`
DIR=$(dirname $( (cd $DIR ; pwd -P) ))
PATH=$PATH:$DIR/buddy:$DIR/controller
###
### leaving only
### 
cd $DIR/store
exec env - PATH=$PATH buddy --log --quiet -- buddy-controller
