#!/bin/sh
#
# Possible equivalent of svscanboot.
#
DIR=`dirname $(which $0)`
DIR=$(dirname $( (cd $DIR ; pwd -P) ))
PATH=$PATH:$DIR/buddy:$DIR/controller
###
### leaving only
### 
exec buddy -- $(which buddy-controller) --verbose
