.TH "_upk_controller_config" 3 "30 Jun 2011" "Version 1" "libupkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_upk_controller_config \- controller configuration.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <upk_config.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBStateDir\fP [UPK_MAX_PATH_LEN]"
.br
.ti -1c
.RI "char \fBSvcConfigPath\fP [UPK_MAX_PATH_LEN]"
.br
.ti -1c
.RI "char \fBSvcRunPath\fP [UPK_MAX_PATH_LEN]"
.br
.ti -1c
.RI "char \fBcontroller_socket\fP [UPK_MAX_PATH_LEN]"
.br
.ti -1c
.RI "char \fBcontroller_buddy_sock\fP [UPK_MAX_PATH_LEN]"
.br
.ti -1c
.RI "\fBupk_svc_desc_t\fP \fBServiceDefaults\fP"
.br
.ti -1c
.RI "\fBupk_svc_desc_t\fP * \fBsvclist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
controller configuration. 
.PP
.SH "Field Documentation"
.PP 
.SS "char \fB_upk_controller_config::StateDir\fP[UPK_MAX_PATH_LEN]"
.PP
path to variable state-dir for controller and buddies 

.SH "Author"
.PP 
Generated automatically by Doxygen for libupkeeper from the source code.
