.TH "_upk_svcinfo_t" 3 "29 Jun 2011" "Version 1" "libupkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_upk_svcinfo_t \- see definition in *protocol_fields.h.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <types.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBUPK_V0_SVCINFO_T_FIELDS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
see definition in *protocol_fields.h. 
.PP
.SH "Field Documentation"
.PP 
.SS "\fB_upk_svcinfo_t::UPK_V0_SVCINFO_T_FIELDS\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libupkeeper from the source code.
