.TH "_upk_json_type_handlers" 3 "30 Jun 2011" "Version 1" "libupkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_upk_json_type_handlers \- 
.SH SYNOPSIS
.br
.PP
\fC#include <upk_json.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "void(* \fBupk_json_null\fP )(char *key)"
.br
.ti -1c
.RI "void(* \fBupk_json_bool\fP )(char *key, bool val)"
.br
.ti -1c
.RI "void(* \fBupk_json_double\fP )(char *key, double val)"
.br
.ti -1c
.RI "void(* \fBupk_json_int\fP )(char *key, int val)"
.br
.ti -1c
.RI "void(* \fBupk_json_string\fP )(char *key, char *val)"
.br
.ti -1c
.RI "void(* \fBupk_json_array\fP )(char *key, void *jobj)"
.br
.ti -1c
.RI "void(* \fBupk_json_object\fP )(char *key, void *jobj)"
.br
.ti -1c
.RI "void(* \fBupk_json_pop_obj\fP )(char *key, void *jobj)"
.br
.ti -1c
.RI "void(* \fBupk_json_pop_array\fP )(char *key, void *jobj)"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* \fB_upk_json_type_handlers::data\fP"
.PP
.SS "void(* \fB_upk_json_type_handlers::upk_json_array\fP)(char *key, void *jobj)"
.PP
.SS "void(* \fB_upk_json_type_handlers::upk_json_bool\fP)(char *key, bool val)"
.PP
.SS "void(* \fB_upk_json_type_handlers::upk_json_double\fP)(char *key, double val)"
.PP
.SS "void(* \fB_upk_json_type_handlers::upk_json_int\fP)(char *key, int val)"
.PP
.SS "void(* \fB_upk_json_type_handlers::upk_json_null\fP)(char *key)"
.PP
.SS "void(* \fB_upk_json_type_handlers::upk_json_object\fP)(char *key, void *jobj)"
.PP
.SS "void(* \fB_upk_json_type_handlers::upk_json_pop_array\fP)(char *key, void *jobj)"
.PP
.SS "void(* \fB_upk_json_type_handlers::upk_json_pop_obj\fP)(char *key, void *jobj)"
.PP
.SS "void(* \fB_upk_json_type_handlers::upk_json_string\fP)(char *key, char *val)"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libupkeeper from the source code.
