.TH "upkeeper/c_isxdigit.c" 3 "29 Jun 2011" "Version 1" "libupkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upkeeper/c_isxdigit.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "static bool \fBc_isxdigit\fP (char c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static bool c_isxdigit (char c)\fC [inline, static]\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for libupkeeper from the source code.
