.TH "upkeeper/config.h" 3 "29 Jun 2011" "Version 1" "libupkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upkeeper/config.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'std_include.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_upk_svc_desc\fP"
.br
.ti -1c
.RI "struct \fBupk_controller_config_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fB_upk_svc_desc\fP \fBupk_svc_desc_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBupk_svc_logopts_t\fP { \fBUPK_SVC_LOG_CAPTURE_STDOUT\fP =  1, \fBUPK_SVC_LOG_CAPTURE_STDERR\fP =  2, \fBUPK_SVC_LOG_SYSLOG_STDOUT\fP =  4, \fBUPK_SVC_LOG_SYSLOG_STDERR\fP =  8, \fBUPK_SVC_LOG_STDOUT_FILE\fP =  16, \fBUPK_SVC_LOG_STDERR_FILE\fP =  32 }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_upk_svc_desc\fP \fBupk_svc_desc_t\fP"
.PP
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBupk_svc_logopts_t\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIUPK_SVC_LOG_CAPTURE_STDOUT \fP\fP
.TP
\fB\fIUPK_SVC_LOG_CAPTURE_STDERR \fP\fP
.TP
\fB\fIUPK_SVC_LOG_SYSLOG_STDOUT \fP\fP
.TP
\fB\fIUPK_SVC_LOG_SYSLOG_STDERR \fP\fP
.TP
\fB\fIUPK_SVC_LOG_STDOUT_FILE \fP\fP
.TP
\fB\fIUPK_SVC_LOG_STDERR_FILE \fP\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for libupkeeper from the source code.
