.TH "Controller" 3 "30 Jun 2011" "Version 1" "libupkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controller \- 
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_upk_controller_config\fP"
.br
.RI "\fIcontroller configuration. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fB_upk_controller_config\fP \fBupk_controller_config_t\fP"
.br
.RI "\fIcontroller configuration. \fP"
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_upk_controller_config\fP  \fBupk_controller_config_t\fP"
.PP
controller configuration. 
.PP

