.TH "upkeeper/controller.c" 3 "30 Jun 2011" "Version 1" "libupkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upkeeper/controller.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'upk_std_include.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBCONTROLLER\fP   yay"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define CONTROLLER   yay"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for libupkeeper from the source code.
