.TH "upkeeper/stdbool.in.h" 3 "30 Jun 2011" "Version 1" "libupkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upkeeper/stdbool.in.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_Bool\fP   signed char"
.br
.ti -1c
.RI "#define \fBbool\fP   _Bool"
.br
.ti -1c
.RI "#define \fBfalse\fP   0"
.br
.ti -1c
.RI "#define \fBtrue\fP   1"
.br
.ti -1c
.RI "#define \fB__bool_true_false_are_defined\fP   1"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define __bool_true_false_are_defined   1"
.PP
.SS "#define _Bool   signed char"
.PP
.SS "#define bool   _Bool"
.PP
.SS "#define false   0"
.PP
.SS "#define true   1"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for libupkeeper from the source code.
