.TH "upkeeper/strnlen.c" 3 "30 Jun 2011" "Version 1" "libupkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upkeeper/strnlen.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBstrnlen\fP (const char *string, size_t maxlen)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "size_t strnlen (const char * string, size_t maxlen)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for libupkeeper from the source code.
