.TH "upkeeper/upk_json.c" 3 "30 Jun 2011" "Version 1" "libupkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upkeeper/upk_json.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'upk_json.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBupk_json_obj_iter\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBupk_json_obj_iter\fP \fBupk_json_obj_iter_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBupk_json_default_null_handler\fP (char *key)"
.br
.ti -1c
.RI "void \fBupk_json_default_bool_handler\fP (char *key, _Bool val)"
.br
.ti -1c
.RI "void \fBupk_json_default_double_handler\fP (char *key, double val)"
.br
.ti -1c
.RI "void \fBupk_json_default_int_handler\fP (char *key, int val)"
.br
.ti -1c
.RI "void \fBupk_json_default_string_handler\fP (char *key, char *val)"
.br
.ti -1c
.RI "void \fBupk_json_default_array_handler\fP (char *key, void *jobj)"
.br
.ti -1c
.RI "void \fBupk_json_default_object_handler\fP (char *key, void *jobj)"
.br
.ti -1c
.RI "static void \fBupk_json_value\fP (char *key, struct json_object *jobj)"
.br
.ti -1c
.RI "static void \fBupk_json_parse_array\fP (char *key, struct json_object *jarray)"
.br
.ti -1c
.RI "void \fBupk_json_default_bool_handler\fP (char *key, bool val)"
.br
.ti -1c
.RI "void \fBupk_json_parse_node\fP (struct json_object *jobj)"
.br
.ti -1c
.RI "bool \fBupk_json_parse_string\fP (const char *string)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBupk_json_type_handlers_t\fP \fBupk_json_type_callbacks\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBupk_json_obj_iter\fP  \fBupk_json_obj_iter_t\fP"
.PP
.SH "Function Documentation"
.PP 
.SS "void upk_json_default_array_handler (char * key, void * jobj)"
.PP
.SS "void upk_json_default_bool_handler (char * key, bool val)"
.PP
.SS "void upk_json_default_bool_handler (char * key, _Bool val)"
.PP
.SS "void upk_json_default_double_handler (char * key, double val)"
.PP
.SS "void upk_json_default_int_handler (char * key, int val)"
.PP
.SS "void upk_json_default_null_handler (char * key)"
.PP
.SS "void upk_json_default_object_handler (char * key, void * jobj)"
.PP
.SS "void upk_json_default_string_handler (char * key, char * val)"
.PP
.SS "static void upk_json_parse_array (char * key, struct json_object * jarray)\fC [inline, static]\fP"
.PP
.SS "void upk_json_parse_node (struct json_object * jobj)"
.PP
.SS "bool upk_json_parse_string (const char * string)"
.PP
.SS "static void upk_json_value (char * key, struct json_object * jobj)\fC [inline, static]\fP"
.PP
.SH "Variable Documentation"
.PP 
.SS "\fBupk_json_type_handlers_t\fP \fBupk_json_type_callbacks\fP"
.PP
\fBInitial value:\fP
.PP
.nf
 {
    .data = NULL,
    .upk_json_null = upk_json_default_null_handler,
    .upk_json_bool = upk_json_default_bool_handler,
    .upk_json_double = upk_json_default_double_handler,
    .upk_json_int = upk_json_default_int_handler,
    .upk_json_string = upk_json_default_string_handler,
    .upk_json_array = upk_json_default_array_handler,
    .upk_json_object = upk_json_default_object_handler,
    .upk_json_pop_obj = NULL,
    .upk_json_pop_array = NULL,
}
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for libupkeeper from the source code.
