.TH "upk_controller_config_t" 3 "29 Jun 2011" "Version 1" "libupkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upk_controller_config_t \- 
.SH SYNOPSIS
.br
.PP
\fC#include <config.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBstatedir\fP [UPK_MAX_PATH_LEN]"
.br
.ti -1c
.RI "unsigned char \fBsvc_config_path\fP [UPK_MAX_PATH_LEN]"
.br
.ti -1c
.RI "unsigned char \fBsvc_run_path\fP [UPK_MAX_PATH_LEN]"
.br
.ti -1c
.RI "unsigned char \fBcontroller_socket\fP [UPK_MAX_PATH_LEN]"
.br
.ti -1c
.RI "unsigned char \fBcontroller_buddy_sock\fP [UPK_MAX_PATH_LEN]"
.br
.ti -1c
.RI "unsigned char \fBdefault_log_path\fP [UPK_MAX_PATH_LEN]"
.br
.ti -1c
.RI "unsigned char \fBdefault_stderr_logpath\fP [UPK_MAX_PATH_LEN]"
.br
.ti -1c
.RI "unsigned char \fBdefault_stdout_logpath\fP [UPK_MAX_PATH_LEN]"
.br
.ti -1c
.RI "\fBupk_svc_logopts_t\fP \fBdefault_logopts\fP"
.br
.ti -1c
.RI "\fBupk_svc_desc_t\fP * \fBsvclist\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned char \fBupk_controller_config_t::controller_buddy_sock\fP[UPK_MAX_PATH_LEN]"
.PP
.SS "unsigned char \fBupk_controller_config_t::controller_socket\fP[UPK_MAX_PATH_LEN]"
.PP
.SS "unsigned char \fBupk_controller_config_t::default_log_path\fP[UPK_MAX_PATH_LEN]"
.PP
.SS "\fBupk_svc_logopts_t\fP \fBupk_controller_config_t::default_logopts\fP"
.PP
.SS "unsigned char \fBupk_controller_config_t::default_stderr_logpath\fP[UPK_MAX_PATH_LEN]"
.PP
.SS "unsigned char \fBupk_controller_config_t::default_stdout_logpath\fP[UPK_MAX_PATH_LEN]"
.PP
.SS "unsigned char \fBupk_controller_config_t::statedir\fP[UPK_MAX_PATH_LEN]"
.PP
.SS "unsigned char \fBupk_controller_config_t::svc_config_path\fP[UPK_MAX_PATH_LEN]"
.PP
.SS "unsigned char \fBupk_controller_config_t::svc_run_path\fP[UPK_MAX_PATH_LEN]"
.PP
.SS "\fBupk_svc_desc_t\fP* \fBupk_controller_config_t::svclist\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libupkeeper from the source code.
