.TH "upkeeper/upk_crc32.h" 3 "30 Jun 2011" "Version 1" "libupkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upkeeper/upk_crc32.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'upk_std_include.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBupk_create_crc32_table\fP (uint32_t crc_table[256])"
.br
.ti -1c
.RI "uint32_t \fBupk_crc32\fP (unsigned char *block, uint32_t len)"
.br
.ti -1c
.RI "bool \fBupk_verify_crc32\fP (unsigned char *block, uint32_t crc32, uint32_t len)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint32_t upk_crc32 (unsigned char * block, uint32_t len)"
.PP
.SS "void upk_create_crc32_table (uint32_t crc_table[256])"
.PP
.SS "bool upk_verify_crc32 (unsigned char * block, uint32_t crc32, uint32_t len)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for libupkeeper from the source code.
