.TH "upkeeper/upk_compat.h" 3 "30 Jun 2011" "Version 1" "libupkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upkeeper/upk_compat.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBc_isxdigit\fP(c)   ((c >= '0' && c <= '9') || (c >= 'A' && c <= 'F') || (c >= 'a' && c <= 'f'))"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define c_isxdigit(c)   ((c >= '0' && c <= '9') || (c >= 'A' && c <= 'F') || (c >= 'a' && c <= 'f'))"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for libupkeeper from the source code.
