.TH "upk_repl_preamble_t" 3 "30 Jun 2011" "Version 1" "libupkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upk_repl_preamble_t \- 
.SH SYNOPSIS
.br
.PP
\fC#include <upk_protocol.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBupk_repl_msgtype_t\fP \fBmsgtype\fP"
.br
.ti -1c
.RI "uint32_t \fBbest_version\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t \fBupk_repl_preamble_t::best_version\fP"
.PP
.SS "\fBupk_repl_msgtype_t\fP \fBupk_repl_preamble_t::msgtype\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libupkeeper from the source code.
