.TH "upkeeper/upk_config.c" 3 "30 Jun 2011" "Version 1" "libupkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upkeeper/upk_config.c \- configuration defaults, and implementation 
.SH SYNOPSIS
.br
.PP
\fC#include 'upk_include.h'\fP
.br
\fC#include 'upk_json.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_stringify\fP(A)   #A"
.br
.ti -1c
.RI "#define \fBstringify\fP(A)   _stringify(A)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBupk_ctrlconf_string_handler\fP (char *key, char *string)"
.br
.ti -1c
.RI "static void \fBupk_svcconf_bool_handler\fP (char *key, _Bool val)"
.br
.ti -1c
.RI "static void \fBupk_svcconf_string_handler\fP (char *key, char *string)"
.br
.ti -1c
.RI "static void \fBupk_ctrl_service_pop_handler\fP (char *key, void *obj)"
.br
.ti -1c
.RI "static void \fBupk_service_parse_handlers\fP (void)"
.br
.ti -1c
.RI "static void \fBupk_ctrlconf_object_handler\fP (char *key, void *jobj)"
.br
.ti -1c
.RI "static void \fBupk_ctrl_config_parse_handlers\fP (void *buf)"
.br
.ti -1c
.RI "static char * \fBupk_config_loadfile\fP (const char *filename)"
.br
.ti -1c
.RI "static void \fBupk_ctrl_config_pack\fP (\fBupk_controller_config_t\fP *cfg, const char *json_string)"
.br
.ti -1c
.RI "static void \fBupk_svcconf_bool_handler\fP (char *key, bool val)"
.br
.ti -1c
.RI "static void \fBupk_svcconf_int_handler\fP (char *key, int val)"
.br
.ti -1c
.RI "static void \fBupk_svcconf_double_handler\fP (char *key, double val)"
.br
.ti -1c
.RI "void \fBupk_load_config\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static void * \fB_upk_ctrl_service_pop_handler_data_buf\fP"
.br
.ti -1c
.RI "const char \fBupk_ctrl_configuration_file\fP [UPK_MAX_PATH_LEN] = stringify(CONF_SYSCONFDIR) '/upkeeper.conf'"
.br
.ti -1c
.RI "const char \fBupk_default_configuration_vec\fP []"
.br
.ti -1c
.RI "\fBupk_controller_config_t\fP \fBupk_default_configuration\fP"
.br
.ti -1c
.RI "\fBupk_controller_config_t\fP \fBupk_runtime_configuration\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
configuration defaults, and implementation 


.SH "Author"
.PP 
Generated automatically by Doxygen for libupkeeper from the source code.
