.TH "upkeeper/upk_v0_protocol_serializer.c" 3 "30 Jun 2011" "Version 1" "libupkeeper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upkeeper/upk_v0_protocol_serializer.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'upk_v0_protocol.h'\fP
.br
\fC#include 'upk_error.h'\fP
.br
\fC#include <assert.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBUPK_MSG_IDENTIFIER\fP   msgtype"
.br
.ti -1c
.RI "#define \fBUPK_MSG_IDENTIFIER_TYPEDEF\fP   \fBupk_req_msgtype_t\fP"
.br
.ti -1c
.RI "#define \fBUPK_MSG_IDENTIFIER_TYPEDEF\fP   \fBupk_repl_msgtype_t\fP"
.br
.ti -1c
.RI "#define \fBUPK_MSG_IDENTIFIER_TYPEDEF\fP   \fBupk_pub_msgtype_t\fP"
.br
.ti -1c
.RI "#define \fBUPK_MSG_IDENTIFIER_TYPEDEF\fP   \fBupk_req_msgtype_t\fP"
.br
.ti -1c
.RI "#define \fBUPK_MSG_IDENTIFIER_TYPEDEF\fP   \fBupk_repl_msgtype_t\fP"
.br
.ti -1c
.RI "#define \fBUPK_MSG_IDENTIFIER_TYPEDEF\fP   \fBupk_pub_msgtype_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void *(*) \fBdeserialize_payload_t\fP (\fBupk_pkt_buf_t\fP *)"
.br
.ti -1c
.RI "typedef \fBupk_pkt_buf_t\fP *(*) \fBserialize_payload_t\fP (void *, size_t)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserialize_req_payload\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserialize_repl_payload\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserialize_pub_payload\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static void * \fBdeserialize_req_payload\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserialize_repl_payload\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserialize_pub_payload\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_req_seq_start\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_req_seq_end\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_req_action\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_req_signal\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_req_list\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_req_status\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_req_subscribe\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_req_unsub\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_req_disconnect\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_repl_seq_start\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_repl_seq_end\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_repl_result\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_repl_listing\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static \fBv0_svcinfo_t\fP * \fBdeserial_svcinfo_data\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_repl_svcinfo\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_repl_ack\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_repl_err\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_pub_pub\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static void * \fBdeserial_pub_cancel\fP (\fBupk_pkt_buf_t\fP *UPK_BUF)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_req_seq_start\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_req_seq_end\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_req_action\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_req_signal\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_req_list\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_req_status\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_req_subscribe\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_req_unsub\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_req_disconnect\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_repl_seq_start\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_repl_seq_end\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_repl_result\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_repl_listing\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_svcinfo_data\fP (\fBv0_svcinfo_t\fP *data, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_repl_svcinfo\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_repl_ack\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_repl_err\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_pub_pub\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "static \fBupk_pkt_buf_t\fP * \fBserial_pub_cancel\fP (void *UPK_DATA_PTR, size_t UPK_DATA_LEN)"
.br
.ti -1c
.RI "void * \fBv0_deserialize_payload\fP (\fBupk_pkt_buf_t\fP *UPK_BUF, \fBupk_pkttype_t\fP pkttype)"
.br
.ti -1c
.RI "\fBupk_pkt_buf_t\fP * \fBv0_serialize_payload\fP (\fBupk_packet_t\fP *pkt)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBupk_pkttype_t\fP \fBupk_pkt_proto_limit\fP []"
.br
.ti -1c
.RI "\fBupk_req_msgtype_t\fP \fBupk_req_proto_limit\fP []"
.br
.ti -1c
.RI "\fBupk_repl_msgtype_t\fP \fBupk_repl_proto_limit\fP []"
.br
.ti -1c
.RI "\fBupk_pub_msgtype_t\fP \fBupk_pub_proto_limit\fP []"
.br
.ti -1c
.RI "static \fBdeserialize_payload_t\fP \fBdeserial_pkt_dispatch\fP []"
.br
.ti -1c
.RI "static \fBdeserialize_payload_t\fP \fBdeserial_req_dispatch\fP []"
.br
.ti -1c
.RI "static \fBdeserialize_payload_t\fP \fBdeserial_repl_dispatch\fP []"
.br
.ti -1c
.RI "static \fBdeserialize_payload_t\fP \fBdeserial_pub_dispatch\fP []"
.br
.ti -1c
.RI "static \fBserialize_payload_t\fP \fBserial_pkt_dispatch\fP []"
.br
.ti -1c
.RI "static \fBserialize_payload_t\fP \fBserial_req_dispatch\fP []"
.br
.ti -1c
.RI "static \fBserialize_payload_t\fP \fBserial_repl_dispatch\fP []"
.br
.ti -1c
.RI "static \fBserialize_payload_t\fP \fBserial_pub_dispatch\fP []"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define UPK_MSG_IDENTIFIER   msgtype"
.PP
.SS "#define UPK_MSG_IDENTIFIER_TYPEDEF   \fBupk_pub_msgtype_t\fP"
.PP
.SS "#define UPK_MSG_IDENTIFIER_TYPEDEF   \fBupk_repl_msgtype_t\fP"
.PP
.SS "#define UPK_MSG_IDENTIFIER_TYPEDEF   \fBupk_req_msgtype_t\fP"
.PP
.SS "#define UPK_MSG_IDENTIFIER_TYPEDEF   \fBupk_pub_msgtype_t\fP"
.PP
.SS "#define UPK_MSG_IDENTIFIER_TYPEDEF   \fBupk_repl_msgtype_t\fP"
.PP
.SS "#define UPK_MSG_IDENTIFIER_TYPEDEF   \fBupk_req_msgtype_t\fP"
.PP
.SH "Typedef Documentation"
.PP 
.SS "typedef void*(*) \fBdeserialize_payload_t\fP(\fBupk_pkt_buf_t\fP *)"
.PP
.SS "typedef \fBupk_pkt_buf_t\fP*(*) \fBserialize_payload_t\fP(void *, size_t)"
.PP
.SH "Function Documentation"
.PP 
.SS "static void * deserial_pub_cancel (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserial_pub_pub (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserial_repl_ack (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserial_repl_err (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserial_repl_listing (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserial_repl_result (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserial_repl_seq_end (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserial_repl_seq_start (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserial_repl_svcinfo (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserial_req_action (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserial_req_disconnect (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserial_req_list (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserial_req_seq_end (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserial_req_seq_start (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserial_req_signal (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserial_req_status (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserial_req_subscribe (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserial_req_unsub (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static \fBv0_svcinfo_t\fP * deserial_svcinfo_data (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [inline, static]\fP"
.PP
.SS "static void * deserialize_pub_payload (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserialize_repl_payload (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static void * deserialize_req_payload (\fBupk_pkt_buf_t\fP * UPK_BUF)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_pub_cancel (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_pub_pub (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_repl_ack (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_repl_err (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_repl_listing (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_repl_result (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_repl_seq_end (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_repl_seq_start (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_repl_svcinfo (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_req_action (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_req_disconnect (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_req_list (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_req_seq_end (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_req_seq_start (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_req_signal (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_req_status (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_req_subscribe (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_req_unsub (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serial_svcinfo_data (\fBv0_svcinfo_t\fP * data, size_t UPK_DATA_LEN)\fC [inline, static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serialize_pub_payload (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serialize_repl_payload (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "static \fBupk_pkt_buf_t\fP * serialize_req_payload (void * UPK_DATA_PTR, size_t UPK_DATA_LEN)\fC [static]\fP"
.PP
.SS "void* v0_deserialize_payload (\fBupk_pkt_buf_t\fP * UPK_BUF, \fBupk_pkttype_t\fP pkttype)"
.PP
.SS "\fBupk_pkt_buf_t\fP* v0_serialize_payload (\fBupk_packet_t\fP * pkt)"
.PP
.SH "Variable Documentation"
.PP 
.SS "\fBdeserialize_payload_t\fP \fBdeserial_pkt_dispatch\fP[]\fC [static]\fP"
.PP
\fBInitial value:\fP
.PP
.nf
 {
    [PKT_REQUEST] = deserialize_req_payload,
    [PKT_REPLY] = deserialize_repl_payload,
    [PKT_PUBMSG] = deserialize_pub_payload,
}
.fi
.SS "\fBdeserialize_payload_t\fP \fBdeserial_pub_dispatch\fP[]\fC [static]\fP"
.PP
\fBInitial value:\fP
.PP
.nf
 {
    [PUB_PUBLICATION] = deserial_pub_pub,
    [PUB_CANCELATION] = deserial_pub_cancel,
}
.fi
.SS "\fBdeserialize_payload_t\fP \fBdeserial_repl_dispatch\fP[]\fC [static]\fP"
.PP
\fBInitial value:\fP
.PP
.nf
 {
    [REPL_SEQ_START] = deserial_repl_seq_start,
    [REPL_SEQ_END] = deserial_repl_seq_end,
    [REPL_RESULT] = deserial_repl_result,
    [REPL_LISTING] = deserial_repl_listing,
    [REPL_SVCINFO] = deserial_repl_svcinfo,
    [REPL_ACK] = deserial_repl_ack,
    [REPL_ERROR] = deserial_repl_err,
}
.fi
.SS "\fBdeserialize_payload_t\fP \fBdeserial_req_dispatch\fP[]\fC [static]\fP"
.PP
\fBInitial value:\fP
.PP
.nf
 {
    [REQ_SEQ_START] = deserial_req_seq_start,
    [REQ_SEQ_END] = deserial_req_seq_end,
    [REQ_ACTION] = deserial_req_action,
    [REQ_SIGNAL] = deserial_req_signal,
    [REQ_LIST] = deserial_req_list,
    [REQ_STATUS] = deserial_req_status,
    [REQ_SUBSCRIBE] = deserial_req_subscribe,
    [REQ_UNSUBSCRIBE] = deserial_req_unsub,
    [REQ_DISCONNECT] = deserial_req_disconnect,
}
.fi
.SS "\fBserialize_payload_t\fP \fBserial_pkt_dispatch\fP[]\fC [static]\fP"
.PP
\fBInitial value:\fP
.PP
.nf
 {
    [PKT_REQUEST] = serialize_req_payload,
    [PKT_REPLY] = serialize_repl_payload,
    [PKT_PUBMSG] = serialize_pub_payload,
}
.fi
.SS "\fBserialize_payload_t\fP \fBserial_pub_dispatch\fP[]\fC [static]\fP"
.PP
\fBInitial value:\fP
.PP
.nf
 {
    [PUB_PUBLICATION] = serial_pub_pub,
    [PUB_CANCELATION] = serial_pub_cancel,
}
.fi
.SS "\fBserialize_payload_t\fP \fBserial_repl_dispatch\fP[]\fC [static]\fP"
.PP
\fBInitial value:\fP
.PP
.nf
 {
    [REPL_SEQ_START] = serial_repl_seq_start,
    [REPL_SEQ_END] = serial_repl_seq_end,
    [REPL_RESULT] = serial_repl_result,
    [REPL_LISTING] = serial_repl_listing,
    [REPL_SVCINFO] = serial_repl_svcinfo,
    [REPL_ACK] = serial_repl_ack,
    [REPL_ERROR] = serial_repl_err,
}
.fi
.SS "\fBserialize_payload_t\fP \fBserial_req_dispatch\fP[]\fC [static]\fP"
.PP
\fBInitial value:\fP
.PP
.nf
 {
    [REQ_SEQ_START] = serial_req_seq_start,
    [REQ_SEQ_END] = serial_req_seq_end,
    [REQ_ACTION] = serial_req_action,
    [REQ_SIGNAL] = serial_req_signal,
    [REQ_LIST] = serial_req_list,
    [REQ_STATUS] = serial_req_status,
    [REQ_SUBSCRIBE] = serial_req_subscribe,
    [REQ_UNSUBSCRIBE] = serial_req_unsub,
    [REQ_DISCONNECT] = serial_req_disconnect,
}
.fi
.SS "\fBupk_pkttype_t\fP \fBupk_pkt_proto_limit\fP[]"
.PP
.SS "\fBupk_pub_msgtype_t\fP \fBupk_pub_proto_limit\fP[]"
.PP
.SS "\fBupk_repl_msgtype_t\fP \fBupk_repl_proto_limit\fP[]"
.PP
.SS "\fBupk_req_msgtype_t\fP \fBupk_req_proto_limit\fP[]"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for libupkeeper from the source code.
